### ISSUE TITLE
Typescript: property not initialized warning when using property injection

### ISSUE THREAD

**Issue by annajolly** [inversify/InversifyJS#1018]
I am trying to inject a service as a property into a class *outside* of the constructor (since this particular class requires an empty constructor) as below:

```javascript
@injectable()
export class CustomAuthProvider implements interfaces.AuthProvider {

  @inject(AUTH_TYPES.AUTH_SERVICE)
  private readonly _authService: AuthService;

}
```

This gives the TS error: `Property "_authService" has no initializer and is not definitely assigned in the constructor`

I am curious if anyone has run into this issue and found a way around it. It would appear that the typescript compiler is throwing a warning because it doesn't know that the `@inject` decorator is going to provide the auth service, but as my testing confirms, the property injection is working as expected. Thanks in advance!

**Comment by gejgalis** [comment]
@annajolly have you tried with `!` ?
```  @inject(AUTH_TYPES.AUTH_SERVICE)
  private readonly _authService!: AuthService;
```

**Comment by dcavanagh** [comment]
@annajolly another option in addition to @gejgalis would be to inject the service in the constructor.

```ts
@injectable()
export class CustomAuthProvider implements interfaces.AuthProvider {

  constructor(@inject(AUTH_TYPES.AUTH_SERVICE) private readonly _authService: AuthService) {}

}
```

**Comment by dcavanagh** [comment]
@annajolly I am going to close this. Please reopen if you have more problems

**Comment by annajolly** [comment]
@dcavanagh @gejgalis Yes, I ended up using `!`, thank you!

**Comment by linonetwo** [comment]
I get `Unable to resolve signature of parameter decorator when called as an expression.ts(1239)`

When using it like:

```ts
  constructor(@lazyInject(serviceIdentifiers.Window) private readonly windowService: Window) {
    this.cachedPreferences = this.getInitPreferencesForCache();
  }
```

Why?

While this is good:

```ts
constructor(@inject(serviceIdentifiers.Preference) private readonly preferenceService: Preference) {}
```

---

I ended up using !, too...
