### ISSUE TITLE
Decorate attribute of third party class causes TSError

### ISSUE THREAD

**Issue by marvinrabe** [inversify/InversifyJS#1027]
## Current Behavior

When I decorate an attribute with the decorate function like this:

```
import { decorate, unmanaged } from 'inversify'
decorate(unmanaged(), Foo, 0)
```

It causes this error:

```
TSError: ⨯ Unable to compile TypeScript:
src/command.ts(7,10): error TS2345: Argument of type '(target: any, targetKey: string, index: number) => void' is not assignable to parameter of type 'ClassDecorator | ParameterDecorator | MethodDecorator'.
  Type '(target: any, targetKey: string, index: number) => void' is not assignable to type 'ClassDecorator'.

```

## Expected Behavior

No error.

## Possible Solution

When I typecast the function to be a ParameterDecorator everything works as expected.

```'typescript'
decorate(unmanaged() as ParameterDecorator, Foo, 0)
```

## Context

See `src/command.ts`

## Your Environment

* Version used: 11.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 11.3 with TypeScript 3.2
* Operating System and version (desktop or mobile): Current Mac OS
* Link to your project: https://github.com/marvinrabe/inversify-oclif-utils

**Comment by ceelsoin** [comment]
I am also having this error using the following library https://github.com/IRCraziestTaxi/typeorm-linq-repository

``` 
decorate(unmanaged(), RepositoryBase, 0);
decorate(unmanaged(), RepositoryBase, 1);
```

Error:

Argument of type '(target: any, targetKey: string, index: number) => void' is not assignable to parameter of type 'ClassDecorator | ParameterDecorator | MethodDecorator'.
  Type '(target: any, targetKey: string, index: number) => void' is not assignable to type 'ClassDecorator'.ts(2345)

**Comment by notaphplover** [comment]
Closing issue as it's already working using the latest `inversify` version (`inversify@6.1.5`)
