### ISSUE TITLE
compatibility between inversify-express-utils and express-ws

### ISSUE THREAD

**Issue by lefebvresam** [inversify/InversifyJS#1030]
Is there any posibility to use the inversify-express-utils decorators to define a router after extending a server with ws with express-ws?

**Comment by lonix1** [comment]
@lefebvresam Did you figure it out?

**Comment by lefebvresam** [comment]
Yes, I wrote the server implementation with web socket as following (intendation lost):

import "reflect-metadata"; // keep on first line!!
// tslint:disable-next-line:ordered-imports
import bodyParser from "body-parser";
import { Request, Response, static as serveStatic } from "express";
import expressWs from "express-ws";
import { Container } from "inversify";
import { InversifyExpressServer } from "inversify-express-utils";
import path from "path";
import URLParse from "url-parse";
import WebSocket from "ws";
import { WebSockets } from "./interfaces/websockets";
import { bindings } from "./inversify.config";

export async function main() {
  console.log("webserver: Starting webserver");

  const port = 3000;
  // "0.0.0.0" for all interfaces on device
  //const ipaddr = "127.0.0.1";
  const ipaddr = "0.0.0.0";
  // use "/" to define root as websocket
  const websocketpath1 = "/websocket";
  const websocketpath2 = "";
  const websocketpath3 = "";
  const apppath = path.join(__dirname, "../../creaclics-frontend/dist/creaclics-frontend");
  const frontendpath = "/";

  const container = new Container();
  await container.loadAsync(bindings);
  const server = new InversifyExpressServer(container);

  server.setConfig(a => {
    a.use(bodyParser.json());
    a.use(bodyParser.urlencoded({ extended: true }));
    a.use(frontendpath, serveStatic(apppath));
    expressWs(a, undefined, {
      wsOptions: {
        verifyClient: (info: any) => {
          const urlo = URLParse(info.req.url);
          return (
            urlo.pathname === websocketpath1 ||
            urlo.pathname === websocketpath2 ||
            urlo.pathname === websocketpath3
          );
        }
      }
    });
  });

  server.setErrorConfig(a => {
    a.use((err: Error, req: Request, res: Response, next: any) => {
      console.error(err.stack);
      res.status(500);
      res.send("Something broke, see logs for more detailled info.");
    });
  });

  const app = server.build();

  app.listen(port, ipaddr, () => {
    console.log("webserver: Server running at http://%s:%i", ipaddr, port);
  });

  if (websocketpath1.length) {
    app.ws(websocketpath1, (ws: WebSocket, req: Request) => {
      WebSockets.addWebSocketInstance(websocketpath1, { ws, req });
    });
  }

  if (websocketpath2.length) {
    app.ws(websocketpath2, (ws: WebSocket, req: Request) => {
      WebSockets.addWebSocketInstance(websocketpath2, { ws, req });
    });
  }

  if (websocketpath3.length) {
    app.ws(websocketpath3, (ws: WebSocket, req: Request) => {
      WebSockets.addWebSocketInstance(websocketpath3, { ws, req });
    });
  }
}

export function serverError(error: string) {
  console.log("Webserver error:", error);
  return `<head></head><body><h1>Internal Server Error</h1><p>${error}</p></body>`;
}
