### ISSUE TITLE
TypeError: Proxy is not a function

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#106]
We can't test an example with real proxies (#86) due to an [issue with the `--harmony-proxies` and gulp-mocha](http://stackoverflow.com/questions/35906938/how-to-enable-harmony-proxies-in-gulp-mocha).

At the moment [some unit tests assertions are commneted](https://github.com/inversify/InversifyJS/search?utf8=%E2%9C%93&q=BLOCK&type=Code). You can remove the comments if you want to try to help to fix the issue.

**Comment by jamesadarich** [comment]
Hey Remo,

Just tried to recreate this issue and I don't seem to get any issues. I swapped the comments out in this test  (see below) and it still passes for me. I get a TypeScript error on not knowing what the Proxy class is but I suspect this is expected.

```

it("Should be able to configure the proxyMaker of a binding", () => {

        interface INinja {}
        let ninjaIdentifier = "INinja";

        let binding = new Binding<INinja>(ninjaIdentifier);
        let bindingInWhenProxySyntax = new BindingInWhenProxySyntax<INinja>(binding);

        bindingInWhenProxySyntax.proxy((ninja: INinja) => {
            let handler = {};
            return new Proxy<INinja>(ninja, handler);
        });

        expect(binding.proxyMaker).not.to.eql(null);

    });

```

![image](https://cloud.githubusercontent.com/assets/8244919/13728019/25ffcef8-e901-11e5-8864-a9055a8b42b7.png)

Could you please clarify what the issue is? :)

**Comment by remojansen** [comment]
If we target ES6 typescript imports [`es6.d.ts`](). This file declares the typings  for the Proxy class. We don't want to target ES6, so when targeting ES5 the imported file is [`lib.d.ts`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts) and the typings for the Proxy object are not declared. That's why you are getting the TypeScript error. 

I added type definitions for Proxy (just to test) and I was getting another error at runtime because Proxy is not defined at runtime. My node.js runtime is `v4.2.1` so this is probably the problem.

We need to use a polyfill to ensure that the TravisCI build will work in old node versions. We also need to find how to do it to document it in the [environmemt support and polyfills](https://github.com/inversify/InversifyJS/wiki/Environmemt-support-and-polyfills) wiki page. 

There are two popular polyfills:
- [harmony-reflect](https://www.npmjs.com/package/harmony-reflect) (I tried this but t conflicts with the reflect-metadata polyfill).
- [harmony-proxy](https://www.npmjs.com/package/harmony-proxy)

We need to try with the second one and probably create the `harmony-proxy.d.ts` file and send it to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project. 

I hope this makes sense... 

Please let me know if it is not clear enough.

**Comment by remojansen** [comment]
Please take a look to https://github.com/inversify/InversifyJS/pull/117 it seems to be fixed but I'm waiting for [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8532) to remove a [hard code path to one a fork](https://github.com/inversify/InversifyJS/pull/117/files#diff-f250c91a3af297345966eea7ef8d2116R10). I have created an issue for this: https://github.com/inversify/InversifyJS/issues/118
