### ISSUE TITLE
Inversify: Not compiling after adding "types": ["reflect-metadata"] to tsconfig.json

### ISSUE THREAD

**Issue by algolee** [inversify/InversifyJS#1066]
I have installed "inversify" and followed the steps to get started.  The steps dictated that I needed to add the following lines to the _tsconfig.json_ file:
...
_"lib": ["es6"],
"types": ["reflect-metadata"],
"experimentalDecorators": true,
"emitDecoratorMetadata": true_
...
When _types: ["reflect-metadata"]_ was added to the _tsconfig.json_ file, unit tests no longer compile and my Redux store fails to build with this error:
```
configureReduxStore.ts(19,7)
      TS2580: Cannot find name '**process**'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
```
I have already installed **@types/node** and the problem continues.

For now i will be removing  _types: ["reflect-metadata"]_ from the _tsconfig.json_ file and see what happens. However, any other suggestions will be nice.

**Comment by tonyhallett** [comment]
when you specify types in tsconfig it affects default type behaviour.  You need to add node to types as well.  It is described in the typescript documentation

**Comment by notaphplover** [comment]
Closing the issue as no feedback from the user was received. Submit a minimum reproduction code of the issue and I'll be happy to have it a look.
