### ISSUE TITLE
Child-container-resolving problem within hierarchical DI

### ISSUE THREAD

**Issue by nighca** [inversify/InversifyJS#1156]
Hi guys, I think the child-container-resolving behavior is not correct within hierarchical DI. I will use some example code to show the problem. Given code like this: (typescript)

```ts
import { Container, injectable, inject } from 'inversify'

// options to create containers
// note that this problem is about scope singleton
const options = {
  autoBindInjectable: true,
  defaultScope: 'Singleton'
} as const

// two injectable class: Foo & MockFoo
@injectable()
class Foo {
  value = 'foo'
}

@injectable()
class MockFoo {
  value = 'mock foo'
}

// another injectable class who has a dependency Foo
@injectable()
class Bar {
  constructor(public foo: Foo) {}
}

// create a parent container and request foo and bar from it
const parent = new Container(options)
const fooFromParent = parent.get(Foo)
const barFromParent = parent.get(Bar)

// create a child container and bind Foo to MockFoo
const child = new Container(options)
child.parent = parent
child.bind(Foo).to(MockFoo)

// request foo and bar from the child container
const fooFromChild = child.get(Foo)
const barFromChild = child.get(Bar)
```

## Expected Behavior

We expect these expressions to be true:

```ts
fooFromParent instanceof Foo
barFromParent.foo instanceof Foo
fooFromChild instanceof MockFoo
barFromChild.foo instanceof MockFoo
```

## Current Behavior

While the current behavior is:

```ts
fooFromParent instanceof Foo
barFromParent.foo instanceof Foo
fooFromChild instanceof MockFoo
barFromChild.foo instanceof Foo // problem here
```

When I do `child.bind(Foo).to(MockFoo)`, it build a new binding in the child container. So when we do `child.get(Foo)`, it will do the resolution again and give me an instance of `MockFoo`. 

But when I do `child.get(Bar)`, there is no corresponding binding in the child container, so it will try the parent container. In the parent container, it finds the binding with cached `Bar` instance. As a result, we get the cached `Bar` instance, whose property `foo`'s value is an instance of `Foo`, instead of `MockFoo`.

## Possible Solution

Maybe the behavior I expect can be achieved by dependency analysis: after we did `child.bind(Foo).to(MockFoo)`, we know that cache for `Foo` should not be used for resolution of `Foo`; If we also disable cache for bindings (`Bar` here) who requires `Foo` as dependency, 
we will get a new / correct result for `child.get(Bar)`.

## Context

I'm trying to use inversify in my react project. So I need to construct an injector tree parallel to the component tree. While I implementing the injector tree, I found the unexpected behavior as I described above.

**Comment by tonyhallett** [comment]
Your expectations are incorrect.  This is not how child/parent/autoBindInjectable works.  

```
const parent = new Container(options)
//this create a binding in the parent container - bind(Foo).toSelf();
const fooFromParent = parent.get(Foo)
////this create a binding in the parent container - bind(Bar).toSelf();
const barFromParent = parent.get(Bar)

// create a child container and bind Foo to MockFoo
const child = new Container(options)
child.parent = parent
child.bind(Foo).to(MockFoo)

// request foo and bar from the child container
const fooFromChild = child.get(Foo)

//******************
//child container has no bindings with service identifier Bar, but parent container does.
//No auto binding in child container and singleton Bar created before is returned.
const barFromChild = child.get(Bar)
```
 
Either make the scope transient or add a new Bar binding to the child container

**Comment by nighca** [comment]
@tonyhallett Thanks for reply.

> Either make the scope transient or add a new Bar binding to the child container

I know that this will not be an issue with scope transient, but that is not my use case.

If you agree that, instinctively the child container should behave like this (I think it's reasonable expectation from a DI library user's view, instead of the DI library author):

```ts
barFromChild.foo instanceof MockFoo
```

It's impossible to do "add a new Bar binding to the child container", because when dependencies become complex, developers are not able to find all such bindings (who injects `Foo` directly or indirectly) by themselves.

**Comment by tonyhallett** [comment]
Perhaps it should be called autoBindIfNotBound.  

As for is it a reasonable expectation for it to behave as you expect it to.  

Is the documentation clear ?

[Support for hierarchical DI systems](https://github.com/inversify/InversifyJS/blob/master/wiki/hierarchical_di.md)
Doc 1) 'When a container at the bottom of the hierarchical structure requests a dependency, the container tries to satisfy that dependency with it's own bindings. If the container lacks bindings, it passes the request up to its parent container.'

[autoBindInjectable](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#autobindinjectable)
Doc 2) 'Manually defined bindings will take precedence'

Step 1) Parent container lacked bindings, no parent to pass request to - auto binding.
Step 2) From Doc 1) Child container lacked bindings, passed the request to parent which it can satisfy due to Step 1.  ( If you had not used the parent  before then the child would have had the binding auto created ) 

Perhaps Doc 2) should state 'bindings are only auto created if there is no existing binding'.

Should the child container behave like this ?  

Personally not sure.  

I would expect that there are use cases for the current behaviour and that your reasonable expectation stems from your current use case.

Perhaps the Container class option autoBindInjectable should become an enumeration to include your desired behaviour.

There is currently another outstanding hierarchical DI issue #954.  Once that is responded to I would happily incorporate that change and yours.

**Comment by nighca** [comment]
@tonyhallett 

Actually the option `autoBindInjectable` is not the key point, I'm just using it to simplify the example code. It's totally ok if I remove that and do binding by hand:

```ts
import { Container, injectable, inject } from 'inversify'

// options to create containers
// note that this problem is about scope singleton
const options = {
  defaultScope: 'Singleton'
} as const

// two injectable class: Foo & MockFoo
@injectable()
class Foo {
  value = 'foo'
}

@injectable()
class MockFoo {
  value = 'mock foo'
}

// another injectable class who has a dependency Foo
@injectable()
class Bar {
  constructor(public foo: Foo) {}
}

// create a parent container and request foo and bar from it
const parent = new Container(options)
parent.bind(Foo).toSelf()
parent.bind(Bar).toSelf()

const fooFromParent = parent.get(Foo)
const barFromParent = parent.get(Bar)

// create a child container and bind Foo to MockFoo
const child = new Container(options)
child.parent = parent
child.bind(Foo).to(MockFoo)

// request foo and bar from the child container
const fooFromChild = child.get(Foo)
const barFromChild = child.get(Bar)
```

Still, it will not give my expected result.

I should admit that the current result is expected according to the hierarchical DI document. What I care is that it is not expected for real use case. I will try to explain:

IMO a container works like an environment, which provides different resources. Each resource in the environment will be bound to a unique identifier who tells the role of the resource. We expect that there is only one resource (at least only one type of resource) exists in one environment corresponding to one identifier. For example, when we bind `cup` to `red-cup` in one kitchen, we expect that all cups that will be used in this kitchen are `red-cup`s.

My problem is, based on current behavior of inversify, we get `red-cup`s if we use it directly, while we may get `blue-cup` if we use a coffee-maker and it requires a cup, still in this kitchen. I consider this result unexpected, what do you think?

**Comment by tonyhallett** [comment]
```
([true,false] as boolean[]).forEach(constructSingletonInParent => {
        it(`constructing singleton from ${constructSingletonInParent?"Parent":"Child"}`,()=>{
            // options to create containers
            // note that this problem is about scope singleton
            const options = {
                defaultScope: 'Singleton'
            } as const
            interface ICup{
    
            }
            @injectable()
            class RedCup implements ICup{}
            @injectable()
            class BlueCup implements ICup{}
    
            interface ICoffeeMachine{}
            @injectable()
            class RedSingletonCoffeeMachine{
                constructor(@inject("Cup") public cup: ICup){}
            }
            
            const redReserveKitchen = new Container(options);
            redReserveKitchen.bind("Cup").to(RedCup);
            redReserveKitchen.bind(RedSingletonCoffeeMachine).toSelf();
            if(constructSingletonInParent){
                //assemble the RedSingletonCoffeMachine with the parts in this kitchen
                redReserveKitchen.get(RedSingletonCoffeeMachine);
            }
    
            const blueMainKitchen = new Container(options);
            blueMainKitchen.parent = redReserveKitchen;
            blueMainKitchen.bind("Cup").to(BlueCup);
    
            //ask the waiter for a cup we get the ( only cup ) from the main kitchen
            expect(blueMainKitchen.get("Cup")).toBeInstanceOf(BlueCup);

            //ask the waiter for the cup that comes with the red singleton coffee machine
            //if has not already been assembled by the parent is assembled with the parts in blue kitchen
            const redSingletonCoffeeMachineCup = blueMainKitchen.get(RedSingletonCoffeeMachine).cup;
            expect(redSingletonCoffeeMachineCup).toBeInstanceOf(constructSingletonInParent?RedCup:BlueCup);
    
        })
    });
```

I expect the result that we get.  The coffee maker has been assembled and it is a singleton.  There being a blue cup in the blue kitchen is not going to make any difference ( to a customer in the blue kitchen that is enjoying drinking coffee from the red cup of the only coffee machine borrowed from the red kitchen ).  If you want the blue kitchen to have a coffee machine with a blue cup then either stop people drinking coffee in the red kitchen, buy a new coffee machine or assemble in the red kitchen each time a coffee machine is required from either the red kitchen or the blue kitchen.

**Comment by nighca** [comment]
@tonyhallett Thank u, but I think you are explaining why it happens, not why it is reasonable.

Suppose that you are the owner of a kitchen. Your part maybe a small part of a big application, so you may not know if someone has called `parentKitchen.get(CoffeeMachine)` somewhere else. You just want to make sure that all the cups used in your kitchen are blue (I think this is a common case). You found that impossible unless you discard **scope singleton**. I say it "impossible", because:

> It's impossible to do "add a new Bar binding to the child container", because when dependencies become complex, developers are not able to find all such bindings (who injects Foo directly or indirectly) by themselves.

But if we take a look at the direct dependency: `cup`. When we do `blueMainKitchen.bind("Cup").to(BlueCup);`, Inversify guarantees us that all **direct**-cups you get from the kitchen will be blue, even if it is under scope singleton and there is already a cached result in the parent kitchen. If you think it is the **scope singleton** which breaks the kitchen-owner's full control over the child kitchen, then I think it will make more sense if `blueMainKitchen.get("Cup")` returns a red cup, too. At least that keeps a consistent behavior: what you get from you container under scope singleton may not be constructed by your logic.

Of course it will be much better if we can guarantee that: anything you get from you container is constructed by your logic, whether under scope singleton or not.

As a conclusion, I think the current strategy breaks scope singleton, by making its behavior inconsistent / unpredictable.

**Comment by tonyhallett** [comment]
Scope singleton will return a singleton and I expect it to do so.  It does what it says on the tin.  

You get the coffee machine then you get the singleton ( that you configured ).  You get the coffee machine again you get the singleton.
You get a cup directly from the blue kitchen you get a singleton blue cup ( that you configured )  and if you get from the red kitchen you get a singleton red cup ( that you configured ).

It is consistent, you get what you configure.  

If you want 'full control' then fully control it.

I think that you are looking for a scope that is not built in, singleton container scope.  You could use toDynamicValue or middleware to achieve your goals.

**Comment by nighca** [comment]
What I mean "inconsistent" is that: rebinding for cup makes (singleton) cache expired for direct access, but not for indirect access in the same container. User has to accept concept of binding and understands that cache / singleton scope is for binding instead of identifier, which seems not so straight forward.

> I think that you are looking for a scope that is not built in, singleton container scope. You could use toDynamicValue or middleware to achieve your goals.

Yes. Maybe you are right that I can get such result by using middleware. I thought it should be the default behavior of scope singleton because I thought "full control" is what most people want. 🤣 

Any way, thanks very much for your reply @tonyhallett

**Comment by jpsfs** [comment]
@tonyhallett I trully believe this is an issue on Inversify.

Taking @nighca example:

```js

import { Container, injectable, inject } from 'inversify'

// options to create containers
// note that this problem is about scope singleton
const options = {
  autoBindInjectable: true,
  defaultScope: 'Singleton'
} as const

// two injectable class: Foo & MockFoo
@injectable()
class Foo {
  value = 'foo'
}

@injectable()
class MockFoo {
  value = 'mock foo'
}

// another injectable class who has a dependency Foo
@injectable()
class Bar {
  constructor(public foo: Foo) {}
}

// create a parent container and request foo and bar from it
const parent = new Container(options)
const fooFromParent = parent.get(Foo)
const barFromParent = parent.get(Bar)

// create a child container and bind Foo to MockFoo
const child = new Container(options)
child.parent = parent
child.bind(Foo).to(MockFoo)

// request foo and bar from the child container
const fooFromChild = child.get(Foo)
const barFromChild = child.get(Bar)

```

When assigning a new DI level:

```js
// create a child container and bind Foo to MockFoo
const child = new Container(options)
child.parent = parent
child.bind(Foo).to(MockFoo)
```

Then when doing:

```js
const barFromChild = child.get(Bar)
```

I believe ```barFromChild.foo``` should be an instance of ```MockFoo``` and not ```Foo```, because at that DI Level, ```Foo``` is implemented by ```MockFoo``` and not ```Foo```.

Any way this behavior could be changed in the future or do you have any suggestion to accomplish this scenario?
