### ISSUE TITLE
[inversify-restify-utils]: new release due to security vuln in dependency

### ISSUE THREAD

**Issue by Pekery** [inversify/InversifyJS#1158]
For inversify-restify-utils:
Due to a security vulnerability in the dependency "csv" (see [here](https://nodesecurity.io/advisories/1171)) would be nice to create a release of the current master branch version.

The current master branch version updates the restify dependency, which already supports the new fixed "csv" [version 5.1.3](https://github.com/adaltas/node-csv). But unfortunately there is no release for this.

## Expected Behavior
New Release version with the fixed dependency.

## Current Behavior
There is no current release version with the updated dependency.

## Possible Solution
Release a new version with the current master branch

**Comment by sublimator** [comment]
Is anyone still maintaining this lib ?

**Comment by f-barth** [comment]
@dcavanagh @tenowg @remojansen @endel @hourliert @jamesadarich @Jameskmonger @ktutnik @lholznagel

Is inversify still maintained? We (https://github.com/Stocard) would be very happy to help in maintaining the lib. Currently, the above issue is blocking our CI pipelines and it would be great if you could create a release of the current master to npm.

**Comment by remojansen** [comment]
Hi @f-barth I gave access to do new releases to @Jameskmonger last week. We need more help because we are all busy with personal stuff... The more people contributing the better. I will try to find some time to merge some of the PRs and do a release.

**Comment by sublimator** [comment]
Great to hear!

**Comment by f-barth** [comment]
Thx for the update @remojansen :) Would be great to see a release in the wild, @Jameskmonger 

What would be the best way to connect / support you guys moving forward?

**Comment by Jameskmonger** [comment]
I'm currently working on clearing the backlog of PRs for inversify-restify-utils and then will publish

@Pekery while I'm here, do you think that `restify` should be a peer dependency of this package, rather than a full dependency?

**Comment by Pekery** [comment]
I think it would improve future issues since the inversify restify utils is more like a plugin here for restify and a simple peer dependency on a major revision should suffice.

And issues like this would not need any involvement from your side

**Comment by danehorak-callaway** [comment]
> I'm currently working on clearing the backlog of PRs for inversify-restify-utils and then will publish

@Jameskmonger Do you have an ETA when you'll have that backlog of PRs taken care of? Any chance we can get an updated version with the vulnerability addressed before the PRs?

**Comment by Jameskmonger** [comment]
@danehorak-zennify I will publish the new version today - sorry for the wait

**Comment by Jameskmonger** [comment]
Unfortunately I don't have the correct access yet to publish this package - I have contacted @remojansen to resolve this

**Comment by danehorak-callaway** [comment]
> Unfortunately I don't have the correct access yet to publish this package - I have contacted @remojansen to resolve this

Thanks @Jameskmonger Please keep us posted.

**Comment by danehorak-callaway** [comment]
@Jameskmonger Any updates on gaining publish access?

**Comment by Jameskmonger** [comment]
Sorry @danehorak-zennify I am still waiting to get the correct access from @remojansen

**Comment by PodaruDragos** [comment]
@Jameskmonger are there any updates regarding this or any of the backlog issues ?

**Comment by iniva** [comment]
@Jameskmonger @remojansen any news about this?

**Comment by aflinchb** [comment]
+1 any updates? @Jameskmonger @remojansen

**Comment by sublimator** [comment]
sad state of affairs :(

**Comment by Jameskmonger** [comment]
I'm afraid I've still not been given publish access for the `inversify-restify-utils` package and not heard from @remojansen since October.

@iniva @aflinchb @sublimator

**Comment by aflinchb** [comment]
Do any of the other inversify team members have suggestions on how to get a version released? 

@dcavanagh @mgebundy @tenowg @remojansen @endel @hourliert @jamesadarich @Jameskmonger @ktutnik @lholznagel

**Comment by lholznagel** [comment]
Sorry for the late reply, I don´t have the repo watched.

I just tried to publish it, but I don´t have the permissions to do so :(

**Comment by jamesadarich** [comment]
@aflinchb having a brief look at this looks like @remojansen has been inactive on github for quite some months now, so getting this done urgently I would say is unlikely.

It's probably worth emailing him (email is on his github profile) to check in to see if circumstances have changed for him which mean that he can no longer.

If either he doesn't get back to you or this is a super urgent vulnerability for you to get solved I would suggest either a fork and publish, or a fork and add a `prepare` script so you can install from your forked repo (looks like that `prepare` script would simply be `gulp` from a quick look at that repo).

If Remo no longer has the capacity to support this collection of projects then I'd suggest that it's best that an alternative arrangement is figured out how to maintain in the long term. Personally I probably don't have capacity to lead on this at the moment due to other commitments but I'm happy to help and advise with this. Let me know how you get on @aflinchb contacting Remo and we can figure out what's best for the future.

**Comment by aflinchb** [comment]
Thanks @jamesadarich -- I will try emailing him and look into the fork and publish option as well. 

I will let you know if I hear back (and if I don't).

**Comment by aflinchb** [comment]
@jamesadarich - I have not been successful at contacting Remo.  My team does not prefer the option of forking our own version (as we also do not have the capacity to lead/own the dependency).  I am sure there are many others leveraging this package, is there a way to go through github/npm to transfer/assign access?

**Comment by Jameskmonger** [comment]
I also haven't heard from Remo for quite some time. I have access to publish to npm for some packages, but not all.

**Comment by PodaruDragos** [comment]
@aflinchb last time i contacted @remojansen, i wrote him on twitter and he responded

**Comment by ekenigs** [comment]
@Jameskmonger on his website there is a link to his LinkedIn account https://www.linkedin.com/in/remojansen/

**Comment by dcavanagh** [comment]
I used to have publish access and tried today but I don't anymore. I'll see what I can figure out

**Comment by dcavanagh** [comment]
Just published 3.4.1 let me know if that helps

**Comment by aflinchb** [comment]
@dcavanagh - Thank you!!

**Comment by robertgr991** [comment]
Any chances someone continues maintaining this? It's a great lib and I haven't found yet a similar lib that has all this features and such a friendly API.

**Comment by PodaruDragos** [comment]
@dcavanagh are there any plans to merge some of the PR's here and in other packages ( inversify-express-utils ) ?

**Comment by Jameskmonger** [comment]
@dcavanagh Which packages do you have publish rights to?

I have access to publish `inversify` only - but I seem to have GitHub merge access on a few.
