### ISSUE TITLE
How to inject array of same binding

### ISSUE THREAD

**Issue by reachmehere89** [inversify/InversifyJS#1168]
Need help to find out how to inject an array of one binding.
@multiInject allows array but it injects all bindings of same type and not one binding.

Ex: 
Suppose I have below binding
container.bind('xyz').to(XYZ)

now I need to inject something like :
@inject('xyz') variable: XYZ[];

Where I'm expecting to get an array of XYZ instance injected with a specified value given a runtime.

Does factory Pattern will work here? If yes, Please give example on how this can be achieved using factory pattern.

**Comment by AEPKILL** [comment]
```typescript 
import { Container as IocContainer, injectable } from 'inversify';

const container = new IocContainer();

@injectable()
class Xyz {}

container
  .bind('xyz')
  .to(Xyz)
  .onActivation((_ctx, injectable) => {
    return [injectable];
  });

// or
// container.bind('xyz').toDynamicValue(_ctx => {
//   return [_ctx.container.resolve(Xyz)];
// });

```

maybe can help you

**Comment by notaphplover** [comment]
Hey @reachmehere89, when you `@multiInject('xyz')`, you should get all the bindings you want. If you only want one of them, you can name them and `@multiInject`, so inversify will provide an array with the tagged binding:

```ts
class Foo {
  @named('my-awesome-name')
  @multiInject('xyz')
  public variable!: [XYZ];
}
```
