### ISSUE TITLE
confused about tsconfig.json mandatory attributes not being needed on my example

### ISSUE THREAD

**Issue by malarres** [inversify/InversifyJS#1172]
## Expected Behavior

In the documentation I read that `tsconfig.json` should have

````
{
    "compilerOptions": {
        "target": "es5",
        "lib": ["es6"],
        "types": ["reflect-metadata"],
        "module": "commonjs",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
````

## Current Behavior

However in my project I have

````
 "target": "es2018",    
    // "lib": [],      
  "types": ["node"],       
  "module": "commonjs",   
 // "moduleResolution": "node",   
"experimentalDecorators": true,
"emitDecoratorMetadata": true, 

````

And it's still working, so now I'm confused.

## Context

Could it be because I have just used a minimum portion of the library and I will find problems in the future? May it be due to my project being deployed as AWS lambda?

## Your Environment

* Version used:
````

 "inversify": "^5.0.1",
    "reflect-metadata": "^0.1.13"
````
* Environment name and version (e.g. Chrome 39, node.js 5.4):
nodejs v10.16.3
* Operating System and version (desktop or mobile):
w10

Thanks,

**Comment by kegi** [comment]
"**moduleResolution**" is automatically set to "**node**" if you use ```"module"="commonjs"```.
Also, if missing, "**lib**" is automatically set to defaults values based on your "**target**" value.

source : https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options
