### ISSUE TITLE
Revisiting import "reflect-metadata"

### ISSUE THREAD

**Issue by rweads0520** [inversify/InversifyJS#1189]
Different aspects of this have been covered in many forums, but I'd like to revisit to get some clarity and current thoughts. Is there no way the library can be updated to avoid this requirement? I don't see this requirement in other libraries that use TypeScript decorators. In its current state, it appears that even using modern javascript engines, e.g. Node.js 12+, and the documented additions to tsconfig.json, I still have to have `import "reflect-metadata"` at least once somewhere in the app. If it was only in the main app entry points that would be manageable, but in the case of unit tests that means in every spec file as well.

If you forget, it causes no compile-time errors, only run-time errors. So IDE's that make it easier to import required modules and highlight errors don't know anything about it. You just have to remember to add this seemingly arbitrary import every time or things don't work.

Great library, just this one issue adds a little confusion getting it to work.

**Comment by yuric18** [comment]
Hi, @rweads0520! 

Great points mentioned. Looking forward to a newer version that solves this issue (even 3 years after this issue). For now, all that I recommend is to have a setup file and import `reflect-metadata` on it. This way it's not needed to import it on every single test file.

```typescript
// .vitest/setup.ts
import 'reflect-metadata'


// vitest.config.ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    // ...
    setupFiles: ['.vitest/setup.ts']
  },
})

```

**Comment by thevuong** [comment]
v8 migrated to peerDependency but still requires reflect-metadata. With TC39 decorator metadata (Symbol.metadata) now stable in TS 5.2+, is there a roadmap to support zero-reflect-metadata mode using native accessor + TC39 metadata?

**Comment by notaphplover** [comment]
> is there a roadmap to support zero-reflect-metadata mode using native accessor + TC39 metadata?

`Symbol.metadata` might be available in Typescript, but most browsers and node still don't provide it.

Having said that, the real blocker is this one: tc39 doesn't provide parameter decorators, so I'd love to know what's your proposal to adopt it while keeping a developer friendly decorator API such as `inject`. I am really looking forward to using the latest standards, but I won't adopt them at the expenses of having a worse developer experience.

I would prefer not to run off-topic, so if you're interested to delve into the details of the current approach or propose tc39 adoption, please consider opening an issue or a discussion in the [monorepo](https://github.com/inversify/monorepo).
