### ISSUE TITLE
Using react-redux , is it possible, how to use?

### ISSUE THREAD

**Issue by johnico** [inversify/InversifyJS#1192]
I would like to use inversify in react-redux application but only in the service layer

I have  a settingsService that need to call to API (Http service) 
I would like a kind of provider that will give me the option to call settingsService.get() in the actions.ts file 

my actions.ts file :

```
export const increment = () => (dispatch: any) => {
  dispatch({
    type: INCREMENT
  });
};
```

My settings Service

```
@injectable()
export class SettingsService implements Settings {
@inject(TYPES.Test) private testService!: Test;
  get() {
   // some api call
    return this.testService.test();
  }
}

```

My inversify.ts

```
const container = new Container();

function init() {
  container
    .bind<Settings>(TYPES.Settings)
    .to(SettingsService)
    .inSingletonScope();
  container
    .bind<Test>(TYPES.Test)
    .to(TestService)
    .inSingletonScope();
}

export { container, init };

```

My question :
1 - where do I initialize the services? is the definition in iversify.ts is ok? do I need to initialize the container in index.ts on the react app? now I call init() in index.ts 

2 - how do I call to settingsService in the actions.ts ( action.ts is not class-based) is a redux action function 

3- should easy to test 

## Your Environment
React, redux , typescript

**Comment by vitorfreitas** [comment]
One way of solving this is by transforming your `actions.ts` in a factory

```ts
class ActionsFactory {
  constructor(@inject settingsService: SettingsService) {}

  static create () {
    return {
      increment: this.increment
    }
  
  private increment(dispatch) {
    dispatch({ type: INCREMENT })
  }
}

...

// Usage
const actions = ActionsFactory.create()

// or using object destructuring
const { increment } = ActionsFactory.create()
```

I don't see any problems on calling `init()` at index.ts, perhaps there is a better way but by far I think this solves the problem very well.

**Comment by johnico** [comment]
@vitorfreitas thanks 

In component or reducer
, i call the actios like this 
`const { increment } = ActionsFactory.create()`

Instead of regular import ? 
How do i test it with jest?

Do i neesto convvert the reducer to class also?
Thamks a lot

**Comment by vitorfreitas** [comment]
Yeah, that's right. You will import your ActionsFactory and only that.

As you're using an dependency injection container, you can pass a stubbed instance of you dependency (SettingsService) into the ActionsFactory and write your tests as you want.

**Comment by notaphplover** [comment]
Closing as the issue seems to be resolved
