### ISSUE TITLE
Broken @lazyInject decorator in TypeScript >=3.7

### ISSUE THREAD

**Issue by BANOnotIT** [inversify/InversifyJS#1212]
@lazyInject relies on instrumenting class prototype and prototype bubble mechanism. For now in TS >= 3.7 any of decorators from [inversify-inject-decorators](https://github.com/inversify/inversify-inject-decorators) don't work

## Why worked earliar
1. `@lazyInject*` instruments prototype of class with getter and setter for field `something`
2. developer tries to access that property like so: `classInstance.something.doSomething`
    1. JS finds no `something` propery in current instance
    2. JS find `something` getter in `classInstance.__proto__`
    3. JS calls inversify resolver
    4. ...
    5. PROFIT!!!

## Current Behavior
1. `@lazyInject*` instruments prototype of class with getter and setter for field `something`
2. TS [instruments `classInstance` with `something` getter on construction](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier)
3. developer tries to access that property like so: `classInstance.something.doSomething`
    1. JS **finds** `something` propery getter in current instance
    2. ~~JS find `something` getter in `classInstance.__proto__`~~
    3. ~~JS calls inversify resolver~~
    4. ~~...~~
    5. ~~PROFIT!!!~~

## Possible Solution
For now there are two solutions:
1. downgrade to TS 3.6
2. use `"useDefineForClassFields": false` in `tsconfig.json` -- set by default

**Comment by MirKml** [comment]
Hm, seems as potential trouble in the future, because TS team wants to use DefineForClassFields compiler strategy as default as I understood.

**Comment by TheBudgetMan** [comment]
This is an issue for us as well, because of using mobX with Inversify. [MobX 6.x requires the setting of useDefineForClassFields to true](https://github.com/mobxjs/mobx/discussions/3216) (or the Babel equivalent `["@babel/plugin-proposal-class-properties", { "loose": false }]`), which breaks `lazyInject`. Is there any update on this issue?

**Comment by unknown1337** [comment]
> This is an issue for us as well, because of using mobX with Inversify. [MobX 6.x requires the setting of useDefineForClassFields to true](https://github.com/mobxjs/mobx/discussions/3216) (or the Babel equivalent `["@babel/plugin-proposal-class-properties", { "loose": false }]`), which breaks `lazyInject`. Is there any update on this issue?

same issue here :(

**Comment by notaphplover** [comment]
As discussed in [a recent issue](https://github.com/inversify/InversifyJS/issues/1678#issuecomment-2539968294), the package is being archived their usage is discouraged.
