### ISSUE TITLE
React ts typing failed on conpile  when set types: "reflect-metadata"in tsconfig

### ISSUE THREAD

**Issue by johnico** [inversify/InversifyJS#1216]
I am trying to add 
``
types:["reflect-metadata" ,"node"] 
``
Or just with reflect-metadata 

And when its set the react app using create-react-app is faile to conpile abd o got errors on serviceWorker.ts aboit node typing .

I already installed all packages like reflect-metada also with @types/reflect-metadata
And installed @types/node

looks like its skip typing after reflect netadata has been adedd .

For now i removed it and it works but i guess I will need it .

**Comment by notaphplover** [comment]
You don't need to add `reflect-metadata` types, you just need to import the module so the `ReflectMetadata` API is available.
