### ISSUE TITLE
getServiceIdentifierAsString uses Function.name property which is not avbialable in internet explorer

### ISSUE THREAD

**Issue by rent-a-developer** [inversify/InversifyJS#1218]
The function getServiceIdentifierAsString causes issues when run in internet explorer, because it uses the property Function.name which is not supported in internet explorer.

## Expected Behavior
The function getServiceIdentifierAsString should not use Function.name.
It should use the getFunctionName function instead.

## Current Behavior
In the function getServiceIdentifierAsString the property Function.name is used (see https://github.com/inversify/InversifyJS/blob/068732327fcbfe061975d1400e582120fea4ea36/src/utils/serialization.ts#L7). Function.name in IE returns undefined, which causes issues for example in the function _validateActiveBindingCount (see https://github.com/inversify/InversifyJS/blob/068732327fcbfe061975d1400e582120fea4ea36/src/planning/planner.ts#L109).

## Possible Solution
The function getServiceIdentifierAsString should use the getFunctionName function (see https://github.com/inversify/InversifyJS/blob/068732327fcbfe061975d1400e582120fea4ea36/src/utils/serialization.ts#L127) instead of the Function.name property.

## Steps to Reproduce (for bugs)

1. Do anything that causes InversifyJS to call the getServiceIdentifierAsString (with parameter serviceIdentifier being a function), e.g. call Container.get for an object that has a dependecy that is not registered to the container.

## Your Environment

* Version used: 5.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Internet Explorer 11
* Operating System and version (desktop or mobile): Windows 8.1 64 Bit

# Stack trace

**Comment by notaphplover** [comment]
We don't support internet explorer. If possible, I would suggest you to rely on polyfills.
