### ISSUE TITLE
Annotating dependencies with inversify.inject() and inversify.decorate() produces a TypeScript type error

### ISSUE THREAD

**Issue by baronswindle** [inversify/InversifyJS#1222]
My project is using TypeScript for type checking and Babel to compile the TypeScript source to JavaScript. Because the current TC39 proposal for decorators does not current include support for parameter decorators, we're using the `inversify.decorate()` method to annotate our classes. However, when we use the `inversify.inject()` decorator, we're getting a type error.

```
Argument of type '(target: any, targetKey: string, index?: number | undefined) => void' is not assignable to parameter of type 'ClassDecorator | ParameterDecorator | MethodDecorator'.
  Type '(target: any, targetKey: string, index?: number | undefined) => void' is not assignable to type 'ClassDecorator'.
```

Root cause seems to be that the return type of `inversify.inject()` is not compatible with the `ParameterDecorator` type from TypeScript's `lib.es5.d.ts`. The `targetKey` argument can be a `string` or `symbol` in `ParameterDecorator`, but it's defined as `string` only in the return type of `inversify.inject()`.

## Expected Behavior
The following lines of code SHOULD NOT generate a 
```ts
inversify.decorate(inversify.inject(TYPES.KATANA), Ninja, 0);
inversify.decorate(inversify.inject(TYPES.SHURIKEN), Ninja, 1);
```

## Current Behavior
The lines of code above DO produce a type error.

## Steps to Reproduce (for bugs)
I've pushed up a pretty minimal example to reproduce the type error.
https://github.com/baronswindle/inversify-bug/tree/6149a7694d124aa84796aba463615142ec5565bd

Once you've cloned the repo, run `npm install` followed by `npx tsc`.

**Comment by monteki** [comment]
Same here. Any solutions?

**Comment by vzkhrv** [comment]
> ```
> Argument of type '(target: any, targetKey: string, index?: number | undefined) => void' is not assignable to parameter of type 'ClassDecorator | ParameterDecorator | MethodDecorator'.
>   Type '(target: any, targetKey: string, index?: number | undefined) => void' is not assignable to type 'ClassDecorator'.
> ```

Same here. Any solutions?

**Comment by sonewman** [comment]
I’m no wizard, but I think you should be using `injectable` and not `inject`

**Comment by valjusha** [comment]
@baronswindle Where did you end up?

**Comment by baronswindle** [comment]
@valjusha Inversify is effectively a dead project. Though some maintainers are able to merge PRs, the only person with the ability to publish to npm is no longer around, and nobody has been able to reach them. Thus, I'm investigating alternative DI libraries. In the meantime, I'm working around it using type assertion. Here's a utility function I'm using:
```ts
import * as inversify from 'inversify';

interface AnnotateOptions {
  injectable?: boolean;
  inject?: (string | symbol)[];
}

export function annotate(options: AnnotateOptions) {
  return function decorate<T extends NewableFunction>(target: T): T {
    if (options.injectable) {
      inversify.decorate(inversify.injectable(), target);
    }
    if (options.inject) {
      options.inject.forEach((parameter, i) => {
        inversify.decorate(
          inversify.inject(parameter) as ParameterDecorator,
          target,
          i,
        );
      });
    }
    return target;
  };
}
```

**Comment by nstratton-lfa** [comment]
They published a new update in Dec 2020. So not dead, although it had been two years since the previous update.

**Comment by notaphplover** [comment]
> @valjusha Inversify is effectively a dead project. Though some maintainers are able to merge PRs, the only person with the ability to publish to npm is no longer around, and nobody has been able to reach them. Thus, I'm investigating alternative DI libraries. In the meantime, I'm working around it using type assertion. Here's a utility function I'm using:
> 
> ```ts
> import * as inversify from 'inversify';
> 
> interface AnnotateOptions {
>   injectable?: boolean;
>   inject?: (string | symbol)[];
> }
> 
> export function annotate(options: AnnotateOptions) {
>   return function decorate<T extends NewableFunction>(target: T): T {
>     if (options.injectable) {
>       inversify.decorate(inversify.injectable(), target);
>     }
>     if (options.inject) {
>       options.inject.forEach((parameter, i) => {
>         inversify.decorate(
>           inversify.inject(parameter) as ParameterDecorator,
>           target,
>           i,
>         );
>       });
>     }
>     return target;
>   };
> }
> ```

Hi @baronswindle, @monteki, @valjusha, we are trying to revive this project. We are fixing several bugs in the next patch and we are trying to do some refactors regarding typings. We are aware of this issue, I expect to fix it in the next weeks. For those who cannot wait, I encourage them to have a look at #1311

**Comment by alanyong91** [comment]
> @valjusha Inversify is effectively a dead project. Though some maintainers are able to merge PRs, the only person with the ability to publish to npm is no longer around, and nobody has been able to reach them. Thus, I'm investigating alternative DI libraries. In the meantime, I'm working around it using type assertion. Here's a utility function I'm using:
> 
> ```ts
> import * as inversify from 'inversify';
> 
> interface AnnotateOptions {
>   injectable?: boolean;
>   inject?: (string | symbol)[];
> }
> 
> export function annotate(options: AnnotateOptions) {
>   return function decorate<T extends NewableFunction>(target: T): T {
>     if (options.injectable) {
>       inversify.decorate(inversify.injectable(), target);
>     }
>     if (options.inject) {
>       options.inject.forEach((parameter, i) => {
>         inversify.decorate(
>           inversify.inject(parameter) as ParameterDecorator,
>           target,
>           i,
>         );
>       });
>     }
>     return target;
>   };
> }
> ```

why need this function and where to use it?

**Comment by PodaruDragos** [comment]
this should have been fixed in https://github.com/inversify/InversifyJS/pull/1311.
