### ISSUE TITLE
what kind of sorcery is this?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [inversify/InversifyJS#1224]
I try to find the simplest way to benefit from inversify, how to use it? 
I discovered inversify by looking at some source code in another repository. The concept seems very confusing to me.

There is a part where they just import a service which extends an eventEmitter without starting it, and they can listen to events from that service by adding it inside the constructor ( service : ..) 

I don't understand why it magically connects to the active instance of that service .
I mean they just imported that service, no instance, no initialization, not a single "new" keyword. 
If I import a module in multiple parts of my project it won't run unless i create an instance and start it. 

I look at this code and it seems like a whole new language, its upside down.
How is this possible?

**Comment by Maaartinus** [comment]
> I mean they just imported that service, no instance, no initialization, not a single "new" keyword.

This sounds exactly like it should: [Dependency injection](https://en.wikipedia.org/wiki/Dependency_injection). The `eventEmitter` gets initialized and configured elsewhere and your part gets it injected. Other parts get the same instance, if configured so.

> I look at this code and it seems like a whole new language, its upside down.

That's it: [Inversion of Control](https://en.wikipedia.org/wiki/Inversion_of_control). Note that DI != IoC, but for now, let's ignore the difference.

**Comment by hp8wvvvgnj6asjm7** [comment]
> 
> > I mean they just imported that service, no instance, no initialization, not a single "new" keyword.
> 
> This sounds exactly like it should: [Dependency injection](https://en.wikipedia.org/wiki/Dependency_injection). The `eventEmitter` gets initialized and configured elsewhere and your part gets it injected. Other parts get the same instance, if configured so.
> 
> > I look at this code and it seems like a whole new language, its upside down.
> 
> That's it: [Inversion of Control](https://en.wikipedia.org/wiki/Inversion_of_control). Note that DI != IoC, but for now, let's ignore the difference.

How do i get started with this if my application uses a Crockford class free javascript style?

**Comment by hp8wvvvgnj6asjm7** [comment]
Are there any class free examples of this?

**Comment by hp8wvvvgnj6asjm7** [comment]
do i have to rewrite my whole project to use classes now?

**Comment by hp8wvvvgnj6asjm7** [comment]
```
const config    = require('../config.json').rti
const gateway   = require('./gateway')
const router    = require('./router')
const actions   = require('./actions')
const session   = require('./session')

const log = require('node-color-log')

module.exports = async infra_type => {

    try{

    const [_y_gateway, _y_router, _y_actions, _y_session] = [gateway(config), router, actions, session(config)].map(_y => _y(infra_type))

    const _router   = await _y_router(_y_gateway)

    const _session  = _y_session(_router)
    
    const _actions  = _y_actions(_router)
    
    const active_session = await _session(_actions.shared)
    
    log.info(`${infra_type} - init - success`)

        return {

            shared : _actions.shared,
            specific : _actions.specific,

```

That's what i'm dealing with.. gateway inside router, router has to start gateway, session needs router, actions needs router... session needs actions.. all need config and infra type.. its some sort of DI but i already see that IOC containers would be more helpful. Problem is i'm not using classes at all. Its all just factory functions with encapsulation.
