### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by InExtremaRes** [inversify/InversifyJS#1225]
Hi everyone, hi @dcavanagh. Is this project still under maintenance? Last commit was almost a year ago and there are issues and PRs that have been opened without any answer. Many projects are using this framework (my own included) and it'd be too bad if this is just dying. So I'm asking, what is the status of this project? Are you, @dcavanagh, still maintaining it?

**Comment by Jameskmonger** [comment]
Please see here https://github.com/inversify/InversifyJS/issues/1158

**Comment by ringods** [comment]
@Jameskmonger what I can deduce from the mentioned issue is that besides @remojansen, other contributors have mixed access to the repository and/or the rights to publish NPM packages. Is there a plan of action to rectify this?

FYI, I bumped into Inversify today in my search for DI/IoC support in Typescript. It seems to be the only project which had (some) attention. Without some assurance of a proper maintenance model behind the project, I am a bit scared to integrate it in my solution.

**Comment by PodaruDragos** [comment]
@Jameskmonger maybe you and other core contributors can make a fork and if the time allows, maybe merge some of the PR's. Untill @remojansen comes back.

Do you guys ever considered this alternative ?

**Comment by Jameskmonger** [comment]
@dcavanagh Which packages do you have npm publish rights to?

I have access to publish inversify only - but I seem to have GitHub merge access on a few.

**Comment by remojansen** [comment]
Hi guys, I'm not maintaining it but I have ownership rights to @dcavanagh yesterday. He also has publishing rights for all npm modules. I will not be working on open source for now because I have become too busy with work/personal life. I'm happy for someone to take over.

**Comment by joelday** [comment]
@remojansen Thank you, Remo! Glad to know that you are well.

**Comment by dcavanagh** [comment]
Hi Everyone, I was given ownership rights to inversify. I really need a lot of help getting it back under maintenance. Please let me know if you are able and willing to help out or know of someone who would be a good fit. @Jameskmonger 

- Fix dependencies and gulp 
- Review Pull Requests

**Comment by jlmurphysa** [comment]
Hi @dcavanagh ,

If you and James need a hand, I have some spare capacity to lend a hand with maintaining Inversify.

Have been working with Typescript for some time, and my organization is onboard with helping keep the project alive for the benefit of the JS ecosystem.

We're in a similar position to @ringods - looking to adopt an IoC framework into our stack, but hesitant to select a dependency that has an uncertain future in terms of maintenance.

I'm fairly fresh to OSS, but given nobody else is willing to step up at this point, I should be able to grasp core aspects of the codebase and start getting PRs rolling again over the next few weeks.

**Comment by dcavanagh** [comment]
@Jameskmonger I gave you permission in npm for the rest of the packages

**Comment by leonardssh** [comment]
![image](https://user-images.githubusercontent.com/35312043/109148701-e490da80-7766-11eb-879e-c4a50f75080f.png)

Is this project still under maintenance? ~2021

**Comment by jlmurphysa** [comment]
I planned to get involved, but the year has been crazy so far...

@dcavanagh Can help with code review and getting PRs flowing, but that's about it for now. :/

**Comment by leonardssh** [comment]
Apparently, the work on the project has resumed, that's super awesome. 😊👏

![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2F7rj2ZgttvgomY%2Fgiphy.gif&f=1&nofb=1)

**Comment by PodaruDragos** [comment]
@LeonardSSH what do you mean has resumed ? it's just some commits over the couple of months.

**Comment by leonardssh** [comment]
> 
> 
> @LeonardSSH what do you mean has resumed ? it's just some commits over the couple of months.

It is an initiative. 😊

**Comment by dcavanagh** [comment]
@LeonardSSH @PodaruDragos @jlmurphysa  I need help with reviews

**Comment by PodaruDragos** [comment]
@dcavanagh  I'd like to help. I would also like to submit some PR's myself (like switching to eslint) since tslint is deprecated.
I can maybe tackle that if someone of you guys is interested to join the efforts since it's probably gonna be a big PR.

**Comment by leonardssh** [comment]
@PodaruDragos I would like to help you. 😊

**Comment by dcavanagh** [comment]
@PodaruDragos @LeonardSSH I just pushed a branch where I started migrating to eslint. https://github.com/inversify/InversifyJS/tree/dc/eslint

**Comment by benedyktdryl** [comment]
@dcavanagh may I help with reviews, even if I was never involved in inversify development? If not, how can I help you other way?

**Comment by dcavanagh** [comment]
@benedyktdryl YES!

**Comment by benedyktdryl** [comment]
@dcavanagh do we have any channel on Discord where we can talk more about the project process and priorities? Found a Discord invitation but no channel is enabled for me to chat more.

**Comment by notaphplover** [comment]
@dcavanagh @LeonardSSH @PodaruDragos @jlmurphysa, I'm open to help you guys :). I've never involved in inversify development but I'm open to try it in order to keep this project alive

**Comment by calvinwyoung** [comment]
I'm also happy to pitch in — is there a Discord / Slack / mailing list? Or is all the conversation happening here?

**Comment by leonardssh** [comment]
@calvinwyoung https://discord.gg/jXcMagAPnm

**Comment by bfunc** [comment]
From my point of view, I just need simplest DI container. Would be nice to get very light version of package with only basic functionality.

**Comment by notaphplover** [comment]
Hi @bfunc, I agree, that would be awesome. We are focusing now in bugs and maintainability, I hope we can go that way soon. If you really want a minimalist IoC container and you cannot wait for inversify, I started to write an IoC from scratch inspired on inversify a year ago, trying to figure out exactly that: how a minimalistic IoC should work. For that purpose, I started building [iocuak](https://cuaklabs.github.io/iocuak-docs/) with the following purposes:

1. Figure out which steps we should follow to improve inversify.
2. Focus on core features.
3. Try to get the best of both inversify and NestJs dependency injection system.

If you really want inversify to go that way, you can also contribute to the inversify project :)

**Comment by agorina** [comment]
@dcavanagh , We have been using it for the last 3 years but the lack of updates is very concerning.  Are there any updates on the future of this project?

**Comment by notaphplover** [comment]
Hey @agorina, I'm taking the lead these days, giving the repo some love. I am taking care of issues and iterating towards a monorepo approach while designing the future of the library, step by step. The project is not dead, I'll make sure of it :smile:
