### ISSUE TITLE
[inversify-express-utils] Not found page / 404 error page

### ISSUE THREAD

**Issue by exwyezed** [inversify/InversifyJS#1231]
`inversify-express-utils` does not support 404 error pages?

```ts
server.setConfig(app => {
  app.use((_, res) => {
    res.sendStatus(404)
  })
})

// or 

server.setConfig(app => {
  app.get('*', (_, res) => {
    res.sendStatus(400)
  })
})
```
^When I add this all routes throws out an 404

What's the right way to do it? I can't find any example btw.

**Comment by exwyezed** [comment]
Is this maybe related to https://github.com/inversify/InversifyJS/issues/854?

**Comment by exwyezed** [comment]
All you need to do is add a middleware function at the very bottom of the stack (below all other functions) to handle a 404 response, but for some reason this doesn't work in Inversify... :/

**Comment by alfonmga** [comment]
const server = new InversifyExpressServer(container)
  server.setErrorConfig(app => {
    app.use((_: any, res: Express.Response) => {
      res.sendStatus(404)
    })
  })
