### ISSUE TITLE
Discussion: Proxy Injection API

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#124]
I'm creating this issue to collect some feedback about the proxy injection API.
# A) Current implementation

The current implementation of Proxy injection looks as follows:

```
interface IKatana {
    use: () => void;
}

class Katana implements IKatana {
    public use() {
        console.log("Used Katana!");
    }
}

interface INinja {
    katana: IKatana;
}

@inject("IKatana")
class Ninja implements INinja {
    public katana: IKatana;
    public constructor(katana: IKatana) {
        this.katana = katana;
    }
}
```

```
kernel.bind<INinja>("INinja").to(Ninja);

kernel.bind<IKatana>("IKatana").to(Katana).proxy((katana) => {
    let handler = {
        apply: (target, thisArgument, argumentsList) => {
            console.log(`Starting: ${new Date().getTime()}`);
            let result = target.apply(thisArgument, argumentsList);
            console.log(`Finished: ${new Date().getTime()}`);
            return result;
        }
    };
    katana.use = new Proxy(katana.use, handler);
    return katana;
});
```

```
let ninja = kernelget<INinja>();
ninja.katana.use();
> Starting: 1457895135761
> Used Katana!
> Finished: 1457895135762
```
# B) Alternative implementation

I was wondering based on the feedback from @ktutnik if it is possible to improve it without loosing flexibility.

We could do the following:

```
kernel.bind<IKatana>("IKatana").to(Katana).proxy("use", {
    apply: (target, thisArgument, argumentsList) => {
        console.log(`Starting: ${new Date().getTime()}`);
        let result = target.apply(thisArgument, argumentsList);
        console.log(`Finished: ${new Date().getTime()}`);
        return result;
    }
});
```

Internally we could then generate the ES6 Proxy (no other interception method would be allowed):

```
function proxyMaker(propertyName, handler) {
  function _(instance) {
    instance[propertyName] = new Proxy(instance[propertyName], handler);
    return instance;
  }
}
```

This reduces the amount of work required from developers. My main concern is that I'm not fully sure about this approach working in all scenarios. Also we are forcing developers to use a Proxy. With the current approach developers have more freedom and can do things like not using ES6 Proxy at all.
# C) Can you think about a better way?

Please share them if so!

**Comment by remojansen** [comment]
Based on Ninject:

> The activation actions are run the first time an instance is resolved even if not created by Ninject (e.g. Constants)

I think we need to rename `proxy` and change it for `onActivation` and this method would allow you to do something of your choice with the instance about to be injected and added to the cache. One of the use cases is injecting a Proxy. So **injecting a proxy becomes more a use case than a feature**:

```
kernel.bind<INinja>("INinja").to(Ninja);

kernel.bind<IKatana>("IKatana").to(Katana).onActivation((katana) => {
    let handler = {
        apply: (target, thisArgument, argumentsList) => {
            console.log(`Starting: ${new Date().getTime()}`);
            let result = target.apply(thisArgument, argumentsList);
            console.log(`Finished: ${new Date().getTime()}`);
            return result;
        }
    };
    katana.use = new Proxy(katana.use, handler);
    return katana;
});
```

**Comment by jamesadarich** [comment]
I was pondering about proxies myself and unfortunately because TypeScript doesn't reflect out Interface information it makes it difficult to do any smart proxying.

Perhaps whilst we await proper reflection from the all wonderful Microsoft! :) We can proxy out the bound class. This would mean that we can tell what members a class has and proxy all of them automatically leaving the developer to not do anything. We've proxied out more than we need to but it's more workable from a dev point of view.

**Comment by ktutnik** [comment]
i just thinking the same, i think "proxy" is not a good name. and also i like the B implementation, so proxy is provided by the IOC itself.

by the way my intention to add this "proxy" discussion is the need of AOP feature (interception) support which is a common function in today IOC.

**Comment by remojansen** [comment]
I've been reading about this an the majority of IoC container don't include interception as part of the IoC container itself. They support it via plugins and extensions. So I decided to change `proxy` fro `onActivation`. This can be used for interception and for other purposes.

This example implements interception without the help of plugins or external libraries thanks to ES6 proxies:

```
kernel.bind<INinja>("INinja").to(Ninja);

kernel.bind<IKatana>("IKatana").to(Katana).onActivation((context, katana) => {
    let handler = {
        apply: (target, thisArgument, argumentsList) => {
            console.log(`Starting: ${new Date().getTime()}`);
            let result = target.apply(thisArgument, argumentsList);
            console.log(`Finished: ${new Date().getTime()}`);
            return result;
        }
    };
    katana.use = new Proxy(katana.use, handler);
    return katana;
});
```

If you want you could easily plug in an external library for interception. Here is an example with @ktutnik's Benalu:

```
kernel.bind<INinja>("INinja").to(Ninja);
kernel.bind<IKatana>("IKatana").to(Katana);
kernel.bind<IBenalu>("IBenalu").toValue(Benalu);

kernel.bind<IKatana>("IKatana").to(Katana).onActivation((context, katana) => {

    let Benalu = context.kernel.get<IBenalu>("IBenalu");

    var proxy = Benalu.fromInstance(katana)
        .addInterception(function(i) {

            //filter the invocation
            if(i.methodName == "use"){

                //call the real method
                i.proceed();

                //override the return value
                i.returnValue = "Custom return!";
            }
        })
        .build();
});
```

This is done in #135
