### ISSUE TITLE
toValue

### ISSUE THREAD

**Issue by acopalipsis** [inversify/InversifyJS#126]
```
import {Kernel, inject} from 'inversify';

export const kernel = new Kernel();

class Hero {
    public name: string = 'superman';
}

kernel.bind('hero').to(Hero);

console.log(kernel.get('hero').name); // superman
```

```
import {Kernel, inject} from 'inversify';

export const kernel = new Kernel();

class Hero {
    public name: string = 'superman';
}

kernel.bind('hero').toValue(new Hero());

console.log(kernel.get('hero').name); //  Error: null is not an object!
```

the second option toValue is not working.

**Comment by remojansen** [comment]
Thanks for reporting! I have take a look and I know what's going on but I have spotted a performance optimization. Will let you know as soon as I fix it (probably tonight).

**Comment by remojansen** [comment]
Hi @acopalipsis this has been resolved but it has not been released yet. I will try to remember to notify you once we do a release but please keep an eye for releases.

**Comment by remojansen** [comment]
Release `2.0.0-alpha.4` is out live demo available at https://tonicdev.com/remojansen/inversify-2.0.0-alpha.4
