### ISSUE TITLE
Share state between containers.

### ISSUE THREAD

**Issue by lillallol** [inversify/InversifyJS#1276]
So lets say I have published two different packages in npmjs. Lets call them A and B. They are not libraries and they work in nodejs.

Here is how package's A entry point file look like :
```ts
import { Container } from "inversify";
    
export const container = new Container();
    
export const TYPES = {
    	logState: Symbol(),
    	logStart: Symbol(),
    	logEnd: Symbol(),
    	log: Symbol(),
    	//more symbols
    	A: Symbol(),
};
    
// registration omitted for brevity
    
export type interfaces = {
    	logState: {depth: number};
    	logStart: (...args: unknown[]) => void;
    	logEnd: (...args: unknown[]) => void;
    	log: (...args: unknown[]) => void;
    	/* a lot of other interfaces that are registered to the dic and needed from A */
    	A: string /*or whatever type*/;
};
    
export const composeEntryPoint: () => interfaces["A"] = () => {
    	return container.get<interfaces["A"]>(TYPES.A);
};
```
Replace A with B and this is also how modules B look likes.

Here is an example of what the loggers are supposed to do :
```ts
logStart("domToPdf");
logStart("scrollingForLazyLoad");
log("dom to be scrolled located");
log("finished scrolling");
logEnd("successfully executed");
logEnd("successfully executed");
```
logs to the console the following message :
```txt
┏ domToPdf
┃ ┏ scrollingForLazyLoad
┃ ┃ dom to be scrolled located
┃ ┃ finished scrolling
┃ ┗ successfully executed
┗ successfully executed
```
`logStart`, `logEnd` and `log` share the common state `logState` so that they can properly indent their logged message.

I want to use both of these modules : A , B , to create a third module called C which has an entry point file that looks like this : 
```ts
import {Container} from "inversify";
import { container as containerA, TYPES as TYPESB , interfaces as interfacesA} from "A";
import { container as containerB, TYPES as TYPESA , interfaces as interfacesB} from "B";
    
export const containerC = Container.merge(containerA,containerB);
    
export const TYPES = {
    	logState: Symbol(),
    	logStart: Symbol(),
    	logEnd: Symbol(),
    	log: Symbol(),
    	//more symbols
    	C: Symbol(),
};
    
// registration omitted for brevity
    
export type interfaces = {
    	logState: {depth: number};
    	logEnd: (...args: unknown[]) => void;
    	log: (...args: unknown[]) => void;
    	logStart: (...args: unknown[]) => void;
    	/* a lot of other interfaces that are registered to the dic and needed from A */
    	C: string /*or whatever type*/;
};
    
export const composeEntryPoint: () => interfaces["C"] = () => {
    	return containerC.get<interfaces["C"]>(TYPES.C);
};
```
In module C, I want the merged registration of container A and B to use the `logState` of C so that all modules A,B,C have common log state and not three independent log states.

The issue that I am facing is that even if I merge the containers or apply hierarchical containers, the final container will have three registrations for the logger state that each has different symbol, and the registrations from A B and C will depend on their corresponding logState symbol .

The only solution that I see is un-registering the logState from A and B imported containers. Then replace in all registrations the symbol of logState for package A and B with the symbol of logState for package C.

But my issue is that as far as I know inversify js does not provide any such built in replace-symbol-with-another-symbol functionality. Why ? Is there any different way to do it ? Am I missing something?

**Comment by notaphplover** [comment]
I would need to see a minimum reproduction code example to be totally sure, but my guess is you're not using Type `symbol` properly. `Types.logState` from your `A` package is different than `Types.logState` from your `B` package. Consider using `Symbol.for('your-symbol-alias')` instead.

Closing the issue now. Consider submitting a code sandbox or a reproduction repository with a minimum repreoduction code of your issue. If I have some time I'll have it a look :smiley:. Having said that, StackOverflow is a way better forum for this kind of issues.
