### ISSUE TITLE
Error: Cannot apply @injectable decorator multiple times.*

### ISSUE THREAD

**Issue by nsd-david** [inversify/InversifyJS#1277]
I'm getting this error
**Exception: Error: Cannot apply @injectable decorator multiple times.**

because `var inversify = require('inversify');` makes inversify global.

```
var inversify = require('inversify');
const EmailService = require('../services/EmailService');

module.exports = async (req, context) => {
  inversify.decorate(inversify.injectable(), EmailService);
  const container = new inversify.Container();
  container.bind('emailService').to(EmailService).inSingletonScope();

  context.res = {
    status: 200,
    body: 'body'
  };
  context.done();
};
```

When I run this function the first time everything works. Then every single call after fails with the cannot apply decorator multiple times exception.

`var inversify = require('inversify');` gets called when I start the function, and `inversify.decorate(inversify.injectable(), EmailService);` gets called each time I call the function, so the problem is that inversify gets initialized once, but decorate gets called multiple times.

I'm able to get around the problem by calling `inversify.decorate(inversify.injectable(), EmailService);` globally along with `var inversify = require('inversify');`
```
var inversify = require('inversify');
inversify.decorate(inversify.injectable(), EmailService);
const EmailService = require('../services/EmailService');

module.exports = async (req, context) => {
  const container = new inversify.Container();
  container.bind('emailService').to(EmailService).inSingletonScope();

  context.res = {
    status: 200,
    body: 'body'
  };
  context.done();
};
```

Another solution that works is
```
var inversify = require('inversify');
const EmailService = require('../services/EmailService');

module.exports = async (req, context) => {
  const container = new inversify.Container();
  container.bind('emailService').toConstantValue(new EmailService());

  context.res = {
    status: 200,
    body: 'body'
  };
  context.done();
};
```

I tried moving `var inversify = require('inversify');` inside the module.exports function, but it seems to still be global.

What's the correct way to solve this problem? Why does inversify need to be global? Also what's advantage of using 
```
inversify.decorate(inversify.injectable(), EmailService);
container.bind('emailService').to(EmailService).inSingletonScope();
```
instead of
`container.bind('emailService').toConstantValue(new EmailService());`

If I ever need to use EmailService in another class, I can just use `toDynamicValue` or `toFactory` and `context.container.get('emailService')`

That way I never need to call `inversify.decorate(inversify.inject('emailService'), ClassThatNeedsEmailService, 0);` which seems more complicated than `toDynamicValue` or `toFactory`

## Expected Behavior

inversify shouldn't be global, or there should be a way to instantiate inversify

## Current Behavior

inversify is global, but decorate isn't which causes inversify to be called once and decorate to be called multiple times on the same inversify object

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm using Inversify with Azure Functions to avoid instantiating classes multiple times

## Your Environment

I'm using vanilla Javascript (Node.js v12.18.2) on Azure Functions.

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by notaphplover** [comment]
Hi @nsd-david, I would need a minimal example to reproduce this, but I think the way inversify is initialized is not related to this issue. It doesn't matter how inversify is initialized, if you decide to apply the `inversify.injectable()` multiple times to the same class this error should be thrown. It's not about global or local scope, it's about decorating one or multiple times. I would suggest you to decorate `EmailService` in the same module where is declared, this way it should be decorated once:

```js
var inversify = require('inversify');

class EmailService {
  // your stuff here
}

inversify.decorate(inversify.injectable(), EmailService);

module.exports = EmailService;
```

**Comment by nsd-david** [comment]
@notaphplover yeah that would probably work.
