### ISSUE TITLE
Support dynamic container in inversify-inject-decorators

### ISSUE THREAD

**Issue by gshokanov** [inversify/InversifyJS#1279]
Hello 👋 !

I'm working on a project that creates container dynamically at runtime using a factory function. Unfortunately this doesn't play nicely with `inversify-inject-decorators` since it requires container's instance available before the application gets a chance to bootstrap. The issue could be fixed if `getDecorators` accepted a container selector as well as container instance. This is how it could be used:
```ts
import getDecorators from 'inversify-inject-decorators';
import { getContainer } from './inversify.config';

const { lazyInject } = getDecorators(getContainer);
```

In order for that to work `getContainer` signature should look something like this:
```ts
function getDecorators(container: interfaces.Container | () => interfaces.Container, doCache = true) {
  // Code here
}
```

I took a look at the source code and it seems pretty straightforward to implement. Is this something that can be done?

**Comment by notaphplover** [comment]
As discussed in [a recent issue](https://github.com/inversify/InversifyJS/issues/1678#issuecomment-2539968294), the package is being archived their usage is discouraged.
