### ISSUE TITLE
how to use it with functions, no classes?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [inversify/InversifyJS#1284]

**Comment by kferrone** [comment]
Factory injection: https://github.com/inversify/InversifyJS/blob/master/wiki/factory_injection.md
Or Provider injection for async: https://github.com/inversify/InversifyJS/blob/master/wiki/provider_injection.md

**Comment by hp8wvvvgnj6asjm7** [comment]
thx
