### ISSUE TITLE
Migrate to Eslint

### ISSUE THREAD

**Issue by dcavanagh** [inversify/InversifyJS#1295]
tslint is deprecated.

**Comment by leonardssh** [comment]
I'm working on that.

**Comment by leonardssh** [comment]
I created a special discord server for the community, join us too! 
https://discord.gg/jXcMagAPnm

@benedyktdryl  @mgebundy @Jameskmonger @jlmurphysa @remojansen @dcavanagh

**Comment by notaphplover** [comment]
Closing as already done
