### ISSUE TITLE
What should I do if I want to multiInject multiple targetName?

### ISSUE THREAD

**Issue by ytetsuro** [inversify/InversifyJS#1300]
I want a Ninja per Weapon in every game board class.

```typescript
@injectable()
class Katana implements Weapon {
    public hit() {
        return "cut!";
    }
}

@injectable()
class Shuriken implements Weapon {
    public hit() {
        return "hit!";
    }
}

@injectable()
class Ninja implements Warrior {
    public constructor(
	    @inject(TYPES.Weapon) private readonly weapon: Weapon
    ) {
    }

    public fight() { return this._katana.hit(); }
}

@injectable()
class GameBoard {
    public constructor(
	    @multiInject(TYPES.Warrior) private readonly warriors: Warrior[]
    ) {
    }
}

const container = new Container();
container.bind(TYPE.Weapon).to(Shuriken).whenTargetName('shuriken');
container.bind(TYPE.Weapon).to(Katana).whenTargetName('katana');
container.bind(TYPE.Warrior).to(Ninja);
container.bind(GameBoard).to(GameBoard);

// ???
```

## Expected Behavior

I want an instance that is equivalent to the following code.

```typescript
new GameBoard([
  new Ninjya(new Katana()),
  new Ninjya(new Shuriken()),
]);
```

## Current Behavior

Can't do this currently?

**Comment by dcavanagh** [comment]
I think the best way to do this would be to use a factory.

**Comment by ytetsuro** [comment]
@dcavanagh

Thanks for taking the time to reply.
I think the only current solution is probably to create a factory.
Does inversifyJS want to change to allow multiple target names in multiInjection?
Is it worth the PR to make that change?

**Comment by dcavanagh** [comment]
@ytetsuro we are pretty swamped trying to revive this project. Are you interested in helping out? 

Could you describe your proposal some more and we can have a discussion about it.

**Comment by notaphplover** [comment]
As said, a factory is probably the way to go. Trying to multiInject a service with a single binding should return a single Ninja.
