### ISSUE TITLE
Automatic self-binding of concrete types

### ISSUE THREAD

**Issue by fabis94** [inversify/InversifyJS#1302]
The docs show how to shorten self-bindings like so:
```
container.bind<Samurai>(Samurai).toSelf();
```

Even this is way too verbose - why would I have to define this for every single class, when the container is able to figure out these kinds of bindings on its own?

If I have classes like this:
```
class Foo {
  constructor(bar: Bar) { .. }
}

class Bar {}
```

I would just expect the container to instantiate a new instance of Bar when creating Foo, without me having to tell it that yes - Bar should in fact be bound to Bar.

**Comment by contrasam** [comment]
Hello @fabis94 , Auto injection actually works, if the constructor arguments use a concrete class type like you have done with `Bar` its automatically injected by inversify, only if the constructor arguments are interfaces, inversify would not be able to instantiate the dependencies

**Comment by notaphplover** [comment]
Hello @fabis94, as @contrasam said I think you could create a `Container` with `autoBindInjectable` option enabled (see [docs](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#autobindinjectable) for more details):

```Typescript
@injectable()
class Katana {}

@injectable()
class Ninja {
  public constructor(public weapon: Katana) {}
}

const container1 = new Container({autoBindInjectable: true});
const katana1 = container1.get(Katana);
const ninja1 = container1.get(Ninja);
```

**Comment by fabis94** [comment]
Hi, I wasn't aware of this because this wasn't mentioned anywhere in the docs. I'll try it out thanks

**Comment by notaphplover** [comment]
You are welcome @fabis94 :), I'm closing the issue then
