### ISSUE TITLE
version 5.1.0 NPM publish is broken (missing lib/es folders and files)

### ISSUE THREAD

**Issue by danielweck** [inversify/InversifyJS#1316]
https://unpkg.com/browse/inversify@5.1.0/

```
  "main": "lib/inversify.js",
  "jsnext:main": "es/inversify.js",
  "types": "lib/inversify.d.ts",
```

**Comment by danielweck** [comment]
Compare with the previous working version:

https://unpkg.com/browse/inversify@5.0.5/

**Comment by erdzan12** [comment]
Indeed, can confirm that it currently is broken.
<img width="263" alt="Screenshot 2021-04-26 at 00 19 30" src="https://user-images.githubusercontent.com/32931186/116011416-3057e700-a625-11eb-955d-86559907a951.png">

**Comment by notaphplover** [comment]
Hi guys, it seens the prepublish script only ran tests :( , we should patch it soon

**Comment by erdzan12** [comment]
5.1.1 works now 👍

**Comment by dcavanagh** [comment]
Thank you for reporting this. We switched the CI from travis to github and moved off of gulp. this was missed in the pre-publish script.
