### ISSUE TITLE
Refactor resolver

### ISSUE THREAD

**Issue by notaphplover** [inversify/InversifyJS#1321]
As commented at https://github.com/inversify/InversifyJS/pull/1132#discussion_r623786374, Resolver can be refactored.

- A `resolveBinding` function could be extracted.
- result is guaranteed to be undefined | T | Promise<T> if `!(targetIsAnArray && targetParentIsNotAnArray)`
- resolveInstance should be passed <T> as generic paramenter:

```ts
...
        } else if (binding.type === BindingTypeEnum.Instance && binding.implementationType !== null) {
            result = resolveInstance<T>(
                binding,
                binding.implementationType,
                childRequests,
                _resolveRequest<T>(requestScope)
            );
        } else {
...
```

**Comment by notaphplover** [comment]
@tonyhallett This is the issue, do you agree to all those statements? If that's the case just answer this message and I'll submit a PR

**Comment by tonyhallett** [comment]
Yes !

The T in `Binding<T>' is TActivated, the resolved value of T.
add image here
The T in the "get" methods applies equally to resolve - if you type correctly you get it back from the binding ( or cache )
![image](https://user-images.githubusercontent.com/11292998/116721621-70c4b580-a9d5-11eb-8b80-6c80bfccd740.png)

**Comment by tonyhallett** [comment]
We also need to change the nonsense T's to any 
https://github.com/inversify/InversifyJS/blob/094bcd6e0b1a56ed85ac9b4f66410910075ef4fc/src/bindings/binding.ts#L34 to match the interface.

**Comment by tonyhallett** [comment]
Perhaps we should change `Binding<T>` to `Binding<TActivated`> to be clear.

**Comment by tonyhallett** [comment]
@notaphplover Taking this one

**Comment by notaphplover** [comment]
> @notaphplover Taking this one

I already made the PR sorry. There is a test which fails on node14 es6 build, I'll be missing for some hours so if you want could you see what's happening?

**Comment by tonyhallett** [comment]
No problem commit it and I will have a look

**Comment by tonyhallett** [comment]
I will have a look

**Comment by notaphplover** [comment]
Closing as #1323 is merged
