### ISSUE TITLE
[suggestion] Container API haven't ability to check bound dependency only current container

### ISSUE THREAD

**Issue by dmitry-nizovsky** [inversify/InversifyJS#1351]
Then I did integration InversifyJS with ReactJs I found one issue.
I cannot check bound dependency only current container.

I have PR with add new method for this and update wiki with examples, but I cannot do push to this REPO
But I realy want have ability check dependency in current container.
Could you check this issue please? I can help this code, If you want. 
Thank you for your time!

**Comment by PodaruDragos** [comment]
hello @dmitry-nizovsky.
Did you create a fork and then try to make a PR ?

If not that should work. looking forward for your PR

**Comment by dmitry-nizovsky** [comment]
Hello @PodaruDragos , yes I can create PR with changes (https://github.com/inversify/InversifyJS/pull/1354),
Thanks
