### ISSUE TITLE
Init before first inject

### ISSUE THREAD

**Issue by Igrokqq** [inversify/InversifyJS#1353]
## Expected Behavior

make a function/hook which will init a bound dependency on server start. It's useful when you need to init a db connection on server bootstrap. I had searching but found no one what can help me with.
## Possible Solution

a function/hook which will init a needed dependency on server start.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by PodaruDragos** [comment]
without an example it's hard to tell, but you can use the `AsyncContainerModule` where you can have `async` code.
there is also a `toDynamicValue` which can resolve a `Promise`

**Comment by Igrokqq** [comment]
@PodaruDragos Thank you, I re-wrote my code and used toDynamicValue. It helped me :)
