### ISSUE TITLE
Improve Bundling (switch to rollup)

### ISSUE THREAD

**Issue by leonardssh** [inversify/InversifyJS#1371]
I was sitting and looking over the NPM downloads of this library, and the size of the bundle jumped out at me.

![image](https://user-images.githubusercontent.com/35312043/130705977-c46b6ff5-05a9-4b9a-a2c4-de351a84a9fe.png)
I mean, 1.15 MB with 400 files for a library? Seems a little too much to me. 

That's why I thought it would be cool to switch to rollup, like the other libraries.

Results: ~194kb and only 3 files, no more!
![image](https://user-images.githubusercontent.com/35312043/130706374-2f2a305a-ee11-42a1-a93c-e2711df61ab4.png)

Also, to be able to merge all the `.d.ts` into single file, I used [@microsoft/api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor), which imo is really good and efficient.

TODO:
- [ ] Fix tests (or switch to JEST)
- [ ] Improve CI

**Comment by notaphplover** [comment]
The library can be tree shaked in the userland. We're reducing the package size distrubuting packages in the current monorepo approach. `webpack` is already doing an excellent job even if `rollup` is designed for libraries.
