### ISSUE TITLE
Propery injection of 'toConstantValue' bind is undefined

### ISSUE THREAD

**Issue by Emilian5** [inversify/InversifyJS#1376]
## Expected Behavior
Injected property should not be undefined.

## Current Behavior
Injected property is undefined.

## Steps to Reproduce (for bugs)

```typescript
const ID = {
    NUMBER: Symbol.for("Number")
}

@injectable()
class Foo {
    @inject(ID.NUMBER) private _id: number;
    constructor(@inject(ID.NUMBER) private id: number) {
        console.log(`Foo > ${this._id} | ${this.id}`);
    }
}
@injectable()
class Bar {
    @inject(ID.NUMBER) private _id: number;
    constructor(@inject(ID.NUMBER) private id: number) {
        console.log(`Bar > ${this._id} | ${this.id}`);
    }
}

const rootDI = new Container();
rootDI.bind<number>(ID.NUMBER).toConstantValue(100);
rootDI.bind(Bar).toSelf();

rootDI.resolve(Foo); // Foo > undefined | 100
rootDI.get(Bar); // Bar > undefined | 100
```

## Your Environment
node.js app

"inversify": "^5.1.1"
"reflect-metadata": "^0.1.13",
"typescript": "^4.3.2"

# Stack trace

**Comment by tonyhallett** [comment]
Why do you expect

> Injected property should not be undefined.

**Comment by tonyhallett** [comment]
It does get set but not in the constructor

**Comment by Emilian5** [comment]
> It does get set but not in the constructor

Oh, I see. It's available after instantiation. I didn't see anything related to this in docs, I may have missed it.
Thank you.

**Comment by tonyhallett** [comment]
This is how javascript works
