### ISSUE TITLE
Is it a typing error?

### ISSUE THREAD

**Issue by ruanwenfeng** [inversify/InversifyJS#1378]
can't find the description of the **@injectNamed**
### how this works
in this file _[InversifyJS/wiki/inheritance.md](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#workaround-c-property-injection)_
![image](https://user-images.githubusercontent.com/27943586/132081466-e7fd9261-5c9d-446c-b60e-c30f8f476c3c.png)

**Comment by tonyhallett** [comment]
yes that is a typo.  Should be '@inject(TYPES.Rank)`
