### ISSUE TITLE
how can we group different provides into separated modules in inversify-binding-decorators?

### ISSUE THREAD

**Issue by tlyau62** [inversify/InversifyJS#1379]
I got 3 classes, and I would like to have (ServiceA) as a group, and (ServiceB, ServiceBChild) as another group.
Such that, there are 2 modules can be provided.

## Expected Behavior
```ts
@provide("ServiceA")
class ServiceA {
}

@provide("ServiceB1")
class ServiceB1 {
}

@provide("ServiceB2")
class ServiceB2 {
}

// ...

const container = new Container();

container.load(moduleA); // moduleA contains ServiceA only.
container.load(moduleB); // moduleB container ServiceB1 and serviceB2
```

**Comment by AEPKILL** [comment]
maybe you need see: [container_modules](https://github.com/inversify/InversifyJS/blob/master/wiki/container_modules.md)

**Comment by notaphplover** [comment]
As said, rely on [container modules](https://github.com/inversify/InversifyJS/blob/master/wiki/container_modules.md)

**Comment by tlyau62** [comment]
@notaphplover looks like it does not say about using inversify-binding-decorators to group the bindings?

**Comment by notaphplover** [comment]
Oh, I see, sry. You cannot do that given the current design of the library, you need to rely on `buildProviderModule()` :(
