### ISSUE TITLE
inversify-express-utils 6.4.0 breaking builds with noImplicitAny

### ISSUE THREAD

**Issue by mhetes** [inversify/InversifyJS#1387]
InversifyJS package **inversify-express-utils** in version **6.4.0** is breaking builds that have enabled _noImplicitAny_ in _tsconfig.json_:

`{
  "compilerOptions": {
    "noImplicitAny": true
  }
}`

This is caused by invalid of _types_ config in package.json: https://github.com/inversify/inversify-express-utils/blob/adaa6ea9dd9cd52c2b3ff5bc3ad1704521e78939/package.json#L8

In current **inversify-express-utils** version **6.4.0** all **.d.ts** files are located in `lib/` folder, but package.json specifies that those are in `dts/` folder. Older **inversify-express-utils** version **6.3.2** did not have this problem, as there was correct folder with name `dts/`.

## Expected Behavior
`import { InversifyExpressServer } from 'inversify-express-utils';`
Should build without problem.

## Current Behavior
`import { InversifyExpressServer } from 'inversify-express-utils';`
Is giving me TSC build error:
`c:/xxx/src/app.ts(2,40): error TS7016: Could not find a declaration file for module 'inversify-express-utils'. 'c:/xxx/node_modules/inversify-express-utils/lib/index.js' implicitly has an 'any' type.`

## Possible Solution

1. Fix **inversify-express-utils** build to correctly create all **d.ts** files in `dts/` directory
2. Or change `package.json` configuration for _types_ to `./lib/index.d.ts`
3. Temporary fix is to disable `noImplicitAny` in typescript configuration file `tsconfig.json`

## Steps to Reproduce (for bugs)
**app.ts**
```
import 'reflect-metadata';
import { Container } from 'inversify';
import { InversifyExpressServer } from 'inversify-express-utils';
let server = new InversifyExpressServer(new Container());
let instance = server.build();
export { instance as app };
```

**package.json**
```
{
    "description": "Inversify Express Utils Bug",
    "dependencies": {
        "express": "^4.17.1",
        "inversify": "^5.1.1",
        "inversify-express-utils": "^6.4.0",
        "reflect-metadata": "^0.1.13"
    },
    "devDependencies": {
        "@types/node": "^16.11.0"
    }
}
```

**tsconfig.json**
```
{
    "compilerOptions": {
        "rootDir":".",
        "target": "es2019",
        "lib": ["esnext", "dom"],
        "types": ["reflect-metadata", "node"],
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitAny": true,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true,
        "noResolve": false,
        "noUnusedParameters": false,
        "noUnusedLocals": true,
        "strictNullChecks": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Run** `tsc`

## Your Environment

* Version used: **inversify** `5.1.1` and **inversify-express-utils** `6.4.0`
* Environment name and version (e.g. Chrome 39, node.js 5.4): **node.js** `v12.22.1`

**Comment by mro-pbraswell** [comment]
Also experienced these issues related to the missing types:
## Context
### healthCheck.controller.ts
```
import {BaseHttpController, controller, httpGet} from 'inversify-express-utils';

@controller('/')
export class HealthCheckController extends BaseHttpController {
  constructor() {
    super();
  }

    @httpGet('')
  public get(): any {
    return this.ok();
  }
}
```

## Stacktrace
```
ERROR: src/controller/healthCheck.controller.ts:1:55 - error TS7016: Could not find a declaration file for module 'inversify-express-utils'.
  Try `npm install @types/inversify-express-utils` if it exists or add a new declaration (.d.ts) file containing `declare module 'inversify-express-utils';`

    5 import {InversifyExpressServer} from 'inversify-express-utils';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
```
and
```
src/controller/healthCheck.controller.ts:11:17 - error TS2339: Property 'ok' does not exist on type 'HealthCheckController'.

11     return this.ok();
                   ~~
```

## Current Workaround
Downgrade to v6.3.2

**Comment by dcavanagh** [comment]
6.4.3 published
