### ISSUE TITLE
inversify-express-utils fix merged but not published

### ISSUE THREAD

**Issue by guidojw** [inversify/InversifyJS#1390]
## Expected Behavior
The fix implemented in https://github.com/inversify/inversify-express-utils/pull/355 is published to npm.

## Current Behavior
The [GitHub release](https://github.com/inversify/inversify-express-utils/releases/tag/v6.4.2) says it is included, but it is not.

## Possible Solution
Publish the fix to npm under the v6.4.3 tag.

## Steps to Reproduce (for bugs)
1. Import results as is documented in the README:
 ```ts
import { results } from 'inversify-express-utils'
// results.OkResult
```
2. It doesn't work.
3. Importing the single results works (and didn't in 6.3.2):
```ts
import { OkResult } from 'inversify-express-utils'
```

## Context
As explained in https://github.com/inversify/inversify-express-utils/pull/355, the ESLint PR there broke the results imports. According to the documentation in the README the results should be imported the way done in step 1 above, but this currently cannot be done.

## Your Environment
* Version used: 6.4.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js 16.9.1
* Operating System and version (desktop or mobile): Docker 20.10.8
* Link to your project: https://github.com/guidojw/arora-api/pull/345

# Stack trace
![firefox_SoA0uwgGX6](https://user-images.githubusercontent.com/35309288/137741627-0ea4f513-2752-4a17-b218-9a15d9d77c97.png)

**Comment by dcavanagh** [comment]
@guidojw Please try now. 6.4.3 Published

**Comment by guidojw** [comment]
It's working now, thanks!
