### ISSUE TITLE
Browserify: import "reflect-metadata" leads to additional 0.5MB in final file (Notice in documentation would be great)

### ISSUE THREAD

**Issue by KarolBuchta** [inversify/InversifyJS#146]
## Expected Behavior

If i import reflect-metadata, i want only the library itself, not the node built ins. They increase the size of my package of about 0.5mb, which is obviously bad when using inversify in a browser environment.
## Current Behavior

When using import reflect-metadata, node built ins are always pulled into my package when using browserify to bundle inversify as dependency.

This happens due to this code line in the reflect-metadata dependency:
https://github.com/rbuckton/ReflectDecorators/blob/1a07d3346d48ffbc77927c70245740debe09eb13/Reflect.js#L842

This issue is discussed in another project too, mentioning browserify:
https://github.com/jspm/npm/issues/77
## Possible Solution

This issue is not actually one on your site, but if developers want to use your library in a browser app, they should definitely know what's happening when they import reflect-metadata.

I think, if the docu would provide a workaround for that, it would be great, here is what i did in my init task:

```

replace = require('gulp-replace');

  tasks.push(
    gulp.src(['node_modules/reflect-metadata/Reflect.js'])
    .pipe(replace(/var nodeCrypto = isNode && require\("crypto"\);/g, "var nodeCrypto = false;"))
    .pipe(gulp.dest('src/ts/libs'))
  )
```

And then the file can be used as a browserify-shim, for that one has to add a shim in it's package.json:

```

"browser": {
  "reflect-metadata": "./src/ts/libs/Reflect.js"
}
```

This is a workaround of course, but i cannot see how the reflect people could to a dynamic requiring together with browserify, this doen't work, as far as i understand the system (sry i'm quite new to browserify, also to ts).

I have seen another comment from one of you, saying this dependency is not wanted to be included into your own library. But maybe you could provide it anyway, as an option, something like import "reflect-metadata-browser" ... I will make an issue on the reflect page as well. We'll see what comes up.
## Steps to Reproduce (for bugs)

Using browserify with tsify to build a package that should use inversify. require('reflect-metadata') or import "reflect-metadata" in one of the js or ts files.
## Context
- Using inversify in a browser context. 
- Using browserify to build a package, that depends on inversifym and hence on reflect-metadata.
## Your Environment
- Version used: 2.0.0-alpha-6
- Environment name and version: node.js 4.3.2, browserify 13.0.0
- Operating System and version (desktop or mobile): Desktop MAC OSX Yosemite
- Link to your project: Company internal, sry.

**Comment by remojansen** [comment]
Thanks for reporting this :+1:  I will add something to the docs for the beta release.

**Comment by remojansen** [comment]
@KarolBuchta I have assign it to you. Thanks a lot for helping me with this :smile:

**Comment by remojansen** [comment]
Hi @KarolBuchta the wiki is now part of the source code you can find the new page [here](https://github.com/inversify/InversifyJS/blob/master/wiki/module_bundlers.md). Thanks!
