### ISSUE TITLE
DI in constructors doesn't work

### ISSUE THREAD

**Issue by ballwood** [inversify/InversifyJS#149]
I've probably made a mistake setting this up but the following doesn't work
## Expected Behavior

console.log();
`Ninja { _katana: Katana, _shuriken: Shuriken }`
## Current Behavior

console.log();
`Ninja { _katana: undefined, _shuriken: undefined }`
## Steps to Reproduce (for bugs)

Paste this code into a app.ts file, compile using tsc (1.8.9) and run node (v5.10.0) app.js

```
require("reflect-metadata"); // for some reason we were getting 'Reflect is not defined' 

interface INinja {
    fight(): string;
    sneak(): string;
}

interface IKatana {
    hit(): string;
}

interface IShuriken {
    throw();
}

import { injectable, inject } from "inversify";

@injectable()
class Katana implements IKatana {
    public hit() {
        return "cut!";
    }
}

@injectable()
class Shuriken implements IShuriken {
    public throw() {
        return "hit!";
    }
}

@injectable()
class Ninja implements INinja {

    private _katana: IKatana;
    private _shuriken: IShuriken;

    public constructor(
        @inject("IKatana") katana: IKatana,
        @inject("IShuriken") shuriken: IShuriken
    ) {
        this._katana = katana;
        this._shuriken = shuriken;
    }

    public fight() { return this._katana.hit(); };
    public sneak() { return this._shuriken.throw(); };

}

import { Kernel } from "inversify";

var kernel = new Kernel();
kernel.bind<INinja>("INinja").to(Ninja);
kernel.bind<IKatana>("IKatana").to(Katana);
kernel.bind<IShuriken>("IShuriken").to(Shuriken);

var ninja = kernel.get<INinja>("INinja");

console.log(ninja);
```

tsconfig.json

```
{
  "compilerOptions": {
    "target": "es6",
    "sourceMap": true,
    "outDir": "build",
    "module": "commonjs",
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```
## Your Environment

TSC - v1.8.9, NodeJS v5.10.0

**Comment by remojansen** [comment]
I think we are missing an important detail in the docs. Can you please try to add the following to your `tsconfig.json` file:

```
"emitDecoratorMetadata": true
```

Please let me know if it works.

**Comment by ballwood** [comment]
awesome, worked perfectly. might wanna add the npm package `reflect-metadata` as a dependency as well. doesn't seem to work without a `require("reflect-metadata");`

**Comment by remojansen** [comment]
Great! We don't want to add it as a dependency because it will eventually become part of the run time. So it is a temporal fallback. Same applies for the Promise and Proxy APIs. We have documented it at https://github.com/inversify/InversifyJS/wiki/Environment-support-and-polyfills

**Comment by ballwood** [comment]
Ok cool, didn't realise. Looks like a good project, will be giving it a thorough workout in the next few days to see if it's suitable for us.

**Comment by remojansen** [comment]
Thanks! feel free to ask for support again if you have any problems. We are trying to go into beta soon. I'm hopping sometime this month.
