### ISSUE TITLE
Add support for "contextual injections"

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#15]
The idea is to allow developers to bind multiple implementation types (classes) to one service type (interface). A "constraint" function is used to decide whether InversifyJS should inject one implementation type (class) or another based on the context of the injection.

The context of the injection will be provided via the Reflection metadata API.
See https://github.com/inversify/InversifyJS/issues/14

Initial API thoughts:
https://gist.github.com/remojansen/dbd57b72622ebf1129f8

**Comment by remojansen** [comment]
Closing this issue to create a more detailed one

**Comment by johndoe2361289638163** [comment]
What is the state of this issue? Are contextual injections now fully supported?
