### ISSUE TITLE
Multi-injection with different runtime identifiers

### ISSUE THREAD

**Issue by hourliert** [inversify/InversifyJS#153]
Hi,

First of all, thanks for the **alpha.8**! It is awesome!!! :tada: 

This is not really an issue, but more a demand for advices. In **alpha.7**, we were able to do multi-injection with different runtime identifiers.

Eg:

``` typescript

// === in an hypothetic 3rd party library ===
export function PersonStoreFactory(People: IPersonConstructor[]) {

  @inject(...People) // we are using class identifiers here
  class PersonStore {
    constructor(...people: IPerson[]) {
      // ...
    }
  }

  return PersonStore;
}

export const kernel = new Kernel();
export interface IPerson {}
export interface IPersonConstructor {
  new(): IPerson;
}

// === user code ===
class Ninja implements IPerson {}
class Samurai implements IPerson {}

kernel.bind(Ninja).to(Ninja);
kernel.bind(Samurai).to(Samurai);

const People = [Ninja, Samurai];
const PersonStore = PersonStoreFactory(People);

kernel.bind(PersonStore).to(PersonStore);

const personStore = kernel.get(PersonStore); //it works and Ninja and Samurai are instantiated.

```

This was useful when the array `People` had a dynamic `length` known only at runtime.

I cannot find a way to reproduce this in **alpha.8** except one but I am not sure this a good practice?

The solution could be:
- at runtime, create an abstraction and bind to it `Ninja` and `Samurai` (do this into the `PersonStoreFactory`)
- use `@multiInject` with this abstraction

The issue with that, is that you have to create an abstraction each time this case happened whereas before, you had just to register your services once.

A potential problem is that you could have a lot of abstractions registered into the kernel. Is that a problem? If so, what is the recommended solution?

Thanks in advance!!

**Comment by remojansen** [comment]
I'm glad to know that you like the library :smile_cat: 

I haven't run the following code sample so it may contain some errors but the following should work:

``` ts
@injectable()
class PersonStore {
    constructor(@multiInject("IPerson") people: IPerson[]) {
      // ...
    }
  }

export const kernel = new Kernel();
export interface IPerson {}
```

``` ts
@injectable()
class Ninja implements IPerson {}

@injectable()
class Samurai implements IPerson {}

kernel.bind("IPerson ").to(Ninja);
kernel.bind("IPerson").to(Samurai);
kernel.bind("IPersonStore").to(PersonStore);

const personStore = kernel.get("IPersonStore"); 

// If you need a factory
kernel.bind("IFactory<IPersonStore>").toAutoFactory("IPersonStore");
const personStoreFactory = kernel.get("IFactory<IPersonStore>");

```

**Comment by hourliert** [comment]
Ok, you are confirming my thoughts!

I will let you know if I have an issue when using this.

**Comment by remojansen** [comment]
Thanks, do you want to close the issue or keep it open until you can confirm?

**Comment by hourliert** [comment]
We can close as this is not really an issue I guess.

**Comment by remojansen** [comment]
Thanks!
