### ISSUE TITLE
Inheritance and DI

### ISSUE THREAD

**Issue by hourliert** [inversify/InversifyJS#156]
Hi,

I cannot make the injection work when extending a class that uses DI. It worked on alpha.7.
## Expected Behavior

It should work. Base class should be able to use DI.
## Current Behavior

The following snippet doesn't work:

``` typescript
const DepId = Symbol('Dep');
const AId = Symbol('A');
const BId = Symbol('B');

@injectable()
class Dep {

}

@injectable()
class A {
  constructor(
    @inject(DepId) dep
  ) {
    console.log(dep);
  }
}

@injectable()
class B extends A {}

const kernel = new Kernel();

kernel.bind(DepId).to(Dep);
kernel.bind(AId).to(A);
kernel.bind(BId).to(B);
```

``` typescript
const a = kernel.get(AId);
console.log(a); // works perfectly, dep is shown in the constructor of A
```

``` typescript
const b = kernel.get(BId);
console.log(b); // doesn't work. dep is undefined
```
## Context

I am trying to extend a class that uses DI. My new class does not use DI and doesn't override the base constructor. (It is basically adding new methods on a parent class).
## Your Environment

inversify@alpha.8
TS@1.8.9
reflect-metada@0.1.3

**EDIT:**
After doing some reading, it seems to declare a class that extends another without declaring a constructor is a bad practice (ie: `class B extends A {}`). Maybe this 'regression' is intended and ensures better code quality?

**Comment by remojansen** [comment]
Great I really need help to spot this kind of stuff because there are millions of use cases. Thanks a lot for helping me to tests and please feel free to try to do a PR with a bud fix If you think that you know what is going on.

**Comment by hourliert** [comment]
I am going to work on this.
Just before starting. What the final decision?

I have written some tests to help us to understand the 2 possibles solutions:

**This one works out of the box** (look at the comment `//INTERESTING PART HERE` to save some time)
**EDIT**: the test is available [here](https://github.com/hourliert/InversifyJS/blob/di-inheritance/test/inversify.test.ts#L1151L1266)

``` typescript
    it("Should be able to inject dependencies into a mother class", () => {

        interface INinja {
            fight(): string;
            sneak(): string;
        }

        interface ICyberNinja extends INinja {
            hack(): string;
        }

        interface IKatana {
            hit(): string;
        }

        interface IShuriken {
            throw(): string;
        }

        @injectable()
        class Katana implements IKatana {
            public hit() {
                return "cut!";
            }
        }

        @injectable()
        class Shuriken implements IShuriken {
            public throw() {
                return "hit!";
            }
        }

        let TYPES = {
            Katana: Symbol("IKatana"),
            Ninja: Symbol("INinja"),
            Shuriken: Symbol("IShuriken")
        };

        class Ninja implements INinja {

            private _katana: Katana;
            private _shuriken: Shuriken;

            public constructor(
                katana: Katana,
                shuriken: Shuriken
            ) {
                this._katana = katana;
                this._shuriken = shuriken;
            }

            public fight() { return this._katana.hit(); };
            public sneak() { return this._shuriken.throw(); };

        }

        //INTERESTING PART HERE
        @injectable()
        class CyberNinja extends Ninja implements ICyberNinja {
            public constructor(
                @inject(TYPES.Katana) katana: Katana,
                @inject(TYPES.Shuriken) shuriken: Shuriken
            ) {
                super(katana, shuriken);
            }

            public hack() { return "hack!"; }
        }

        let kernel = new Kernel();
        kernel.bind<ICyberNinja>(TYPES.Ninja).to(CyberNinja);
        kernel.bind<IKatana>(TYPES.Katana).to(Katana);
        kernel.bind<IShuriken>(TYPES.Shuriken).to(Shuriken);

        let ninja = kernel.get<ICyberNinja>(TYPES.Ninja);

        expect(ninja.fight()).eql("cut!");
        expect(ninja.sneak()).eql("hit!");
        expect(ninja.hack()).eql("hack!");

    });
```

**This one doesn't** because _katana and _shuriken are undefined.

``` typescript
        @injectable()
        class Ninja implements INinja {

            private _katana: Katana;
            private _shuriken: Shuriken;

            public constructor(
                //INTERESTING PART HERE
                @inject(TYPES.Katana) katana: Katana,
                @inject(TYPES.Shuriken) shuriken: Shuriken
            ) {
                this._katana = katana;
                this._shuriken = shuriken;
            }

            public fight() { return this._katana.hit(); };
            public sneak() { return this._shuriken.throw(); };

        }

        @injectable()
        class CyberNinja extends Ninja implements ICyberNinja {
            public hack() { return "hack!"; }
        }

        let kernel = new Kernel();
        kernel.bind<ICyberNinja>(TYPES.Ninja).to(CyberNinja);
        kernel.bind<IKatana>(TYPES.Katana).to(Katana);
        kernel.bind<IShuriken>(TYPES.Shuriken).to(Shuriken);

        let ninja = kernel.get<ICyberNinja>(TYPES.Ninja);

        expect(ninja.fight()).eql("cut!");
        expect(ninja.sneak()).eql("hit!");
        expect(ninja.hack()).eql("hack!");
```

**Comment by remojansen** [comment]
Hi, thanks for the examples. I can see why the following won't work:

``` ts
@injectable()
class SamuraiMaster extends Samurai {
    public isMaster: boolean;
}
```

By looking at the JS output:

``` ts
var SamuraiMaster = (function (_super) {
    __extends(SamuraiMaster, _super);
    function SamuraiMaster() { // No declared constructor arguments
        _super.apply(this, arguments); // HERE!
        this.isMaster = true;
    }
    return SamuraiMaster;
}(Samurai));
```

However, the following works:

``` ts
@injectable()
class SamuraiMaster extends Samurai {
    public isMaster: boolean;
    public constructor(@inject(SYMBOLS.IKatana) weapon: IWeapon) {
        super(weapon);
        this.isMaster = true;
    }
}
```

The JS output looks as follows:

```
var SamuraiMaster = (function (_super) {
    __extends(SamuraiMaster, _super);
    function SamuraiMaster(weapon) {
        _super.call(this, weapon);
        this.isMaster = true;
    }
    SamuraiMaster = __decorate([
        injectable(),
        __param(0, inject(SYMBOLS.IKatana))
    ], SamuraiMaster);
    return SamuraiMaster;
```

So it looks to me like a limitation more than a bug. The main problem for me is that it fails because weapon is undefined but there are no friendly errors like: 

```
Error: Derived classes must explicitly declare its constructor.
```

I know a hack that we can use to be able to provide a friendly error. We can check the `SamuraiMaster.prototype.__proto__.constructor` to access the `Samurai` constructor from the `SamuraiMaster` constructor.

The problem is that [it is a really bad idea to use `__proto__`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto). However, I saw a new API I wasn't aware of [`Object.getPrototypeOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf). 

I'm going to sleep now because is 1:39 am here :( but let me think about it and I will share some ideas tomorrow :sleeping: :wink:

**Comment by remojansen** [comment]
Take a look to this [early implementation](https://github.com/remojansen/InversifyJS/blob/master/src/planning/planner.ts#L206-L230). I need to to more testing but this will probably solve this problem :smile:

**Comment by remojansen** [comment]
The example that you used to showcase the error:

> This one doesn't because _katana and _shuriken are undefined.

Should now throw:

```
Uncaught Error: Derived class must explicitly declare its constructor: CyberNinja.
```

Thanks a lot for helping me to spot this issue.

**Comment by hourliert** [comment]
Nice, I didn't know about `Object.getPrototypeOf()`. That's neat.
