### ISSUE TITLE
multiInject with nested injects

### ISSUE THREAD

**Issue by hourliert** [inversify/InversifyJS#159]
Hi,

I have spotted another issue related to `multiInject`. It seems that when I try to `@multiInject` an array of ninjas with only one binding (each of them needs to `@inject` a katana and a shuriken too) their resolution is incorrect.

The following test doesn't work:

``` ts
        interface INinja {
            fight(): string;
            sneak(): string;
        }

        interface IKatana {
            hit(): string;
        }

        interface IShuriken {
            throw(): string;
        }

        @injectable()
        class Katana implements IKatana {
            public hit() {
                return "cut!";
            }
        }

        @injectable()
        class Shuriken implements IShuriken {
            public throw() {
                return "hit!";
            }
        }

        @injectable()
        class Ninja implements INinja {

            private _katana: IKatana;
            private _shuriken: IShuriken;

            public constructor(
                @inject("IKatana") katana: IKatana,
                @inject("IShuriken") shuriken: IShuriken
            ) {
                this._katana = katana;
                this._shuriken = shuriken;
            }

            public fight() { return this._katana.hit(); };
            public sneak() { return this._shuriken.throw(); };

        }

        interface INinjaSchool {
            ninjaMaster: INinja;
        }

        @injectable()
        class NinjaSchool implements INinjaSchool {
            public ninjaMaster: INinja;

            constructor(
                @multiInject("INinja") ninja: INinja[]
            ) {
                this.ninjaMaster = ninja[0];
            }
        }

        let kernel = new Kernel();
        kernel.bind<IKatana>("IKatana").to(Katana);
        kernel.bind<IShuriken>("IShuriken").to(Shuriken);
        kernel.bind<INinja>("INinja").to(Ninja);
        kernel.bind<INinjaSchool>("INinjaSchool").to(NinjaSchool);

        let ninjaSchool = kernel.get<INinjaSchool>("INinjaSchool");
        expect(ninjaSchool.ninjaMaster.fight()).eql("cut!");
        expect(ninjaSchool.ninjaMaster.sneak()).eql("hit!");
```
## Expected Behavior

Each `Ninja` instance should receive a katana and a shuriken.
## Current Behavior

The `Ninja` instance seems to be instantiated twice. 
- First instance: a `Katana` and a `Shuriken` instance are passed as arguments. This is OK.
- Second instance: the First `Ninja` instance is passed as a single argument in the `Ninja` constructor.

Unfortunately, this is the second instance that is injected into `NinjaSchool`.

At the end, the `ninjaMaster` of `ninjaSchool` has a `_katana` equals to (a ninja with a katana and a shuriken) and a `_shuriken` equals to `undefined`.
## Possible Solution

Check if that the spread operator is correctly applied.
## Your Environment

inversify@af36bf72dad6706ff07cebdff65366f566de72dd (388th commit)
typescript@1.8.9

**Comment by hourliert** [comment]
I am working on the fix.

In fact, I found a more generic solution to https://github.com/inversify/InversifyJS/issues/155.

Instead of [this](https://github.com/inversify/InversifyJS/blob/af36bf72dad6706ff07cebdff65366f566de72dd/src/resolution/resolver.ts#L19) we should do something like this:

``` ts
        if (
            request.target && request.target.isArray() &&
            (!request.parentRequest.target || !request.parentRequest.target.isArray())
        ) {

            // Create an array instead of creating an instance
            return childRequests.map((childRequest) => { return this._resolve(childRequest); });

        } else { ... }
```

It solves https://github.com/inversify/InversifyJS/issues/155 more elegantly too (so we could remove [this](https://github.com/inversify/InversifyJS/blob/af36bf72dad6706ff07cebdff65366f566de72dd/src/resolution/resolver.ts#L61)).
The **problem** with that is if we are doing a `@multiInject` of a `@multiInject`.

Another way is to hack something [here](https://github.com/inversify/InversifyJS/blob/af36bf72dad6706ff07cebdff65366f566de72dd/src/resolution/resolver.ts#L66). I am not sure this is the really elegant...

Do you see another solution?

**EDIT**: 
I found the proper solution. I added a method on `interfaces/planning/target.d.ts` to check if the target has a metadata `multi_inject` for a specific service.
This allows me to test if the parent has a metadata `multi_inject` in the same 'family'.

It seems to work well. I am going to push soon. I just need to write more tests.

**Comment by remojansen** [comment]
Hi @hourliert thanks for your help. I have assigned this issue it to you.

Removing the change from #155 and doing the following sounds good to me:

```
if (
    request.target && request.target.isArray() &&
    (!request.parentRequest.target || !request.parentRequest.target.isArray())
) {
// ..
```

I need to think about the `@multiInject` of a `@multiInject` is a complex case :smile:

**Comment by hourliert** [comment]
I will push something that solves `@multiInject` of `@multiInject` very soon. You tell me if that is acceptable 😃 

I have also written more tests of complex situations. I hope that will better cover 'real world' use cases.

**Comment by remojansen** [comment]
Sounds great :smile: I will code review your PR. If you think that there is going to be something that could lead to limitations on the future or that feels like a hack maybe ask here before actually implementing it but otherwise work ahead :rocket:
