### ISSUE TITLE
Error message typo

### ISSUE THREAD

**Issue by markis** [inversify/InversifyJS#166]
## Expected Behavior

Error: No bindings found for serviceIdentifier: IKatana
## Current Behavior

Error: No bindigns found for serviceIdentifier: IKatana
## Possible Solution

Fix the typo in the error message.
## Steps to Reproduce (for bugs)

import \* as ERROR_MSGS from "../constants/error_msgs";
throw new Error(`${ERROR_MSGS.NOT_REGISTERED}`);
## Your Environment

Node.js
# Stack trace

Doesn't matter, it's a global constant.

**Comment by remojansen** [comment]
Thanks :+1:
