### ISSUE TITLE
IProvider Example in the README doesn't compile

### ISSUE THREAD

**Issue by markis** [inversify/InversifyJS#169]
## Expected Behavior

Copy and Paste the code in the 'Injecting a Provider (asynchronous Factory)' section of the readme should compile and run.
## Current Behavior

error TS2339: Property '_katana' does not exist on type 'Ninja'.
error TS2339: Property '_shuriken' does not exist on type 'Ninja'.
## Possible Solution

Update the code to something that compiles
## Steps to Reproduce (for bugs)

1.) Copy the code in the 'Injecting a Provider (asynchronous Factory)' section
2.) Paste the code into another file
3.) Run tsc <filename>
4.) Error in console
## Context

Just trying to learn.
## Your Environment

Node.js 5.10
# Stack trace

README.md

**Comment by markis** [comment]
Hi, I like what you all are doing with this project.  Just trying to help out when I find things that need addressed.

**Comment by remojansen** [comment]
Thanks a lot for the PR. Your help is more than welcome we really need people like you to help us to spot issue before we do a production-ready release.
