### ISSUE TITLE
Use with vanilla javascript

### ISSUE THREAD

**Issue by colthreepv** [inversify/InversifyJS#17]
this project is promising, but is possible to be used without Typescript, at least for a start?

Me, as many javascript coders out there, _might_ be interested in Typescript in the near future, but for now a DI library without dependencies is even more attractive :)

**Comment by remojansen** [comment]
Hi @mrgamer sorry for the late reply I had a crazy summer... you can use InversifyJS with vanilla javascript. Please take a look  to the example at http://inversify.io/ search for: "The Basics (with JavaScript)" in the page and you will be able to find a basic example.

Please ask me any questions here if you need additional help.
