### ISSUE TITLE
How to add the dependency into the function?

### ISSUE THREAD

**Issue by acopalipsis** [inversify/InversifyJS#183]
How to add the dependency into the function?

```
@injectable()
class Store {}

const SomeComponent: ReactElement<any> = ({store}) => <div>{store}</div>;
```

**Comment by remojansen** [comment]
We don't support injection into functions. We only support injection via class constructors  at the moment but we have documented a work around [here](https://github.com/inversify/InversifyJS/blob/master/wiki/recipes.md#injecting-dependencies-into-a-function).
