### ISSUE TITLE
.ts.d typo?

### ISSUE THREAD

**Issue by acopalipsis** [inversify/InversifyJS#184]
In native js has a type `symbol`. But You have to .ts.d specified the type `Symbol`? It's a typo?

**Comment by remojansen** [comment]
The native `Symbol` [should start with uppercase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol). The type definitions [use uppercase as well](https://github.com/inversify/InversifyJS/blob/master/type_definitions/inversify/inversify.d.ts#L9-L18). Can you share more details about the error please?

**Comment by acopalipsis** [comment]
```
let id: symbol = Symbol.for('some-id'); // Symbol is constructor which retutn type symbol
typeof id === "symbol"; // true
```

`String === string, Number === number, Symbol === symbol`

**Comment by remojansen** [comment]
`Symbol` can be used to declare global and local symbols:

``` ts
Symbol.for("foo"); // create a new global symbol
Symbol.for("foo"); // retrieve the already created symbol

// Same global symbol, but not locally
Symbol.for("bar") === Symbol.for("bar"); // true
Symbol("bar") === Symbol("bar"); // false

// The key is also used as the description
var sym = Symbol.for("mario");
sym.toString(); // "Symbol(mario)"
```

More info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for).

InversifyJS is designed to use local symbols:

``` ts
let TYPES = {
    Katana: Symbol("IKatana"),
    Ninja: Symbol("INinja"),
    Shuriken: Symbol("IShuriken")
};

@injectable()
class Ninja implements INinja {

    private _katana: Katana;
    private _shuriken: Shuriken;

    public constructor(
        @inject(TYPES.Katana) katana: Katana,
        @inject(TYPES.Shuriken) shuriken: Shuriken
    ) {
        this._katana = katana;
        this._shuriken = shuriken;
    }

    public fight() { return this._katana.hit(); };
    public sneak() { return this._shuriken.throw(); };

}
```

A full example is available [here](https://github.com/inversify/InversifyJS/blob/master/test/inversify.test.ts#L168-L232).

**Comment by acopalipsis** [comment]
https://www.typescriptlang.org/play/#src=let%20a%3A%20Symbol%3B%0Alet%20b%3A%20symbol%3B
see that red Symbol? in .ts.d validation of the type Symbol.. but the compiler is yelling that this is a mistake, because there is no type Symbol is symbol.

**Comment by remojansen** [comment]
When you select a compilation target, TypeScript imports a file named `lib.d.ts`. This file delcares all the native JavaScript objects. The `Symbol` object is not recognized by typescript unless you target ES6. But if you add the InversifyJS type definitions:

``` ts
/// <reference path="node_modules/inversify/type_definitions/inversify/inversify.d.ts" />
```

You will be able to target ES5 and the `Symbol` should be declared.

**Comment by acopalipsis** [comment]
You are right I compile es6. It was easier for me to .ts.d edit Symbol on the symbol.
