### ISSUE TITLE
@inject in react components

### ISSUE THREAD

**Issue by otbe** [inversify/InversifyJS#187]
Hi

I would like to use `@inject` in constructors of react components. Something like this:

```
export class Settings extends Component<SettingsProps, {}> {
  constructor (props: SettingProps, context: any, @inject(MyService) private myService: MyService) {
    super(props, context);
  }
```

@remojansen mentioned, that we need to build an adapter for react to manipulate the way how react instantiate components.

Maybe after RC there is time for this :)

**Comment by remojansen** [comment]
I've been thinking about this for a while. I'm not sure about how will exactly work but I will share the my progress on it here...

**Comment by otbe** [comment]
Another thought on this. What I really want to do is:

```
export class Settings extends Component<SettingsProps, {}> {
  @inject(MyService)
  private myService: MyService;

  render() {}
}
```

Its more declarative and closer to other DI frameworks (like guice) :)

I have hacked a decorator to do this, but with the disadvantage of injecting at accessing the property. :(

**Comment by remojansen** [comment]
I will do some analysis but implementing property injection is something possible.

**Comment by kenjiru** [comment]
An integration with React would be really cool, something like the connect() wrapper from "react-redux". This would allow us to wrap the root component of our application and then inject all the needed classes in the child components.

**Comment by donaldpipowitch** [comment]
Looking forward to this! Thank you.

**Comment by remojansen** [comment]
I would like to share some thoughts about this.... All kinds of feedback will be much appreciated.

### The current behaviour

Connect could actually be used to inject some props using the latest release:

``` ts
function mapStateToPropsReposPage(state: any) {
    return { 
        repos: state.get("repos"),
        myService: kernel.get<MyService>(MyService)
    };
}

function mapDispatchToPropsReposPage(dispatch: Redux.Dispatch) {
    return { actions : bindActionCreators(settingsActions, dispatch) };
}

@connect(mapStateToPropsReposPage, mapDispatchToPropsReposPage)
class Settings extends Component<SettingsProps, {}> {
  // ...
}
```

### Option A: Optional dependencies

``` ts
export class Settings extends Component<SettingsProps, {}> {
  constructor (props: SettingProps, context: any, @inject(MyService) private myService: MyService) {
    super(props, context);
  }
  // ...
}
```

This introduces optional dependencies. We **won't be implementing this** because it can lead to bad practices and in the context of React is useless.

### Option B: Property injection

``` ts
export class Settings extends Component<SettingsProps, {}> {
  @inject(MyService)
  private myService: MyService;

  render() {}
}
```

In the current version when we use `@inject` (as a parameter decorator) we are generating metadata but nothing is resolved. Later, when we invoke `kernel.get<T>("T")` is when the actual entities are resolved and injected.

In the case of property injection (and in particular React) when we use  `@inject` (as a property decorator) we are not generating metadata we are actually resolving  and setting the dependency. This means that  `@inject` (as a property decorator) needs access to the kernel:

``` ts
let kernel = new Kernel();
kernel.bind<ISomeService>("ISomeService").to(SomeService);
let inject = makeInjectPropertyDecorator(kernel);

class SomeWebComponent {
    @inject("ISomeService")
    private _service: ISomeService;
    public doSomething() {
        let count =  this._service.count;
        this._service.increment();
        return count;
    }
}
```

When we access the property (getter) is when `kernel.get<T>("T")` is invoked. We can optimise this so the dependency is resolved only when we access the property for the first time. 

This seems to be the way to go. My main concern is how to support some of the contextual binding constraints like `whenNoAncestorIs` or `whenAnyAncestorNamed`. I need to do some more thinking on this...

**Comment by otbe** [comment]
@remojansen 
Would love to see option B in inversify :)

My current implementation of `@inject` does exactly what you describe :) I could share it, but its a bit hacky :) 
This includes your optimization about only one `kernel.get<T>("T")`. This is necessary, because we have to provide the same reference for MyService for every hit of `this.myService`.  We also have to support multiple injections of the **same** service (for different keys). Something like:

``` javascript
export class Settings extends Component<SettingsProps, {}> {
  @inject(MyService)
  private myService: MyService;

  @inject(MyService)
  private myService2: MyService;

  render() {}
}
```

`myService` and `myService2` should be different objects (if transient).

Btw: in the same manner we could provide `@provideTransientScope` and `@provideSingletonScope` decorators for unifying `@injectable()` and `kernel.bind<ISomeService>("ISomeService").to(SomeService);`. For example:

``` javascript
// for singletons
@provideSingletonScope
class MyService {}

// for transient instances
@provideTransientScope
class MyService {}
```

Our code looks very elegant and organized with this three decorators (`@inject`, `@provideSingletonScope`/`@provideTransientScope`) :)

**Comment by remojansen** [comment]
@otbe I would like to ask a few questions if you don't mind...

### How @provideSingleton works?

You are suggesting that `@provideSingletonScope` will generate the following binding:

``` ts
kernel.bind<ISomeService>("ISomeService").to(SomeService).inSingletonScope();
```

I assume that you mean the following:

``` ts
kernel.bind<any>(SomeService).to(SomeService).inSingletonScope();
```

As we don't have any other identifier or type information at that point? It would be like the following:

``` ts
let kernel = new Kernel();
let provideSingleton = makeProvideSingletonDecorator(kernel);
let provideTransient = makeProvideTransientDecorator(kernel);

// AKA kernel.bind<any>(MyService1).to(MyService1).inSingletonScope()
@provideSingleton
class MyService1 {}

// AKA kernel.bind<any>(MyService2).to(MyService2).inTransientScope()
@provideTransient
class MyService2 {}
```

### What about a fluent decorators?

Your idea made me think about the following:

``` ts
let kernel = new Kernel();
let provide = makeProvideDecorator(kernel);

// AKA kernel.bind<any>(MyService1).to(MyService1).inSingletonScope()
@provide().inSingletonScope().done()
class MyService1 {}

// AKA kernel.bind<any>(MyService2).to(MyService2).inTransientScope()
@provide().inTransientScope().done()
class MyService2 {}

// AKA kernel.bind<any>(Katana).to(Katana).whenTargetTagged("canThrow", false)
@provide().whenTargetTagged("canThrow", false).done()
class Katana {}

// AKA kernel.bind<any>(Shuriken).to(Shuriken).whenTargetTagged("canThrow", true)
@provide().whenTargetTagged("canThrow", true).done()
class Shuriken {}
```

Creating aliases would be straight forward:

``` ts
let provideSingleton = provide().inSingletonScope().done();
let provideTransient = provide().inTransientScope().done();
let provideThrowable = provide().whenTargetTagged("canThrow", true).done();

@provideSingleton
class Katana {}

@provideTransient
class Katana {}

@provideThrowable
class Shuriken {}
```

What do you guys think?

### Using `@set` instead of `@inject`?

I also have a question for everyone. To avoid confusion between `@inject` as a parameter decorator and `@inject` as a property decorator I think we should use a better naming.

How about naming the property decorator `@set`?

``` ts
let kernel = new Kernel();
kernel.bind<ISomeService>("ISomeService").to(SomeService);
let set = makeSetDecorator(kernel);

class SomeWebComponent {
    @set("ISomeService")
    private _service: ISomeService;
    public doSomething() {
        let count =  this._service.count;
        this._service.increment();
        return count;
    }
}
```

**Comment by remojansen** [comment]
I'm adding the `discussion` label to this because this ticket will be splitted into a few tickets once we have a better idea of what needs to be done. For the moment it is likely that we will have two tickets:
- Property injection support
- Declaration of bindings via decorators

**Comment by donaldpipowitch** [comment]
I don't know if `@set` is as clear as `@inject`. "Set" always sounds very "final" to me. I wouldn't guess I could change the passed service at runtime.

I personally don't mind using `@inject` for properties _and_ parameters, if they do basically the "same" things in two different contexts and if these contexts can't clash with each other.

**Comment by otbe** [comment]
@remojansen 
Yes you're right. `@provideSingletonScope` would create `kernel.bind<any>(SomeService).to(SomeService).inSingletonScope();` (this was a copy&paste error :))

Fluent decorators would be fine for me. Im not sure if I would use it the following way `@provide().inTransientScope().done()` (its a bit long :)), but +1 for aliases.

Like @donaldpipowitch said, `@set` seems a bit out of context. Basically its an injection and I prefer
to `@inject`, but with aliasing its up to me 👍 

Just for clarification:
The following should work as expected? Note the `SomeService` in `@set`. I don't want to pass string constants through my application :)

``` javascript
let kernel = new Kernel();
kernel.bind<SomeService>(SomeService).to(SomeService);
let set = makeSetDecorator(kernel);

class SomeWebComponent {
    @set(SomeService)
    private _service: ISomeService;
    public doSomething() {
        let count =  this._service.count;
        this._service.increment();
        return count;
    }
}
```

**Comment by remojansen** [comment]
Hi @otbe and @donaldpipowitch thanks for your comments.

We will use `@inject` instead of `@set`. 

About the string constants. The `@inject` decorator will work with classes, strings and symbols, just like the current `bind` method.

``` ts
interface IKernel {
    bind<T>(serviceIdentifier: (string|Symbol|INewable<T>)): IBindingToSyntax<T>;
    // ...
}
```

``` ts
let kernel = new Kernel();
kernel.bind<SomeService>(SomeService).to(SomeService);
let inject= makeInjectPropertyDecorator(kernel);

class SomeService {}

class SomeWebComponent {
    @inject(SomeService)
    private _service: SomeService;
    public doSomething() {
        let count =  this._service.count;
        this._service.increment();
        return count;
    }
}

// or

let ISomeService = "ISomeService";

class SomeWebComponent {
    @inject(ISomeService)
    private _service: ISomeService;
    public doSomething() {
        let count =  this._service.count;
        this._service.increment();
        return count;
    }
}

// or 

let ISomeService = Symbol("ISomeService");

class SomeWebComponent {
    @inject(ISomeService)
    private _service: ISomeService;
    public doSomething() {
        let count =  this._service.count;
        this._service.increment();
        return count;
    }
}
```

**Comment by remojansen** [comment]
I have created [an issue for property injection support ](https://github.com/inversify/InversifyJS/issues/189) please review too see If I forgot to think about something...

Let's focus on `@provide` in this issue. I will create a ticket for it once I feel more confident about the final requirements.

**Comment by otbe** [comment]
The only thing you may have missed to mention in your examples: support for multiple `@inject`s for the same service on different properties. Something like:

``` javascript
export class Settings extends Component<SettingsProps, {}> {
  @inject(MyService)
  private myService: MyService;

  @inject(MyService)
  private myService2: MyService;

  render() {}
}
```

Is this necessary?

**Comment by remojansen** [comment]
@otbe thanks for spotting it :)

**Comment by remojansen** [comment]
I'm going to close this issue you can track the progress and share feedback at:
- [@provide support](https://github.com/inversify/InversifyJS/issues/190)
- [Property injection support](https://github.com/inversify/InversifyJS/issues/189)

Thanks a lot @otbe @donaldpipowitch and @kenjiru for sharing your feedback! :+1:
