### ISSUE TITLE
Properties decorated by @inject are not enumerable

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#196]
## Expected Behavior

`obj.propertyIsEnumerable('prop')` returns true
## Current Behavior

`obj.propertyIsEnumerable('prop')` returns false
## Possible Solution
- Create unit test to reproduce the issue
- Investigate why [property descriptor](https://github.com/inversify/InversifyJS/blob/master/src/annotation/property_injectors.ts#L47-L48) is not working.

**Comment by otbe** [comment]
Use case

``` javascript

export class MyServiceB {
  @inject(MyServiceA)
  myServiceA: MyServiceA

  name: string;
}

let s = kernel.get(MyServiceB);
console.log(Object.keys(s)); // [ 'name' ]
console.log(s.propertyIsEnumerable('myServiceA'); // false
```

**Comment by remojansen** [comment]
From [SO](http://stackoverflow.com/questions/10968962/hasownproperty-vs-propertyisenumerable):

> `propertyIsEnumerable` will return true only for enumerable "own" properties.

**Comment by otbe** [comment]
Maybe we could add a hint to the docs !?
From a users point of view (and non decorator expert) its a bit unexpected, because we declare this property like any other property within the class. So why it should not be enumerable?

**Comment by SET001** [comment]
maybe I'm doing something wrong but methods/properties of classes decorated with `@injectable` also not enumerable

**Comment by remojansen** [comment]
Well `@injectable` should only be applied to classes and `@inject` only applied to properties or the arguments of a method. So they can't be applied to a method. In the case of properties it will be not enumerable.

**Comment by SET001** [comment]
The problem was that to enumerate object methods in ES6 one should use `Object.getOwnPropertyNames` on that object prototype.
Not Inversify related.
