### ISSUE TITLE
Investigate optional @injectable() annotations

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#210]
This was issue was suggested by @gjsduarte on Gitter...
## Suggested Behavior

The `@injectable()` annotation could become optional in some cases.
## Current Behavior

The `@injectable()` annotation is mandatory.
## Possible Solution

When the `@inject` decorator is used, the `@injectable()` annotation could become optional.
When a class has no dependencies, the `@injectable()` annotation could become optional.
We need to be able to help developers with friendly exceptions.
## Context

The `@injectable()` annotation is mandatory because it help us to provide the users with friendly exceptions.

**Comment by gjsduarte** [comment]
I suggest two possibilites here:
- Extend the binding to syntax to optionally automatically decorate the class:
  `if (!Reflect.hasOwnMetadata(METADATA_KEY.PARAM_TYPES, constructor)) {
          decorate(injectable(), constructor);
   }`
- Change the planner to only check for the @injectable attribute on sub-dependencies:
  Perhaps by adding a flag to the _getDependencies that is set by the _createChildRequest method.

**Comment by remojansen** [comment]
Hi @gjsduarte I'm sorry bad I have bad news. The following is extracted from the angular 2.0 docs by Google:

> We recommend adding @Injectable() to every service class, even those that don't have dependencies and, therefore, do not technically require it. Here's why:
> - Future proofing: No need to remember @Injectable() when we add a dependency later.
> - Consistency: All services follow the same rules, and we don't have to wonder why a decorator is missing.

We could make then optional but by adding @injectable to all our classes we can provide better error handling. Also in the future @inject might be not needed if the metadata generated by the TypeScript compiler for @injectable becomes more rich (at the moment it cannot be used for interfaces).

If this happens and we have all our classes decorated with @injectable, it will be save to remove all @inject annotations so it will be easier to migrate to a new version.

So I'm sorry but @injectable will remain mandatory.
