### ISSUE TITLE
inversify-express-utils

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#214]
See [comment](https://github.com/inversify/InversifyJS/issues/71#issuecomment-220280269) and [inversify-express-utils](https://github.com/inversify/inversify-express-utils) for more details.

**Comment by remojansen** [comment]
Hi @codyjs I did a release yesterday https://www.npmjs.com/package/inversify-express-utils I haven't test it yet though... let me know if you find issues and need a new release :wink:

**Comment by remojansen** [comment]
p.s. do you think we can close this issue as we have an [issue for the example](https://github.com/inversify/InversifyJS/issues/71). If there are bugs or new features we can create new issues...

**Comment by codyjs** [comment]
Cool, I'll try it out!

Yeah, we can close this issue and use the new repository for any bugs/features
