### ISSUE TITLE
toValue is not a function on beta.6

### ISSUE THREAD

**Issue by simon-hardy** [inversify/InversifyJS#221]
Current example is a string, but also exists with other types.
## Expected Behavior

Should resolve the string literal value in this instance.
## Current Behavior

`container.bind('base-api-address').toValue('http://localhost:5000/api/');
                                               ^
TypeError: container.bind(...).toValue is not a function`
## Possible Solution

Unknown, sorry.
## Your Environment
- Version used: 2.0.0.beta.6
- Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs v6.2.0
- Operating System and version (desktop or mobile): Windows 10
# Stack trace

TypeError: container.bind(...).toValue is not a function
    at Function.BootApi (C:\code\xx\build\boot\Bootstrapper.js:18:48)
    at Function.Boot (C:\code\xx\build\boot\Bootstrapper.js:12:38)
    at Object.<anonymous> (C:\code\xx\build\app.js:5:43)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

**Comment by remojansen** [comment]
Hi, we renamed `toValue` a couple of releases ago. It is now called `toConstantValue`

We need to update [our website](http://inversify.io/) but the [docs on GitHub](https://github.com/inversify/InversifyJS/blob/master/README.md) should be up to date.

Can you please try with the following?

``` ts
container.bind('base-api-address').toConstantValue('http://localhost:5000/api/');
```

**Comment by simon-hardy** [comment]
@remojansen thanks mate, there are still a couple of toValue calls in the github docs as well

What threw me is that intellisense is still showing toValue.

**Comment by remojansen** [comment]
I will try to fix the docs ASAP. Can you please let me know which inversify.d.ts file are you using? Is it the [inversify-dts](https://www.npmjs.com/package/inversify-dts) one? In beta.6 we have done some changes to [the installation process](https://github.com/inversify/InversifyJS#installation).

**Comment by simon-hardy** [comment]
I originally was using the typings DefinitelyTyped ones, when I realised those were alpha I uninstalled them. I then looked for ones in the npm package but didn't find any. Honestly not sure where my IDE is picking them up from now (tried both atom.io and VS Code).

**Comment by remojansen** [comment]
I have updated the GitHub docs. Can you please confirm that the type definitions included in https://www.npmjs.com/package/inversify-dts work for you?

**Comment by simon-hardy** [comment]
OK, that's solved my problem, but raised another...

During build of my Typescript, I get the following issue:

> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(667,9): error TS2300: Duplicate identifier 'concurrency'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(670,9): error TS2300: Duplicate identifier 'spread'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(673,9): error TS2300: Duplicate identifier 'suffix'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(674,9): error TS2300: Duplicate identifier 'filter'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(676,9): error TS2300: Duplicate identifier 'promisifier'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(683,9): error TS2300: Duplicate identifier 'promise'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(707,9): error TS2300: Duplicate identifier 'callback'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(743,5): error TS2300: Duplicate identifier 'export='.
> typings/globals/bluebird/index.d.ts(667,9): error TS2300: Duplicate identifier 'concurrency'.
> typings/globals/bluebird/index.d.ts(670,9): error TS2300: Duplicate identifier 'spread'.
> typings/globals/bluebird/index.d.ts(673,9): error TS2300: Duplicate identifier 'suffix'.
> typings/globals/bluebird/index.d.ts(674,9): error TS2300: Duplicate identifier 'filter'.
> typings/globals/bluebird/index.d.ts(676,9): error TS2300: Duplicate identifier 'promisifier'.
> typings/globals/bluebird/index.d.ts(683,9): error TS2300: Duplicate identifier 'promise'.
> typings/globals/bluebird/index.d.ts(707,9): error TS2300: Duplicate identifier 'callback'.
> typings/globals/bluebird/index.d.ts(743,5): error TS2300: Duplicate identifier 'export='.

**Comment by remojansen** [comment]
You are importing bluebird.d.ts but inversify already imports bluebird for you. Try to remove bluebird from you `typings.json` and `typings/index.d.ts` Also, if you are importing `harmony-proxy` you will have the same problem with it.

**Comment by remojansen** [comment]
Your comments have helped me to spot an issue I have documented it [here](https://github.com/inversify/InversifyJS/issues/222). I will fix it as soon as I can. Thanks a lot for asking for help this is the only way we can improve the library.

**Comment by remojansen** [comment]
We have published a new version of [inversify-dts](https://www.npmjs.com/package/inversify-dts). Is everything working for you now?

**Comment by simon-hardy** [comment]
Yep all looks good from my end. Thanks for the quick turnaround.

The only suggestion I might have is to version the inversify-dts package the same as the main inversify package as currently it is 1.0.1 and correlates to 2.0.0-beta.6.

**Comment by remojansen** [comment]
Thanks, I don't think we will be able to do that because `inversidy-dts` constains definitions for all our projects and `inversify` is only one of the projects. This means that there will be many more releases of `inversidy-dts` than `inversify`. I'm sorry for all this `.d.ts` mess but we are just waiting for TypeScript 2.0 to be relased as it will include a new a better way to distribute `.d.ts` files.

About the duplicated identifiers issue I believe we have to do more work so I have created another issue [#231](https://github.com/inversify/InversifyJS/issues/231) and I'm going to close this one.
