### ISSUE TITLE
Travis builds are running tests twice

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#224]
## Expected Behavior

The tests should only be run once per Travis build.
## Current Behavior

The builds are running twice.
## Steps to Reproduce (for bugs)
1. Look at a Travis CI log (e.g. https://travis-ci.org/inversify/InversifyJS/jobs/133177140)
2. Notice that on the `npm install` command, `gulp build && gulp test` is executed (because the `prepublish` script is executed on local `npm install`)
3. Travis then runs `npm test` which runs the tests again
## Context

The build is taking almost 17 minutes when it could be much much shorter.

**Comment by remojansen** [comment]
This should be fixed now thanks to [an AWESOME npm module](https://github.com/inikulin/publish-please). Thanks for reporting the issue!
