### ISSUE TITLE
vscode directory in git

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#230]
I'm not sure there is any value in having the vscode directory tracked by git.

I don't use Visual Studio when developing so it's redundant for me, and I imagine for other people interested in the project, too.

What do you think @remojansen?

**Comment by remojansen** [comment]
The problem for me is that vscode shows all the JS files in the project explorer and it creates a lot of noise. If the file is not creating any issues in other IDEs I would like to keep it as it helps me. The TypeScript guys [do it as well](https://github.com/Microsoft/TypeScript/blob/master/.vscode/tasks.json).

**Comment by Jameskmonger** [comment]
Sure, there are no issues with having it in IDEs, I wasn't sure of any benefits but I'm happy to close this if it significantly helps the developers using Visual Studio :smile:
