### ISSUE TITLE
Duplicate identifiers caused by .d.ts files

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#231]
## Expected Behavior

No duplicated .d.ts errors should be caused by installation as suggested by @tenowg in the chat.
## Current Behavior

Some users have reported issues caused by duplicated .d.ts files:

> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(667,9): error TS2300: Duplicate identifier 'concurrency'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(670,9): error TS2300: Duplicate identifier 'spread'.
> node_modules/inversify-dts/typings/globals/bluebird/index.d.ts(673,9): error TS2300: Duplicate identifier 'suffix'.
## Possible Solution

Remove reference from [actual d.ts files](https://github.com/inversify/dts/blob/master/inversify/inversify.d.ts#L6-L7):

```
/// <reference path="../typings/globals/bluebird/index.d.ts" />
/// <reference path="../typings/globals/harmony-proxy/index.d.ts" />
```

Move then to [`tsconfig.json:`](https://github.com/inversify/dts/blob/master/tsconfig.json):

``` js
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": false
    },
    "files": [
        "typings/index.d.ts"
    ]
}
```

Users will need to install bluebird and harmony proxy manually. If the users have then installed already they will not get duplication errors.

This might allow us to [typings-for-npm-packages](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html); as  what was stopping us from using typings-for-npm-packages was the triple-slash references.

> Your definition files should
> - be.d.ts files :white_check_mark: 
> - be written as external modules :white_check_mark: 
> - not contain triple-slash references :x:

**Comment by tenowg** [comment]
I might mention.. that manually removing both /// from inversify.d.ts does NOT require that I install the typings for harmony-proxy or bluebird, as my builds are working without these, nor did I change any other settings in tsconfig.json...

On a side note... I seriously hope that 2.0 typscript fixes many of these issues...

**Comment by remojansen** [comment]
Are you targeting ES6? When targeting ES5 I need to manually install bluebird or Promise type is not found...

**Comment by remojansen** [comment]
I have released inversify-dts@1.0.3 this issue should be fixed now. Sometimes it is required to manually install typings but no duplicated typings errors should take place...

**Comment by tenowg** [comment]
Sorry for late reply... targetting es5, Promise is part of node, just install typings for node and forget about bluebird

**Comment by remojansen** [comment]
No worries... I will document that. If using node.d.ts no need for bluebird but if you are working on a browser app you do need it.
