### ISSUE TITLE
Typings should not be in devDependencies if used in postinstall

### ISSUE THREAD

**Issue by FGRibreau** [inversify/InversifyJS#233]
[This commit](https://github.com/inversify/InversifyJS/commit/00cbd0306603ab9698ec0898232a9838e8ebe33a) in inversify beta7 breaks the build in production because typings is only available from devDependencies while still being used in npm postinstall step

**Comment by remojansen** [comment]
Thanks for reporting I'm working on this now...

**Comment by remojansen** [comment]
Hi I have roll back that commit and beta.8 has been released can you please try it?

**Comment by remojansen** [comment]
Another note the .d.ts files in the inversify-dts project have been updated. Before if a third party library was required (e.g. bluebird) it was included. If the users had already included this library they would get a duplicated type identifier error. To solve this problem we don't include them anymore but we do require the users to install them manually.

**Comment by remojansen** [comment]
Hi @FGRibreau was this problem solved for you? Can I close the issue?

**Comment by FGRibreau** [comment]
@remojansen yes :)
