### ISSUE TITLE
inversify-express-utils: async calls fails with 'Can't set headers after they are sent'

### ISSUE THREAD

**Issue by m-abs** [inversify/InversifyJS#241]
I'm trying convert an existing webservice to inversify-express-utils.
Most (if not all) path/routes are async, when I send the response my service throws this "Error: Can't set headers after they are sent.", even though I haven't sent anything yet in my code.
## Expected Behavior

I'd like to be able to create async path/routes in my Express service, without sending headers prior to returning from the function.

I suggest a change here:
https://github.com/inversify/inversify-express-utils/blob/master/src/route-container.ts#L44
Check that result isn't undefined/null or expect a promise.
## Current Behavior

Current behavior, https://github.com/inversify/inversify-express-utils/blob/master/src/route-container.ts#L47, sends the result-variable if res.headersSent isn't true.
## Steps to Reproduce (for bugs)
1. Create a route/path that responds async: See https://github.com/m-abs/testing-inversify-express-utils/blob/master/index.ts#L19
2. Make an HTTP-request to that path,
3. Once the response is sent, express throws the error:
   "Error: Can't set headers after they are sent."
## Context

I'm converting a webservice that delivers content for an audiobook player.
The service makes various calls to other services and thus responds async.
The service can't sent the headers right away, because it needs to request another service or check the filesystem before it knows if it can respond with a 2xx-code or a failure code.
This issue has the effect that I can't convert the service to inversify-express-utils
## Your Environment
- Version used:
- nodejs 6.2
- Fedora Linux 23
- Link to example: https://github.com/m-abs/testing-inversify-express-utils

**Comment by codyjs** [comment]
I think this is a must-have.

I think it would be nice if the user could have a choice of calling `res.send()` (or equivalent) after resolving the promise, or instead just have the promise resolve to the value to be sent.

We just need to have a similar check after the resolution of the promise, something like:

``` ts
let handler: express.RequestHandler = (req: express.Request, res: express.Response, next: any) => {
    let result = this.kernel.get(target.constructor.name)[targetMethod](req, res, next);

    // try to resolve promise
    if (result && result instanceof Promise) {

        result.then((value: any) => {
            if (!res.headersSent) {
                res.send(value);
            }
        });

    } else if (!res.headersSent) {
        res.send(result);
    }
};
```

But either way, the controller method would need to return the promise.

**Comment by m-abs** [comment]
@codyjs It's a great idea, but a few thoughts.
What about different types of responses? We return both HTML, json, images, mp3, zip and streams
Error handling? There should be a catch, but what about the statusCode and message?

Of cause with a Promise, the controller method could handle that, if only it sends the header before resolving.

**Comment by m-abs** [comment]
Looking at https://github.com/inversify/inversify-express-utils/blob/master/src/route-container.ts#L44-49

I don't think that the next-function and be used. We don't need it in our project, but I still think it should work :+1:

**Comment by codyjs** [comment]
> What about different types of responses? We return both HTML, json, images, mp3, zip and streams

The idea was to give users as much freedom as possible by giving them access to the Response object, but also allow the common case (i.e., `res.send()`) to be the easiest to implement by simply returning an object from your controller's method.

I was thinking to get around this, we could add an optional parameter to the method decorators that specifies the method on `res` to call, something like `@Get('/', 'sendFile')`, but really this would be just as easy as calling `res.sendFile()` in the method itself.

> Error handling? There should be a catch, but what about the statusCode and message?

This is something that hasn't been implemented yet, but definitely should. There should be a method on the InversifyExpressServer that lets you set up the error handlers, kind of like `.setConfig()`. That would be where you specify the error message and statusCode.

Then either use `next(err)`, or like you said, use a try/catch to around the controller method call and then pass the error along.

> I don't think that the next-function and be used.

I don't understand this point. Why can't the next function be used?

**Comment by m-abs** [comment]
I think you're right, it's much easier just to call the res.sendFile() within our own function.

Thank you for the `next(err)` suggestion, I'll try that.

> I don't understand this point. Why can't the next function be used?

Sorry, I was confused. I had some wrong assumptions about how the next-function works.

**Comment by m-abs** [comment]
I tried your patch and hit a minor problem, see here:
https://github.com/m-abs/testing-inversify-express-utils/blob/next-fn/index.ts#L14
Request to http://localhost:3000/ works as expected, index(...) calls next() and index2() returns 'indexi'

https://github.com/m-abs/testing-inversify-express-utils/blob/next-fn/index.ts#L25-L43
Request to http://localhost:3000/async respond with an empty page and the server throws:

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/home/mabs/project/inversify-express-utils/node_modules/express/lib/response.js:718:10)
    at ServerResponse.json (/home/mabs/project/inversify-express-utils/node_modules/express/lib/response.js:246:10)
    at Timeout._onTimeout (index.ts:60:25)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by m-abs** [comment]
Inspired by @codyjs fix, I've tried to solve the problem I had with next()-calls. 

``` typescript
        let handler: express.RequestHandler = (req: express.Request, res: express.Response, next: any) => {
            let nextCalled = false;
            let postHandler = (value: any) => {
                if (!nextCalled && !res.headersSent) {
                    res.send(value);
                }
            };

            let result = this.kernel.get(target.constructor.name)[targetMethod](req, res, (...nextArgs: any[]) => {
              nextCalled = true;
              next(...nextArgs);
            });

            // try to resolve promise
            if (result && result instanceof Promise) {
                result.then(postHandler);
            } else {
                postHandler(result);
            }
        };
```

https://github.com/m-abs/inversify-express-utils/blob/handle-promise-and-next/src/route-container.ts#L44-63

The problem:
- The function notAsync() calls next() (https://github.com/m-abs/testing-inversify-express-utils/blob/next-fn/index.ts#L26)
- So the function async() is called and returns a promise. (https://github.com/m-abs/testing-inversify-express-utils/blob/next-fn/index.ts#L31)
- notAsync() then returns the result from next(), which is undefined, so the RequestHandler returns an empty page to the client.
- So when the promise async() is resolved, the headers was already sent.

The solution:
- Wrap the next-function parameter, to register if it's called.
- If next() was called, don't send the data to the client.

**Comment by remojansen** [comment]
Hi @codyjs I have granted you pushing permissions for this repo. This should help you to contribute and merge PR from others.

I will use the express Dev utils soon in one of my projects and I will collaborate them. At the moment all my time its being consumed by [the chrome devtools](https://vimeo.com/169354465) but I'm nearly done :smile_cat: I will ask you for help in the future because maybe is possible to enable the DevTools for Node.js using a child process...

**Comment by codyjs** [comment]
@remojansen Thanks for the access! It will come in handy.

@m-abs Sorry for the delay, I have been on vacation.

At first glance, I think the solution here would be to pass in the original `next()` function from the outer request handler to the controller method, but I would need to test it. When I get home tonight I'll hopefully be able to work on this.

**Comment by codyjs** [comment]
I think I found the solution to your problem. It seems that the request handler was sending the response even if the controller method didn't return anything. This was negating any calls to `next()`. Adding an additional check to the `else if` condition seems to have fixed this:

``` ts
let result: any = this.kernel.getNamed("IController", controllerName)[key](req, res, next);

// try to resolve promise
if (result && result instanceof Promise) {

    result.then((value: any) => {
        if (value && !res.headersSent) {
            res.send(value);
        }
    });

} else if (result && !res.headersSent) {
    res.send(result);
}
```

After this fix, the following two test cases pass:

``` ts
it ("should work for async methods which call next()", (done) => {
    @injectable()
    @Controller("/")
    class TestController {
        @Get("/") public getTest(req: express.Request, res: express.Response, next: express.NextFunction) { 
            return new Promise(((resolve) => {
                setTimeout(() => {next(); resolve();}, 100, "GET");
            }));
        }

        @Get("/") public getTest2(req: express.Request, res: express.Response) {
            return "GET";
        }
    }
    kernel.bind<TestController>("TestController").to(TestController);

    server = new InversifyExpressServer(kernel);
    request(server.build())
        .get("/")
        .expect(200, "GET", done);
});


it ("should work for async methods called by next()", (done) => {
    @injectable()
    @Controller("/")
    class TestController {
        @Get("/") public getTest(req: express.Request, res: express.Response, next: express.NextFunction) { 
            next();
        }

        @Get("/") public getTest2(req: express.Request, res: express.Response) {
            return new Promise(((resolve) => {
                setTimeout(resolve, 100, "GET");
            })); 
        }
    }
    kernel.bind<TestController>("TestController").to(TestController);

    server = new InversifyExpressServer(kernel);
    request(server.build())
        .get("/")
        .expect(200, "GET", done);
});
```

Let me know if this also worked for you.

**Comment by m-abs** [comment]
@codyjs 
I've just tested your fix and it solved the issue I had, thanks :+1:

**Comment by codyjs** [comment]
Great! I'm glad this helped. I'll be including this change in a 1.0.0-alpha.4 release sometime later this week.

**Comment by remojansen** [comment]
Hi @codyjs can this issue be closed now that we have released the latest version?

**Comment by codyjs** [comment]
Yes, this can be closed now.

**Comment by remojansen** [comment]
Thanks!

**Comment by satya-jugran** [comment]
I have raised a similar issue. If someone can look into this - inversify/inversify-express-utils#452
