### ISSUE TITLE
Use async/await for provider injection

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#248]
Once TypeScript 2.1 is released we will be able to use async await and remove the need for the bluebird npm package and its type definitions.

We will need to list TypeScript 2.0 as a peer dependency.

**Comment by remojansen** [comment]
I'be been doing some analysis on this and it is better to wait for now until TypeScript 2.0 becomes stable.

**Comment by jamesadarich** [comment]
Hey Remo,

Just in case you haven't seen this feature has moved to TypeScript 2.1 :)

**Comment by remojansen** [comment]
Thanks for letting me know I have updated the description :)

**Comment by remojansen** [comment]
I'm closing this issue because I changed my original plans... You can learn more about the proposed alternative at https://github.com/inversify/InversifyJS/issues/404
