### ISSUE TITLE
Suggestion: Add 'typings' in package.json

### ISSUE THREAD

**Issue by davidstellini** [inversify/InversifyJS#252]
Instead of splitting up the definitions into two libraries, it would be nice if you do what `@angular` does.
Here's an example: https://github.com/angular/angular/blob/master/modules/%40angular/core/package.json#L7

All you need to do is grab this file: `node_modules/inversify-dts/inversify/inversify.d.ts`, ensure it is under the root directory of 'inversify', and then, in your package.json, add this entry:
`typings : 'index.d.ts'`.

This makes sure that as soon as someone does:
`npm install inversify`,
they are ready to go if they have `moduleResolution : node` in their `tsconfig.json` It's super easy!

**Comment by davidstellini** [comment]
Meanwhile, for anyone looking to install inversify typings, they can do:
    npm install inversify --save
    npm install inversify-dts  --save-dev
    typings install npm:inversify-dts/inversify/inversify.d.ts --save --global

This is always better than manually adding a ///<reference path=...

I've added a readme.md change here: https://github.com/inversify/InversifyJS/pull/253

**Comment by remojansen** [comment]
I'm sorry but we can't use typings like angular does for a few reasons you can find more at https://github.com/inversify/InversifyJS/issues/186
