### ISSUE TITLE
Gulp build

### ISSUE THREAD

**Issue by CobeLapierre** [inversify/InversifyJS#257]
When building the project the lib folder should contain the necessary folders and their files

Now the files in the folders are required in. But do not exist.
e.g. : require(./kernel/kernel)
while kernel folder does not exist.

Therefore "npm install inversify@2.0.0-beta.9" is broken (came across this issue using this command)

i'm not a good gulp devoloper but should gulp.src in build-lib task not contain "src/*_/_.ts"

**Comment by remojansen** [comment]
Thanks for reporting will try to fix this ASAP.

**Comment by remojansen** [comment]
I just released beta.10 it please let me know if it works for you.

**Comment by remojansen** [comment]
Hi I just released 2.0.0-beta.10 please let me know if it works for you.

**Comment by remojansen** [comment]
Hi @carbosound1 I just rleased beta.10 please let me know if it works for you.

**Comment by remojansen** [comment]
Hi @carbosound1 I just rleased beta.10 please let me know if it works for you.

**Comment by CobeLapierre** [comment]
The issue is resolved. thanks for both resolving the issue and writing this amazing ioc.

**Comment by remojansen** [comment]
Thanks to you for using it :)
