### ISSUE TITLE
Broken imports in express-utils

### ISSUE THREAD

**Issue by lholznagel** [inversify/InversifyJS#263]
## Expected Behavior

All tests should run successful
## Current Behavior

The tests don´t run because it tries to import `IKernel` which does not exist in the typescript definition
## Possible Solution

Change imports so that they match the new typescript definitions
## Steps to Reproduce (for bugs)

1. Clone project
2. run npm install & typings install
3. run npm test
4. Error occurs
## Context

I just wanted to build the project on my local system. During `npm test` the error occurs
Note: The link to my project is the link to a fork and the branch where I fixed the error (wanted to do a PR until I saw that I have to do a issue)
## Your Environment

- Version used: Cloned from master
- Environment name and version (e.g. Chrome 39, node.js 5.4): Node 6.2.0
- Operating System and version (desktop or mobile): Linux Ubuntu 15.10
- Link to your project: https://github.com/lholznagel/inversify-express-utils/tree/fix_test
# Stack trace

events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeScript error: src/server.ts(2,10): Error TS2305: Module '"inversify"' has no exported member 'IKernel'.
npm ERR! Test failed.  See above for more details.

**Comment by remojansen** [comment]
Hi, thanks for reporting. I started working on this yesterday but is not ready. I'm working on [this](https://github.com/remojansen/inversify-express-utils) fork.

**Comment by lholznagel** [comment]
Ah okay, so nearly the same solution I used.
