### ISSUE TITLE
Discussion: Managing examples

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#265]
As you guys know the [inversify-code-samples](https://github.com/inversify/inversify-code-samples) repo has not been updated for some time and have some issues. I'm creating this issue to collelt some feedback about the future of this Repo...
## Current Behavior

Examples are really important because it helps use to gain new users. The main problem with the Repo is that is hard to implement multiple builds for multiple technology stacks. Also we can't configure automatic dependency updates powered by [https://greenkeeper.io/](https://greenkeeper.io/) as we do in the other projects. 

New devs may also find it scary a huge project full of examples.
## Expected Behavior

I think we should split the repo in multiple repos:
- inversify-express-example
- inversify-binding-decorators-example
- inversify-marionette-example
- inversify-hapi-example

Each repo would have an automatic build, automatic updates, etc. A page in the wiki and website will provide access to the full list of examples.

What do you guys think?

Thanks :four_leaf_clover:

**Comment by lholznagel** [comment]
I totally agree with you. When we split the example you can do multiple example and don´t have a folder in folder in folder insanity. Then also greenkeeper could work when we just have one package.json in the root and then instead of `app` or so the example name.
For example `BasicMongoDBTest`. This would include a basic example which uses MongoDB and also is shows how to test it.

**Comment by remojansen** [comment]
I just created the repos:
- https://github.com/inversify/inversify-express-example
- https://github.com/inversify/inversify-binding-decorators-example
- https://github.com/inversify/inversify-marionette-example
- https://github.com/inversify/inversify-hapi-example

If someone can help to migrate the examples to individual repositories that would be great.

**Comment by remojansen** [comment]
I will crate some issues of stuff that needs to be done. Here is the first one:
- [Refactor examples: split the inversify-code-samples into multiple projects](https://github.com/inversify/InversifyJS/issues/271)

**Comment by remojansen** [comment]
I have migrated each example to its new repo now we need to get done the following:
- [x] Update dependencies inversify-express-example
- [x] Add CI checks inversify-express-example
- [x] Enable greenkeeper for inversify-express-example
- [ ] Update dependencies inversify-binding-decorators-example
- [ ] Add CI checks inversify-binding-decorators-example
- [ ] Enable greenkeeper for inversify-binding-decorators-example
- [ ] Update dependencies inversify-marionette-example
- [ ] Add CI checks inversify-marionette-example
- [ ] Enable greenkeeper for inversify-marionette-example
- [ ] Update dependencies inversify-hapi-example
- [ ] Add CI checks inversify-hapi-example
- [ ] Enable greenkeeper for inversify-hapi-example

I will work on this once I release the [devtools](https://github.com/inversify/inversify-devtools). If someone want to help PRs are more than welcome!

Thanks :four_leaf_clover:

**Comment by lholznagel** [comment]
> Add CI checks inversify-express-example

A new example is nearly finished, probably tomorrow. After that I would work on this.

When all have CI we could add greenkeeper.

**Comment by remojansen** [comment]
:+1:  that also on my list. I will enable the builds on travis appveyor and greenkeeper :smile:

**Comment by remojansen** [comment]
I'm closing this remaining actions can be tracked by #306
