### ISSUE TITLE
Property injection with multiple tests in seperate files

### ISSUE THREAD

**Issue by CobeLapierre** [inversify/InversifyJS#266]
using: inversify@2.0.0-beta.10

I'm getting an error using property injection for one of the two tests.
When i remove one of these tests no errors at all.

Error: Missing required @injectable annotation in: C.

I recreated the problem in a small project see url below.
I can't figure out what the problem might be.
My guess would be something gets executed twice.

repo:
[https://github.com/carbosound1/inversify-testing-example](https://github.com/carbosound1/inversify-testing-example)
you can use "gulp watch" or "gulp test" to run karma

**Comment by remojansen** [comment]
Hi thanks for reporting. I will investigate and try to fix this ASAP.

**Comment by remojansen** [comment]
Hi, I'm trying to reproduce this issue in our unit test. I'm using the following test:

``` ts
    it("Trying to reproduce issue #266", () => {

        const kernel = new Kernel();
        let pInject = makePropertyInjectDecorator(kernel);

        let symbols = {
            IC: Symbol("IC")
        };

        class A {
            public b: B;

            constructor() {
                this.b = new B("test");
            }
        };

        class B {

            public name: string;

            @pInject(symbols.IC)
            public c: IC;

            constructor(name: string) {
                this.name = name;
            }

        };

        interface IC {
            test: string;
            getName(name: string): string;
        }

        @injectable()
        class C implements IC {
            public test: string;

            constructor() {
                this.test = "this is a test property";
            }

            public getName(name: string): string {
                return "this is the getName function " + name;
            }
        }

        kernel.bind<IC>(symbols.IC).to(C);
        let a = new A();
        expect(a.b).not.eql(undefined);
        expect(a.b.name).eql("test");
        expect(a.b.c.getName(a.b.name)).eql("this is the getName function " + a.b.name);

    });
```

The test is working so I'm almost sure that your problem is the same as [#262](https://github.com/inversify/InversifyJS/issues/262). You are importing `reflect-metadata` multiple times.
- [import 1](https://github.com/carbosound1/inversify-testing-example/blob/9659b999413d10a22b1895f6624b5e20e473eeb0/Root/src/inversify.config.ts#L2)
- [import 2](https://github.com/carbosound1/inversify-testing-example/blob/a3a7f4c599661433436a1fc41eb7d160e99b7912/Root/src/c.ts#L2)

As I explained in #262:

> You need to remove the following from your code:

``` ts
import "reflect-metadata";
```

> This line should be be used only once by the consumers.
> 
> The consumers are the ones that need to import it. For example, InversifyJS uses Reflect but you as a consumer need to import it.
> 
> We do [import reflect when we run the unit test](https://github.com/inversify/InversifyJS/blob/master/gulpfile.js#L174) because the unit test can be considered as a consumer.

So you need to change your code to import "reflect-metadata" only once in your whole application.

**Comment by CobeLapierre** [comment]
Sorry, it is indeed the problem with importing the metadata. I hadn't noticed the #262 issue.
The ticket can be closed. Thanks

**Comment by remojansen** [comment]
No problem :smile: happy to help.
