### ISSUE TITLE
inversify-express-utils@1.0.0-rc.1

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#274]
I'm creating this issue to as a few questions to @codyjs and @lholznagel ...

I have released inversify@2.0.0-rc.1 and I'm now upgrading and releasing the side projects as release candidate 1. 

So I'm wondering is inversify-express-utils ready to be a release candidate? Or should I wait more?

Thanks!

**Comment by lholznagel** [comment]
When the updates comes, I would check if my example works, if not I would update it.

Currently working on a new example, will take some time because I don´t have much time this weekend.

Would be nice if the new Version has some new commits, but to keep everything on the same Version I find it ok

**Comment by remojansen** [comment]
I have released inversify-express-utils@1.0.0-rc.1 🎉

**Comment by codyjs** [comment]
I think inversify-express-utils is ready to be a release candidate. I can't think of any more features that would be needed.
