### ISSUE TITLE
Importing Kernel interface is difficult

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#298]
## Expected Behavior

It should be easier to import the `Kernel` interface. I expected to be able to do:

```
import { IKernel } from 'inversify';
```
## Current Behavior

I have to import the interface like so:

```
import * as Inversify from 'inversify';

// the Kernel interface is then reachable here: Inversify.interfaces.Kernel;
```
## Context

I want to be able to reference the `Kernel` interface as a function argument.

**Comment by remojansen** [comment]
We moved the interfaces under the `interfaces` namespace because we decided to remove the `I` prefix from all interfaces:

``` ts
import { Kernel } from "inversify"; // is Kernel the class or the interface?
```

By doing the following we can solve the naming collision:

``` ts
import { interfaces, Kernel } from "inversify"; // is Kernel the class or the interface?
let kernel: interfaces.Kernel = new Kernel();
```

**Comment by remojansen** [comment]
Hi @Jameskmonger can this be closed? Do you have any ideas about how to improve this without introducing `I` prefix?

**Comment by Jameskmonger** [comment]
I personally think that we should add the `I` prefix to all interfaces.

The documentation that @mocanu-razvan linked to in #242 was for [writing declaration files](http://www.typescriptlang.org/docs/handbook/writing-declaration-files.html) rather than writing TypeScript.

I don't know of any other projects where the interfaces are stored in a separate `interfaces` module.

I would expect to be able to import them like this (and I think lots of others would also):

```
import { Kernel, IKernel } from 'inversify';
```

**Comment by remojansen** [comment]
I also like the `I` prefix but it is not [recommended in TypeScript](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines). I researched multiple issues and all the developers seems to agree:
- https://github.com/Azure/autorest/issues/498
- https://github.com/Microsoft/TypeScript-Handbook/issues/121

And it has recently been [added as a TsLint rule](https://github.com/palantir/tslint/issues/512). I understand that:

``` ts
import { Kernel, IKernel } from 'inversify';
let kernel: IKernel = new Kernel();
```

Is nice but is breaking the recommended style guides. 

The current solution:

``` ts
import { Kernel, interfaces } from 'inversify';
let kernel: interfaces.Kernel = new Kernel();
```

Requires just one extra word and it allow us to follow the style guide.

**Comment by Jameskmonger** [comment]
I am happy with the style, I guess it is just odd coming from a .NET perspective. Will close this as not an issue :)

**Comment by remojansen** [comment]
Thanks!
