### ISSUE TITLE
options.className in constructor makes injection fail

### ISSUE THREAD

**Issue by pnocera** [inversify/InversifyJS#30]
example 

``` javascript
export class MyClass extends AnotherClass implements IMyClass {
    constructor( 
      IShouldbeInjected: IShouldbeInjected ) {
        var options: any = {}
        options.el = '#mydiv';
        options.className = "row";
        super(options);
        this.childView = ChildView;
        this.collection = IShouldbeInjected;
    }
}
```

comes from kernel.ts _getConstructorArguments at line 96 in
if ('function' === typeof Map &&
            fnStr.indexOf("class") !== -1 &&
            fnStr.indexOf("constructor") === -1) {

```
        result = null;
    }
```

you probably have to replace fnStr.indexOf("class") with fnStr.indexOf("class ")

**Comment by jamesadarich** [comment]
Hey,

I've encountered this issue as well and it will probably be a bit further reaching than just adding a space at the end. I added a regular expression to check if the words "constructor" or "class" are in there as keywords and tested against your code (and mine) and all looks hunky dory :)

Cheers!

**Comment by pnocera** [comment]
That's pretty cool, thanks !

**Comment by remojansen** [comment]
@pnocera thanks for reporting the issue :+1:
