### ISSUE TITLE
Run test in web browsers

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#300]
As reported by @endel there are some issues in some versions of IE we need to put in place some testing in real browsers to prevent this kind of issues.

At the moment we run the tests in bot windows and linux but in node.js not browser environments.

**Comment by remojansen** [comment]
The issues in IE are caused because [Function.name](https://github.com/inversify/InversifyJS/blob/d6d8364484be0f06cae58ae07e66ed3a6d78e55a/src/planning/planner.ts#L175) is not an standard in JS versions < ES6.

The good news is that function name is only used to provide developer-friendly errors and it will be fine to use the following:

```
function getFunctionName(f) {
    return f.name ?  f.name : f.toString().match(/^function\s*([^\s(]+)/)[1];
}

let constructorName = getFunctionName(func);
```

Beyond this issue we need to prevent issues in browsers and to do so we need to run the tests on a web browser.

**Comment by remojansen** [comment]
We should mention our problem at https://github.com/facebookincubator/create-react-app/issues/102

**Comment by remojansen** [comment]
The function.name issue was fixed #302  by but it has not been released yet.

**Comment by remojansen** [comment]
Hi @endel,

Based on your feedback I have impelmented [browser testing](https://ci.appveyor.com/project/remojansen/inversifyjs/build/51/job/7i5tt8j0f4s2w79k#L922):

```
START:
31 07 2016 09:39:38.721:INFO [karma]: Karma v1.1.2 server started at http://localhost:9876/
31 07 2016 09:39:38.736:INFO [launcher]: Launching browsers Firefox, Chrome, IE with unlimited concurrency
31 07 2016 09:39:38.736:INFO [launcher]: Starting browser Firefox
31 07 2016 09:39:38.814:INFO [launcher]: Starting browser Chrome
31 07 2016 09:39:38.861:INFO [launcher]: Starting browser IE
31 07 2016 09:39:41.468:INFO [IE 11.0.0 (Windows 8.1 0.0.0)]: Connected on socket /#WnT7WRE6ip9Zi6wjAAAA with id 55234899
31 07 2016 09:39:42.966:INFO [Chrome 51.0.2704 (Windows 8.1 0.0.0)]: Connected on socket /#mU6ZwPr-SmIQDas4AAAB with id 13681852
31 07 2016 09:39:43.726:INFO [Firefox 47.0.0 (Windows 8.1 0.0.0)]: Connected on socket /#E4TyJvgr6NEtzvmvAAAC with id 63667869
// ...
Finished in 0.21 secs / 0.185 secs
SUMMARY:
√ 133 tests completed
× 2 tests failed
FAILED TESTS:
  InversifyJS
    × Should support the injection of providers
      IE 11.0.0 (Windows 8.1 0.0.0)
    ReferenceError: 'Promise' is undefined
       at Anonymous function (temp/bundle.test.js:10711:17)
       at Anonymous function (temp/bundle.test.js:10718:9)
    × Should be able to identify missing @injectable in a base class
      IE 11.0.0 (Windows 8.1 0.0.0)
    expected [Function: throws] to throw error including 'Missing required @injectable annotation in: Samurai' but got 'Missing required @injectable annotation in: undefined.'
    Error
```

It is almost ready, all the integration tests are running on the latest version of IE, Chrome and Firefox on AppVeyor. 

There two test failing on IE 11 once I get those two sorted I will merge and close the issue.

There might be problems in IE < 11 but I asume that everything can be fixed using polyfills.

**Comment by remojansen** [comment]
Done by #316

**Comment by endel** [comment]
Yay! 🎉  👏
