### ISSUE TITLE
Analysis needed for some user suggestions

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#303]
I'm creating this issue so I remember to investigate some suggestions from users...
### Extending a third party class

The first suggestion was [reported](https://github.com/inversify/InversifyJS/issues/297#issuecomment-234723021) by @lukas-zech-software and is about the exception: 

> The number of constructor arguments in a derived class must be >= than the number of constructor arguments of its base class

There is missing documentation about how to solve this issue when we are extending a third party class...
### Use `makePropertyInjectDecorator()` with kernel modules

The second suggestion comes from @otbe on Gitter:

```
let masterKernel = new Kernel();
let subKernel = new Kernel();
let inject = makePropertyInjectDecorator(subKernel);
masterKernel.load(subKernel);
```

> In this way I don't have to leak my masterKernel to other modules.
> Or in other words, every module can provide a own kernel and I can compose it in my main app

**Comment by endel** [comment]
Hey @remojansen,

What about when I'm extending another class but not implementing a constructor? E.g.:

``` typescript
@injectable()
class Base {
    constructor(@inject(Foo) foo: Foo) {
    }

    bar () {}
}

@injectable()
class Child extends Base {
    bar() {}
}
```

When trying to retrieve a `Child` through injection the same error pops out. Shouldn't I be able to just omit the constructor when extending another class?

**Comment by remojansen** [comment]
Hi @endel,

We try to provide developers with useful errors like `Missing @injectable annotation in class X` or `Missing @inject annotation in argument Y in class X` however we noticed a case in which the library was failing without errors.  

Due to technical limitation we had to reach a compromise. We had to choose only one of the following options:
- Not required  the declaration of constructors in derived classes and be unable to prevent silent errors that would lead developers to very confusing scenarios.
- Require the declaration of constructors in derived classes and matching number of arguments to prevent silent errors.

I decided that silent errors is much worst than enforcing the declaration of constructors. I'm sorry if it is not great at the moment.  I have recieved this feedback before and it is something I'm personally not happy about. The problem is caused mainly by [non-standard behavior in versions of node](http://stackoverflow.com/questions/37432443/how-to-identify-missing-constructor-arguments-in-base-derived-classes) so I believe that we will be able to improve this in the future but is something that we can't do at the moment.

**Comment by remojansen** [comment]
Hi @otbe sorry for the following really long comment! I've been thinking about ways to use property injection in an npm module that is not aware of the InversifyJS kernel. Here are my thoughts:

## The proposed solution doesn't feel right

About you proposed solution:

``` ts
masterKernel.load(subKernel);
```

This solution doesn't feel right for me. The parent (`masterKernel`) would be able to load all the bindings from the child (`subkernel`). 
However, we would have a few problems:
- We wouldn't be able to unload them.
- The `@inject` property decorator would not be able to access the `masterKernel`.

So I've been thinking about other solutions and the bad news is that all my options are quite big breaking changes.  This means that I will not be able to add this to the 2.0 release.

## Using global variables as a temporal fix?

At the moment your problem is that you have the following:
- Module A) Declares a singleton kernel instance and the @inject property decorator and it is the composition root
- Module B) Standalone but requires @inject property decorator

As you know this creates a circular dependency:

```
A --> B
B --> A
```

The solution with the current implementation would be to create an additional module so you will have:
- Module A) Declares a singleton kernel instance and the @inject property decorator as global variables
- Module B) Standalone but consumes the global variables declared by A
- Module C) It is the composition root and consumes B and consumes the global variables declared by A

```
B --> A
C --> B
C --> A
```

## Child kernels (2.1) will allow you to remove the globals in the future

After the 2.0 release. I will work on the [support for child kernels](https://github.com/inversify/InversifyJS/issues/199). The child kernel system is going to behave as a  [hierarchical dependency injection system](https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html). This means that the bindings of the parent kernel are only accessed when no bindings are found in the child kernel.

Once this feature is added you could declare a kernel in each module. Then, in your core module you could create the master parent and import each of the child kernels:

``` ts
subKernel.setParent(masterKernel);
```

Which is not far from:

``` ts
masterKernel.load(subKernel);
```

The main difference is that there is hierarchical structure but it should be able to fix your problem.

## Should we re-write the property inject feature in the future?

The current implementation:
- The property inject decorator calls the kernel under the hood.
- The property getter is replaced by the decorator when the class is DECLARED. 
- The property is then lazy initialized when it is accessed for the first time.

The new implementation:
- The property inject decorator will NOT call the kernel and will generate metadata instead.
- The property getter is replaced by the decorator when the class is RESOLVED.
- The property is then lazy initialized when it is accessed for the first time.

I see a few potential problems: 
- More complex resolution (especially when working with inheritance).
- Additional step when resolving a dependency (check for property metadata) may affect performance.
- Only classes that are resolved will get injected properties

```
@injectable()
class Ninja {
  @inject()
  public weapon: Weapon;
}

let ninja1 = kernel.get<Warrior>("Ninja");
ninja1.weapon.name === "Shuriken"; // true (weapon was injected)

let ninja2 = new Ninja();
ninja2.weapon.name === "Shuriken"; 
// false (weapon was NOI injected because ninja2 was not resolved)
```

This re-write is a breaking change and we are probably talking about InversifyJS 3.0.

**Comment by endel** [comment]
Hi @remojansen, thanks for your precise thoughts on this. We're building a IoC sort of framework over here and I'd be glad if I could help you out on property injection and child kernels implementation if you haven't started with it yet. Cheers!

**Comment by remojansen** [comment]
Hi @endel I'm still working on 2.0 but help would be much appreciated.

The child kernel feature requirements are very clear and has been documented at #307 PRs for this feature are welcome!

For the new implementation I would like to wait until we get more feedback about the potential problems:

> I see a few potential problems:
> - More complex resolution (especially when working with inheritance).
> - Additional step when resolving a dependency (check for property metadata) may affect performance.
> - Only classes that are resolved will get injected properties.

So please let me think a bit more about the new implementation. I will create an issue and let you know when it's ready :)

Thanks a lot for helping out!

**Comment by otbe** [comment]
@endel I dont know if I get you wrong, but property injection is already in inversify :)

@remojansen 
Dont worry about long comments/posts. Sometimes I do it myself :)

> Child kernels (2.1)

Your `child kernel / hierarchical dependency injection` proposal is exactly what I had in mind when asking this question on gitter :) Maybe my `load` function was a bit misleading, but thats exactly what I want :)

**Comment by remojansen** [comment]
I'm closing this as we now have: 

#307 to follow the implementation progress  of child kernel support
#310 to talk about property injection
