### ISSUE TITLE
Unclear error message on resolving named/tagged dependencies

### ISSUE THREAD

**Issue by lukas-zech-software** [inversify/InversifyJS#305]
When trying to resolve a dependency with `getTagged` or `getNamed` and either the tag or the name is wrong/misstyped the planner will throw an error stating _No bindings found for serviceIdentifier: xyz_ even though the serviceIdentifier is correct and only the tag/name was wrong

`kernel.getNamed('xyz',' wrongName')`
`kernel.getTagged('xyz',' wrongTag', true)`

> "No bindings found for serviceIdentifier: xyz"

It would be much more convenient if the error message would contain information about the used meta data  like names or tags if applicable
## Expected Behavior

When a dependency fails to resolve with names/tags, the error should provide information about the used meta data to indicate, that the lookup failed not only because of the provided serviceIdentifier

`kernel.getNamed('xyz',' wrongName')`

> "No bindings found for serviceIdentifier: 'xyz' and 'name' "
## Current Behavior

If a dependency is fails to resolve with a correct serviceIdentifier but a wrong tag/name, the error only states that the serviceIdentifier is wrong
## Possible Solution

If meta data is available in the failing request it should be appended to the error message to help locating the root of the problem
## Steps to Reproduce (for bugs)

``` typescript
let kernel = new Kernel();
kernel.bind<Weapon>("Weapon").to(Katana).whenTargetNamed("japonese");
kernel.bind<Weapon>("Weapon").to(Shuriken).whenTargetNamed("chinese");

let katana = kernel.getNamed<Weapon>("Weapon", "japochinese"); // typo in name

// currently throws "No bindings found for serviceIdentifier: Weapon"
// should throw "No bindings found for serviceIdentifier: 'Weapon' and name: 'japochinese' "
```

``` typescript
let kernel = new Kernel();
kernel.bind<Weapon>("Weapon").to(Katana).whenTargetTagged("faction", "samurai");
kernel.bind<Weapon>("Weapon").to(Shuriken).whenTargetTagged("faction", "ninja");

let katana = kernel.getTagged<Weapon>("Weapon", "faction", "ninjarai"); // typo in tag value

// currently throws "No bindings found for serviceIdentifier: Weapon"
// should throw "No bindings found for serviceIdentifier: 'Weapon' and tag: {key:'faction', value:'ninjarai'} "
```
## Context

We are registering some of our dependencies dynamically during runtime. When a dependency fails to resolve due to a wrong tag or name, debugging is a lot harder when you think its the serviceIdentifier thats wrong.

I also had the same issue with simple typos, where I triple checked the serviceIdentifier and did not look at the name as the error mislead me
## Your Environment
- Version used: 2.0.0-rc.1
- Environment name and version: NodeJS 5.7.0
- Operating System and version (desktop or mobile): OSX 10.11.6

If this issue is approved, I'll provide a merge request for it shortly

**Comment by lukas-zech-software** [comment]
To further improve the error message, the request could, in case of above error, lookup dependencies without the meta data to provide possible solutions:

``` typescript
No bindings found for serviceIdentifier: 'Weapon' and tag: {key:'faction', value:'ninjarai'} 
Possible bindings for serviceIdentifier: 'Weapon': [ {'tagged': {key:'faction', value:'ninja'}}, {'tagged': {key:'faction', value:'samurai'}} ]
```

Again, if approved, I"ll implement this and provide a pull request

**Comment by remojansen** [comment]
Hi @lukas-zech-software sounds like a good idea to me :smile: I will be happy to merge a PR!

**Comment by remojansen** [comment]
Hi @lukas-zech-software I would like to include this in the 2.0 release. Are you planing to send a PR please let me know and I will implement it if you don't have time. Thanks!

**Comment by robertmain** [comment]
I'm chipping in here to say that I'm getting this too, except it's complaining about my controllers. The error I'm getting says `No matching bindings found for serviceIdentifier: String`. It gets thrown when `Server.build()` is called.

**Comment by paul-marechal** [comment]
I had the same problem as @robertmain, and the cause was that I expected inversify to only use attribute injection, while in fact it also tried to do constructor injection. See the following:
```ts
class Example {

    @inject(Dependency)
    protected dep: Dependency;

    constructor(
        public defaultArg: string = 'defaultValue'
    ) {
        console.log(this.defaultArg);
    }

    @postConstruct()
    actualInitialization() {
        this.dep.use();
    }
}
```

In this case inversify tries to provide a dependency for the constructor argument `defaultArg`, even though we never decorated it to inject something.

The fix:
```ts
    constructor(
        @optional() public defaultArg: string = 'defaultValue'
    ) {
```

Even with `@optional()` I think inversify will try to provide a dependency for it, but if it fails it will not throw an error.
