### ISSUE TITLE
Upgrade examples

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#306]
I have migrated each example to its new repo now we need to get done the following:
# marionette
- [ ] Update dependencies inversify-marionette-example
- [ ] Add CI checks inversify-marionette-example
- [ ] Enable greenkeeper for inversify-marionette-example
# hapi
- [ ] Update dependencies inversify-hapi-example
- [ ] Use TS 2.0 & `@types`
- [ ] Add CI checks inversify-hapi-example
- [ ] Enable greenkeeper for inversify-hapi-example

I will work on this once I release the [devtools](https://github.com/inversify/inversify-devtools). If someone want to help PRs are more than welcome!

Context https://github.com/inversify/InversifyJS/issues/265#issuecomment-228744171

**Comment by lholznagel** [comment]
I can take a look at upgrading as soon as I am home from work.
CI is just enabling it in travis?

**Comment by remojansen** [comment]
Hi @lholznagel Thanks a lot for helping me out :clap: I will enable greenkeeper and travis for you this evening :smile:

**Comment by remojansen** [comment]
@lholznagel the marionette is very very old and may require to be rewrite... (it uses requirejs for exmaple) maybe start by with the hapi example and we can think if we really want to keep the marionette example alive...

The idea is that I wanted at least one example of a front-end application but maybe makes more sense to create a React + Mobx example and remove the marionette example.

**Comment by lholznagel** [comment]
You're welcome, I am glad that I can help you :).
Will take a look at the hapi example.

**Comment by remojansen** [comment]
I'm closing this issue. We can use https://github.com/inversify/InversifyJS/issues/435 instead
