### ISSUE TITLE
Ability to create child kernels

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#307]
Based on the proposal #199.

We need to implement support for child kernels.

In order to create a child kernel we need to add a new private property `_parentkernel` to the Kenrel class.

This property is initialized by public setter:

``` ts
childKernel.setParentkernel(parentKernel);
```

We use a setter instead of the constructor because sometimes we will declare a child kernel in a module and this module is unaware of parent kernels. Then another module may import the child kernel and connect it to a parent. This allow us to develop an application with multiple modules independent of the core Kernel.

The planing phase needs to be refactor so it behaves like a [hierarchical dependency injection system](https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html). This means that the bindings of the parent kernel are only accessed when no bindings are found in the child kernel.

**Comment by remojansen** [comment]
Hi @endel I have invited you to the organization I will assign this issue to you once you join it :smile:

**Comment by endel** [comment]
Hi @remojansen, great! Thanks for the invitation 😄

**Comment by remojansen** [comment]
Done by #318
