### ISSUE TITLE
README.md: Ninja should implement Warrior

### ISSUE THREAD

**Issue by Robotregent** [inversify/InversifyJS#308]
Just a minor confusion in README.md
I think the Ninja should implement Warrior.

**Comment by remojansen** [comment]
Hi thanks for reporting, the words warrior and ninja are used in many places can you please let me know the section in which you found the issue? Thank!

**Comment by Robotregent** [comment]
Hi, I added a PR to the ticket. Can you see it? I'm not sure if i have done it right :)

**Comment by remojansen** [comment]
Sorry I just saw it. You send the PR to your fork `Robotregent/InversifyJS` you need to send the PR to the inversify repo `inversify/InversifyJS`.

**Comment by remojansen** [comment]
I have created and merged the PR #309 thanks a lot for fixing the typo!

**Comment by Robotregent** [comment]
Thanks for helping me with this PR stuff :)
