### ISSUE TITLE
Rewrite property inject so it becomes not aware of kernel instances

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#310]
The current implementation:
- The property inject decorator calls the kernel under the hood.
- The property getter is replaced by the decorator when the class is DECLARED. 
- The property is then lazy initialized when it is accessed for the first time.

The new implementation:
- The property inject decorator will NOT call the kernel and will generate metadata instead.
- The property getter is NOT replaced.
- The property is then initialized immediately after the instance is created.

I see a few potential problems: 
- More complex resolution (especially when working with inheritance).
- Additional step when resolving a dependency (check for property metadata) may affect performance.
- Only classes that are resolved will get injected properties

```
@injectable()
class Ninja {
  @inject()
  public weapon: Weapon;
}

let ninja1 = kernel.get<Warrior>("Ninja");
ninja1.weapon.name === "Shuriken"; // true (weapon was injected)

let ninja2 = new Ninja();
ninja2.weapon.name === "Shuriken"; 
// false (weapon was NOI injected because ninja2 was not resolved)
```

Motivation #303

**Comment by remojansen** [comment]
> Only classes that are resolved will get injected properties

This is a major problem in React! React is a huge sector of potential users. The new implementation feels right but I don't feel like killing compatibility with react is a good idea. 

The kernel child support will be an alternative solution (see "Child kernels (2.1) will allow you to remove the globals in the future" [here](https://github.com/inversify/InversifyJS/issues/303#issuecomment-235571277)) and will allow us to keep supporting react.

**Comment by remojansen** [comment]
I think I have a solution. The current implementation of property injection should be moved to a new npm module **"inversify-inject-decorators"**:

## inversify-inject-decorators

``` ts
import makePropertyInjectDecorator from "./makePropertyInjectDecorator";
import makePropertyInjectNamedDecoratorfrom "./makePropertyInjectNamedDecorator";
import makePropertyInjectTaggedDecoratorfrom "./makePropertyInjectTaggedDecorator";
import makePropertyMultiInjectDecoratorfrom "./makePropertyMultiInjectDecorator";


function getDecorators() {

    let lazyInject = makePropertyInjectDecorator(Kernel);
    let lazyInjectNamed = makePropertyInjectNamedDecorator(Kernel);
    let lazyInjectTagged = makePropertyInjectTaggedDecorator(Kernel);
    let lazyMultiInject = makePropertyMultiInjectDecorator(Kernel);

    return {
        lazyInject ,
       lazyInjectNamed,
       lazyInjectNamed,
       lazyMultiInject
    };

}

export default getDecorators;
```

``` ts
import { getDecorators } from "inversify-inject-decorators";
import { Kernel } from "inversify";

let kernel = new Kernel();

let {
   lazyInject ,
   lazyInjectNamed,
   lazyInjectNamed,
   lazyMultiInject
} = getDecorators(kernel );

```

This implementation is useful for React and maybe other projects but I believe it should not be part of the core module.

Then we can rewrite the current implementation of property injection. With the new implementation, only classes that are resolved will get injected properties. This means that it won't work with react but that will not be a problem because inversify-inject-decorators will be compatible with React.

**Comment by remojansen** [comment]
The module inversify-inject-decorators has been released and the old implementation of the property injection has been removed by #337.

**Comment by remojansen** [comment]
After #337 this is no longer a breaking change added minor label.

**Comment by endel** [comment]
Hey @remojansen, I see that you made some progress here, that's great! May I help you with this?

**Comment by remojansen** [comment]
Hi @endel thanks for trying to help me. I don't think it will be easy to share work because it affects a lot of parts of the library and is not fully clear to me yet what needs to be done in detail. I know we are going to need a lot of unit tests but we are note ready for that either 😢 I will let you once I get to a more mature implementation. Thanks a lot for trying to help :)

**Comment by remojansen** [comment]
Implemented by #350

**Comment by endel** [comment]
Awesome @remojansen! Thanks for your work here. 

Are the property injections happening during instantiation or they are they lazy evaluated? 

Cheers!

**Comment by endel** [comment]
That's really great, can finally inject properties across inherited classes, without having to repeat the constructor signature <3 <3 <3 <3

**Comment by remojansen** [comment]
Hi @endel, Thanks! at the end it was easier than expected. Properties are injected [just after an instance iscreated](https://github.com/inversify/InversifyJS/blob/master/src/resolution/resolver.ts#L77-L78) and are NOT lazy evaluated.  Remember that if you want lazy evaluated you can use [inversify-inject-decorators](https://github.com/inversify/inversify-inject-decorators).
