### ISSUE TITLE
Publish version 2.0.0-rc.4

### ISSUE THREAD

**Issue by endel** [inversify/InversifyJS#321]
Hey @remojansen, thanks for your work during the weekend!

Is it possible to publish the last version to npm? The latest there is `2.0.0-rc.1`. 

Cheers, have a great week :)

**Comment by remojansen** [comment]
HI @endel thanks! I'm working on It I want to get auto-deployments to npm on build success + tag but I'm having some problems. You should see the new release at some point over the next couple of hours 😄

**Comment by remojansen** [comment]
2.0.0-rc.5 should be released now :)

**Comment by endel** [comment]
Great, thanks!
