### ISSUE TITLE
inversify-express-utils: support another web framework ?

### ISSUE THREAD

**Issue by rundef** [inversify/InversifyJS#322]
Hi,

I really like the idea behind **inversify-express-utils**, but I needed the same thing for a [restify](https://www.npmjs.com/package/restify) app instead of express - so I modified my fork here: https://github.com/inversify/inversify-express-utils/compare/master...rundef:master

Do you think I should create a PR with a more generic solution - so that **inversify-express-utils** could support multiple web app frameworks ? Or perhaps it would be better to create a new repo ? What do you think ?

**Comment by lholznagel** [comment]
Just took a quick look. Is it really mostly just renaming?
When yes I think a generic solution would be better.

**Comment by rundef** [comment]
Yes, it's mostly just renaming (restify is based on express)
Cool, then I'll send a PR later !
Thanks

**Comment by lholznagel** [comment]
Wait for a response from @remojansen. I just gave my two cents :D

**Comment by remojansen** [comment]
At the moment express-utils is very basic but maybe if it evolves we will have problems to also support restify. Also the fact that the npm module is called `express` utils makes me think that supporting also restify may be confusing. A lot of restify users could ignore this just because the name. I'm coping @codyjs because he is the author of the express-utils let's see what he thinks but maybe a new repo `inversify-restify-utils` would be better?

**Comment by codyjs** [comment]
I agree with @remojansen , it could be confusing since the name of the module is **express**. I think a new repo would be better

**Comment by lholznagel** [comment]
good point with the npm module name. Would also say a new repo

**Comment by remojansen** [comment]
:+1:  new repo and new npm module

**Comment by remojansen** [comment]
@rundef I can create a repo under the @inversify organization if you want? I will be able to help you with the DevOps stuff (Travis, npm releases, ...) and we will be able to monitor all the projects in [one place](https://travis-ci.org/inversify).

**Comment by rundef** [comment]
Yes, sound good to me

**Comment by remojansen** [comment]
Great, the repo is available at https://github.com/inversify/inversify-restify-utils I'm closing this issue but you can comment if you have any questions also you can find us on the gitter chat :)

**Comment by remojansen** [comment]
Hi @rundef thanks a lot for your PR. I have configured the travis CI build and done the first npm release https://www.npmjs.com/package/inversify-restify-utils please let me know you experience any problems with it 😄
