### ISSUE TITLE
Broken build: Accessors are only available when targeting ECMAScript 5 and higher

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#326]
PR [#325](https://github.com/inversify/InversifyJS/pull/325) breaks the build with the following [error](https://travis-ci.org/inversify/InversifyJS/jobs/149387354#L1225-L1229):

> TypeScript error: /home/travis/build/inversify/InversifyJS/src/kernel/kernel.ts(171,16): Error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

Line [171](https://github.com/inversify/InversifyJS/blob/master/src/kernel/kernel.ts#L171) in `/src/kernel/kernel.ts` delcares the following `set`:

``` ts
public set parent (kernel: interfaces.Kernel) {
    this._parentKernel = kernel;
}
```

I'm going to replace the `set` with:

``` ts
public setParent (kernel: interfaces.Kernel) {
    this._parentKernel = kernel;
}
```

This is a breaking change of the child kernel feature that was added in the latest release.
### Update

As comented by @endel no breaking change is required 🎉

**Comment by endel** [comment]
Hey @remojansen, that's odd. Do you have any idea why `tsify` is changing the target to anything below ES5? IMHO nobody on earth would have a reason to use anything below that, isn't it? Cheers!

**Comment by remojansen** [comment]
Hi @endel will try my best to not introduce the breaking change. I'm trying to find out why it is using the wrong target. Maybe the latest tsify release is broken...

**Comment by endel** [comment]
It was actually a bug on on that version: https://github.com/TypeStrong/tsify/commit/90b86265a38f0cca8d950798162e6b5cfbc2825b

**Comment by remojansen** [comment]
Perfect 🎉  Will upgrade to 1.0.3 them :)
