### ISSUE TITLE
Investigate perperty injection failing when a class used as identifier

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#334]
## Expected Behavior

No exceptions should be thrown
## Current Behavior

```
Error: NULL argument at Lookup.hasKey
```
## Steps to Reproduce (for bugs)

```
import { Kernel } from "inversify";

const inject = makePropertyInjectDecorator(kernel);

@provideSingleton(Store1)
class Store1 { }

@provideSingleton(Store2)
class Store2 {
  @inject(Store1)
  store1: Store1;
}
```

**Comment by donaldpipowitch** [comment]
This problem occurred, because `Store1` was exported as `undefined`. This was a problem with an older version of `typescript@next`. The current version `2.1.0-dev.20160807` works.

**Comment by remojansen** [comment]
Thanks for letting me know. I will close this issue now.
