### ISSUE TITLE
Investigate required inject() when identifier is a class

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#340]
## Expected Behavior

No inject() should be required 
## Steps to Reproduce (for bugs)

``` ts
    it("injects a class with no interface", () => {
        @injectable()
        class Child {
            public sayHello(): string {
                return "hello";
            }
        }

        @injectable()
        class Parent {
            constructor(private child: Child) {}

            public sayHello(): string {
                return child.sayHello();
            }
        }

        let kernel = new Kernel();
        kernel.bind<Child>(Child).toSelf();
        kernel.bind<Parent>(Parent).toSelf();

        let parent = kernel.get<Parent>(Parent);
        expect(parent.sayHello()).equals("hello");
    });
```
## Context

Reported by @johnfields
## Your Environment

TS 1.8.10

**Comment by johnfields** [comment]
fyi for anyone working on this return child.sayHello() should be this.child.sayHello()

**Comment by remojansen** [comment]
I tried to the code above in our unit tests and it works fine. The @inject decorator is not required when you use classes. The annotation is not required because the typescript compiler generates the metadata for us. However, for that to happen it is required to do two things:
- import reflect-metadata
- Set `emitDecoratorMetadata` to `true` in [tsconfig.json](https://github.com/inversify/InversifyJS/blob/master/tsconfig.json#L8-L9).

I will add a note about this in the docs. Please let me know if this issue can be closed.

**Comment by remojansen** [comment]
Hi @johnfields were you able to solve the issue? Can this issue be closed? Thanks!

**Comment by johnfields** [comment]
@remojansen yes it can be closed.  Thanks for investigating!

**Comment by remojansen** [comment]
No problem :smile:
