### ISSUE TITLE
Implementing getAllTagged and getAllNamed for tagged multi-injection

### ISSUE THREAD

**Issue by Offirmo** [inversify/InversifyJS#348]
Following this discussion: https://github.com/inversify/InversifyJS/issues/345#issuecomment-242015984

``` js
interface IIntl {
    [k: string]: string
}

// module 1
kernel
    .bind<IIntl>('intl')
    .toConstantValue({
        hello: 'bonjour'
    })
    .whenTargetTagged('lang', 'fr')

// module 2
kernel
    .bind<IIntl>('intl')
    .toConstantValue({
        goodbye: 'au revoir'
    })
    .whenTargetTagged('lang', 'fr')

// get all
kernel.getAllTagged<IIntl>('intl', 'lang', 'fr') // IIntl[]
```
## Expected Behavior

getAllTagged return an array of corresponding services, like `getAll`
## Current Behavior

n/a
## Context

trying to use inversify for declaring intl fragments, each app module would be able to declare its own intl fragments

**Comment by remojansen** [comment]
Hi @Offirmo, this has been implemented by https://github.com/inversify/InversifyJS/issues/348 and is now available in **2.0.0-rc.11**

**Comment by remojansen** [comment]
Docs available [here](https://github.com/inversify/InversifyJS/blob/master/wiki/get_all_named_tagged.md)

**Comment by Offirmo** [comment]
OMG. Testing it. Are typings up to date, too ?

**Comment by Offirmo** [comment]
`index.ts (70,37): Property 'getAllTagged' does not exist on type 'Kernel'. (2339)`

**Comment by Offirmo** [comment]
implemented by https://github.com/inversify/InversifyJS/pull/349

**Comment by remojansen** [comment]
Typings should be available in inversify-dts@2.1.0

**Comment by Offirmo** [comment]
```
TSError: ⨯ Unable to compile TypeScript
index.ts (9,36): Cannot find module 'inversify'. (2307)
```

I've broken my setup and can't even find why... :cry:

**Comment by remojansen** [comment]
I just updated the examples repository for node and everything seems to be working fine (https://github.com/inversify/inversify-express-example/pull/44) We can try to help if you give us more details.

**Comment by Offirmo** [comment]
Working. For some unknown reason, latest typescript@next went wild and I had to give it previously unneeded options: files: [ (reference paths) ]

reference path in code are not working anymore. :unamused:
