### ISSUE TITLE
Allow toDynamicValue to access the current context

### ISSUE THREAD

**Issue by Offirmo** [inversify/InversifyJS#351]
## Expected Behavior

Still using Inversify. Works great so far, but I feel something is missing in the range of possible services.

I'm trying to do functional programming, using pure functions and not using classes (no state + considered harmful in javascript)

However, my modules still need injected dependencies.

With inversify, we can declare a range of ressources, from the simplest to the more complex
- constant value
- dynamic value
- class
- factory
## Current Behavior

I'm forced to use a factory:

``` js
bind<interfaces.Factory<WeaponComponentModel>>(RSRCIDS.factory)
    .toFactory<WeaponComponentModel>((context: interfaces.Context) => () => module_factory({
        schema: context.kernel.get<IJsonSchema>(RSRCIDS.schema)
    }))

// usage:
const module = context.kernel.get<() => WeaponComponentModel>(RSRCIDS.factory)()
```
## Possible Solution

A simpler "module" service, half-way between dynamic values and factories, but not a class:

``` js
bind<interfaces.Module<WeaponComponentModel>>(RSRCIDS.module)
    .toModule<WeaponComponentModel>((context: interfaces.Context) => module_factory({
        schema: context.kernel.get<IJsonSchema>(RSRCIDS.schema)
    }))

// usage:
const module = context.kernel.get<WeaponComponentModel>(RSRCIDS.module)
```

I'm still using a factory, but calling code doesn't have to be aware of it.
## Steps to Reproduce (for bugs)

n/a
## Context

trying to do functional programming, using pure functions and not using classes (no state + considered harmful in javascript)

**Comment by Offirmo** [comment]
Note: I'm not sure of the "module" terminology. I made it up, but a more experienced programmer may use a more fitting name.

**Comment by remojansen** [comment]
I think we can achieve this in an easier way:

``` ts
kernel.bind<WeaponComponentModel>(RSRCIDS.module).toDynamicValue((context: interfaces.Context) => {
    return module_factory({
        schema: context.kernel.get<IJsonSchema>(RSRCIDS.schema)
    });
});

// usage:
const module = context.kernel.get<WeaponComponentModel>(RSRCIDS.module);
```

Notice how we used:

``` ts
.toDynamicValue((context: interfaces.Context) => { /**/ });
```

Instead of:

``` ts
.toDynamicValue(() => { /**/ });
```

This is not possible at the moment but it is easy to implement 😄  I will try to implement it as soon as I can but might take me over a week because I have too much work at the moment with other stuff...

Also check the recipe for [Injecting dependencies into a function](https://github.com/inversify/InversifyJS/blob/master/wiki/recipes.md#injecting-dependencies-into-a-function).

**Comment by remojansen** [comment]
This has been implemented by #352 and will be released soon

**Comment by Offirmo** [comment]
This is perfect ! You are working so fast !

**Comment by remojansen** [comment]
Thanks! I will try to do another release tonight I'm closing this issue now :smile:
