### ISSUE TITLE
bluebird docs update

### ISSUE THREAD

**Issue by nbalu** [inversify/InversifyJS#359]
sorry for the quick ticket opening and I know I should make the PR for that

TS with ES5 compatibility should work as docs describes -> except bluebird 3+ is the current ver.
## Expected Behaviour

build should be fine
## Current Behavior

3+ is installed - and error as usual:
TypeScript error: node_modules/inversify-dts/inversify/inversify.d.ts(108,13): Error TS2304: Cannot find name 'Promise'.
## Possible Solution

fix the docs that typings install dt~bluebird#2.0.0+20160701023356 --global should be used - as you are building against this

**Comment by remojansen** [comment]
Hi, Thanks for using InversifyJS and reporting this issue. I'm going to fix this issue as part of #330 I will close this issue now but you can follow the progress at #330.

I'm working on a PR #360 so the fix should be available very soon.
