### ISSUE TITLE
Allow abstract classes to be used as identifiers

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#363]
Extending `ServiceIdentifier<T>` to accept Abstract classes.

Constructor of abstract class can be used as service identifier and can also be binded to a concret implementation.

```
// Declare interface as below
@injectable()
abstract class MyServiceInterface { void f(); }

class MyService extends MyServiceInterface { /*...*/ }

// Inject as below
class MyBusiness {
  constructor(@inject(MyServiceInterface) x: MyServiceInterface) {
    /*...*/
  }
}
```

And such way should be more easier than injecting an interface, which need to define a symbol for it.

This was reported by https://github.com/inversify/inversify-dts/pull/19

**Comment by remojansen** [comment]
Done by 38b9a8a888ef4430bc60cda900abe118d225c35d

**Comment by mpontus** [comment]
Does this eliminate the need to maintain `TYPES` object if every interface was replaced with an abstract class?  Are there any downsides to using this approach?

**Comment by Exifers** [comment]
I was looking for an IOC container for Typescript that allows usage of abstract classes like this.

Unless I haven't seen it it's not specified in the [npm doc](https://www.npmjs.com/package/inversify) that abstract classes can be used as identifiers.
Maybe this could be worth mentioning it, as it simplifies a lot compared to maintaining `TYPES`.
