### ISSUE TITLE
Typings of inversify-logger-middleware linked incorrectly

### ISSUE THREAD

**Issue by andreasrueedlinger** [inversify/InversifyJS#368]
Typings of inversify-logger-middleware linked incorrectly
## Expected Behavior

Installing the npm package `inversify-logger-middleware` should also include the typings definitions automatically. However, VS Code for example does not find the module.
## Possible Solution

I think it is because package.json of the module references to the wrong `d.ts`-file:
`"typings": "./dts/inversify.d.ts"` instead of `"typings": "./dts/index.d.ts"`

**Comment by lholznagel** [comment]
Ups, my mistake. Sorry for that.
Thanks for reporting.

Can confirm that an index.d.ts is created and not an inversify.d.ts. When you change it locally, does it work then?

**Comment by andreasrueedlinger** [comment]
Yes, this was my workaround locally :-)

**Comment by remojansen** [comment]
Hi guys I just released inversify-logger-middleware@2.0.1 it should fix your issue

**Comment by lholznagel** [comment]
Can confirm this bug in another project also. Will create a PR to fix both projects :)

**Comment by remojansen** [comment]
I have also released inversify-restify-utils@2.0.1 I think that's all so I'm closing this issue.

**Comment by lholznagel** [comment]
@remojansen in [inversify-express-utils](https://github.com/inversify/inversify-express-utils/blob/master/package.json#L7) is the same problem.

**Comment by remojansen** [comment]
@lholznagel thanks for letting me know! I'm at work now. I have done the changes but I won't be able to release it until this evening :cry:

**Comment by remojansen** [comment]
I just released inversify-express-utils@2.0.1

**Comment by lufzle** [comment]
I'm getting a `Cannot find name 'Controller'.` when doing this:

``` typescript
import { inject, injectable } from 'inversify'
import { Controller, Get } from 'inversify-express-utils'

@Controller('/foo')
@injectable()
export class FooController implements Controller  {
}
```

My `tsconfig.json`:

``` json
  "compilerOptions": {
    "target": "es2015",
    "lib": ["es6"],
    "types": ["reflect-metadata"],
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true
  },
```

Now I might be mistaken, but I'm wondering how does the following code in `decorators.d.ts` 

``` typescript
import interfaces from "./interfaces";
export declare function Controller(path: string, ...middleware: express.RequestHandler[]): (target: any) => void;
export declare function All(path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
export declare function Get(path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
export declare function Post(path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
export declare function Put(path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
export declare function Patch(path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
export declare function Head(path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
export declare function Delete(path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
export declare function Method(method: string, path: string, ...middleware: express.RequestHandler[]): interfaces.HandlerDecorator;
```

export the `Controller` interface. It's importing the interfaces for using them when exporting the decorators, but is not exporting the interface itself. Right?

**Comment by lholznagel** [comment]
Hey, I think it matches this issue #371

**Comment by lufzle** [comment]
Thanks, I'll continue on that thread!
