### ISSUE TITLE
Bloated npm distribution

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#37]
At the moment, too much is being distributed with the npm distribution.

Included in the distribution is the TypeScript source, the Karma configuration, and the test files.

The package size could be slimmed down considerably by only distributing the compiled JS and the package.json.

**Comment by jamesadarich** [comment]
Sounds fair enough to me - just needs an npmignore file to be added :+1: I'll have an investigate tonight if I get a chance

**Comment by remojansen** [comment]
@Jameskmonger @jamesrichford It sounds good to me too, feel free to send a pull request.

**Comment by Jameskmonger** [comment]
I'm working on this now, @remojansen. I will most likely also remove the /dist/ directory from the repo because it doesn't really need to be distributed with the repo if it's published on npm.
