### ISSUE TITLE
Improve test coverage of some projects

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#370]
We need to push all the way up to 100% test coverage the following projects:

- [x] [**100%**  inversify-restify-utils](https://codeclimate.com/github/inversify/inversify-restify-utils/coverage)
- [x] [**100%**  inversify-express-utils](https://codeclimate.com/github/inversify/inversify-express-utils/coverage) done by inversify/inversify-express-utils/pull/26
- [x] [**95.66%** inversify-logger-middleware](https://codeclimate.com/github/inversify/inversify-logger-middleware/coverage)

**Comment by rsaz** [comment]
`inversify-restify-utils` code coverage 100%

![image](https://github.com/user-attachments/assets/fc87d2d7-2a37-4297-ae28-a58c5b840b2d)

PR: https://github.com/inversify/inversify-restify-utils/commit/44151753409030327c5d066008195c4c8b4b4aed

**Comment by rsaz** [comment]
`inversify-logger-middleware` code coverage 100%
![image](https://github.com/user-attachments/assets/eb11d58a-40e6-497d-bad4-ce32d1e4a8cf)
