### ISSUE TITLE
inversify-vanillajs-helpers

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#375]
This is a new project that aims to help devs using VanillaJS.

You can learn more at https://github.com/inversify/inversify-vanillajs-helpers/blob/master/README.md

**Comment by lholznagel** [comment]
Is this also a small libary or only a collection of code snippets?

**Comment by remojansen** [comment]
It will be a very small library that you will be able to install using npm.

**Comment by remojansen** [comment]
@timdp I have done an initial release of the helpers you can find out more at https://github.com/inversify/inversify-vanillajs-helpers please not that this new library is not production ready yet (I have to write a lot of unit tests...).

**Comment by timdp** [comment]
Thanks. I actually ended up writing a simple decorator (called wire) that basically does the same as helpers.annotate. Could be one of the helpers maybe?

**Comment by remojansen** [comment]
No problem, sure feel free to send a PR or share the code here.

**Comment by timdp** [comment]
It's very similar to yours:

``` js
import {decorate, injectable, inject} from 'inversify'

export default (dependencies = []) => (constructor) => {
  decorate(injectable(), constructor)
  dependencies.forEach((dep, index) => {
    decorate(inject(dep), constructor, index)
  })
}
```

which allows you to write things like

``` js
import TYPES from './ioc/types'
import wire from './ioc/wire'

@wire()
class Foo {}

@wire()
class Bar {}

@wire([TYPES.Foo, TYPES.Bar])
class Baz {
  constructor (foo, bar) {
    this._foo = foo
    this._bar = bar
  }
}
```

**Comment by remojansen** [comment]
This works fine with babel right?

**Comment by timdp** [comment]
Yep, with `transform-decorators-legacy` at least.

**Comment by remojansen** [comment]
Hi @timdp I've been doing some work on this please check the latest release https://github.com/inversify/inversify-vanillajs-helpers#registration-helper I would like to hear your thoughts. Thanks!

**Comment by remojansen** [comment]
I think i'm only [a few unit tests away](https://github.com/inversify/inversify-vanillajs-helpers/blob/master/test/constraints.test.ts#L137-L144) from closing this issue.

**Comment by remojansen** [comment]
I'm closing this issue. I have released inversify-vanillajs-helpers 1.0.0 with 100% test coverage. More info at https://www.npmjs.com/package/inversify-vanillajs-helpers

**Comment by timdp** [comment]
Good job! `register` looks like a drop-in replacement for the `wire` decorator that I wrote and I'm sure the other ones will be useful to us in the long run as well. :+1:

**Comment by remojansen** [comment]
Thanks!
