### ISSUE TITLE
Typings not referenced correctly.

### ISSUE THREAD

**Issue by jt-helsinki** [inversify/InversifyJS#376]
Hi, 

In the **[inversify-express-utils](https://github.com/inversify/inversify-express-utils)** project the generated typescript declarations make reference to:

`/// <reference types="express" />`

Is this able to be removed as part of the build? It means that the only way to use the library is by importing the `@types/express` which won't work with all configurations/packages/libraries. 

Cheers

JT
## Expected Behavior

That it works...
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:
# Stack trace

**Comment by remojansen** [comment]
Can you please let us know more about your configuration or the packages that you are having issues with? The "@types/express" is the new official way to use type definitions. All projects will move in that direction. Also as we have documented in the installation guide our library requires typescript 2.0.

**Comment by jt-helsinki** [comment]
OK, I upgraded to the new way and it all worked. Fantastic! Thankyou! 👍  

Basically, I had a mix of typings and @type definitions. It got the point where there were so many conflicts that it just became unmanageable. That's seems to be pretty much it. 

Thanks again

JT

**Comment by remojansen** [comment]
No problem 😄
