### ISSUE TITLE
Cannot find module 'inversify'

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#38]
I have installed Inversify version 1.2.0 from NPM and have saved it to my `dependencies` in package.json, and I have installed the typings with TSD also.

When I import `Inject` from the `inversify` module, I get an error `Cannot find module 'inversify'`.

```
/// <reference path="../typings/inversify/inversify.d.ts" />

import { Inject } from 'inversify';
```

The `///` reference is pointing to the correct typings file.

**Comment by jamesadarich** [comment]
This is probably linked to #35 at the moment 1.2.0 is a broken build - a temporary fix is noted in my comment on #32 (which are the typings changes found in #34) if you want to use 1.2.0 whilst this issue is being resolved?

**Comment by remojansen** [comment]
@Jameskmonger sorry for the recent problems with type definitions I have some times this weekend so I will try my best to get it fixed by monday...

**Comment by remojansen** [comment]
I'm going to close this issue to ensure that we only have one unique issue to refer to this problem. You can follow the updates at #46
