### ISSUE TITLE
Unable to specify Restify ServerOptions 

### ISSUE THREAD

**Issue by markterm** [inversify/InversifyJS#383]
## Expected Behavior

Should be able to specify custom ServerOptions for Restify (eg custom formatters, logger) if using the 'inversify-restify-utils'

## Current Behavior

There is no way to provide these parameters

## Possible Solution

I'm submitting a candidate PR.

**Comment by remojansen** [comment]
Thanks for adding this :+1:  I'm just waiting for a second code review to merge your PR.

**Comment by remojansen** [comment]
Thanks a lot for your contribution. I just released inversify-restify-utils@2.1.2 so I'm closing this issue 👍
