### ISSUE TITLE
getFunctionName throws, regexp returns null

### ISSUE THREAD

**Issue by stjepangolemac** [inversify/InversifyJS#385]
Function getFunctionName throws when its called by baseClassDependencyCount which passes following function.

``` javascript
function (options) {
  events.EventEmitter.call(this);
  this.configure(options);
}
```
## Expected Behavior

I don't know what should happen when it receives function with no name because I don't know what is that function there for.
## Current Behavior

getFunctionName receives function with no name and throws. Here is the output.
return v.name ? v.name : v.toString().match(/^function\s*([^\s(]+)/)[1];
TypeError: Cannot read property '1' of null
## Possible Solution

I don't know if my implementation is causing this but if it's not, function should check does the name ([1] in the array) exist after the regexp is done and continue accordingly.
## Context

I'm trying to resolve my Logger class that depends on Settings class.

Logger

``` typescript
import { injectable, inject } from "inversify";
import "reflect-metadata";
import * as INTERFACES from "../interfaces";
import * as winston from "winston";

/**
 * Asynchronous server logger
 */
@injectable()
export default class Logger extends winston.Logger implements INTERFACES.ILogger {
  public settings: INTERFACES.ISettings;

  constructor(
    @inject("Settings") settings: INTERFACES.ISettings
  ) {
      super();
      this.settings = settings;
      this.setLogger();
  }

  /**
   * Sets logging outputs based on settings
   */
  private setLogger() {
    if (this.settings.logConsole) {
      this.add(winston.transports.Console,
        {
          level: this.settings.logConsoleLvl,
        }
      );
    }

    if (this.settings.logFile) {
      this.add(winston.transports.File,
        {
          filename: this.settings.logFilename,
          level: this.settings.logFileLvl,
        }
      );
    }
  }
}
```

Settings

``` typescript
import { injectable } from "inversify";
import "reflect-metadata";
import * as INTERFACES from "../interfaces";

/**
 * Settings for server
 */
@injectable()
export default class Settings implements INTERFACES.ISettings {
  public port: number;
  public logConsole: boolean;
  public logConsoleLvl: string;
  public logFile: boolean;
  public logFileLvl: string;
  public logFilename: string;
  public dbUrl: string;
  public dbUser: string;
  public dbPass: string;

  constructor() {
    this.setup(process.env.CONFIG);
  }

  /**
   * Reads the settings from configuration variable
   */
  private setup = (config: string) => {
    let configuration: any;
    try {
      configuration = require("../../configuration/" + config + ".js");
    } catch (error) {
      console.log("Settings cannot find", config, "configuration file");
      throw error;
    }

    this.port = configuration.port;
    this.logConsole = configuration.logconsole;
    this.logConsoleLvl = configuration.logconsolelvl;
    this.logFile = configuration.logfile;
    this.logFileLvl = configuration.logfilelvl;
    this.logFilename = configuration.logfilename;
    this.dbUrl = configuration.dburl;
    this.dbUser = configuration.dbuser;
    this.dbPass = configuration.dbpass;
  }
}
```

Kernel

``` typescript
import Settings from "./classes/settings";
import Logger from "./classes/logger";

import { Kernel } from "inversify";

let kernel = new Kernel();
kernel.bind<INTERFACES.ISettings>("Settings").to(Settings);
kernel.bind<INTERFACES.ILogger>("Logger").to(Logger);

kernel.get<INTERFACES.ILogger>("Logger"); //  <= breaks here
export default kernel;
```
## Your Environment
- Inversify version used:2.0.0
- Environment name and version (tsc 2.0.3, node.js 6.6.0):
- Operating System and version (desktop or mobile): Ubuntu 16.04
# Stack trace

return v.name ? v.name : v.toString().match(/^function\s*([^\s(]+)/)[1];
                                                                        ^

TypeError: Cannot read property '1' of null
    at Object.getFunctionName (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/utils/utils.js:5:70)
    at Planner._getTargets (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/planning/planner.js:132:39)
    at Planner._baseClassDepencencyCount (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/planning/planner.js:195:32)
    at Planner._getDependencies (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/planning/planner.js:184:45)
    at Planner.createPlan (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/planning/planner.js:23:37)
    at Kernel._createContext (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/kernel/kernel.js:220:23)
    at /home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/kernel/kernel.js:214:26
    at Array.map (native)
    at Kernel._plan (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/kernel/kernel.js:213:33)
    at Kernel._planAndResolve (/home/stjepan/Development/houseremote2.1/node_modules/inversify/lib/kernel/kernel.js:173:29)

**Comment by remojansen** [comment]
Hi, thanks a lot for reporting this issue. I'm about to release `inversify@2.0.1` which contains a fix for this issue. 

However, `getFunctionName` is only called when there is an issue (e.g. a missing annotation). At the moment you are not able to see the error message because it throws but after upgrading to 2.0.1 you will get some error. The error description should help you but feel free to ask any questions if you need additional help.

**Comment by remojansen** [comment]
I just released inversify@2.0.1 please let me know if it solves your issue 😄

**Comment by stjepangolemac** [comment]
It solves that error but now I have another one (caused by my implementation). My logger class extends winston logger which doesn't have injectable decorator. How am I supposed to fix this?

Here is the error.

```
Error: Missing required @injectable annotation in: Anonymous function: function (options) {
  events.EventEmitter.call(this);
  this.configure(options);
}
```

And it seems to point to this function in the winston logger [https://github.com/winstonjs/winston/blob/master/lib/winston/logger.js](LINK) line 25

``` javascript
var Logger = exports.Logger = function (options) {
  events.EventEmitter.call(this);
  this.configure(options);
};
```

**Comment by remojansen** [comment]
Hi @stjepangolemac we have a small guide about this issue in our wiki https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#what-can-i-do-when-my-base-class-is-provided-by-a-third-party-module hope it solves your issue

**Comment by stjepangolemac** [comment]
Yes, that helped me a lot. You are very responsive and helpful, keep up the good work!
