### ISSUE TITLE
Discussion: Use inversify middleware in express utils to allow request-based constraints

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#388]
Hi @codyjs, one of our users has the following use case.

He needs to inject a different instance based on a request header in express:

> if req.headers.A => UserController > UserService > Db_A_Instance
> if req.headers.B => UserController > UserService > Db_B_Instance

I was thinking that we need request scope support for this but actually request scope will not work either. Because with request scope you can create a binding that lives as a singleton within the scope of a request but we cannot declare constraints based on the context.

So I'm thinking that we can try to declare a inversify middleware (not a express middleware) in the `inversify-express-utils` project that will add a property named `locals` to the `Context`:

``` ts
interface ExpressIoCContext extends interfaces.Context {
    locals: {
        request: Express.Request
    }
}

function middleware(planAndResolve: PlanAndResolve<any>): PlanAndResolve<any> {
    return (args: PlanAndResolveArgs) => {
        let nextContextInterceptor = args.contextInterceptor;
        args.contextInterceptor = (context: interfaces.Context) => {
            let expressContext:  ExpressIoCContext  = context;
            expressContext.locals = { request: request }; // how can we get the current request value?
            return nextContextInterceptor(expressContext);
        };
        return planAndResolve(args);
    };
}
```

Then the users will be able to declare a constraint based on request headers:

``` ts
kernel.bind("db").toConstantValue(Db_A_Instance).when(request: interfaces.Request) => {
  let context: ExpressIoCContext = request.parentContext;
  return  context.locals.request.headers.A !== undefined;
});

kernel.bind("db").toConstantValue(Db_B_Instance).when(request: interfaces.Request) => {
  let context: ExpressIoCContext = request.parentContext;
  return context.locals.request.headers.B !== undefined;
});
```

Session could also be added to locals.

What do you guys think? Any ideas about how to access the current requests from a different scope?

cc: @ramlez

**Comment by codyjs** [comment]
I think it would be much easier and simpler to inject _both_ instances into a service, an then implement the conditional logic explicitly in the controller:

``` TypeScript
if (req.headers.A) {
    user = this.service.getUsersFromA();
} else if (req.headers.B) {
    user = this.service.getUsersFromB();
}
```

This way it's clear just by reading the controller what is happening. Otherwise, you would have to dig through the IoC container configuration (app root) to find this logic, and even then it's not quite as clear.

I suppose that if this is a common enough problem with Inversify in general, it isn't a bad feature to have. But right now I'm not convinced that it's necessary for this particular use case.

**Comment by remojansen** [comment]
I'm going with @codyjs advice for now. We might revisit this if we get other use cases :smile:
