### ISSUE TITLE
Is it possible to change the default scope?

### ISSUE THREAD

**Issue by jbcpollak** [inversify/InversifyJS#389]
I would like to default to singleton scope. Is it possible to do that so I don't have to always add `.inSingletonScope();` to the end of my declarations?

```
kernel.bind<Foo>('foo').to(Foo).inSingletonScope();
kernel.bind<Bar>('bar').to(Bar).inSingletonScope();
kernel.bind<Baz>('baz').to(Baz).inSingletonScope();
```

vs something like:

```
kernel.setDefaultScope(Singleton);
kernel.bind<Foo>('foo').to(Foo);
kernel.bind<Bar>('bar').to(Bar);
kernel.bind<Baz>('baz').to(Baz);
```

**Comment by remojansen** [comment]
Hi! Thanks for sharing this request :smile:  Unfortunately this feature doesn't match adhere to our vision.  We want to encourage developers to avoid singletons. Using everything as a singleton is normally a bad practice and we want to encourage good practices.

However, you can do something like:

``` ts
import { interfaces } from "inversify";

function bindInSingletonScope<T>(
    kernel: interfaces.Kernel,
    serviceIdentifier: interfaces.ServiceIdentifier<T>,
    service: constructor: interfaces.Newable<T>
) {
    return kernel.bind<T>(serviceIdentifier, service); // return so you can create constraints
}

bindInSingletonScope<Foo>('foo', Foo);
bindInSingletonScope<Bar>('bar', Bar);
bindInSingletonScope<Baz>('baz', Baz).whenTargetNamed("something"); // you can create constraints
```

**Comment by jbcpollak** [comment]
Hum, in my experience true singletons (ie, a module that returns a class instance) are bad practice (it makes testing hard for one), but using an IoC instantiated singleton is ok, it avoids instantiating unnecessary duplicate objects, etc.

For example, I have a 'MapProvider' class that is needed by multiple components and has an in-memory construct of the map. I don't want multiple copies of the MapProvider during production runtime, so I'd like to make it a singleton.

I'm coming from the Java/Spring IoC world however - so perhaps there is a better pattern in JavaScript.

Can you point me to some articles on how to avoid IoC singletons? What do you do about service modules? 

Interesting work around - I hadn't thought about a helper function, thanks. But as you said - if its a bad idea even for an IoC, I'd like to learn more about why.

**Comment by remojansen** [comment]
I started the development of InversifyJS after reading [this post](http://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html) and my main motivation was the following about DI in Angular 1.0:

<img width="778" alt="screen shot 2016-10-12 at 21 35 01" src="https://cloud.githubusercontent.com/assets/10656223/19326795/dd31e6fa-90c3-11e6-830f-dccde7e43e0b.png">

InversifyJS solves all these problems. 

About the first point "internal cache" I think that the main problem is that the "internal cache" is like a "global state" and global state can break your unit tests. For example, one tests does something using X and the next test will also use X because is a singleton. 

You can see some other thoughts at [SO](http://stackoverflow.com/questions/2662842/dependency-injection-singleton-design-pattern).

**Comment by jbcpollak** [comment]
Thanks! I'll read the post and the SO link. I understand those points and agree inversify doesn't have those problem. I would say that one solution to the internal cache problem is to keep singletons but make factories easier to create (Spring does this nicely).

Anyway, I'll review the links you sent and see if I can think of ways to restructure my code, although I'm skeptical there are solutions around it.

**Comment by jbcpollak** [comment]
Just a follow up - I read both links you sent:

The SO explains why you would not want to use manually constructed singletons - I completely agree. The Angular link explains their improvements, but doesn't explain how a service can be used to share state between components - it must be possible, but I don't see how. For example, in their article they created a NameService - if each component has its own instance of `NameService`, how can they every share state?

**Comment by remojansen** [comment]
Here are [some Angular 2  examples](http://stackoverflow.com/questions/36198785/how-do-i-create-a-singleton-service-in-angular-2) I guess is not harm to give the power of choice to our users.

I will do something to allow overriding of some defaults when creating a kernel instance:

``` ts
let kernel = new Kernel({
    defaultScope: "singleton",
    hierarchicalNavigation: "descending"
});
```
- `defaultScope` is what you are asking for.
- `hierarchicalNavigation` allows to configure hierarchical dependency injection to be ascending or descending by default it will be descending.

Angular 2 is ascending by default but I have been talking with other devs about it in other issues and descending allow us to split apps into multiple npm modules.

**Comment by remojansen** [comment]
This will be implemented soon. Keep an eye on the following issue to find out when it becomes available https://github.com/inversify/InversifyJS/issues/393
