### ISSUE TITLE
Singleton Scope For Async Provider

### ISSUE THREAD

**Issue by Shepless** [inversify/InversifyJS#397]
I cannot find a way of creating a singleton when using `toProvider()`.
## Expected Behavior

I'd like to be able to use `toProvider(...).inSingletonScope()` so that the provider function is only executed once.
## Current Behavior

Currently, the provider function is called every time the item is injected.
## Context

I would like to create a database connection (which is async to initialise) but it be provided as singleton.

**Comment by remojansen** [comment]
Hi,

Sorry for the late reply I was away for the weekend.

This is not possible because the value treated as a singleton would be the provider `() => Promise<T>` not the value `T`.

However, there is a work around using closures:

``` ts
kernel.bind<interfaces.Provider<DbConn>>("Provider<DbConn>").toProvider<DbConn>((context) => {
    let singleton = null; 
    return () => {
        if (singleton === null) {
            return new Promise<DbConn>((resolve, reject) => {
                let dbConn = new MongoClient(new Server('localhost', 27017));
                dbConn.open(function(err, conn) {
                    if (err) { reject(err); }
                    singleton = conn;
                    resolve(dbConn);
                });
            });
        } else {
            return Promise.resolve(singleton);
        }
    };
});
```

**Comment by Shepless** [comment]
@remojansen works a treat. Thank you! I'll close the issue.

**Comment by Sergiodfdez** [comment]
Iknj  vgtoñ0
