### ISSUE TITLE
Use Mocha to run tests

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#40]
At the moment, we are using Karma to test the project after it has been passed through browserify. This means that we test some of the code added by browserify, which we shouldn't be testing (such as `var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f`).

This results in skewed test coverage results (of 99.78%) because some of the lines are not possible to test with Karma.

By using Mocha, we can directly test our compiled commonjs code, which will give us a true reflection of our test coverage.

**Comment by remojansen** [comment]
Nice one :) I had this issue on my list I'm really happy to see that is fixed :+1:

**Comment by remojansen** [comment]
Closing as it is done by https://github.com/inversify/InversifyJS/pull/39
