### ISSUE TITLE
[inversify-restify-utils] Support specifying restify route options via Get, Post etc annotations

### ISSUE THREAD

**Issue by alexmt** [inversify/InversifyJS#412]
Currently it is impossible to specify any route settings except route path via @Get, @Post etc annotations. This is pretty inconvenient since a lot of existing restify middleware/plugins uses route settings as configuration. For example https://github.com/z0mt3c/node-restify-validation requires to define validation configuration in route settings:

```
server.get({url: '/test/:name', validation: {
      resources: {
        name: { isRequired: true, isIn: ['foo','bar'] }
      },
      queries : {
        status: { isRequired: true, isIn: ['foo','bar'] },
        email: { isRequired: false, isEmail: true },
        age: { isRequired: true, isNatural: true }
      }
    }}, function (req, res, next) {
        res.send(req.params);
    });
```

Versioned routes are supported in same way:

```
server.get({path: PATH, version: '1.1.3'}, sendV1);
```

## Possible Solution

I would suggest to change @Get, @Post, @Put, @Delete definition in following way:

```
export declare function Get(settings: string | any, ...middleware: restify.RequestHandler[]): interfaces.HandlerDecorator;
```

if settings value is a string then it should be treated as route path, otherwise it should be treated as route settings. 

## Context
We are building web app using restify and inversify. Route settings support would be very helpful. As workaround I implemented ugly patch for InversifyRestifyServer:

```
export function Get(options: string | RouteOptions, ...middleware: restify.RequestHandler[]) {
    return utils.Get(<any> options, ...middleware);
}

let builder = new InversifyRestifyServer(kernel);

builder.registerControllers = () => {
        let controllers = builder.kernel.getAll(utils.TYPE.Controller);
        controllers.forEach(controller => {
            let controllerMetadata = Reflect.getOwnMetadata('_controller', controller.constructor);
            let methodMetadata = Reflect.getOwnMetadata('_controller-method', controller.constructor);
            if (controllerMetadata && methodMetadata) {
                methodMetadata.forEach(metadata => {
                    let handler = builder.handlerFactory(controllerMetadata.target.name, metadata.key);
                    let options = typeof metadata.path === 'string' ?
                        <RouteOptions> {path: metadata.path} :
                        <RouteOptions> metadata.path;
                    options.version = options.version || DEFAULT_ROUTE_VERSION;
                    if (controllerMetadata.path !== '/') {
                        options.path = controllerMetadata.path + options.path;
                    }
                    builder.app[metadata.method](
                        options, controllerMetadata.middleware.concat(metadata.middleware), handler);
                });
            }
        });
    };
```

**Comment by remojansen** [comment]
Hi @alexmt I just release 3.0.0-beta.2 which I believe you need for this. Your suggestion looks good to me. However, I mainly look after the InversifyJS core. I would like @codyjs and @lholznagel to share their thoughts just to be sure because they are more experienced than me with node 😄

**Comment by lholznagel** [comment]
Oh yeah, I can totally understand you, that really is ugly. From my point it looks good.

**Comment by alexmt** [comment]
Thank you response guys! @lholznagel , can you take a look at PR please?

**Comment by remojansen** [comment]
The PR has been merged 🎉 

I have created another issue to do the same in the express utils https://github.com/inversify/InversifyJS/issues/422.

I'm going to try to update the dependencies and do a release ASAP.
