### ISSUE TITLE
[inversify-express-utils] Support specifying restify route options via Get, Post etc annotations

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#422]
Need to implement inversify/inversify-restify-utils/pull/19 in express as well.

**Comment by codyjs** [comment]
I'm not very familiar with Restify, so I could be wrong, but after some reading it looks like Express doesn't support these "route options", only a simple string for a path.

Restify API: http://restify.com/#routing (Scroll a bit down to see that server.get() takes an object as the first argument)
Express API: http://expressjs.com/en/4x/api.html#app.get.method

One thing that _is_ missing from express-utils is the ability to have an array of paths, as specified in the Express API.

@lholznagel, @alexmt thoughts?

**Comment by remojansen** [comment]
Thanks for letting me know @codyjs If you guys can confirm that this is not possible I will close this issue :)

**Comment by lholznagel** [comment]
I also think that express not supports this kind of options.

**Comment by remojansen** [comment]
Thanks for the details 👍
