### ISSUE TITLE
Proposal: ability to use numbers in `whenTargetNamed` and numbers/symbols as tag in `whenTargetTagged`

### ISSUE THREAD

**Issue by sanex3339** [inversify/InversifyJS#425]
It would be nice if you add ability to use `numbers` as name in `whenTargetNamed` and `numbers`/`symbols` as tag in `whenTargetTagged`

I want to use `enums` as names in `whenTargetNamed`. But current signature of this method allows only `string` values, so i can't use `enums`.

```javascript
enum NodeTransformers {
    CatchClauseObfuscator,
    FunctionDeclarationObfuscator,
    FunctionObfuscator
}

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(CatchClauseObfuscator)
    .whenTargetNamed(NodeTransformers.CatchClauseObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionDeclarationObfuscator)
    .whenTargetNamed(NodeTransformers.FunctionDeclarationObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionObfuscator)
    .whenTargetNamed(NodeTransformers.FunctionObfuscator);
```

Same with `whenTargetTagged`. It would be nice to use as tag `numbers` or `symbols`:
```javascript
const tag: symbol = Symbol();

enum NodeTransformers {
    CatchClauseObfuscator,
    FunctionDeclarationObfuscator,
    FunctionObfuscator
}

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(CatchClauseObfuscator)
    .whenTargetTagged(tag, NodeTransformers.CatchClauseObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionDeclarationObfuscator)
    .whenTargetTagged(tag, NodeTransformers.FunctionDeclarationObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionObfuscator)
    .whenTargetTagged(tag, NodeTransformers.FunctionObfuscator);
```

**Comment by remojansen** [comment]
Sounds reasonable to me. Would you like to send a PR?

**Comment by sanex3339** [comment]
I can try to do it in weekend.

**Comment by remojansen** [comment]
Cool I will be working in other issues first but If I finish them I will also work on this. I will comment here if I'm working on it...

**Comment by sanex3339** [comment]
I made some changes and update few tests but my MacBook Air just dying on that project so very hard to write additional tests, IDE is freezes.

https://github.com/sanex3339/InversifyJS/commit/2ef3c17d975ed56e39e83272a6c39c150640a801

I can make PR with this changes, but i think this changes should be covered by additional tests.

**Comment by remojansen** [comment]
If you send a PR I will review it and take a look to the build and test coverage 👍

**Comment by remojansen** [comment]
This has been now merged into master https://github.com/inversify/InversifyJS/pull/427

**Comment by sanex3339** [comment]
When i can expect beta version with this?

**Comment by remojansen** [comment]
Released 🎉 
<img width="514" alt="screen shot 2016-12-04 at 16 22 31" src="https://cloud.githubusercontent.com/assets/10656223/20867494/22c8bbf0-ba3e-11e6-9178-1f10c443d36b.png">

**Comment by sanex3339** [comment]
Amazing, thank you!
