### ISSUE TITLE
Add AMD Bundle to inversify-inject-decorators

### ISSUE THREAD

**Issue by abettadapur** [inversify/InversifyJS#430]
Hi @remojansen,
Thanks for doing for implementing #419, I was able to use the AMD library in my project.
Could you do the same for the inversify-inject-decorators library as well?

**Comment by remojansen** [comment]
Hi @abettadapur I will get this done this week but I can't promise you a date at the moment 😉

**Comment by remojansen** [comment]
I have added support for AMD modules and released it:

    $ npm install --save inversify@3.0.0-rc.1 inversify-inject-decorators@3.0.0-beta.1
