### ISSUE TITLE
inversify-express-utils: specify JSON response

### ISSUE THREAD

**Issue by ChrLipp** [inversify/InversifyJS#433]
## Expected Behavior
I would like to have a global / per controller / per route setting to specify that the response is a json.
This would be the same as calling `response.json(result);`, however I want to keep the programming model inversify-express-utils offers me by just returning the result and the framework sends the result.

## Current Behavior
Currently in `server.ts´ you can find two `res.send(..)` calls:

    private handlerFactory(controllerName: any, key: string): express.RequestHandler {
        return (req: express.Request, res: express.Response, next: express.NextFunction) => {
            let result: any = this.container.getNamed(TYPE.Controller, controllerName)[key](req, res, next);
            // try to resolve promise
            if (result && result instanceof Promise) {

                result.then((value: any) => {
                    if (value && !res.headersSent) {
                        res.send(value);
                    }
                })
                    .catch((error: any) => {
                        next(error);
                    });

            } else if (result && !res.headersSent) {
                res.send(result);
            }
        };

## Possible Solution
One of these or you find a better way:

- an  additional annotation and the code reacts to it (per route)
- an  additional annotation and the code reacts to it (per controller)
- the possibility to set it globally

Thanks for your work! Kind regards, Christian

**Comment by remojansen** [comment]
CC: @lholznagel @codyjs 

Hi! thanks for this suggestion. I understand this use case. Just like I usually do I recommend to create an API that feels like the ASP.NET core API. 

We should use the docs about [Formatting Response Data](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/formatting) as a reference. 

So we have 3 requirements:

## Formatting response data at route level
It is very easy to think that an annotation like `@json()` is the best solution but I don't agree with this for a few reasons. This means that we will need a new annotation for each format:  `@textplain()`, `@xml()`... As you can imagine this is not really easy to extend by the community. 

Also, I don't think we should aim for decorators as a solution for everything. We don't want our framework to become like Java spring:

![screen shot 2016-12-05 at 22 32 48](https://cloud.githubusercontent.com/assets/10656223/20905214/d06eb67c-bb3a-11e6-907b-704a607457d0.png)

The way ASP.NET core handles this is:

```
public JsonResult Get()
{
    return Json(_authorRepository.List());
}
```

Is almost identical to the node.js way:

```
response.json(result);
```

Maybe we need to declare our own `JsonResult` class? 


## Formatting response data at controller level
Same as at route level.

## Formating response data at application level
We need a to include something in the server public interface that allows us to register global response formatters. Initially, we can add three basic formatters:

- Xml
- Plain Text
- Json

This is basically a kind of response middleware like gziping responses...

We can then implement a few nice features. For example, routes that allow an extension:

![screen shot 2016-12-05 at 22 28 07](https://cloud.githubusercontent.com/assets/10656223/20905099/5a74afd0-bb3a-11e6-9272-eef4c93147be.png)



We can also add support for content negotiation so we respond in a given format based on the request headers.

**Comment by lholznagel** [comment]
Think that the response based on the Header is one of the best way to deal with that. Because like @remojansen said when we support json as decorator we also need plain, xml.

Maybe we should generally rethink the express utils and look what is missing and what is really needed. But also without the decorator pain like spring boot.

**Comment by ChrLipp** [comment]
Sounds great!
The only downside for the ASP.NET way is that the tests for the controller have to be output-format aware. I would prefer that the selection of the format is based on the header (+1)

**Comment by codyjs** [comment]
+1 for the headers idea.

**Comment by ChrLipp** [comment]
Is it something like this (only json case implemented)?

    private handlerFactory(controllerName: any, key: string): express.RequestHandler {
        return (req: express.Request, res: express.Response, next: express.NextFunction) => {
            let result: any = this.container.getNamed(TYPE.Controller, controllerName)[key](req, res, next);
            // try to resolve promise
            if (result && result instanceof Promise) {
                result
                    .then((value: any) => {
                        if (value && !res.headersSent) {
                            this.sendResult(req, res, value);
                        }
                    })
                    .catch((error: any) => {
                        next(error);
                    });

            } else if (result && !res.headersSent) {
                this.sendResult(req, res, result);
            }
        };
    }

    private sendResult(req: express.Request, res: express.Response, result: any) {
        switch (req.accepts("xml", "json")) {
            case "json":
                res.json(result);
                break;
            default:
                res.send(result);
        }
    }

Works for me.

**Comment by lholznagel** [comment]
With a quick look, it looks good.

**Comment by codyjs** [comment]
:+1: : LGTM as well.

**Comment by remojansen** [comment]
Do you guys want o volunteer to implement this? I would like to do some work on the DevTools projects after the 3.0 release.

**Comment by ChrLipp** [comment]
I did some tests and have some remarks:

- if no accept header is given, express already sets the Content-Type based on the type of the payload. So if I return an Object, express sets the Content-Type already to 'application/json' regardless of the Accept header. I didn't know this.
- This means that the header stuff is only needed if I return e.g. a string and want it converted to json.
- If I want to allow only JSON and the client doesn't send the JSON Accept header I would like to block the request. This would not work within the current solution, but can be easily solved with a custom middleware which just returns 403 when the Accept header is missing.
- The xml case (which I didn't implement) is not trivial since I need a serializer. Ideally the user is able to register his own serialization infrastructure.

So what do you say? Is an implementation still necessary with express standard functionality?
If you want I can send you a PR with the current code (no XML handling) , but at the moment I am not sure if the change is needed at all - the user just has to return an Object.

**Comment by remojansen** [comment]
Hi @ChrLipp thanks for researching this. I guess the best thing to do for now is to close this issue. The XML case may come back in the future but most people use JSON these days... 

I like to implement features only when there is a real need for them, a real use case. In this case adding XML support would be a lot of extra complexity that has not been required by no one so far. That's why I'm closing this issue.
