### ISSUE TITLE
Upgrade all projects to 3.0.0-rc.1

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#435]
We also need to upgrade all the other outdated dependencies.

[Sample PR](https://github.com/inversify/inversify-inject-decorators/compare/2.0.0...master)

## Utils
- [x] inversify-vanillajs-helpers  ➡️ `inversify-vanillajs-helpers@2.0.0-beta.1`
- [x] inversify-restify-utils  ➡️ `inversify-restify-utils@3.0.0-beta.1`
- [x] inversify-express-utils ➡️ `inversify-express-utils@3.0.0-beta.1`
- [x] inversify-binding-decorators ➡️ `inversify-binding-decorators@3.0.0-beta.1`
- [x] inversify-inject-decorators ➡️ `inversify-inject-decorators@3.0.0-beta.2`

## Docs
- [x] inversify.github.io  ➡️ https://github.com/inversify/inversify.github.io/pull/4

## Devtools
- [x] inversify-logger-middleware
- N/A inversify-devtools (Devtools will be upgraded after the 3.0 release)
- N/A inversify-chrome-devtools (Devtools will be upgraded after the 3.0 release)

## Examples
- [x] inversify-express-example
- [x] inversify-basic-example
- [x] inversify-hapi-example

**Comment by lholznagel** [comment]
Would take a look at `express-utils` and `restify-utils` tomorrow :)

**Comment by remojansen** [comment]
Thanks @lholznagel If you could upgrade to the following that would be great:

- inversify-express-utils
- inversify-express-example

I will upgrade the following projects:

- inversify.github.io
- inversify-logger-middleware
- inversify-basic-example

Then we can both try to fix:

- inversify-hapi-example

**Comment by lholznagel** [comment]
When do you plan to create a release for `express-utils`?, so that I can upgrade the `express-examples`.

**Comment by remojansen** [comment]
Sorry I forgot about it 😢 I will try to do a release later tonight I have to go offline now for 2 or 3 hours...

**Comment by lholznagel** [comment]
No worries, going to bed in an hour :)

**Comment by remojansen** [comment]
No worries! We can do it tomorrow :)
