### ISSUE TITLE
Restify and Express utils hang if there's a thrown error in the controller

### ISSUE THREAD

**Issue by mrsimonemms** [inversify/InversifyJS#436]
If an error is thrown inside the controller, the route is never resolved. This results in the route never being resolved.

## Expected Behavior
I'd expect for the error to resolved as an error up the callback chain

## Current Behavior
The route is never resolved

## Possible Solution
Wrap in a try/catch and resolve the callback/

## Steps to Reproduce (for bugs)
1. Create controller
2. Add `throw new Error('some error')` as the first line
3. Hit the endpoint in your browser

## Context
This is a problem in production in case something throws an error and it'll cause a bottleneck.

## Your Environment
* Version used: 2.1.2 (restify) 2.0.2 (express)
* Environment name and version: Node 6
* Operating System and version: OSX

# Stack trace
None

**Comment by remojansen** [comment]
Hi @riggerthegeek are you using inversify 2.0 or 3.0 ? express-utils is not ready for 3.0 we are working on that this week.

**Comment by mrsimonemms** [comment]
Aaah, that'll explain it @remojansen. I'm using v3.0.

Is that the case with Restify?

In fairness, it does largely seem to work with Inversify 3 as I've done a full end-to-end with it on Restify

**Comment by remojansen** [comment]
Yes, all the side projects are not ready for 3.0 we are going to upgrade one by one during this week. Try using 2.0 please let me know if that fix your issue.

**Comment by mrsimonemms** [comment]
Yeah, it works with Inversify v2.x.x.

I'll leave for you to close the issue, but I'm a happy chappie with v2. Thanks

**Comment by remojansen** [comment]
Sorry about the problems caused. You can expect a release compatible with 3.0 later this week :smile:

**Comment by mrsimonemms** [comment]
Apologies @remojansen, that hasn't fixed the issue (I was mistakenly using the version I was going to add to a PR).

If you look in the `/src/server.ts` file, line 82 is:

    let result: any = this.container.getNamed(TYPE.Controller, controllerName)[key](req, res, next);

This line needs to be wrapped in a try/catch. Is it worth me submitting a PR with a fix?

**Comment by lholznagel** [comment]
Currently, I don´t understand the problem. When your code throws an error, inverify express (restify) utils don´t work as expected anymore?

**Comment by mrsimonemms** [comment]
If you create a controller as this:

    @Controller('/foo')
    @injectable()
    export class FooController implements Controller {

        constructor( @inject('FooService') private fooService: FooService ) {}

        @Get('/')
        private index(req: restify.Request): string {
            throw new Error("some error");
        }
}

My server is going into a spin and never resolving. If I replace that with `return Promise.reject("some error")` it's fine, but it won't work when trying to handle uncaught exceptions due to my idiocy

**Comment by remojansen** [comment]
I think I get it.

> This line needs to be wrapped in a try/catch. Is it worth me submitting a PR with a fix?

That sounds good to me. 

@lholznagel do you think try/catch is correct here?

**Comment by lholznagel** [comment]
This would be the only idea I have. Question is what we do in the `catch` only make an output saying that there is an unexpected problem?

Wondering why @riggerthegeek don´t uses a try-catch but ok.

**Comment by remojansen** [comment]
I think in the case of a catch we need to return a HTTP Error 500 Internal server error

**Comment by mrsimonemms** [comment]
@lholznagel I'm of the opinion that, as it's already checking for a promise/callback error it should also check for a try/catch. 

@remojansen I wouldn't want Inversify to decide. That's why the `app.on("uncaughtException")` middleware exists

**Comment by remojansen** [comment]
I'm happy with your suggestion, do you want to send a PR?

**Comment by lholznagel** [comment]
ah okay.

We could make use of `setErrorConfig(errorConfig)` from `inversify-express-utils` and use that when a error happens

**Comment by mrsimonemms** [comment]
@lholznagel I don't think we need to do that as Restify and Express already handle that as they do a `cb('err')` or `Promise.reject('err')`.

PR will be incoming - I'm on a train at the moment so WiFi keeps cutting out

**Comment by mrsimonemms** [comment]
Hmmmm, it's failed the CI stage. It seems that most of the failures are pre-existing stuff - have I taken it from the wrong branch? (I took from master)

**Comment by remojansen** [comment]
This has now been released 🎉 
<img width="787" alt="screen shot 2016-12-07 at 00 05 18" src="https://cloud.githubusercontent.com/assets/10656223/20949382/e0ac9212-bc10-11e6-8402-3930383f7e69.png">

@lholznagel do we need to do this in the express utils as well?

**Comment by lholznagel** [comment]
Hm, hard to say. But @riggerthegeek says that the same problem occurs with express. So I think we should also update the express repo with this fix.

**Comment by mrsimonemms** [comment]
I would suggest we do need it on the Express utils. I'll do a PR at some point in the next 24 hours. If anyone gets to it before me, the `handlerFactory` method appears to be exactly the same in both packages.

**Comment by lholznagel** [comment]
Both packages should be nearly equal. To have them in separate repos and packages was more a design choice.

**Comment by remojansen** [comment]
Cool 😎 I will await for the PR before closing this

**Comment by mrsimonemms** [comment]
Hello chaps, I have bad news.  I think I may have wasted everyone's time on this for which I profusely apologise. I think there is still an issue, but it's not the one I first thought it was.

When I came in this morning and installed the update, it was still failing to first the `uncaughtException` event. I've traced through what's happening and it appears that it's sending the issue up through the middleware that I'm setting using the `@Get` decorator.

My middleware (largely stubbed) is as follows (it's a PassportJS strategy).

**Controller**
```
@Get('/', [
      (req, res, cb) => passport.authenticate('basic', { session: false })(req, res, cb),
    ])
    index () {
      throw new Error('some error')
    }
}
```

**Middleware**
```
export default fooService => {
    return new BasicStrategy((email, pass, cb) => {
        fooService.login(emailAddress, password)
           .then(user => {
                if (user) {
                    cb(null, user);
                } else {
                    cb(null, false);
                }
          }).catch(err => {
              console.log('auth');
              console.log(err);
              cb(err);
          });
    });
}
```

The fooService returns a promise, but the strategy is resolving a callback so I'm not returning the promise. My console is showing the 'auth' message and the error that should be thrown up the route which leads me to think that the middleware is misconfigured.

Certainly what I have determined is that the PR I submitted for this issue was wrong as it never fires the restify uncaughtException listener.

Can anyone suggest how to solve this problem?

**Comment by remojansen** [comment]
Sorry, I have no idea :cry: maybe @lholznagel or @codyjs can help ?

**Comment by lholznagel** [comment]
Sorry, I never really worked with passport.

**Comment by remojansen** [comment]
We need to rollback the `handlerFactory` function? 

https://github.com/inversify/inversify-restify-utils/pull/22/files#diff-916156c481141bfcd08c6ae40ce10e00L80

About the issue I won't be able to try until tonight :(

**Comment by mrsimonemms** [comment]
This isn't a Passport issue. It's an issue with using a promise in middleware when resolving a callback. I get exactly the same when stripping out the passport stuff

```
@Get('/', [
        (req, res, cb) => {
        fooService.login('email', 'pass')
          .then(user => {
            if (user) {
              cb(null, user);
            } else {
              cb(null, false);
            }
          }).catch(err => {
          console.log("auth");
          // console.log(err);
          cb(err);
        });
        }
    ])
    index () {
      throw new Error('some error')
    }
}
```

`fooService` is resolved in the Constructor declaration, but still the same file as in the passport example

**Comment by remojansen** [comment]
I'm just trying to guess but this seems wrong to me:

```ts
export default fooService => { // fooService  is a function
    return new BasicStrategy((email, pass, cb) => {
        fooService.login(emailAddress, password) // fooService is an object?
           .then(user => {
                if (user) {
                    cb(null, user);
                } else {
                    cb(null, false);
                }
          }).catch(err => {
              console.log('auth');
              console.log(err);
              cb(err);
          });
    });
}
```

**Comment by mrsimonemms** [comment]
Right, this is me with egg on my face. It is as issue, but it's an issue with restify not with the utils.

Please accept my apologies for wasting everyone's time. I would use the excuse of tight-project deadlines for not checking my stuff properly.

---

In answer to your question @remojansen, I'm using ES6 not TypeScript. `export default fooService` gets compiled as `export default function(fooService)` - that's what's coming in from my injector

**Comment by remojansen** [comment]
No problem! we are here to help :wink: 

I have created a new issue to rollback the changes https://github.com/inversify/InversifyJS/issues/439
