### ISSUE TITLE
Loading inversify-inject-decorators failed because of dependency on global Symbol.

### ISSUE THREAD

**Issue by jkanczler** [inversify/InversifyJS#444]
Loading inversify-inject-decorators failed because of dependency on global Symbol.

## Expected Behavior
Should work on IE without any error.

## Current Behavior
Currently the decorator.js has a reference on the global Symbol.
`var INJECTION = Symbol();`

Because of this inversify-inject-decorators can't work without polyfill.

Though there's a workaround for now:
`import "es6-symbol/implement";` using [es6-symbol npm package](https://www.npmjs.com/package/es6-symbol)

## Possible Solution
Require es6-symbol as a ponyfill can work.

## Steps to Reproduce (for bugs)
1. just use inversify-inject-decorators in IE

## Context
I would like to have an application that doesn't have any dependency on a global.

## Your Environment

* Version used: inversify 3.0.0-rc.2 and inversify-inject-decorators 3.0.0-beta.2
* Environment name and version: IE 11.0.9600.18524
* Operating System and version (desktop or mobile): Windows 7

# Stack trace
"ReferenceError: 'Symbol' is undefined\n   at Anonymous function (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:32433:2)\n   at __webpack_require__ (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:556:12)\n   at fn (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:87:13)\n   at Anonymous function (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:32411:2)\n   at __webpack_require__ (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:556:12)\n   at fn (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:87:13)\n   at Anonymous function (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:29620:2)\n   at __webpack_require__ (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:556:12)\n   at fn (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:87:13)\n   at Anonymous function (http://localhost:8080/application.bundle.js?b0c9579b2964c3bae07b:8379:2)"

**Comment by remojansen** [comment]
Thanks for reporting. We don't include polyfill by default but we document if they are required. I will add a note about it just like the note at https://github.com/inversify/InversifyJS#installation

**Comment by remojansen** [comment]
I have added instructions in the docs https://github.com/inversify/inversify-inject-decorators/commit/ddca3c3aea6028e7e9904aa8e3f079fc7c101df0
