### ISSUE TITLE
integration test for .d.ts

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#46]
Hi guys! 

I have added a label to track all the .d.ts related issues:

https://github.com/inversify/InversifyJS/labels/.d.ts

I think we need to focus on fixing this issues before we add new features.

Also we need to do something so this issues can be spotted in the future, at the moment the issues are are there but the Travis CI build thinks that everything is OK.

So we need integration tests so the build ensures that we don't merge to master broken code:
- Import InversifyJS as a global (reference ``)
- Import InversifyJS as an external module using the TS external module syntax
- import InversifyJS as an external module using the ES6 (import { inject }  from "inversify")

Any ideas about how to implement it? @inversify/collaborators

**Comment by Jameskmonger** [comment]
We could have a separate integration test file for each type, and try to compile them on the server.

**Comment by remojansen** [comment]
Hello guys I just did a release (1.2.1) on npm. Please let me know if it solves the issues :question:

**Comment by jamesadarich** [comment]
Hey Remo,

Looks like 1.2.1 is breaking get issue cannot find module "inversify", looks like the npm distribution is missing the definition and source code.

![image](https://cloud.githubusercontent.com/assets/8244919/12536123/ea7f554a-c292-11e5-9e59-370cee9d6152.png)

This is what I got after a fresh install. Probably need to reinclude this stuff!

**Comment by remojansen** [comment]
@jamesrichford thanks for taking a look. I just released `1.2.2`please take a look :)

**Comment by remojansen** [comment]
I have documented how I tested it [here](https://gist.github.com/remojansen/2158e91bc5b9140111ec#file-howto-md)

**Comment by Jameskmonger** [comment]
The NPM distribution now looks good to me, @remojansen ! Nice work.

**Comment by jamesadarich** [comment]
Tested briefly - run time issues are fixed but getting some compile errors. Need to look into the cause. Initial thinking is the lack of typings in package.json. Will investigate the issues I'm having at compile time when I get the chance

**Comment by remojansen** [comment]
@inversify/collaborators thanks for taking a look guys :) 

About the compilation issues: 

## A) --moduleResolution node

If you were previously using a reference to `./typings/inversify/inversify.d.ts` and an external module import. You should be able to just remove the reference to the `.d.ts` file and use the `--moduleResolution node` flag instead:

```
import { Inject } from "inversify"; 
```

The TypeScript compiler will then search in the `package.json` file for a field named `typings` and use a reference to `./node_modules/inversify/type_definitions/inversify-npm.d.ts`.

## B) --moduleResolution classic

For older versions of TypeScript or when using the `--moduleResolution classic` flag you can reference the file provided with the npm module:

```
/// <reference path="./node_modules/inversify/type_definitions/inversify.d.ts" />

import { Inject } from "inversify"; 
```

## C) global

Just add a reference to the `inversify-global.d.ts` file provided with the npm module:

```
/// <reference path="./node_modules/inversify/type_definitions/inversify-global.d.ts" />

var Inject = inversify.Inject;
```

**Comment by jamesadarich** [comment]
Sorry about late response on this. I have retested and 1.2.2 is working. I had an old cached version of the Inversify package.json which was causing me trouble.

Great work :+1:

**Comment by jmp909** [comment]
hi,

it would be great if someone could upload a version of the foobar example that runs in VS Code. I think I'm missing a few steps with 'require.js' and also it doesn't seem to like the  @Inject 

currently it's turning the statment `import { TypeBindingScopeEnum, TypeBinding, Kernel, Inject } from "inversify"` into `var inversify_1 = require("inversify")` at the top of the file and I get an error `Uncaught Error: Module name "inversify" has not been loaded yet for context: _. Use require([])`

sorry I'm a bit lost!

thanks
j

**Comment by Jameskmonger** [comment]
@jmp909: You're using [AMD](https://en.wikipedia.org/wiki/Asynchronous_module_definition), so wrap your class like this:

```
require(['inversify'], function (inversify) {
    // you will have access to inversify here
}
```

http://requirejs.org/docs/errors.html#notloaded

**Comment by jamesadarich** [comment]
As an added note without seeing the project it's probably the module type your setting for the typescript compiler i.e. in your tsconfig.json

```
{
    "compilerOptions": {
        "module": "amd"
    }
}
```

or for CLI

```
tsc --module amd
```

**Comment by jmp909** [comment]
thanks.. it was mainly that I needed to work out how to bootstrap it properly as well. I've put a working version here https://github.com/jmp909/inversify-typescript-basic , but it'd be good if you could create a similar repository specifically replicating the basic code on the website example, in terms of how to best set it up. It's all new to me, and I decided to jump in at the deep end!

thanks
J

**Comment by remojansen** [comment]
Hi @jmp909 we have a repo for examples at https://github.com/inversify/inversify-code-samples if you create a fork and add your example under a folder named "vscode" I will be happy to merge your pull request ; )

**Comment by remojansen** [comment]
@inversify/collaborators I think we can close this issue?

**Comment by Jameskmonger** [comment]
I agree @remojansen

**Comment by jamesadarich** [comment]
Agreed

**Comment by remojansen** [comment]
Thanks guys!
