### ISSUE TITLE
@optional does not work on properties

### ISSUE THREAD

**Issue by Mika56** [inversify/InversifyJS#460]
Hi,

The `@optional` decorator does not work when defined on a class' property. It works fine when used on a constructor's parameter.

Non-working code:

```js
@injectable()
class RouterBuilder {
    @multiInject(TYPES.RouterInterface) @optional()
    private routers: RouterInterface[];

    getRouters(): RouterInterface[] {
        return this.routers;
    }
}
```

The compiler throws:
```
app/kernel.ts(54,41): error TS1240: Unable to resolve signature of property decorator when called as an expression.
  Supplied parameters do not match any signature of call target.
```

Working code, which does the same thing as the non-working code, but less pretty if you ask me 😄 :

```js
@injectable()
class RouterBuilder {
    constructor(@multiInject(TYPES.RouterInterface) @optional() private routers: RouterInterface[]) {

    };

    getRouters(): RouterInterface[] {
        return this.routers;
    }
}
```

**Comment by remojansen** [comment]
Hi @Mika56 this has been implemented but it is not available yet. It will be included in the next release. Please refer to https://github.com/inversify/InversifyJS/pull/467 for more details.
