### ISSUE TITLE
Auto override bindings feature.

### ISSUE THREAD

**Issue by ivan-shaban** [inversify/InversifyJS#462]
I dont found any information about how to allow auto override exist binding, but i think it will be usefull.

## Expected Behavior

I load several modules and if some of them has the same binding IDs, so only last binding became active.

## Current Behavior

I load several modules and if some of them has the same binding IDs, i got a runtime error.

## Possible Solution

E.g. something like:
```
public bind<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, overrideIfExists:Boolean = false): interfaces.BindingToSyntax<T> {
```
In [SwiftSuspenders library](https://github.com/tschneidereit/SwiftSuspenders) was inverted behaviour, you may override everything at any time and, to prevent it, you should manually `lock` binding with explicit call, e.g.
```
injector.map("serviceIdentifier").toValue("my-value").seal();
```

[In this blob](https://github.com/tschneidereit/SwiftSuspenders/blob/master/src/org/swiftsuspenders/mapping/InjectionMapping.as) in function `seal` described how it works

## Steps to Reproduce (for bugs)

1. Make 2 modules with the same serviceIdentifiers
2. Load them into one container

## Context

I develop feature to extend application with 3rd party plugins, every plugin represented as self-independ module and all plugins loads into one container. Because plugins will be developed by different people it is possible that they may override the same `serviceIdentifier`s in that case i wanna to show warning message that plugins are not compatible, but don't want to block appllication work, it will be enough if only last binding override stay active. 

## Your Environment

    "inversify": "^3.0.0-rc.2",
    "reflect-metadata": "^0.1.9",

# Stack trace

**Comment by remojansen** [comment]
Hi @LordXaoca thanks for using inversify and for your suggestion 👍 

Instead of sealed bindings we allow you to add and remove bindings. You can remove a binding and then create a new one using [`container.unbind`](https://github.com/inversify/InversifyJS/blob/master/src/container/container.ts#L127).

At the moment we only allow you to remove all bindings for a given service identifier but there is already an issue to improve this #447

**Comment by remojansen** [comment]
Re-opening issue as the requirement is to allow to invoke unbind from container modules.

**Comment by remojansen** [comment]
I have implemented support for unbind within container modules https://github.com/inversify/InversifyJS/pull/464 It will be released over the next few days
