### ISSUE TITLE
Custom router not used when building InversifyExpressServer

### ISSUE THREAD

**Issue by maxmalov** [inversify/InversifyJS#486]
## Expected Behavior

`InversifyExpressServer` will use custom router passed to its constructor.

## Current Behavior

Custom router isn't used actually, see [this line](https://github.com/inversify/inversify-express-utils/blob/master/src/server.ts#L99)

## Possible Solution

Replace `this._app` with `this._router` at [this line](https://github.com/inversify/inversify-express-utils/blob/master/src/server.ts#L99)

## Steps to Reproduce (for bugs)

1. Pass custom router with `caseSensitive` option set to `true`
2. Add controller with case sensitive route, eg  GET /Foo
3. Build and start an app

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by remojansen** [comment]
👍
