### ISSUE TITLE
Required @injectable decorator on baseclass

### ISSUE THREAD

**Issue by ktutnik** [inversify/InversifyJS#493]
@injectable decorator seems a "must have" in baseclass. 

## Expected Behavior
@injectable should not required on the baseclass, because in most condition we don't have access to a baseclass to add @injectable decorator.

## Current Behavior
I see from [the source code](https://github.com/inversify/InversifyJS/blob/master/src/planning/reflection_utils.ts#L13) Inversify need to tackle error possibility whenever the baseclass parameter doesn't match with derived, which need to get information about number of baseclass parameters.

Not sure if this check is required, it seems cause more issue then its purposes.

## Steps to Reproduce (for bugs)
```javascript
import {inject, injectable, Container} from "inversify"

@injectable()
export class OtherClass{
    otherProp:string;
}

export class MyBaseClass{
    baseProp:string;
}

@injectable()
export class MyClass extends MyBaseClass{
    
    constructor(@inject("OtherClass") private other:OtherClass){
        super()
    }
}

let container = new Container()
container.bind<OtherClass>("OtherClass").to(OtherClass)
container.bind<MyClass>("MyClass").to(MyClass)

//error
let myclass = container.get<MyClass>("MyClass")
```

## Context
Currently im creating example for [KambojaJS](https://github.com/kambojajs/kamboja) which the controller should be inherited from ApiController provided by KambojaJS.

## Your Environment

* Version used: 3.1.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 5
* Operating System and version (desktop or mobile): desktop
* Link to your project: https://github.com/kambojajs/kamboja-examples

# Stack trace
```
MyClass Should instantiate MyClass properly:
     Error: Missing required @injectable annotation in: MyBaseClass.
      at _createSubRequests (node_modules/inversify/lib/planning/planner.js:106:19)
      at Object.plan (node_modules/inversify/lib/planning/planner.js:125:5)
      at Container._planAndResolve (node_modules/inversify/lib/container/container.js:218:37)
      at Container._get (node_modules/inversify/lib/container/container.js:211:44)
      at Container.get (node_modules/inversify/lib/container/container.js:176:21)
```

**Comment by remojansen** [comment]
Hi, thanks for reporting your issue. There is a solution for this problem already documented on the wiki. Please refer to the section ["What can I do when my base class is provided by a third party module?"](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#what-can-i-do-when-my-base-class-is-provided-by-a-third-party-module).
