### ISSUE TITLE
Spread operator /argumets array not working  

### ISSUE THREAD

**Issue by agalazis** [inversify/InversifyJS#496]
## Current Behavior
 It gives me  an empty array 

## Possible Solution
provide them to constructor  / propose workarounds in readme

## Steps to Reproduce (for bugs)
try to access arguments or use spread operator 

## Context
I am trying to get the arguments in the constructor in an array form

## Your Environment
OSX 64 bit, node 6.9, npm 3.10.9

**Comment by remojansen** [comment]
Hi @agalazis thanks for reporting this issue. Can you please provide some minimal source code to reproduce the issue?

**Comment by agalazis** [comment]
Here is fiddle that demonstrates the difference between creating the object with new and creating it with inversify:
https://jsfiddle.net/bv4eb3rL/2/
(check the console logs)
By the way it's not a huge issue, updating the docs with a warning and to use multi-inject to achieve this  with real arrays could also help some people,  but I understand that there could be some edge-cases where people might need this (once again a warning could do at least)

**Comment by remojansen** [comment]
Hi @agalazis I've been working on a fix for a few days already. It is a tricky bug 😄 I have been able to fix ti but it breaks some of the tests cases related to the usage of abstract classes. If I have to reach a compromise I prefer to support the spread operator than supporting advance errors in abstract classes. I guess most people will prefer this as well. Should have an update soon.

**Comment by remojansen** [comment]
I just created a PR and it includes some documentation. Things have improved a bit but sadly the spread operator is not a recommended option. Please refer to [the new section in the docs](https://github.com/inversify/InversifyJS/pull/502/files#diff-6869aee747b1250528d5f748e34cd76b) to learn more.
