### ISSUE TITLE
Question: Inject node module

### ISSUE THREAD

**Issue by ssljivic** [inversify/InversifyJS#499]
How can I inject a node module? I am looking for something like this feature from electrolyte:

`IoC.use(IoC.node_modules());`

https://github.com/jaredhanson/electrolyte#require-vs-require

**Comment by remojansen** [comment]
You should be able to use `toConstantValue`:

```ts
import { Container } "inversify";
import * as $ from "jquery";

const container = new Container();
container.bind<JQuery>("JQuery").toConstantValue($);

export { container };
```

```ts
import { container } from "inversify";

const $ = container.get<JQuery>("JQuery");
```

Please let me know if this issue can be closed.

**Comment by ssljivic** [comment]
Thanks.
