### ISSUE TITLE
New Feature: Automatic binding

### ISSUE THREAD

**Issue by ssljivic** [inversify/InversifyJS#500]
Would it be possible to have container automatically built with all the classes marked with @injectable() instead of manually calling the following code for each class?

`container.bind<MyClass>(MyClass).toSelf();`

**Comment by Dirrk** [comment]
See here:

https://github.com/inversify/inversify-binding-decorators/

**Comment by remojansen** [comment]
Hi, thanks for sharing your feedback with us :+1:  

I'm programming languages like Java or C# we are able to use reflection to explore the types in an assembly or DLL. We can then automatically generate the bindings. Unfortunately, in JavaScript we don't have a reflection mechanism as powerful and therefore all we can do is to create some utilities and helpers like the `inversify-binding-decorators`. 

The highest level of auto-registration that we can provide is [the auto-provice utility](https://github.com/inversify/inversify-binding-decorators/#the-auto-provice-utility).

I'm closing this issue. Feel free to add a comment if you have any additional questions.

ps @Dirrk thanks for helping here
