### ISSUE TITLE
Comparing with aurelia/dependency-injection

### ISSUE THREAD

**Issue by veeramarni** [inversify/InversifyJS#508]
Do you have comparison chart with other DI projects? I'm wondering whether there is lifecycle management support as shown in [aurelia](http://aurelia.io/hub.html#/doc/article/aurelia/dependency-injection/latest/dependency-injection-basics/3)

I apologize in advance if this is the right place to ask this question.

**Comment by veeramarni** [comment]
I think I found the answer for it [here](https://github.com/inversify/InversifyJS/blob/master/wiki/purpose.md) and will give a try.

**Comment by remojansen** [comment]
:+1: We support transient and singleton but we support contextual constraints which most DI libs for JS don't.
