### ISSUE TITLE
Inversify does not run?  Error TS2656

### ISSUE THREAD

**Issue by RichardJECooke** [inversify/InversifyJS#51]
I've downloaded the latest version of Inversify (1.2.0) and have Typescript (1.7.3).  But when trying to use your documentation to change just two files in my project and compile with tsc I get:

_error TS2656: Exported external package typings file 'node_modules/inversify/type_definitions/inversify.d.ts' is not a module. Please contact the package author to update the package definition._

Is there a typo in the latest version of Inversify perhaps?

---

I'm referencing Inversify like this:
`/// <reference path="../../node_modules/inversify/type_definitions/inversify.d.ts" />`

and using it like this:

```
import { TypeBinding, Kernel, TypeBindingScopeEnum } from "inversify";
import IDatabase = require('../database/iDatabase');
import Database = require('../database/Database');

class Ioc
{
    public container : Kernel;
    constructor()
    {
        let c = new Kernel();
        c.bind(new TypeBinding<IDatabase>("IDatabase", Database, TypeBindingScopeEnum.Transient));
        this.container = c;
    }
}
export = Ioc;
```

**Comment by remojansen** [comment]
Hi @RichardJECooke at the moment we are having a problem with the `.d.ts` files but we are working on it. I'm going to close this issue to ensure that we only have one unique issue to refer to this problem. You can follow the updates at https://github.com/inversify/InversifyJS/issues/46
