### ISSUE TITLE
implement lifecycle

### ISSUE THREAD

**Issue by acopalipsis** [inversify/InversifyJS#515]
I have classes that need to implement life cycle.
```
class A {
    public init(): void {
        
    }
    public destoy(): void {

    }
}
class B {
    public init(): void {

    }
    public destoy(): void {

    }
}

class C {}
```
It would be great if he DI could tell when classes are created and when destroyed. ( 1 )There is a possibility?

Right now I'm writing ReactJS and I need to implement life-cycle life equal route.
I don't know how to get all the necessary dependencies. I looked api Container did not understand how to tagged the dependency is not complicating inject. How best to do?

**Comment by remojansen** [comment]
As far as I know this is [a limitation of JavaScript](http://stackoverflow.com/questions/28564629/how-to-detect-if-an-object-has-been-garbage-collected-in-javascript). I want to implement something custom scopes that will allow users to have more control over when a class is created but we will still not be able to know when it is garbage collected.
