### ISSUE TITLE
Resolve function not available on Container [TypeScript]

### ISSUE THREAD

**Issue by jacks50** [inversify/InversifyJS#516]
I wanted to use the `resolve()` function as described in the container API doc. It doesn't seem to exist, am I missing something or are the docs not updated ?

## Expected Behavior
Expected to find a `resolve<T>(constructorNewable: Newable): T` function when using my `Container` object

## Current Behavior
There is no `resolve` function available on the TypeScript side. By checking the source files, I can see there is no function declared in the `.js` files as well as in the `.d.ts` files.

## Possible Solution
None at the moment

## Steps to Reproduce (for bugs)
1. `var c: Container = new Container();`
2. `c.resolve(MyObject);`
3. `Property "resolve" does not exist on type "Container"`

## Context
I am trying to create instances of unbound objects with the Container, in order to inject values to the related objects. Values are bound in the workflow, and I need property injection with the use of `resolve()` in order to avoid the "pass-by-reference" problem I am facing (or at least do some tests to see if I can resolve it this way).

## Your Environment
* Version used: inversify@3.0.0
* Environment name and version: NodeJs v7.1.0
* Operating System and version : Windows 10 v1607
* Link to your project: x

# Stack trace
Not relevant

**Comment by jacks50** [comment]
Just noticed there was an update to do .. My bad, sorry for inconvenience.

**Comment by remojansen** [comment]
No worries :wink:
