### ISSUE TITLE
[enhancement] Express-utils Add Decorators for binding method parameters to request parameters like in Spring or node-decorators

### ISSUE THREAD

**Issue by dcavanagh** [inversify/InversifyJS#521]
@Request - binds a method parameter to the request object - still provided at the end of the arguments list for backwards compatibility
    @Response - binds a method parameter to the response object - still provided at the end of the arguments list for backwards compatibility
    @RequestParam - binds a method parameter to request.params or to a specific parameter if a name is passed
    @QueryParam - binds a method parameter to request.query or to a specific query parameter if a name is passed
    @RequestBody - binds a method parameter to request.body or to a specific body property if a name is passed
    @RequestHeaders - binds a method parameter to the request headers
    @Cookies - binds a method parameter to the request cookies
    @Next - binds a method parameter to the next() function - still provided at the end of the arguments list for backwards compatibility

## Expected Behavior
```ts
@Get(':id')
    private list(@RequestParam('id') id: string, @QueryParams('start') start: number, @QueryParams('count') cound: number): string {
        return this.fooService.get(start, count);
    }

```
## Possible Solution
Making a pull request for this soon

## Context
Better developer experience than using request and response
modeled after spring and node-decorators
some code reused from node-decorators

**Comment by Dirrk** [comment]
@AltekkeE this looks pretty cool.  Another module that does something similar is https://www.npmjs.com/package/tsoa.  I haven't used the others but in case you wanted other examples I thought I would provide it.

**Comment by remojansen** [comment]
Hi, @AltekkeE thanks a lot for this suggestion. I would be happy to accept a PR for this features. A few months ago we wanted to start a project that provided something like that but due to lack of time, we never implemented it. I will await your PR 👍

**Comment by remojansen** [comment]
I have merged the PR so I'm closing this issue :smile:

**Comment by dcavanagh** [comment]
@remojansen What was the project?

**Comment by remojansen** [comment]
We never started but we had a lot of conversations about it https://github.com/CitadelJS
