### ISSUE TITLE
Fix test coverage reports

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#523]
The cov reports are not working. More info at https://github.com/inversify/inversify-express-utils/pull/41#issuecomment-290918130

**Comment by dcavanagh** [comment]
The problem is with gulp-mocha ^4.0. https://github.com/sindresorhus/gulp-mocha/issues/159
I tried reverting gulp-mocha to ^3.0 and the code coverage worked again.

**Comment by lholznagel** [comment]
Just as a general idea and to prevent things like this, maybe we should lock the dependency versions? I mean we have greenkeeper enabled.

**Comment by remojansen** [comment]
@lholznagel I know but this is an odd one because 3.0 and 4.0 is a breaking change. But the build is successful and the coverage reports are not available :(

**Comment by dcavanagh** [comment]
@remojansen What if you check that the coverage report is not empty?
This fails the build
``` 
var report = require('./coverage/coverage-final.json');
    if (Object.keys(report).length === 0) {
        throw new Error("no test coverage");
    }
    return ret;
```

**Comment by remojansen** [comment]
@AltekkeE That sounds like a good way to prevent this issue in the future. Thanks for sharing it :+1:

**Comment by remojansen** [comment]
Rolled back to 3.0.1 will wait until gulp-mocha fixes the problems.
