### ISSUE TITLE
Issues with @RequestParam @Request @Response

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#527]
So I'm testing the 3.5.0 release of `inversify-express-utils` and I have the following `Controller`:

```ts
@injectable()
@Controller(
    authServerPaths.server.roleFeature.name,
    authorize({ feature: FEATURE.APP_ACCESS_APP_PREFERENCES })
)
class RoleFeatureController {

    @repositoryOfRoleFeature private readonly _roleFeatureRepository: framework.Repository<entities.RoleFeature>;
    @logger private readonly _logger: logging.Logger;

    @Get(authServerPaths.server.roleFeature.endpoints.getById)
    public async getById(
        @RequestParam("id") roleId: string,
        @Request() req: express.Request,
        @Response() res: express.Response
    ) {
        try {
            this._logger.info(`HTTP ${req.method} ${req.url}`);
            return await this._roleFeatureRepository.readMany([{ key: "role_id", val: roleId }]);
        } catch (e) {
            this._logger.error(`HTTP ERROR ${req.method} ${req.url}`, e.message);
            res.status(500).json([]);
        }
    }

    @Post(authServerPaths.server.roleFeature.endpoints.post)
    public async post(
        @RequestBody() roleFeature: entities.RoleFeature,
        @Request() req: express.Request,
        @Response() res: express.Response
    ) {
        try {
            this._logger.info(`HTTP ${req.method} ${req.url}`);
            return await this._roleFeatureRepository.create(roleFeature);
        } catch (e) {
            this._logger.error(`HTTP ERROR ${req.method} ${req.url}`, e.message);
            res.status(500).json({});
        }
    }

    @Delete(authServerPaths.server.roleFeature.endpoints.delete)
    public async delete(
        @RequestParam("role_id") roleId: string,
        @RequestParam("feature_id") featureId: string,
        @Request() req: express.Request,
        @Response() res: express.Response
    ) {
        try {
            this._logger.info(`HTTP ${req.method} ${req.url}`);
            return await this._roleFeatureRepository.delete([
                { key: "role_id", val: roleId },
                { key: "feature_id", val: featureId }
            ]);
        } catch (e) {
            this._logger.error(`HTTP ERROR ${req.method} ${req.url}`, e.message);
            res.status(500).json({ affectedRows: 0 });
        }
    }

}
```

The `@Get()` method `getById` works as expected and it is binding `@RequestParam("id")`, ` @Request()` and `@Response()` correctly. However, the `@Delete()` methoi is not binded correctly:

- `@RequestParam("role_id")` is binded to the request.
- `@RequestParam("feature_id")` is binded to the response.
- `@Request()` is binded to the `next`.
- `@Response()` is not binded at all (undefined).

It looks like it is just not doing any kind of binding. The same problem takes place on the `@Post`() method.

Any ideas of what can be wrong @AltekkeE? Thanks!

**Comment by dcavanagh** [comment]
@remojansen 
it looks like you are getting the default behavior which adds req, res, next to the end of the arguments array that is passed to the RoleFeatureController.delete method. That 

what is the value of "authServerPaths.server.roleFeature.endpoints.delete"?
what is the value of request.params? 
The request.params object must contain an "role_id" and "feature_id" property

it is working for me using this code. 
```
@Delete('/:id/:feature_id')
    public deleteJob(@RequestParam('id') roleId: string,
        @RequestParam('feature_id') featureId: string,
        @Request() req: express.Request,
        @Response() res: express.Response): Promise<Message> {
        return  this.jobService.deleteJob(roleId);
    }
```

**Comment by remojansen** [comment]
I have:

```ts
@Delete(authServerPaths.server.roleFeature.endpoints.delete)
    public async delete(
        @RequestParam("role_id") roleId: string,
        @RequestParam("feature_id") featureId: string,
        @Request() req: express.Request,
        @Response() res: express.Response
    ) {
```

and `authServerPaths.server.roleFeature.endpoints.delete` is `/role_feature/:role_id/:feature_id`.

I'm debugging and looks like there is something wrong with [here](https://github.com/inversify/inversify-express-utils/blob/master/src/decorators.ts#L85-L91). The else is not invoking `Reflect.defineMetadata` ? I'm trying a few things...

**Comment by remojansen** [comment]
Fixed! [these two lines](https://github.com/inversify/inversify-express-utils/blob/master/src/decorators.ts#L83-L84) need to be moved out of the if/else :tada:

**Comment by dcavanagh** [comment]
@remojansen  I'm still having trouble reproducing the problem

**Comment by remojansen** [comment]
I think you need a controller with multiple methods and multiple annotations in the arguments, to reproduce the issue one method is not enough.  Did you try that? I released that change and it is working fine at work for me :)

**Comment by dcavanagh** [comment]
Ok.. I will try that. I just wanted to reproduce it so I could understand why it was going wrong.

**Comment by remojansen** [comment]
I added a [test case](https://github.com/inversify/inversify-express-utils/commit/585eb3bedeae514f9ee56da476144eb1448630a4).  The test case needed to hit this [`else`](https://github.com/inversify/inversify-express-utils/blob/master/src/decorators.ts#L83-L89).

The original code was:

```ts
if (!Reflect.hasOwnMetadata(METADATA_KEY.controllerParameter, target.constructor)) {
    parameterMetadataList.unshift(parameterMetadata);
    metadataList[methodName] = parameterMetadataList; // !
    Reflect.defineMetadata(METADATA_KEY.controllerParameter, metadataList, target.constructor); // !
} else {
    metadataList = Reflect.getOwnMetadata(METADATA_KEY.controllerParameter, target.constructor);
    if (metadataList.hasOwnProperty(methodName)) {
        parameterMetadataList = metadataList[methodName];
    }
    parameterMetadataList.unshift(parameterMetadata);
}
```

The `if` will generate some metadata thanks to the `Reflect.defineMetadata` call but the `else` case is not generating any metadata because it is missing the `Reflect.defineMetadata` call.

The fixed code is:

```ts
if (!Reflect.hasOwnMetadata(METADATA_KEY.controllerParameter, target.constructor)) {
    parameterMetadataList.unshift(parameterMetadata);
} else {
    metadataList = Reflect.getOwnMetadata(METADATA_KEY.controllerParameter, target.constructor);
    if (metadataList.hasOwnProperty(methodName)) {
        parameterMetadataList = metadataList[methodName];
    }
    parameterMetadataList.unshift(parameterMetadata);
}
metadataList[methodName] = parameterMetadataList; // !
Reflect.defineMetadata(METADATA_KEY.controllerParameter, metadataList, target.constructor); // !
```

**Comment by dcavanagh** [comment]
@remojansen Looks great! I was able to reproduce the problem. Sorry for all the trouble.

**Comment by remojansen** [comment]
No, problem thanks for your awesome PR :+1:
