### ISSUE TITLE
How to test a Typescript application

### ISSUE THREAD

**Issue by hdurix** [inversify/InversifyJS#532]
Hi,

I've developed a NodeJS app using InversifyJS and Typescript and I don't really know how to test it. I cannot find any documentation about it on your website. Did I miss something?

For example, I want to do an unit test for my AuthService:
```js
@injectable()
export class AuthService {

    private persistenceService: PersistenceService;
    private configurationService: ConfigurationService;

    constructor(
        @inject("persistence-service") persistenceService: PersistenceService,
        @inject("configuration-service") configurationService: ConfigurationService
    ) {
        log.debug("authentication service constructor");
        this.persistenceService = persistenceService;
        this.configurationService = configurationService;
    }

    ...

}
```

But I don't know how mocking the injected services (persistence and configuration services): I reckon I have to prevent InversifyJS container to inject those 2 services automatically.
I think I could do something like:
```js

// GIVEN
var persistenceServiceMock = /* ... build my mock ...*/;
var configurationServiceMock = /* ... build my mock ...*/;

var serviceUnderTest = new AuthService(persistenceServiceMock, configurationServiceMock);

// WHEN

serviceUnderTest.login("admin", "123123");
```

The problem is building the mocks. As it's Typescript, I imagine the transpiler won't allow me to give stub classes as arguments for my test service.

Have you got any example for this?

Thanks a lot

<details>
<summary>My environment:</summary>
<ul>
<li>NodeJS v7.5.0</li>
<li>Typescript v2.2.20</li>
<li>Npm v4.1.2</li>
<li>Inversify v3.0.0-rc.4</li>
</ul>
</details>

**Comment by remojansen** [comment]
Hi @hdurix please take a look to [Overriding bindings on unit test](https://github.com/inversify/InversifyJS/blob/master/wiki/recipes.md#overriding-bindings-on-unit-tests) also instead of `unbind` you can use [`rebind`](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#containerrebindserviceidentifier-serviceidentifier).

Please let me know if you need additional help and close the issue if you don't have more questions.

**Comment by hdurix** [comment]
Hello @remojansen and thanks for your help.

This wiki page is really helpful to do unit testing ([this one](https://github.com/inversify/InversifyJS/blob/2806aa9908dca34c69504db6f4882ba780b1b2d2/wiki/container_snapshots.md) aswell).

It's just a shame the documentation for tests is so hard to find because it helps a lot, maybe it could be good to add an entry for test documentation both in [welcome readme](https://github.com/inversify/InversifyJS#the-inversifyjs-features-and-api) and in [wiki readme](https://github.com/inversify/InversifyJS/blob/master/wiki/container_snapshots.md) even if it's simple redirects to those pages.

**Comment by lonix1** [comment]
Do you still mock this way? It requires bringing in the entire container into each test.

Is there not a simpler way, using poor-man's DI, just passing mocks into the ctor?

**Comment by hdurix** [comment]
I'm sorry I haven't worked with inversify since my last message so I won't be able to help you. I juste remember how hard it was for me to unit test it with TypeScript.

**Comment by lonix1** [comment]
Yeah inversify is amazing, but testing experience is not easy...

(what container are you using now?)

**Comment by hdurix** [comment]
I don't work in Node.js world anymore :D
So Spring and Vue.js DI are my friends now!
