### ISSUE TITLE
Export MetadataReader

### ISSUE THREAD

**Issue by gagle** [inversify/InversifyJS#542]
Related to #535. I need to access to the constructor and properties metadata. I'm currently reading the Reflect metadata by hardcoding the keys inversify:tagged and inversify:tagged_props and reading the content. I'll be happy to use the MetadataReader class to access them to hide implementation details.

**Comment by remojansen** [comment]
Check out the release 4.1.0 🎉 Here is [a test case](https://github.com/inversify/InversifyJS/blob/master/test/features/metadata_reader.test.ts#L214-L315) that you can use as documentation.
