### ISSUE TITLE
Using classes for injection: No metadata for interfaces

### ISSUE THREAD

**Issue by tsschaffert** [inversify/InversifyJS#548]
I am not sure whether this is a bug or if I do not understand the use case correctly. I tried to use classes for dependency injection as documented here: https://github.com/inversify/InversifyJS/blob/master/wiki/classes_as_id.md

My issue is that I got error messages about missing @inject annotations when using interfaces instead of actual classes for dependency injection. So the example works for me, but as soon as I have an interface as a constructor parameter for injection, I get the error. This breaks the feature of using classes for me, as always using concrete classes does not really make sense to me when using dependency injection.

## Expected Behavior
When testing the example shown at https://github.com/inversify/InversifyJS/blob/master/wiki/classes_as_id.md, I expect to be able to use this with interfaces to get a more realistic example.

## Current Behavior
When using interfaces, I get the runtime error "Missing required @inject or @multiInject annotation in: argument 0 in class App.". This is probably caused in part by the TypeScript compiler. I looked at the generated code and as interfaces are stripped out, there is no type annotation for a parameter if the supplied type is an interface. Everything works fine if I only use classes.

## Steps to Reproduce (for bugs)
1. Get example at https://github.com/inversify/InversifyJS/blob/master/wiki/classes_as_id.md running
2. Split code into multiple files
3. Add interfaces for types that should be injected ("Shuriken" and "Katana")
4. Use interfaces in Ninja constructor

## Your Environment
Inversify: v4.1.0
Node.js: v6.10.0
TypeScript: v2.2.2
Webpack: v2.3.3
Latest Chrome

**Comment by remojansen** [comment]
Hi @tsschaffert this is the expecting behavior. The inject `@inject` decorator was created just to support interfaces. This is due to the way the TS compiler emits decorator metadata and at this point in time there is nothing we can do about it :cry:

**Comment by tsschaffert** [comment]
Ah, that's a shame, but thanks for the info.
