### ISSUE TITLE
Document: Integration with mongoose

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#553]
Creating this issue because @altekkee needs some help with mongoose:

> Im new to using mongo and was wondering if you would be able to give me some advice on using inversify and mongodb. I noticed in the examples that you used the direct mongo driver instead of mongoose. Would you recommend staying with mongo? If you stay with the native drive do you use anything to set up the schema/ handle database updates? Like when you need a field to be unique etc.

**Comment by remojansen** [comment]
@AltekkeE I will have something for you this weekend. I'm working on an example for a presentation at a meetup and it will be useful for you as well.

**Comment by dcavanagh** [comment]
@remojansen Sounds great!

**Comment by remojansen** [comment]
Hi @AltekkeE this is not fully finished but you can start taking a look https://github.com/stelltec/public-tech-demos/tree/master/nodejs-madrid-meetup/demo3/src

Over the next few days there will be a fully working example in that repository.
