### ISSUE TITLE
express-utils: Empty query parameters are returned as an obj

### ISSUE THREAD

**Issue by dcavanagh** [inversify/InversifyJS#554]
If a query parameter is not sent, the parameter is set to the request.query object

## Expected Behavior
an empty query parameter should be set to undefined. 

## Current Behavior
If a query parameter is not sent, the parameter is set to the request.query object.

example controller
```typescript
@injectable()
@Controller("/api/test")
class TestController {
    @Get("/")
    public get(@QueryParam("empty") empty: string,
        @QueryParam("test") test: string) {
        console.log(empty);
        console.log(test);
    }
}
```
if you Get from url: http://{host}/api/test?test=testparam
test = "testparam"
empty = { test: 'testquery' }

## Possible Solution
check for empty query parameters
Working on pull request

## Steps to Reproduce (for bugs)
see above

## Context
Optional query parameters

## Your Environment

* Version used: inversify-express-utils 3.5.1
* Environment name and version: Node 7.4.0
* Operating System and version (desktop or mobile): OSX

**Comment by remojansen** [comment]
I just released `inversify-express-utils@3.5.2` :tada:
