### ISSUE TITLE
inversify-restify-utils an empty context and a body in the controller

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#558]
From [SO](https://stackoverflow.com/questions/44132075/inversify-restify-utils-an-empty-context-and-a-body-in-the-controller)

I try to get working `inversify-restify-utils` but I faced with a problem. Request context and body variable are empty.
My controller:

    @Controller('/users')
    @injectable()
    export class UsersController implements interfaces.Controller {
    
      @Post('/')
      createUser(req: restify.Request, res: restify.Response, next: restify.Next) {
        console.log(req.body); // undefined
      }
    }

My server.ts:

    // to get query params in req.query
    this.server.use(restify.acceptParser(this.server.acceptable));
    // to get passed json in req.body
    this.server.use(restify.bodyParser());

    this.server.post('/test', (req, res, next) => {
      console.log(req.body); // ok
      next();
    });

Any suggestions?

**Comment by remojansen** [comment]
@lholznagel @lynx-r I saw you guys are talking about this in the chat. I will try to take a look this weekend but feel free to help you have time available.

**Comment by lynx-r** [comment]
The solution was easy. I missed setConfig(). I've answered on my question.

**Comment by remojansen** [comment]
@lynx-r I was thinking that but I though you didn't use it to simplify the question :+1:
