### ISSUE TITLE
Context dependent singleton injection

### ISSUE THREAD

**Issue by akosyakov** [inversify/InversifyJS#560]
What will be the best way to achieve the following:
- There are A, B1, B2 and C classes.
- A depends on B1, B2 and C.
- B1 and B2 depend on C. 
- A should be in a transient scope, so a new instance on each injection.
- But B1, B2 and C should be injected as singletons in the context of A.

**Comment by remojansen** [comment]
Hi @akosyakov, this is one of the most complex features that I've been planing for months but it is not ready yet. I have an issue #218 to track it. What you  need is `inRequestScope()`: 

**:warning: This feature is not available yet :warning:**

```ts
container.bind<A>("A").to(A);
container.bind<B1>("B1").to(B1).inRequestScope();
container.bind<B2>("B2").to(B2).inRequestScope();
container.bind<C>("C").to(C).inRequestScope();
```

I have plans to add support for this feature but it is a complicated one. I also have plans for `inCustomScope`.

For the moment, there are multiple ways to hack your way around this use case. They are not very elegant :cry: the less ugly one I can think about is the following:

```ts
@injectable()
class AFactory {

   @inject("A") private A: A;
   @inject("B1") private B1: B1;
   @inject("B2") private B2: B2;
   @inject("C") private C: C;

   public getA() {
       const c = new this.C();
       const b1 = new this.B1(c);
       const b2 = new this.B2(c);
       const a = new this.A(b1, b2, c);
       return a;
   }

}

container.bind<A>("A").toConstructor(A);
container.bind<B1>("B1").toConstructor(B1);
container.bind<B2>("B2").toConstructor(B2);
container.bind<C>("C").toConstructor(C);
container.bind<AFactory>("AFactory").to(AFactory);

const aFactory = container.get<AFactory>("AFactory");
const a = aFactory.getA();
```

Please let me know if it is OK to close this issue.

**Comment by akosyakov** [comment]
@remojansen thanks for the hint

**Comment by akosyakov** [comment]
@remojansen I've managed it with a new child container for each A instance.

**Comment by remojansen** [comment]
That would be my second suggestion I don't think it is better or worst than the factory just a question of personal preference.
