### ISSUE TITLE
Idea: Exception-less failure to resolve from the container

### ISSUE THREAD

**Issue by atrauzzi** [inversify/InversifyJS#564]
I have some scenarios where I'd like to allow for optional bindings when doing lookups against the container.

Currently, to support this I have to put `try { } catch { }` blocks around my `container.get(...)` calls, which works but is obviously a little verbose.

Is there any merit in offering a default value when attempting to resolve from the container and when the resolution doesn't find anything, the default is returned instead?

**Comment by remojansen** [comment]
Better than a try / catch you can create a helper powered by `container.isBound`:

```ts
function getOrDefault<T>(
    container: Container, typeIdentifier: Symbol, defaultValue: T
) {
    if (container.isBound(typeIdentifier) === true) {
        return container.get<T>(typeIdentifier)
    }
    return defaultValue;
}

interface Foo {
    bar: string;
}

const foo = getOrDefault<Foo>(container, typeIdentifier, { bar: "default" });
```

We can add this to the core library but we need more methods `getNamedOrDefault` `getTaggedDefault`:

```ts
const w1 = container.getOrDefault<Ninja>("Ninja", { weapon: "Shuriken" });
const w2 = container.getNamedOrDefault<Warrior>("Warrior", "Sneaky". { weapon: "Shuriken" });
const w3 = container.getTaggedOrDefault<Warrior>("Warrior", { sneaky: true }, { weapon: "Shuriken" });
```

**Comment by atrauzzi** [comment]
Would `defaultValue` be optional and itself default to `null` if not provided?

**Comment by akosyakov** [comment]
@remojansen would be nice just to have overloads for existing methods, e.g. 
```ts
get<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>): T;
get<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, defaultValue: T): T;
```

**Comment by akosyakov** [comment]
btw I was surprised that:
- `multiInject` fails without bindings
- and `multiInject` + `optional` inject `undefined`

I've expected an empty array in both cases.

**Comment by remojansen** [comment]
@atrauzzi I would prefer people to be explicit about it. I think it is better to make `defaultValue` not optional:

```ts
const w1 = container.getOrDefault<Ninja|null>("Ninja", null);
```
If by default is `null` people will have to check for `null` all the time :sob: 

@akosyakov if we do overloads:

```ts
get<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, defaultValue: T): T;
```

How will you allow for null as default?

```ts
const ninja = container.get<Ninja>("Ninja"); // thorws
const nullableNinja = container.get<Ninja|null>("Ninja", null); // null
```

I don't want to force everyone to check for nulls.

Also I was just thinking that we already have [@optional()](https://github.com/inversify/InversifyJS/blob/961acc4715b3cf50049837d8d132479e48925079/wiki/optional_dependencies.md) cpuld **@default(someValue)** be a good thing too?

I'm removing, "Accepting PRs" we need talk this properly first :smile:

**Comment by remojansen** [comment]
I think I like the following:

### A

```ts
const ninja = container.get<Ninja>("Ninja"); // thorws
const nullableNinja = container.get<Ninja|null>("Ninja", null); // null
const defaultNinja = container.get<Ninja>("Ninja", { weapon: "default" }); // Obj
```

More than:

### B

```ts
const ninja = container.get<Ninja>("Ninja"); // thorws
const nullableNinja = container.getOrDefault<Ninja|null>("Ninja", null); // null
const defaultNinja = container.getOrDefault<Ninja>("Ninja", { weapon: "default" }); // Obj
```
What do you guys think?

**Comment by akosyakov** [comment]
I like A more, there also can be `getOptional`:
```ts
/** 
 * return `undefined` if the binding is missing, 
 * a short cut for `get(serviceIdentifier, undefined)`
 */
getOptional<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>): T | undefined;
/** 
 * return an empty array if there is no bindings,
 * a short cut for `getAll(serviceIdentifier, [])`
 */
getAllOptional<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>): T[];
```

**Comment by akosyakov** [comment]
btw `try { } catch { }` is just bogus, since there can be real issues with broken bindings

**Comment by atrauzzi** [comment]
My vote is for **_A_**. I've used similar APIs before and enjoyed it!

**Comment by remojansen** [comment]
So we need to add an optional argument `defaultValue` to [all existing `get*` methods](https://github.com/inversify/InversifyJS/blob/master/src/interfaces/interfaces.ts#L177-L180):

```ts
get<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    defaultValue: T
): T;

getNamed<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    named: string|number|symbol,
    defaultValue: T
): T;

getTagged<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    key: string|number|symbol,
    value: any,
    defaultValue: T
): T;

getAll<T>(
    serviceIdentifier: ServiceIdentifier<T>, defaultValue: T
): T[];
```

The above functions will not use try/catch internally (the will is `isBound`, `isNamed`, `isBoundTagged`) - the whole point of it is that it is implemented without exceptions so that it is fast. 

We also need to create the helpers (just a wrapper around the other functions):

```ts
tryGet<T>(
    serviceIdentifier: interfaces.ServiceIdentifier<T>
): T | null;

tryGetNamed<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    named: string | number | symbol
): T | null;

tryGetTagged<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    key: string | number | symbol,
    value: any
): T | null;

tryGetAll<T>(
    serviceIdentifier: ServiceIdentifier<T>
): T[];
```

I think I like more `get` and `tryGet` than `get` and `getOptional` because reminds me to `Parse` and `TryParse` do you guys agree?

**Comment by atrauzzi** [comment]
If I'm remembering right at the moment, .net's `tryGet` APIs are a little different semantically, taking an out parameter and returning a boolean.  It likely goes without saying, but I'll just put here: Please don't do that! 😉 

But beyond that, nothing really obligates TS to do the same except that it happens to attract the attention of a lot of C# developers.
I feel like `getOptional` is more misleading as it could be conflated with the concept of "optionals".  Seems future-prone, so I would avoid it for your reason, and at least one other.

Alternative names? `getOrThrow`, `getOrFail`.

Is `defaultValue` optional or defaulted?  Should we be returning `undefined` as opposed to null when a get is attempted and no default is provided?

**Comment by akosyakov** [comment]
I would prefer `undefined`, since it is kind of default `null` in js world, and a lot of projects try don't use `null` at all.

`tryGet` sounds good to me, `getOrThrow`/`getOrFail` sound too verbose.

**Comment by akosyakov** [comment]
`container.isBound(typeIdentifier)` can it throw an error or never throws?

**Comment by remojansen** [comment]
Thank for the feedback guys, I really appreciate it 👍 

So, as you pointed out `defaultValue` should include `?`:

```ts
get<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    defaultValue?: T
): T;

getNamed<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    named: string|number|symbol,
    defaultValue?: T
): T;

getTagged<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    key: string|number|symbol,
    value: any,
    defaultValue?: T
): T;

getAll<T>(
    serviceIdentifier: ServiceIdentifier<T>, 
    defaultValue?: T[]
): T[];
```

And should return `undefined` and y think it is ok to stick with `tryGet*` as you said we don't need to follow C# and `getOrThrow` would require us to rename the existing method and the new ones will be named like the currently existing ones. I would like to avoid such breaking change.

```ts
tryGet<T>(
    serviceIdentifier: interfaces.ServiceIdentifier<T>
): T | undefined;

tryGetNamed<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    named: string | number | symbol
): T | undefined;

tryGetTagged<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    key: string | number | symbol,
    value: any
): T | undefined;

tryGetAll<T>(
    serviceIdentifier: ServiceIdentifier<T>
): T[];
```

What do you guys think that should happen for child requests? Let's say that `Ninja` needs `Weapon`. The binding for `Ninja` has been declared but the binding for `Weapon` is missing:

- When invoking `get<Ninja>(Ninja)` I expect a "no bindings found for Ninja" exception.
- When invoking `get<Ninja>(Ninja)` I expect a "no bindings found for Weapon" exception or undefined? I personally fear returning undefined for child requests becoming something very confusing.

**Comment by akosyakov** [comment]
- for `getAll` should not be a type of a default value be `T[]`?
- I think `try*` methods should return `undefined` or an empty array only if there is no bindings for the given `serviceIdentifier` in other cases it should behave like `get*`, so it should throw

**Comment by remojansen** [comment]
Thanks for all the feedback I'm closing this issue. I have created #566 so it is easy to know what are the final requirements.

**Comment by atrauzzi** [comment]
Love the empty array. Totally agree. If we need to know when nothing is bound, the manual checks are still there and are more expressive.

All of this looks great.
