### ISSUE TITLE
@RequestBody("xxx") returns body when property is null or undefined

### ISSUE THREAD

**Issue by massivex** [inversify/InversifyJS#565]
## Expected Behavior
`@RequestBody("title") title : string` 
should be returns null / undefined values when property title is null or undefined in body

## Current Behavior
When I post as body a json data like that 
```
{
  "customerId" : 234,
  "title" : null,
   "firstname" : "Alex"
}
```
and I'm using a property attribute like that 
`@RequestBody("title") title : string`
title variable contains all body data instead of null.

## Possible Solution
I think in server.js the function getParam in that line
`return param[name] || this.checkQueryParam(paramType, param);`
should be
```
if (paramType === "query") {
  return param[name] || undefined;
} else if (paramType === "body") {
  return param[name];
}
return param[name] || param;
```
or something better.

## Steps to Reproduce (for bugs)
1.  Post as body a json data like that 
```
{
  "customerId" : 234,
  "title" : null,
   "firstname" : "Alex"
}
```
2. inside the controller use a property attribute like that 
`@RequestBody("title") title : string`

3. title variable contains all body data instead of null.

## Context
I'm simply posting data to a controller :)

## Your Environment
* Version used: inversify 4.1.1, inversify-express-utils 3.5.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 6.9.2, Chrome 58.0.3029.110 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 (64-bit)
* Link to your project:

# Stack trace

**Comment by dcavanagh** [comment]
`@requestBody()` does not take any arguments. It was intended to supply the body of the request as an object so that you can apply a type to it. So in your case:

```ts
interface Customer {
  customerId: number;
  title: string;
  firstName: string;
}
```
and the method
```ts
@post('/')
public addCustomer (@responseBody() customer: Customer): any {
  let title = customer.title;
}
```

**Comment by remojansen** [comment]
@AltekkeE can we throw or something is someone tries to use it with args `@RequestBody("xxx")`? Should that not be a compilation error.

**Comment by dcavanagh** [comment]
I don't see why not

**Comment by remojansen** [comment]
@massivedynamicsrls are you using TypeScript? how did you pass arguments to `RequestBody` without getting a compilation error?

**Comment by z-f-t** [comment]
I can confirm that typescript compilation goes without any errors.
Also, when you have `@RequestBody("title") title : string` it'll extract "title" parameter from the body, it "title" parameter is part of the body, but if parameter "title" doesn't exist, it'll pick up entire body.
I would say that behaviour isn't consistent. If it's designed to extract entire body, that shouldn't extract any parameter in any case.

**Comment by dcavanagh** [comment]
[#161](https://github.com/inversify/inversify-express-utils/pull/161) thanks!

**Comment by dcavanagh** [comment]
5.2.2

**Comment by just-jeb** [comment]
The [docs](https://github.com/inversify/inversify-express-utils) still state that RequestBody annotation does get an argument. Probably should be fixed.
