### ISSUE TITLE
New feature: Support defaultValues and tryGet* methods

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#566]
```ts
get<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    defaultValue?: T
): T;

getNamed<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    named: string|number|symbol,
    defaultValue?: T
): T;

getTagged<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    key: string|number|symbol,
    value: any,
    defaultValue?: T
): T;

getAll<T>(
    serviceIdentifier: ServiceIdentifier<T>, 
    defaultValue?: T[]
): T[];
```

And should return `undefined` and y think it is ok to stick with `tryGet*` as you said we don't need to follow C# and `getOrThrow` would require us to rename the existing method and the new ones will be named like the currently existing ones. I would like to avoid such breaking change.

```ts
tryGet<T>(
    serviceIdentifier: interfaces.ServiceIdentifier<T>
): T | undefined;

tryGetNamed<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    named: string | number | symbol
): T | undefined;

tryGetTagged<T>(
    serviceIdentifier: ServiceIdentifier<T>,
    key: string | number | symbol,
    value: any
): T | undefined;

tryGetAll<T>(
    serviceIdentifier: ServiceIdentifier<T>
): T[];
```
It should throw if there are no bindings for one of the child requests. The bindings are only optional for the root request (when using `tryGet*`).

**Comment by theodesp** [comment]
Whats the plan on this is it nice to have?

**Comment by remojansen** [comment]
@theodesp this is a needed feature. If someone sends a PR it will be welcome.

**Comment by theodesp** [comment]
Ok let me try to understand this ticket.
When you call `get<T>, getNamed<T>, getTagged <T>, getAll<T>`  with a default value it should proceed with the whole `plan` and create the request and then proceed with the resolve.

Now in the Planner, we have the following decisions:
If there are no bindings available [here](https://github.com/inversify/InversifyJS/blob/master/src/planning/planner.ts#L93)
or we have multiple bindings available [here](https://github.com/inversify/InversifyJS/blob/master/src/planning/planner.ts#L109) = >
**Shall we just proceed as normal and throw the Error?**

Now in the Resolver, we have the following decisions:

If there are no bindings available and the target request is optional [here](https://github.com/inversify/InversifyJS/blob/master/src/resolution/resolver.ts#L31) => **Shall we return the default value instead?**

If the user forgot to setup a BindingToSyndax [here](https://github.com/inversify/InversifyJS/blob/master/src/resolution/resolver.ts#L58) => **Shall we return the default value instead?**

**Comment by theodesp** [comment]
Any further reply on this? hacktoberfest is live!

**Comment by remojansen** [comment]
I have the following vision in mind:

> Now in the Planner, we have the following decisions:
> If there are no bindings available here
> or we have multiple bindings available here = >
> Shall we just proceed as normal and throw the Error?

If a default value is provided the no exception should be thrown. The functions will not use try/catch internally (the should use `isBound`, `isNamed`, `isTagged`) - the whole point of it is that it is implemented without exceptions so that they are fast. The plan should create a constant value binding containing the default as part of the plan. So we can proceed to the resolution phase.

> If there are no bindings available and the target request is optional here => Shall we return the default value instead?

In the resolve phase, there will be a  binding of a constant type always so the idea is that you will not have to do any changes to the resolution phase.

**Comment by theodesp** [comment]
You mean something like that:
```
public get<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, defaultValue?: T): T {
        if (this.isBound(serviceIdentifier) || !defaultValue) {
            return this._get<T>(false, false, TargetTypeEnum.Variable, serviceIdentifier) as T;
        } else {
            return defaultValue
        }
    }

 public getTagged<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, key: string|number|symbol, value: any,  defaultValue?: T): T {
        if (this.isBoundTagged(serviceIdentifier, key, value) || !defaultValue) {
            return this._get<T>(false, false, TargetTypeEnum.Variable, serviceIdentifier, key, value) as T;
        } else {
            return defaultValue
        }
    }

public getNamed<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, named: string|number|symbol, defaultValue?: T): T {
        if (this.isBoundNamed(serviceIdentifier, named) || !defaultValue) {
            return this.getTagged<T>(serviceIdentifier, METADATA_KEY.NAMED_TAG, named) as T;
        } else {
            return defaultValue
        }
    }

public getAll<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, defaultValue?: T[]): T[] {
        if (this.isBound(serviceIdentifier) || !defaultValue) {
            return this._get<T>(true, true, TargetTypeEnum.Variable, serviceIdentifier) as T[];
        } else {
            return defaultValue
        }
    }

```
The problem I see is that internally the `isBound`, `isBoundNamed`, `isBoundTagged` will all throw an error when the lookup fails here:

https://github.com/inversify/InversifyJS/blob/4b2cf1a6d3dc07d98f15c57d4ab28b03d1910d6d/src/container/lookup.ts#L46-L49

so inevitably will throw errors if there are no bindings.

What do you suggest?

**Comment by atrauzzi** [comment]
Still hoping for this to become a thing some day! ❤️

**Comment by atrauzzi** [comment]
Another ping on this one, running into it today.  I have so many scenarios where it's totally fine to not resolve anything.

**Comment by sebastien-comeau** [comment]
@notaphplover glad you took time to implement it. 👍 

I encountered an issue with `container.tryGetAll`. It attempts to resolve binding dependencies even when the `when` condition evaluates to false.

inversify version `6.2.0-beta.1`

Unit tests that reproduce the issue.
https://stackblitz.com/edit/vitest-dev-vitest-uwm57s?file=test%2Fbasic.test.ts

**Comment by notaphplover** [comment]
> @notaphplover glad you took time to implement it. 👍 
> 
> I encountered an issue with `container.tryGetAll`. It attempts to resolve binding dependencies even when the `when` condition evaluates to false.
> 
> inversify version `6.2.0-beta.1`
> 
> Unit tests that reproduce the issue.
> https://stackblitz.com/edit/vitest-dev-vitest-uwm57s?file=test%2Fbasic.test.ts

Hey @sebastien-comeau, you need to pass the enforce binding constraints option in order to accomplish that behavior

**Comment by sebastien-comeau** [comment]
> Hey @sebastien-comeau, you need to pass the enforce binding constraints option in order to accomplish that behavior

@notaphplover I assumed that would be the default behavior.

**Comment by notaphplover** [comment]
> @notaphplover I assumed that would be the default behavior.
> 
> 

Hey @sebastien-comeau, it's done that way so `.getAll` and `.tryGetAll` behave the same way
