### ISSUE TITLE
Inject contextually with class name

### ISSUE THREAD

**Issue by Aboisier** [inversify/InversifyJS#570]
Hi,

I am currently trying to inject loggers in different classes. I am using log4js. My problem is the following:  
I would like to categorize each injected logger the name of the target class (the one it's being injected into).

However, I have not been able to retrieve the class name. Is there any way of doing this? 

```js
container.bind<log4js.Logger>(Types.Logger).toDynamicValue(context => {
    let className = context....?; // Finds class name
    return log4js.getLogger(className );
});
```

Thank you!
Antoine

**Comment by Aboisier** [comment]
Related to : https://github.com/inversify/InversifyJS/issues/576

**Comment by remojansen** [comment]
Hi @Aboisier can you please share your feedback in #576 ? I will close this issue so we can track it in the other one.

**Comment by Aboisier** [comment]
I think the other issue is descriptive enough, I don't have anything to add for now. I think you can close this one. Thanks @remojansen !
