### ISSUE TITLE
[Feature request] Use strings enum for indexing the types.

### ISSUE THREAD

**Issue by dagatsoin** [inversify/InversifyJS#582]
Typescript now use string enums in 2.4.

What do you think about using them to index the concrete types?

```
export const Types = {
    RestClient: "RestClient",
    XHRInstance: "XHRInstance",
};
```
to

```
export enum Types {
    RestClient = "RestClient",
    XHRInstance = "XHRInstance",
};
```

**Comment by remojansen** [comment]
I haven't tested it but InversifyJS allows you to use 3 kinds of identifiers:

- Classes
- Strings Literals
- Symbols

Can you please check if the following works:

```ts
enum Types {
    Something = "Something"
};

const container = new Container();
container.bind<string>(Types.Something).toConstantValue("SOME VALUE");
const value = container.get<string>(Types.Something);
```

My guess is that this should work?

**Comment by dagatsoin** [comment]
Yes it works but my IDE (which is IDEA) mark an warning:
`Argument type Types is not assignable to parameter type etc...` surely because Enum is not an allowed type for bind<T>()?

**Comment by remojansen** [comment]
Do you get this error when you compile with webpack, tsc, .. as well or only in IDEA?

**Comment by dagatsoin** [comment]
Just in IDEA on code inspection.

**Comment by remojansen** [comment]
Will check out but I don't have IDEA, I'm going to upgrade the project to TypeScript 2.4 when it is released (probably next week).

**Comment by dagatsoin** [comment]
Do you see any inspection error in VS?
Because it could be IDEA which is using its bundled version of TS (which is 3.2.4 actually).

**Comment by remojansen** [comment]
@dagatsoin did some work this week on VS with the latest version of TS and I could not see any errors. Can you check this with the IDEA team, please?

**Comment by dagatsoin** [comment]
Sure, actual version of Idea use a version of TS < 2.4
No doubt it will erase the editor red lint when they will bring the 2.4.

Le 8 juil. 2017 à 23:42, Remo H. Jansen <notifications@github.com<mailto:notifications@github.com>> a écrit :


@dagatsoin<https://github.com/dagatsoin> did some work this week on VS with the latest version of TS and I could not see any errors. Can you check this with the IDEA team, please?

**Comment by ghost** [comment]
If you have typescript >= 2.4 installed you can update IDEA to point to the newer version rather than the bundled in the settings.
