### ISSUE TITLE
Rename all decorators in inversify-express-utils to lowercase

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#596]
This should be an easy code change so let's help someone that wants to contribute to open source but has never done it before :smile: 

We need to rename all [decorators in `inversify-express-utils`](https://github.com/inversify/inversify-express-utils) to lowercase:

- `Controller` -> `controller`
- `All` -> `all`
- `Get` -> `httpGet`
- `Post` -> `httpPost`
- `Put` -> `httpPut`
- `Patch` -> `httpPatch`
- `Head` -> `httpHead`
- `Delete` -> `httpDelete`
- `Method` -> `httpMethod`
- `Request` -> `request`
- `Response` -> `response`
- `RequestParam` -> `requestParam`
- `QueryParam` -> `queryParam`
- `RequestBody` -> `requestBody`
- `RequestHeaders` -> `requestHeaders`
- `Cookies` -> `cookies`
- `Next` -> `next`
- `Params` -> `params`

After renaming the decorators you can expect some of the unit tests to not compile because you will have to rename the decorators in [the unit tests](https://github.com/inversify/inversify-express-utils/tree/master/test) as well.

Instructions about how to contribute can be found [here](https://github.com/inversify/inversify-express-utils/blob/master/CONTRIBUTING.md).

**Comment by the-owl** [comment]
Unfortunately, it is not possible, because `delete` is a reserved word and it cannot be used as an identifer. Usage of `delete` decorator will require doing `import { delete as Delete } from 'inversify-express-utils'`

**Comment by remojansen** [comment]
@the-owl sorry about that! let's do the following then:

- `Post` -> `httpPost`
- `Put` -> `httpPut`
- `Patch` -> `httpPatch`
- `Head` -> `httpHead`
- `Delete` -> `httpDelete`
- `Method` -> `httpMethod`

I think the change in name is reasonable, for example in C# they use:

```csharp
[HttpGet]
public ActionResult Login() {
    return View();
}

[HttpPost]
public ActionResult Login(string userName, string password) {
    // do login stuff
    return View();
}
```
