### ISSUE TITLE
Missing release tags for versions after 1.0.2

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [inversify/InversifyJS#60]
Makes quite difficult tracking dependencies, basically the current package in npm is on 1.2.2 but you miss tag 1.2.2 (and anything lesser than that until 1.0.2)

Should be a good idea including at least the latest one to address it

**Comment by remojansen** [comment]
Hi @Fire-Dragon-DoL I just created a [new release](https://github.com/inversify/InversifyJS/releases/tag/v1.2.2). Thanks for reporting this issue :wink:
