### ISSUE TITLE
[inversify-restify-utils] Travis tests are failing on older node versions

### ISSUE THREAD

**Issue by theodesp** [inversify/InversifyJS#601]
I don't know if it's needed since it's my first contribution here but I've provided a simple fix for it so all Travis tests will pass. That will fix some other issues related to builds that are failing.
see [PR here](https://github.com/inversify/inversify-restify-utils/pull/62)

## Expected Behavior

When running Travis test they should all pass.

## Current Behavior

https://travis-ci.org/inversify/inversify-restify-utils/jobs/248936537

Travis Tests fail with the following error:
```
test/server.test.ts(39,30): error TS2345: Argument of type '{ additionalOptions: string; path: string; }' is not assignable to parameter of type 'RouteOptions'.
  Object literal may only specify known properties, and 'additionalOptions' does not exist in type 'RouteOptions'.
```

## Possible Solution

Add more explicit type for `RouteOptions`.

## Steps to Reproduce (for bugs)

1. Push a simple commit for the project
2. Go to travis page https://travis-ci.org/inversify/inversify-restify-utils/ and see the results
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile):
* Link to your project:
https://github.com/theodesp/inversify-restify-utils

# Stack trace

**Comment by remojansen** [comment]
Thanks again for this :+1: I have merged the PR :tada:

**Comment by theodesp** [comment]
Amazing work by the way. You are a God.

**Comment by remojansen** [comment]
Thanks :heart:  I'm just a human that drinks too much Redbull :wink:
