### ISSUE TITLE
Travis tests are failing due to latest update to tslint

### ISSUE THREAD

**Issue by dcavanagh** [inversify/InversifyJS#602]
tslint changed how it enforces the no-shadowed-variable 

## Expected Behavior
Should pass the travis-ci tests

## Current Behavior
Failing Travis tests

## Possible Solution
Refactor some code to remove shadowed variables
Mostly occurs in test files

## Steps to Reproduce (for bugs)
https://travis-ci.org/inversify/InversifyJS/builds/251113743

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by remojansen** [comment]
I have merged your PR :tada: thanks a lot for the fix 😄
