### ISSUE TITLE
Documentation for @postConstruct method decorator

### ISSUE THREAD

**Issue by theodesp** [inversify/InversifyJS#605]
## Expected Behavior

Since we merged  @postConstruct method decorator, it should be documented.
## Current Behavior

I cannot find documentation of  @postConstruct method decorator and how its used
## Possible Solution

We need to add a section in the wiki for @postConstruct
## Steps to Reproduce (for bugs)

1. Navigate to https://github.com/inversify/InversifyJS#the-inversifyjs-features-and-api
2. Try to find documentation for @postConstruct annotation
3. You won't find it
4.

## Context

Public documentation

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by remojansen** [comment]
@theodesp this is needed indeed, feel free to send a PR :+1:

**Comment by theodesp** [comment]
PR https://github.com/inversify/InversifyJS/pull/608

**Comment by theodesp** [comment]
Closed as it's been merged
