### ISSUE TITLE
Create angularjs 2.x example code

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#61]
It would be good to demonstrate how Inversify can be used in an angular (preferably [angular 2](http://angular.io)) as it will help people understand from a wider perspective the importance of DI.

**Comment by remojansen** [comment]
Hi @Jameskmonger an angular 2.0 example would be great! 

I'm not 100% sure about the current version fully working with angular 2.0 but I don't see why not. I would suggest to grab [the TodoMVC example](https://github.com/tastejs/todomvc/tree/master/examples/angular2) and modify it:
- [Split these two classes (Todo & TodoStore)](https://github.com/tastejs/todomvc/blob/master/examples/angular2/app/services/store.ts) in two files and declare their interfaces as well.
- [Inject TodoStore](https://github.com/tastejs/todomvc/blob/master/examples/angular2/app/app.ts#L12) using `@Inject`.
- [Bootstrap is the composition root](https://github.com/tastejs/todomvc/blob/master/examples/angular2/app/bootstrap.ts#L5) 

I'm not familiar with Angular 2.0 but I found the following in the documentation:

> When the app developer invokes bootstrap() with the root component MyApp as its argument, Angular performs the following tasks:
> - It uses the component's selector property to locate the DOM element which needs to be upgraded into the angular component.
> - It creates a **new child injector** (from the platform injector). Optionally, **you can also override the injector configuration for an app by invoking bootstrap with the componentInjectableBindings argument**.
> - It creates a new Zone and connects it to the angular application's change detection domain instance.
> - It creates an emulated or shadow DOM on the selected component's host element and loads the template into it.
> - **It instantiates the specified component**.
> - Finally, Angular performs change detection to apply the initial data providers for the application.

I took a quick look [it doesn't look easy to modify or replace](https://github.com/angular/angular/blob/master/modules/angular2/platform/browser.ts#L105). I don't know what would be better:
- Create our own angular bootstrap function
- Override the angular bootstrap function.

If we create our own bootstrap function we could release it as a package named inverisfy-angular or something similar and explain that it contains the inversify-angular bindings (something like the react-redux bindings...)

**Comment by remojansen** [comment]
Another good resource: http://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html

**Comment by remojansen** [comment]
Hi @Jameskmonger I asked for help at https://github.com/angular/angular/issues/6885 let's see what they answer...

**Comment by remojansen** [comment]
Closing this because it doesn't seem possible for now :( we should focus on 2.0 and all the other JS frameworks and Node.js for now. Once we get that done we should have time to focus on Angular 2.0 integration.

**Comment by ptitjes** [comment]
Hi @remojansen. Do you think this issue could be reopen now that 2.0 is way past ?
I would need some guidance on bridging Angular DI and Inversify.

My use case is the following:
I have an Ionic/Angular/Typescript client application and an Inversify/Node/Typescript server app that interact together and with a database. I'd like to factor out some service code common to both the client and server applications. So I was thinking of extracting a library out of them and using Inversify for DI in it. But then I would need to use that base service container inside Angular DI.

Any hints or advices ?

**Comment by remojansen** [comment]
Hi @ptitjes 

You can create a library that uses inversify internally. If you library exposed as a variable, you should be able to inject that variable into an angular component using the angular injector. 

It is important that you separate the angular and the inversify injectors in something like:

```ts
@injectable() // angular injectable not an inversify injectable
class Service {
    public container: Container;
    public constructor() {
        this.container = new Container();
    }
    doSomething() {
        const something = this.container.get("something");
        return something.doSomething();
    }
}
```

Angular will resolve `Service` and then inversify will resolve everything else on demand.

This is the only way I can think to integrate both because angular is very tightly coupled to its own IoC container. More info @ https://github.com/inversify/InversifyJS/issues/625#issuecomment-352122739

**Comment by ptitjes** [comment]
@remojansen OK. What I had in mind was more to inject the Inversify container in Angular and using providers to make the services accessible. But I still have to test the idea. Something along the lines of

```typescript
@NgModule({
  // ...
  providers: [
    InversifyContext,
    SomeCalledbackServiceInAngular,
    {
      provides: APP_INITIALIZER,
      deps: [InversifyContext, SomeCalledbackServiceInAngular],
      useFactory: (ctx: InversifyContext, s: SomeCalledbackServiceInAngular) => () => {
        ctx.container.bind<ICallbackService>(inversifyToken).toConstantValue(s)
      },
      multi: true,
    },
    inversifyProvided(MyService, MyService),
  ]
})
export class MyApp {
}

@Injectable()
export class InversifyContext {
  public container = new Container()
}

export function inversifyProvided(angularToken, inversifyToken) {
  return {
    provides: angularToken,
    deps: [InversifyContext],
    useFactory: (ctx: InversifyContext) => ctx.container.get(inversifyToken),
  }
}

@Injectable()
export class SomeCalledbackServiceInAngular implements ICalledbackService {
  // ...
}
```

where `ICalledbackService` and `MyService` are defined in my library.

**Comment by remojansen** [comment]
@ptitjes that could work. Let me know how do you get on and if it works we can create a page in the wiki documenting angular limitations and recipes.

**Comment by ptitjes** [comment]
OK, the following worked (also tested with Angular AOT).
A [plunker](https://plnkr.co/edit/jvVLeq?p=info) that demonstrates it.

ServiceA (in Angular) calls ServiceB (in Inversify) calls ServiceC (back in Angular).

```typescript
// To be in library 'mylib'

export function initContainer(s: AServiceC) {
  let container = new Container()
  container.bind<ServiceB>(ServiceB).toSelf()
  container.bind<AServiceC>(AServiceC).toConstantValue(s)
  return container
}

export abstract class AServiceC {

  greet(name: string): string {
    throw new Error('Not implemented')
  }
}

@injectable()
export class ServiceB {

  // The @inject is mandatory when build with Angular AOT removing the class @injectable ?
  // Don't know if it would be necessary in a real library
  constructor(@inject(AServiceC) private service: AServiceC) {
  }

  greet(name: string): string {
    return this.service.greet(name)
  }
}

// To be in the Angular application

@Injectable()
export class ServiceC extends AServiceC {

  greet(name: string): string {
    return `${name}, I'm your father!`
  }
}

@Injectable()
export class ServiceA {

  constructor(private service: ServiceB) {
  }

  greet(name: string): string {
    return this.service.greet(name)
  }
}

export const MyLibContainer = new InjectionToken<Container>('MyLibContainer')

@NgModule({
  // ...
  providers: [
    ServiceA,
    ServiceC,

    // Provider for the Inversify container from 'mylib'
    // Unfortunately, it is not possible to make a macro function due to the lambda.
    // That would fail with Angular AOT!
    {
      provide: MyLibContainer,
      deps: [ServiceC],
      useFactory: (s) => initContainer(s),
    },

    // Provider for ServiceB from 'mylib'
    // Unfortunately, it is not possible to make a macro function due to the lambda.
    // That would fail with Angular AOT!
    {
      provide: ServiceB,
      deps: [MyLibContainer],
      useFactory: (c: Container) => c.get(ServiceB),
    },
  ],
})
export class AppModule {
}
```
