### ISSUE TITLE
decorate third party classes not woking anymore

### ISSUE THREAD

**Issue by GiorgioZett** [inversify/InversifyJS#619]
Hi all.
I'm updating inversify from 3.1 to 4.3.
I had a new issue when decorate a third party class.

package.json working:
```
  "dependencies": {
    "config": "^1.26.1",
    "inversify": "^3.1.0",
    "inversify-binding-decorators": "^3.0.0",
    "reflect-metadata": "^0.1.10",
    "winston": "^2.3.1"
  }
```

packege.json not working:
```
  "dependencies": {
    "config": "^1.26.1",
    "inversify": "^4.3.0",
    "inversify-binding-decorators": "^3.0.0",
    "reflect-metadata": "^0.1.10",
    "winston": "^2.3.1"
  }
```

class declaration:
```
@ProvideNonInjectableAsSingleton(winston.Logger, Logger)
export class Logger extends winston.Logger {
```
annotation declaration:

```
export function ProvideAsSingleton(symbol): any {
  return provide(symbol).inSingletonScope().done();
}

export function ProvideNonInjectableAsSingleton(superSymbol, symbol): any {
   decorate(injectable(), superSymbol);
   return ProvideAsSingleton(symbol);
}
```

error:
`Error: Missing required @injectable annotation in: EventEmitter.`

If I use inversify 3.1 all works fine, when I use inversify 4.3 I have this error.
Any suggestion?
thanks!

**Comment by DrJonki** [comment]
~~Having the same problem.~~

Edit: Nevermind, was able to fix it by decorating the 3rd party base class using decorate().

**Comment by remojansen** [comment]
@GiorgioZett sorry for the very late reply on this. It looks like you are missing:

```ts
decorate(injectable(), EventEmitter);
```

We have unit tests for this feature and no one else has reported issues with it so my guess is that this is a configuration issue. I will close this issue but please feel free to ask more questions using the comments, creating a new issue or contacting us in the chat.
