### ISSUE TITLE
Instantiate a container with array of providers

### ISSUE THREAD

**Issue by amcdnl** [inversify/InversifyJS#623]
## Requirement
Currently to bind classes to a container you have to manually like:

```ts
var container = new Container();
container.bind<Samurai>(Samurai).toSelf();
```

Angular's DI system allows you to pass an array of providers to your container when you instantiate it.

```ts
import { ReflectiveInjector } from 'injection-js';
import { providers } from './providers';
import { App } from './app';

const injector = ReflectiveInjector.resolveAndCreate([...providers, App]);
export default injector.get(App).bootstrap();
```

You can work around this in inversify by doing:

```ts
[...providers, App].forEach(p => container.bind(p).toSelf());
```

But it feels kinda hacky. It would be nice to have this out of the box. This is helpful for reading out all the classes out of a barrel and creating a container for them.

**Comment by remojansen** [comment]
I understand your suggestion but this kind of promotes using classes as identifiers. We actually want to promote using interfaces and also we want to keep the main library as lightweight as possible. For this reasons, I will not add this to the core library but I will share with you some alternatives.

The helper you implemented doesn't feel hacky to me. I have actually recommended doing similar things in the past (See "Tip: Reducing boilerplate" [here](https://stackoverflow.com/questions/47700310/typescript-inject-and-arguments-in-class)).

I recommend you to use [inversify-binding-decorators](https://github.com/inversify/inversify-binding-decorators).

You can use [`@provide`](https://github.com/inversify/inversify-binding-decorators#using-classes-string-literals--symbols-as-identifiers) or you can use `autoProvide`:

You can have an index file that exposes all your entities:

```ts
export { default as Warrior } from "./warrior";
export { default as Katana } from "./katana";
```

Then create bindings for all of them automatically:

```ts
import * as entites from "../entities";

let container = new Container();
autoProvide(container, entites);
```

Please feel free to ask any questions. Thanks a lot for suggesting a feature and for using inversify.

**Comment by leohubert** [comment]
I succeed in doing what you want.


In entities.ts
```typescript
import Dom from "./services/Dom";
import Logger from "./services/Logger";

export default [
    Dom,
    Logger
]
```

In index.ts
```typescript
import "reflect-metadata";
import { Container, injectable } from "inversify";
import entities from "./entities";
import Dom from "./services/Dom";

let container = new Container();

@injectable()
class App {
    constructor(private dom: Dom) {
        console.log(dom);
    }

    lol(msg: string) {
        this.dom.test(msg);
    }
}

for(let entity of entities) {
    if (entity) {
        container.bind<any>(entity).toSelf().inSingletonScope();
    }
}

const dom = container.resolve(App);

dom.lol('THIS IS A TEST !');
```


Dom.ts
```typescript
import { injectable } from "inversify";
import Logger from "./Logger";


@injectable()
export default class Dom {
    constructor (private logger: Logger) {
    }

    test(msg: string) {
        this.logger.debug(msg);
    }
}
```

Logger.ts
```typescript
import { injectable } from "inversify";


@injectable()
export default class Logger {
    constructor () {
    }

    debug(msg: string) {
        console.log(msg);
    }
}

```
