### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by cntech** [inversify/InversifyJS#627]
The example code snippets in README.md could be improved:

- The "entities.ts" file is not mentioned but imported: `import { Ninja, Katana, Shuriken } from "./entities";`
- Interfaces are not imported in the "entities.ts" file.
- `TYPES` should be `const` (not `let`).
- Above `var ninja = myContainer.get<Warrior>(TYPES.Warrior);`, neither `TYPES` nor `Warrior` are imported; `var` should be replaced by `const`

**Comment by lholznagel** [comment]
Feel free to create a PR :)

**Comment by dcavanagh** [comment]
closing issue because PR was merged
