### ISSUE TITLE
inversify-express-utils default path

### ISSUE THREAD

**Issue by ajdnik** [inversify/InversifyJS#631]
I think it would be nice if there was a way to define a default path that is prepended through all controllers. 

## Expected Behavior
I would be great if there was an ability to define a default path when configuring a server and then that path would get prepended to all of the paths defined by controllers.

## Current Behavior
If you want to add versioning for example you would have to add `/v1` to every controller decorator call to achieve this.

## Possible Solution
I've already implemented a possible solution and added some unit tests. You can find the implementation [here](https://github.com/ajdnik/inversify-restify-utils/commit/53ef599d6d4928411a2aaabbd1d451bed5258a17). Essentially what I've done is extended `restify.ServerOptions` in a backwards compatible way so that you can supply `defaultRoot` parameter and change the default root from `/` to whatever you like.

## Context
Where this would be useful is when you're defining path version such as in the example provided above or for instance when you're writing microservices and are using URL load balancing to distinguish between them.

**Comment by lholznagel** [comment]
I think this is a good idea. :+1: Feel free to create a PR, happy to review it

**Comment by ajdnik** [comment]
Since the feature was implemented and [PR](https://github.com/inversify/inversify-restify-utils/pull/72) was merged I will close the issue.
