### ISSUE TITLE
inversify-restify-utils injecting middleware

### ISSUE THREAD

**Issue by ajdnik** [inversify/InversifyJS#635]
I think it would be a good idea to add a way to inject middleware into controllers using inversify. Inversify Express Utils already has something [similar](https://github.com/inversify/inversify-express-utils/pull/35) and I think it makes sense to add it to Restify Utils.

## Expected Behavior
Instead of defining middleware like so:
```ts
@Get('/hello', (req: restify.Request, res: restify.Response, next: restify.Next) => {})
```
We could define them like so:
```ts
const handler = Symbol('handler');
// ...
container.bind<restify.RequestHandler>(handler).toConstantValue((req: restify.Request, res: restify.Response, next: restify.Next) => {});
// ...
@Get('/hello', handler)
```
## Current Behavior
Currently there is no way to inject middleware using IOC.

## Possible Solution
I think the approach that Express Utils used is a good one and if it's OK I can implement a Restify version.

## Context
I think the benefits of adding IOC support to middleware shows when it comes to code maintainability and code testing.

**Comment by mitjarogl** [comment]
👍

**Comment by mindhacker42** [comment]
👍

**Comment by lholznagel** [comment]
Feel free to create a PR :)

**Comment by mitjarogl** [comment]
@remojansen This issue has been resolved. Can you please build npm package inversify-restify-utils so new updates will be available. Thanks :)
