### ISSUE TITLE
inversify-restify-utils is not calling next() after res.send(result)

### ISSUE THREAD

**Issue by premchelliah** [inversify/InversifyJS#636]
inversify-restify-utils is not calling next() after res.send(result)

According to Restify documentation and forums, looks like the 'after' event will fire only if next() is called. See link for more details https://github.com/restify/node-restify/issues/416

Tested by adding a next() call in https://github.com/inversify/inversify-restify-utils/blob/master/src/server.ts and the 'after' event is getting emitted.

Env ( inversify 4.3.0, inversify-restify-utils 3.2.0, restify 6.0.1 and node 8.5 )

Let me know if you need any other info or if there is a better way to get the 'after' event emitted. 

Thanks!
Prem

**Comment by dcavanagh** [comment]
https://github.com/inversify/inversify-restify-utils/pull/101
