### ISSUE TITLE
No return should be return a 204 

### ISSUE THREAD

**Issue by mbayou** [inversify/InversifyJS#637]
Hi all, 
I want to create a resource PUT for update an object and I didn't want to return anything or pass to my method the response object.
## Expected Behavior

I create a method who return void (or Promise<void>) and when code finish, I want to get a 204 status code from my server.

## Current Behavior

When I create a method who return a void (or Promise<void>) and I call it, I didn't get any response.

## Steps to Reproduce (for bugs)

1. create controller
2. create method (PUT for example)
3. configure return type to void
4. execute some code and try to call it you will never get any response

## Your Environment

* Version used: 3.3.0 (inversify) 3.5.2 (inversify-express-utils)
* Environment name and version : nodeJS 8.1.2
* Operating System and version (desktop or mobile): MacOSX Sierra

**Comment by lholznagel** [comment]
Hey,
sorry to say but this is really not an inversify issue. If you want to return 204 you need to return it by yourself.

**Comment by mbayou** [comment]
I know but I propose an enhancement. 
By default inversify return 200 if all is ok. But when I don't return anything I think is better if inversify return by default a 204 to correspond to http code, and if I want a specific return we can set a custom code.

**Comment by lholznagel** [comment]
Status code 200 is the default behavior of express.
Inversify-express-utils is like it says just a util for working with inversify. We should not change the default behavior or do something else that has nothing to do with us, in my opinion.

**Comment by mbayou** [comment]
Ok I understand, I thought inversify manage some behaviors. So If you think it's really impossible I'll try to talk about that with express people. 

Thanks for your responses ;)
