### ISSUE TITLE
inversify-express-utils decorator type declarations throwing errors

### ISSUE THREAD

**Issue by Josh-ES** [inversify/InversifyJS#642]
## Current Behavior

Currently, the decorators exported via the inversify-express-utils package throw an error similar to the following:

![screenshot 2017-10-14 08 26 05](https://user-images.githubusercontent.com/2118803/31573728-9155260e-b0b9-11e7-8e8b-8c1b834debdf.png)

The TypeScript compiler throws the error:

```bash
error TS1241: Unable to resolve signature of method decorator when called as an expression.
```

## Expected Behavior

Use of the decorators from the package should not throw an error when applied to a controller class method.

## Steps to Reproduce (for bugs)

1. Use TypeScript v2.5.3 or higher.
2. Create a controller class, following the documentation given in the README of the [inversify-express-utils repo](https://github.com/inversify/inversify-express-utils)
3. Apply an `httpGet`, `httpPost` etc. decorator to a controller class method
4. The TypeScript transpiler should throw an error.

**Comment by dcavanagh** [comment]
@Josh-ES 
The `@httpPut` function is looking for an `express.RequestHandler` as its second input. This is used as express middleware.
the type signature of `express.RequestHandler` is 
`(req: Request, res: Response, next: NextFunction): any;`

the value that you are passing is not a function it is the return value of `passport.authenticate`

the way that I handle this is to have a separate middleware function

```
function authenticationMiddleware(req: Request, res: Response, next: NextFunction) {
    passport.authenticate(....);
}

@httpPost("/", authenticationMiddleware)
...
```
