### ISSUE TITLE
express-utils add decorator for router.param

### ISSUE THREAD

**Issue by r0bnet** [inversify/InversifyJS#646]
## Expected Behavior
An express router has a param method which will be called automatically when there is a specific request parameter in the url template. Method is described here: http://expressjs.com/de/4x/api.html#router.param
This is very useful if you need to get an object (e.g. an entity). Then you can use this function to describe the behaviour in one single place and don't need to repeat yourself.

I have an example from an old project where i didn't use inversify or express-utils.

**customerRoutes.js**
```js
const express = require('express');
const router = express.Router();
const CustomerCtrl = require('../controllers/CustomerCtrl');

router.param('id', CustomerCtrl.getCustomerById);

router.get('/:id', CustomerCtrl.getCustomer);
router.get('/:id', CustomerCtrl.getCustomer);
router.put('/:id', CustomerCtrl.editCustomer);
router.get('/:id/serviceconfigs', CustomerCtrl.getServiceConfigs);
...
```

**CustomerCtrl.js**
```js
const Customer = require('../models/Customer');

exports.getCustomerById(req, res, next, id) {
  Customer.findOne({ id: id })
    .then(customer => {
      if (!customer) {
        return res.sendStatus(404);
      }

      req.customer = customer;
      return next();
    })
    .catch(next);
}

exports.getCustomer(req, res, next) {
    const customer = _.omit(req.customer.toObject(), ['_id', '__v']);
    res.json(customer);
}
...
```
There is one place which is responsible for handling getting the entity and in subsequent http methods i can use req.customer where the object already is available.

## Current Behavior
Not implemented yet. Until now you have to do the same work in every route when you have a param in your route.

## Possible Solution
Probably a new decorator which can be used to encapsulate the param method in an own controller function (like any http method).

## Context
DRY principles and common scenario handling.

## Your Environment
* Version used: inversify 4.3.0, express-utils 4.0.1

**Comment by robertmain** [comment]
@r0bnet are you using this for express routing also? I'm trying to do something similar, I think - except that I'm using decorators to set-up my routes along these lines: https://spring.io/guides/gs/rest-service/#_create_a_resource_controller

**Comment by r0bnet** [comment]
@robertmain i think i don't get your question? I use router.param in some other projects but i don't see the connection to the link you posted.

**Comment by robertmain** [comment]
I was asking if you wrote the decorators you're using in your code example, or if express provided them. 

I'm trying to build something similar to the way SpringMVC does things with decorators so I was going to ask you how you were doing things. However, I found a package on npm that does what I was after - don't worry about it :)

**Comment by dcavanagh** [comment]
@r0bnet I think what you are looking for is the `@requestParam` decorator
```
@httpGet('/:id')
public getStuffById(@requestParam('id') id: string) {}
```
@robertmain the decorators are part of the Inversify express utils

**Comment by robertmain** [comment]
@AltekkeE oh cool - thanks :)

**Comment by r0bnet** [comment]
Sorry that i didn't respond earlier.

@AltekkeE  that is not what i meant. I know that feature you mentioned but what i'm looking for is another functionality that enables you to define one middleware function that is called on each route that contains a specific variable (like id in my example above). And it will be called before the route function is called.
This is helpful for instance if you need to receive an object from a database and if that object does not exist the middleware will already end the chain and respond with a 404. If the object is found you can bind it to the request object so that it can be used in subsequent middleware (e.g. the route function/middleware).

**Comment by remojansen** [comment]
@r0bnet you can still use traditional express middleware. For example, [here](https://github.com/inversify/inversify-express-example/blob/master/MongoDB/bootstrap.ts#L33-L34) we use the helmet and `bodyParser` `middleware`. You could add path specific middleware like for example:

```ts
app.use("/public", express.static("public"));
```

You could ofcourse, create your own just like in a traditional express app:

```ts
app.use("/public", (req, res, next) => {
  console.log('Time:', Date.now())
  next()
});
```
