### ISSUE TITLE
Using Inversify to do a Multiinject of a class with constant and injected parameters

### ISSUE THREAD

**Issue by prsmith1** [inversify/InversifyJS#650]
Hi,

I'm trying to use Inversify to do a multiinject but the class being multi-injected requires both an injected parameter and a number parameter. How do I do this?

Please see: https://stackoverflow.com/questions/46846883/using-inversify-to-do-a-multiinject-of-a-class-with-constant-and-injected-parame

Thanks

**Comment by remojansen** [comment]
Hi, thanks for asking the question. I have answered this in SO.
