### ISSUE TITLE
Undefined @inject() properties in child class from factory

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [inversify/InversifyJS#655]
Given a parent class and a child class that are both `@injectable()` with an `@inject()` member each...

```typescript
@injectable()
export abstract class ParentStore {
    @inject(TYPES.StoreFactory)
    protected readonly storeFactory: StoreFactory;
}
```

```typescript
@injectable()
export class ChildStore extends ParentStore {
    @inject(TYPES.Logger)
    public readonly logger: Logger;
}
```

...and a class that creates new instances of the `ChildStore` using an Inversify `Container`...

```typescript
export class StoreFactory {
    public constructor(private readonly container: Container) { }

    public create(): ChildStore {
        return this.container.get<() => ChildStore>(TYPES.ChildStore)();
    }
}
```

...and a main that binds `ChildStore` to a simple factory method...

```typescript
const container = new Container();

container.bind(TYPES.Logger).to(Logger);
container.bind(TYPES.StoreFactory).toConstantValue(new StoreFactory(container));
container
    .bind(TYPES.ChildStore)
    .toFactory(
        () =>
            () => new ChildStore());

const storeFactory = new StoreFactory(container);
const childStore = storeFactory.create();

childStore.logger.log("Why am I undefined?");
```

## Expected Behavior

...when we create a new `ChildStore` instance, we expect that the `logger` should be injected.

## Current Behavior

It's `undefined` instead.

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/JoshuaKGoldberg/inversiwat && cd inversiwat && npm i && tsc`
2. `node lib/index.js`

## Context

In a more complex application, the goal is to allow the factory to create different child stores depending on POJO models passed into the factory (see [an earlier inversiwat commit](https://github.com/JoshuaKGoldberg/inversiwat/commit/ec36378cae3156ba8f24390fb52be4c96659ddb6)). Stores can then create child stores dynamically using DI based on their models. 

## Your Environment
* Version used: `4.3.0`
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node `8.0.0`
* Operating System and version (desktop or mobile): Windows 10 Desktop
* Link to your project: https://github.com/JoshuaKGoldberg/inversiwat

**Comment by sleepysort** [comment]
This is expected. Inversify will resolve dependencies when objects are instantiated via the container. In this case, the factory method that you are binding here:
```javascript
container
    .bind(TYPES.ChildStore)
    .toFactory(
        () =>
            () => new ChildStore());
```
is creating a `ChildStore` via its constructor, instead of through the container. What you want is probably:
```javascript
// Bind the ChildStore class
container.bind(TYPES.ChildStore).toFactory(ChildStore);

// Bind the factory
container
    .bind(TYPES.ChildStoreFactory)
    .toFactory(
        () =>
            () => container.get(TYPES.ChildStore));
```

**Comment by JoshuaKGoldberg** [comment]
Thanks so much @sleepysort!
