### ISSUE TITLE
 Update inversify-restify-utils NPM package

### ISSUE THREAD

**Issue by DServy** [inversify/InversifyJS#660]
Right now, the current READ.MD hints at features that would be extremely beneficial, mainly surrounding middleware injection. Currently there is no good way to implement these via NPM through targeting the master branch. Would love to have the NPM package updated to incorporate this.

**Comment by remojansen** [comment]
Thanks for sharing your interest in the project. I just released `inversify-restify-utils@3.3.0`. I'm closing this issue.
