### ISSUE TITLE
Not compiling after adding "types": ["reflect-metadata"] to tsconfig.json

### ISSUE THREAD

**Issue by ouranosv** [inversify/InversifyJS#667]
After installing inversify I added the below lines to tsconfig.json

"lib": ["es6"],
"types": ["reflect-metadata"],
"experimentalDecorators": true,
"emitDecoratorMetadata": true

But the code does not compile and the errors i get are:
Cannot find name 'require'
Cannot find module 'http'
Cannot find namespace 'NodeJS'
etc

The line that causes the problems is 
"types": ["reflect-metadata"] 

I have typescript 2.5.3 installed.
What should i do to solve this?

**Comment by remojansen** [comment]
Looks like you are missing:

```
npm install @types/node
```

The require and http modules are not used by InversifyJS so this is likely not to be a problem with InversifyJs.

**Comment by ouranosv** [comment]
Thanks for your answer.
I already have types/node installed, so this is not the problem.
Any other ideas?

**Comment by remojansen** [comment]
the reflect-metadata.d.ts file is included in the npm module. Have you installed reflect metadata:?

> npm install reflect-metadata

**Comment by ouranosv** [comment]
Yes, i have already installed it. I followed the install instructions as mentioned on the site.

**Comment by remojansen** [comment]
Sorry for not being able to help you. The only thing I can recommend is to maybe start with the basic example as project template? https://github.com/inversify/inversify-basic-example

**Comment by amc6** [comment]
I ran into something similar. It looks like adding the line `"types": ["reflect-metadata"]` causes typescript to ignore all other types defined in the node_modules/@types directory. https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

My solution was just to leave that line off. I've gotten the basic example from the README up and running. So hopefully that line is unneeded and this won't come back to bite me down the road.

**Comment by remojansen** [comment]
This is strange, I have a few projects with `"types": ["reflect-metadata"]` and it has never been a problem.

**Comment by amc6** [comment]
I'm also on typescript 2.5.3 if that matters. I set the project up with create-react-app and microsoft's react-scripts-ts. So its possible that has configured something in some non-standard way that is causing this.  ¯\\\_(ツ)_/¯

`create-react-app my-app --scripts-version=react-scripts-ts`
