### ISSUE TITLE
Update inversify-restify-utils Controller example in READ.MD

### ISSUE THREAD

**Issue by DServy** [inversify/InversifyJS#668]
Update READ.MD to more accurately reflect how to import Restify types to prevent `AssertionError [ERR_ASSERTION]: Constructor already exists!` Restify error on startup. 

Currently importing Restify via `import * as Restify from 'restify'` in a controller causes a `inversify-restify-utils` error

**Comment by remojansen** [comment]
Merged :tada: Thanks for the PR :+1:
