### ISSUE TITLE
Fix 1.3.0 npm download

### ISSUE THREAD

**Issue by RichardJECooke** [inversify/InversifyJS#67]
I upgraded to 1.3.0 using **npm update** to try finally get the class decorators to work, but it seems now it doesn't download the actual .js \ .ts files, it downloads only typings.

![Screenshott](http://s29.postimg.org/cx6rucs6v/Untitled.png)

**Comment by harper84** [comment]
Richard, I think this was fixed in 1.3.1; it was spotted soon after release. Class decorators appear to be working now.

**Comment by remojansen** [comment]
@harper84 @RichardJECooke Hi guys sorry about the problems with the last few releases we have been working on a few things to avoid this kind of problems. For example the last PR #66 ensures that unit tests and build work before publishing to npm. 

We will continue to work to ensure that you can trust the library for production usage please let us know any kind of concerns.
