### ISSUE TITLE
Question: Container is not available in TS

### ISSUE THREAD

**Issue by krysalead** [inversify/InversifyJS#671]
hi,

When following the tutorial on github home page, I have to include the Container from inversify

`import { Container } from "inversify";`

But the Container interface is not available on inversify.ts and I have this compilation issue

## Expected Behavior
There is no build issue following the documentation

## Current Behavior
`server/index.ts(9,33): error TS2339: Property 'Container' does not exist on type 'typeof "/node_modules/inversify/dts/inversify"'.`

## Your Environment
* Version used: 2.0.0-rc.14
* Environment name and version (e.g. Chrome 39, node.js 5.4): Nodejs 6.11.1
* Operating System and version (desktop or mobile): Windows 7 Desktop

**Comment by remojansen** [comment]
You are using a very old not supported version (`2.0.0-rc.14`) the current version is `4.5.1` also the node version (5.4) is quite old the latest version is 9.0.

The following works but you will need to upgrade both node and inversify:

```ts
import { Container, interfaces } from "inversify";

const container: interfaces.Container = new Container();
```
