### ISSUE TITLE
Rename 2.0.0-alpha.0 to 2-alpha.0.0

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#68]
`2.0.0-alpha.0` is not correct semantic versioning.

We should instead use `2-alpha.0.0` as we are in the alpha stage of version 2.

**Comment by Jameskmonger** [comment]
It appears that npm is not happy with appending `alpha` to anything other than the last part of the version.. how about `2.0.0-alpha` rather than `2.0.0-alpha.0`?

**Comment by tenowg** [comment]
Can you give me a link that say that it is not correct, just curious as I have always seen the current (2.0.0-alpha.0) as the correct semantic versioning.

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

from the semvar documentation

**Comment by remojansen** [comment]
Hi guys based on [this](https://docs.npmjs.com/misc/semver#prerelease-tags) and [this](http://semver.org/#spec-item-9) the current semver version `2.0.0-alpha.0` should be correct. I still working on the first release of 2.0 I'm sorry it is takings so long but I have very limited free time at the moment :( I think I have 70% done more or less I will keep you updated.

**Comment by Jameskmonger** [comment]
No problem @tenowg and @remojansen .

After looking into the semantic versioning documentation I am happy that `2.0.0-alpha.0` is valid semantic versioning. It seemed odd to have the `alpha` modifier on the patch version rather than the major version (as we are working on the `alpha` release of version 2).

However after looking into the documentation, I can see that `2.0.0-alpha.0` is correct semantic versioning.

Closing this issue - thanks guys! :thumbsup:
