### ISSUE TITLE
Can't decorate and then `getAll` using custom decorator

### ISSUE THREAD

**Issue by svallory** [inversify/InversifyJS#686]
I'm creating a wrapper around Hapi that integrates inversify so controllers and endpoints can be registered using annotations. I created a decorator to register a controller in inversify. Here is the code:

```
export const Controllers = Symbol.for('cashfarm.tractor.controllers');

export function Controller(target: ConcreteType<any>) {
  try {
    debug(`Providing ${target.name} controller`);
    provide(Controllers)(target);
  }
  catch (e) {
    throw new Exception(`Error decorating controller ${target.name}: ${e.message}`);
  }
}
```

But when I try to get the registered controllers, I get the error: `Missing required @injectable annotation in: NotFoundCtrl.`

If I try to add `@injectable()` to the class declaration, I get the exception that I'm trying to decorate the class twice.

I tried with  inversify 3.3 and 4.5.1 and it failed on both, so I think the problem is in my code.

*How can I debug the `injectable` check so I figure out what's going on?*

## Expected Behavior
I get an array of controller instances

## Steps to Reproduce (for bugs)

Honestly there is a lot of code in the project, I'll deploy it to the repo (it's open source anyway) and update here.

## Context
All I want to do is register many controllers to my `Controllers` symbol and then use `container.getAll(Controllers)` to retrieve them.

## Your Environment
Version used: 3.3.0 and 4.5.1
Env: Node 8.9.1
OS: OSX

# Stack trace
Not a stack trace, just a debug log of the bindings:
```
  tractor:ioc Container (d413f36d-3baa-0af2-de27-38bddeff0a1b) bindings so far +345ms
  tractor:ioc 0 Symbol(cashfarm.plow.controllers) => Transient Instance NotFoundCtrl +1ms
  tractor:ioc 1 Symbol(cashfarm.plow.controllers) => Transient Instance MetaCtl +1ms
  tractor:ioc 2 Symbol(@cashfarm/tractor.IRouter) => Transient ConstantValue Binding +0ms
  tractor:ioc 3 ApiPrefix => Transient ConstantValue "/orgs/v1" +0ms
  tractor:ioc 4 Symbol(IEventBus) => Singleton Instance EventBus +0ms
  tractor:ioc 5 Symbol(@cashfarm/plow.ICommandBus) => Singleton Instance CommandBus +0ms
```

**Comment by remojansen** [comment]
Hi, thanks for reporting this issue. I was unable to reproduce this issue. I was able to run the following code snippet without issues:

```ts
import { Container } from "inversify";
import { makeProvideDecorator } from "inversify-binding-decorators";
import "reflect-metadata";

const container = new Container();
const provide = makeProvideDecorator(container);

export const Controllers = Symbol.for("cashfarm.tractor.controllers");

export function Controller(target: any) {
  try {
    console.log(`Providing ${target.name} controller`);
    provide(Controllers)(target);
  } catch (e) {
    throw new Error(`Error decorating controller ${target.name}: ${e.message}`);
  }
}

@Controller
class Controller1 {
    public id = "Controller1";
}

@Controller
class Controller2 {
    public id = "Controller2";
}

const controllers = container.getAll(Controllers);

console.log(controllers);

/*
[
    Controller1 { id: 'Controller1' },
    Controller2 { id: 'Controller2' }
]
*/
```

Can you please check my example and find out if you are doing something different? Can you also please check that you are importing "reflect-metadata" only one time in your entire application?

**Comment by svallory** [comment]
Hi @ remojansen, thank you for the quick reply. As I suspected, the problem is somewhere in the project, the decorator is fine. I created a simple example later yesterday and could not reproduce the issue either.

What I actually want here is tips on how to find the issue. Something like "Check the metadata key FOO on the controller" or "active `debug("inversify:injecting")`" I don't know... I've spend around 10 hours on this and can't find the problem.

In my case, the contianer is instantiated in `@cashfarm/plow` (as a real singleton [here](https://github.com/cashfarm/plow/blob/v0.4/src/container.ts), then imported, [configured](https://github.com/cashfarm/tractor/blob/master/src/container.config.ts) and exported by `@cashfarm/tractor` (the hapi wrapper) and imported and further configured by the actual project

**Comment by svallory** [comment]
Ok, I just posted the message before so the scenario where the bug appears is clear. As I published the projects so other people could reproduce the bug, it disappeared.

My only guess is that it has something to do with using a container in linked modules. As I can not debug further and add more information, I'm closing this issue. Thank you for the help @remojansen!

**Comment by remojansen** [comment]
No problem @svallory the metadata keys can be found at [`/src/constants/metadata_keys.ts`](https://github.com/inversify/InversifyJS/blob/master/src/constants/metadata_keys.ts).  You can see [here](https://github.com/inversify/InversifyJS/blob/master/src/annotation/injectable.ts#L12) the one used by `@injectable`. So you should be able to try:

```ts
Reflect.hasOwnMetadata("design:paramtypes", target)
```

If it returns `false` it means that it is missing the `@injectable` annotation or that the metadata has been deleted. The metadata is deleted for example when "reflect-metadata"  is imported.

**Comment by svallory** [comment]
Sheeeet! That info about reflect-metadata is really surprising. I had no idea that importing it would delete the metadata. That's really a problem. No library can include an import for it then. Thank you for that, I'll check my OS projects

**Comment by remojansen** [comment]
@svallory yes, that is why `inversify` or `inversify-express-utils` doesn't import it automatically.
