### ISSUE TITLE
Error handling: loosing stacktrace

### ISSUE THREAD

**Issue by jsamr** [inversify/InversifyJS#688]
In the [factoryWrapper](https://github.com/inversify/InversifyJS/blob/aabe43c79475f388d25fb55cb448d355fbe2b18e/src/syntax/binding_to_syntax.ts#L24) function, an error is thrown with caught `error.message`, loosing stacktrace information.
I suggest instead re-throwing the error.

**replace** (src/syntax/binding_to_syntax.ts#L24)
``` typescript
 throw new Error(error.message);
```

**with**  (src/syntax/binding_to_syntax.ts#L24)
``` typescript
 throw error:
```

**Comment by remojansen** [comment]
Hi @sveinburne thanks for reporting this issue. Would you like to send a PR?

**Comment by jsamr** [comment]
@remojansen I have spotted other occurrences of this pattern (`throw new Error(error.message)`).
Are you OK that I dig further and replace'em all in a PR ?

**Comment by remojansen** [comment]
Yes that should be OK :+1:

**Comment by remojansen** [comment]
@sveinburne I just released 4.5.2 🎉

**Comment by jsamr** [comment]
@remojansen Thanks a lot for your reactivity !
