### ISSUE TITLE
Facing issue with typeorm connection

### ISSUE THREAD

**Issue by babbarankit** [inversify/InversifyJS#690]
Even after spending hours and repeatdly studying the same docs, I am still not sure how to do it :-(
Can you please provide some copy-paste-documentation :-)
Thanks.

**Comment by remojansen** [comment]
Hi @babbarankit, do you have a sample repo? Can you provide some details about the error and stack, please? Thanks!

**Comment by babbarankit** [comment]
```
type DbConnectionProvider = () => Promise<Connection>;
container.bind<Connection>(SERVICE_IDENTIFIERS.DbClient).to(Connection).inSingletonScope();
container.bind<DbConnectionProvider(SERVICE_IDENTIFIERS.DbClientProvider).toProvider<Connection>((context) => {
  return async () => {
    const connection : Connection = await createConnection();
    return connection;
  };
});

```

I am trying to then use it in

```
@Injectable()
@EntityRepository(UserEntity)
export class UserRepository  {
  public constructor(
    @inject(SERVICE_IDENTIFIERS.DbClientProvider) private provider: DbConnectionProvider) {}
    add(input: IUserInput) : Promise<IUserPayload> {
      //What to do to save? how to access the db??
    }
}
```
I wish to then use it create/save/edit users using this repositry. I am not clear about my approach.

**Comment by babbarankit** [comment]
I just created a DB Connection in my index file and then used `getConnection()` from `typeorm` in constructor of user repository and my work got done!
I am still not convinced though if its right way.  will be grateful for a right advice :-)
(or Feel, free to close the issue)
Thanks.

**Comment by remojansen** [comment]
Hi @babbarankit your solution sounds good I have never used typeorm but If I have time I will try to create an official typeorm + inversify-express-utils example 👍
