### ISSUE TITLE
Can't set up inversify express route classes with angular universal

### ISSUE THREAD

**Issue by FriOne** [inversify/InversifyJS#693]
I have import controller [here](https://github.com/FriOne/ng-universal-with-socket-io/blob/inversify-inject/server/app.ts) 

## Expected Behavior
My app have route app/test

## Current Behavior
It doesn't

## Steps to Reproduce (for bugs)
My repo is [here](https://github.com/FriOne/ng-universal-with-socket-io/blob/inversify-inject)
1. npm i
2. npm run build:ssr
3. npm run serve:ssr
4. Console will show error

## Context
I'm trying to make server with goo DI :)

## Your Environment
Node: v8.9.1
OS: Ubuntu 16

**Comment by FriOne** [comment]
Ok, I understood, ngExress engine should be moved after inversify server build.

**Comment by remojansen** [comment]
Sorry for the late reply, glad you found a solution!
