### ISSUE TITLE
how ca i use inversify without using InversifyExpressServer 

### ISSUE THREAD

**Issue by kiranagre** [inversify/InversifyJS#702]
Hi Remo,

In Basic example is also using inversify-express-utils.

why we have to put container in InversifyExpressServer while starting the server.

**Comment by lholznagel** [comment]
The example you looked at is from `inversify-express-utils`. That is an extra for inversify to help building express applications.

If you just want to use inversify, take a look at the readme of this repo, where an example is given. These are just plain inverify and no express is involved.

**Comment by remojansen** [comment]
Hi @kiranagre we have two examples:

- **Without inversify-express-utils** :point_right: https://github.com/inversify/inversify-basic-example
- **With inversify-express-utils** :point_right: https://github.com/inversify/inversify-express-example

**Comment by remojansen** [comment]
Hi @kiranagre I'm closing this issue. Feel free to ask questions using the comments or the chat.
