### ISSUE TITLE
Restore and inSingletonScope behavior

### ISSUE THREAD

**Issue by rostislavprovodenko** [inversify/InversifyJS#715]
## Expected Behavior
Injecting a singleton value after container.restore() reinitializes it.

## Current Behavior
Singleton values should be cached and not initialized twice.

## Steps to Reproduce (for bugs)
var inversify = require("inversify");
require("reflect-metadata");

const container = new inversify.Container();

container.bind('bla').toDynamicValue(() => {
    console.log('------initializing------');
    return 'bla';
}).inSingletonScope();

container.get('bla');
container.get('bla');

console.log('---------snapshot and restore---');

container.snapshot();
container.restore();

container.get('bla');
container.get('bla');

Gives the following output:

------initializing------
---------snapshot and restore---
------initializing------

Whereas I would expect to get the following result:

------initializing------
---------snapshot and restore--

## Context
We have some singletons that require additional initialization outside the toDynamicValue function (to avoid circular dependencies). After the restore method is called and a singleton is injected again the additional initialization should be run again, which is undesirable. I looked at the inversify code and it seems that singleton values should be preserved across restores, but they are not.

**Comment by nicolasgramlich** [comment]
A sidenote if it helps debugging, the (unexpectedly) reinitialized singletons also don't have their constructor parameters or attributes re-injected.

**Comment by zontafil** [comment]
the problem is in binding.ts, line 62.

The snapshot function will clone all the singletons and set them to not activated.

Probably in the clone function there should be a check whether the class is a singleton? (I'm new to inversify.js, I don't have any idea)

**Comment by remojansen** [comment]
Hi, I will try to fix this as soon as I can but it might take me some time because I'm currently under pressure trying to finish my upcoming book (http://www.learningtypescript.com/). The problem as @m3l7 says is that we don't share the singletons. We did this because we didn't want to deep-clone the cached instances. I would like to achieve this without external dependencies which means that we are going to need a custom deep-clone function. If someone wants to send a PR it would be very welcome.

**Comment by zontafil** [comment]
@remojansen I've made a PR with a possible solution. Not sure if I took the correct approach though

**Comment by zontafil** [comment]
yeah, actually I didn't check if the instance gets copied or not. Probably the PR is completely wrong

**Comment by SylvainEstevez** [comment]
@remojansen Any news on this one? Snapshots are a awesome for tests, but if I can't use them with singletons (think database instances for examples), then I'm afraid I'm can't use them at all, which removes a good part of DI benefits :(

**Comment by JannesV** [comment]
@remojansen still no progress?

**Comment by Pedrock** [comment]
There is already a PR for fixing this, thanks to @tonyhallett. Any reason for this not to have moved forward? The library seems to not have any recent activity.

**Comment by baptLesta** [comment]
@remojansen Any updates?
