### ISSUE TITLE
NFR: introduce autoinject binding for TypeScript

### ISSUE THREAD

**Issue by cyberhck** [inversify/InversifyJS#722]
When we use experimental decorator and emit metadata for TypeScript, we can use reflection to get the type of property/method/parameters etc.

Aurelia framework has really nice [dependency injection](http://aurelia.io/docs/fundamentals/dependency-injection#injection) decorator called `autoinject` available for TypeScript users. While doing that, one can just do a `@autoinject` and it'll automatically inject the instance.

I'd like to see that happen in InversifyJS. I'm willing to create a PR if someone guides me to it. Since I don't know anything about InversifyJS' architecture.

**Comment by remojansen** [comment]
Hi @cyberhck thanks for the suggestion. 

We are already using the emitted metadata and have a similar behavior.

In the aurelia example:

```ts
import {CustomerService} from 'backend/customer-service';
import {CommonDialogs} from 'resources/dialogs/common-dialogs';
import {EventAggregator} from 'aurelia-event-aggregator';
import {autoinject} from 'aurelia-framework';

@autoinject
export class CustomerEditScreen {
  constructor(private customerService: CustomerService, private dialogs: CommonDialogs, private ea: EventAggregator) {
    this.customer = null;
  }

  activate(params) {
    return this.customerService.getCustomerById(params.customerId)
      .then(customer => this.customer = customer)
      .then(customer => this.ea.publish('edit', customer));
  }
}
```

The entities injected are all classes: 'CustomerService', 'CommonDialogs' and 'EventAggregator'.

When you use classes you can do the following in InversifyJS:

```ts
import {CustomerService} from 'backend/customer-service';
import {CommonDialogs} from 'resources/dialogs/common-dialogs';
import {EventAggregator} from 'aurelia-event-aggregator';
import {injectable} from 'inversify';

@injectable()
export class CustomerEditScreen {
  constructor(private customerService: CustomerService, private dialogs: CommonDialogs, private ea: EventAggregator) {
    this.customer = null;
  }

  activate(params) {
    return this.customerService.getCustomerById(params.customerId)
      .then(customer => this.customer = customer)
      .then(customer => this.ea.publish('edit', customer));
  }
}
```

```ts
container.bind<CustomerEditScreen>(CustomerEditScreen).toSelf();
container.bind<CustomerService>(CustomerService).toSelf();
container.bind<CommonDialogs>(CommonDialogs).toSelf();
container.bind<EventAggregator>(EventAggregator).toSelf();
```

You only need the `@inject` annotations if you use interfaces:

```ts
import {ICustomerService, ICommonDialogs, IEventAggregator} from './interfaces';
import {injectable} from 'inversify';

@injectable()
export class CustomerEditScreen {
  private customerService: ICustomerService;
  private dialogs: ICommonDialogs;
  private ea: IEventAggregator;
  constructor(
     @inject("ICustomerService") customerService: ICustomerService,
     @inject("ICommonDialogs") dialogs: ICommonDialogs,
     @inject("IEventAggregator") ea: IEventAggregator
  ) {
    this.customer = null;
  }

  activate(params) {
    return this.customerService.getCustomerById(params.customerId)
      .then(customer => this.customer = customer)
      .then(customer => this.ea.publish('edit', customer));
  }
}
```

We need the annotation `@inject("ICustomerService")` for interfaces because the metadata is emitted as `Object` which means that we don't have enough information to know what needs to be injected.

So my understanding is that in InversifyJS `@injectable()` works like `@autoinject` in Aurelia but only works with classes, not interfaces. Both Angular and Aurelia have the same problem.

Please let me know if this is what you were wondering and If I can close the issue.

**Comment by cyberhck** [comment]
Hi, thanks for your immediate response, I love it, I didn't know inversify had that. I have one follow up question.
Does this also work with static methods?

I'll close this issue, I'm really happy that `@injectable` does that, I thought `@injectable` is only for making a class injectable.

**Comment by remojansen** [comment]
It doesn't work with static methods 😢  but you can use [`@lazyInject`](https://github.com/inversify/inversify-inject-decorators) in static properties, then the static method could use the static property.
