### ISSUE TITLE
Knockout.js example

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#74]
I'm just going to create some issues for some required examples.

We need a Knockout.js example at:

https://github.com/inversify/inversify-code-samples

I've been doing some analysis and we should be able to integrate InversifyJS with Knockout.js without problems.

Feel free to send PRs.

**Comment by chrispickford** [comment]
Was a Knockout.js example ever created? I'm struggling to integrate Inversify using a custom component loader.
