### ISSUE TITLE
Error while restarting server when using nodemon

### ISSUE THREAD

**Issue by yardz** [inversify/InversifyJS#745]
## Expected Behavior
When saving a file, the nodemon kills the process and restarts.

When I use pure "express" no problem occurs but when I use "inversify-express-utils" when the node restarts the process it does not finish the previous one.

So every time I have to use the command "killall -9 node" to be able to rotate the node again.

When I use "npm start" the problem does not occur...

## Steps to Reproduce (for bugs)
1. init "https://github.com/inversify/inversify-express-example"
2. create at package.json
 "scripts": {
    "start": "ts-node Basic/bootstrap",
  }
3. a nodemon.json
{
 ..
  "exec": "npm start"
}

## Your Environment
* Version used: 
    "inversify": "^4.9.0"
    "inversify-express-utils": "^5.2.0"
    "inversify-logger-middleware": "^3.1.0"

* Environment name and version: node v9.4.0
* Operating System and version: MAC OSX (and Windows 8)

**Comment by remojansen** [comment]
Hi @yardz thanks for reporting this issue.

You need to use the following instead:

```
start": "nodemon --watch 'Basic/**/*.ts' --ignore 'Basic/**/*.spec.ts' --exec 'ts-node' Basic/bootstrap.ts"
```

I will close this issue now. Please feel free to create a new issue if you need additional help.
