### ISSUE TITLE
Server side rendering with Next.js

### ISSUE THREAD

**Issue by anteburazer** [inversify/InversifyJS#752]
Hi guys

Did anyone try InversifyJS with Next.js and server side rendering?
I'm considering using these two tools for my next big project in React and I'm wondering if there is any potential issues with combining server side rendering and dependency Injection/Inversion.

Thanks

**Comment by remojansen** [comment]
Hi @anteburazer, I don't remember any previous questions about Next.js and InversifyJS. I use InversifyJS mostly on the server-side so I don't see why it should not work. I would recommend to give it a go in a small experiment and ask more specific questions if you encounter any issues. We will be happy to help.

**Comment by anteburazer** [comment]
Thanks @remojansen for the response.
I will definitely try it out and give you a feedback if anything goes wrong.

**Comment by kunalnagar** [comment]
@anteburazer - what were your findings when using Inversify with Next.js? Did you run into any particular issues?

**Comment by anteburazer** [comment]
@kunalnagar I didn't use it after all because I changed the project before I got started with this. Please share your thought if you try it out.
