### ISSUE TITLE
Better explanation of tagged bindings - what are the identifiers?

### ISSUE THREAD

**Issue by kristianmandrup** [inversify/InversifyJS#768]
In the wiki example you have:

We are binding `Katana` and `Shuriken` to `Weapon` but a `whenTargetTagged` constraint is added to avoid `AMBIGUOUS_MATCH` errors:

```js
container.bind<Ninja>(ninjaId).to(Ninja);
container.bind<Weapon>(weaponId).to(Katana).whenTargetTagged("canThrow", false);
container.bind<Weapon>(weaponId).to(Shuriken).whenTargetTagged("canThrow", true);
```

But not clear what the references such as `ninjaId` are, how they are supposed to work and what they reference exactly?

**Comment by kristianmandrup** [comment]
Ah, I guess they are just string values (ids), so they could be fx "Ninja" for `ninjaId` etc.

**Comment by remojansen** [comment]
Hi @kristianmandrup an identifier can be 3 things:

## A class

```ts
container.bind<Weapon>(Katana).to(Katana).whenTargetTagged("canThrow", false);
```

Or the shortcut:

```ts
container.bind<Weapon>(Katana).toself().whenTargetTagged("canThrow", false);
```

Then you can use the following to inject:

```ts
@injectable{ 
class SomeClass {
    public constructor(@inject(Katana) @tagged("canThrow", false) weapon: Weapon) {
       // ...
```

But when we use classes we are missing the benefits of the dependency inversion principle.

## A string

```ts
container.bind<Weapon>("Katana").to(Katana).whenTargetTagged("canThrow", false);
```


Then you can use the following to inject:

```ts
@injectable{ 
class SomeClass {
    public constructor(@inject("Katana") @tagged("canThrow", false) weapon: Weapon) {
       // ...
```

## A symbol

```ts
const KatanaId = Symbol.for("Katana");
container.bind<Weapon>(KatanaId).to(Katana).whenTargetTagged("canThrow", false);
```


Then you can use the following to inject:

```
@injectable{ 
class SomeClass {
    public constructor(@inject(KatanaId) @tagged("canThrow", false) weapon: Weapon) {
       // ...
```

You can learn more about symbols at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

I think this should be enough to answer your question, I will close the issue now but please feel free to ask more questions if you need additional help. Also please refer to our wiki, we have more info in it about identifiers.

https://github.com/inversify/InversifyJS/tree/master/wiki

**Comment by kristianmandrup** [comment]
Thanks a lot for the explanation. I didn't notice any documentation on ids, but might be scattered around. The example in point didn't make it clear, would have to search/read all the docs then in any case.
