### ISSUE TITLE
2.0 release progress

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#77]
Hi @inversify/collaborators, is there any news on the release progress of `2.0.0-alpha.0`?

It would be good to get working again towards the roadmap! :fireworks: :smile:

**Comment by remojansen** [comment]
Hi @inversify/collaborators!

I just did a commit today after a lot of changes in the directory architecture, I have also been working on a few new decorators and other things. The project looks like this so far:

```
.
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── package.json
├── src
│   ├── activation
│   │   ├── decorator_utils.ts
│   │   ├── inject.ts
│   │   ├── metadata.ts
│   │   ├── named.ts
│   │   ├── paramnames.ts
│   │   └── tagged.ts
│   ├── bindings
│   │   ├── binding.ts
│   │   ├── binding_count.ts
│   │   └── binding_scope.ts
│   ├── constants
│   │   ├── error_msgs.ts
│   │   └── metadata_keys.ts
│   ├── interfaces
│   │   └── ...
│   ├── inversify.ts
│   ├── kernel
│   │   ├── kernel.ts
│   │   ├── key_value_pair.ts
│   │   ├── lookup.ts
│   ├── planning
│   │   ├── context.ts
│   │   ├── plan.ts
│   │   ├── planner.ts
│   │   ├── queryable_string.ts
│   │   ├── request.ts
│   │   └── target.ts
│   ├── resolution
│   │   └── resolver.ts
│   └── utils
│       └── utils.ts
├── test
│   └── // ...
├── tsconfig.json
├── tslint.json
├── type_definitions
│   ├── inversify-global-test.ts
│   ├── inversify-global.d.ts
│   ├── inversify-npm.d.ts
│   ├── inversify-test.ts
│   └── inversify.d.ts
├── typings
│   └── ...
├── typings.json
└── wallaby.js
```

I have managed to get to a point in which all the old stuff still works except the kernel because I'm in the middle of the implementation of the new process. The build logs look as follows:

```
[01:42:24] Using gulpfile ~/Desktop/InversifyJS/gulpfile.js
[01:42:24] Starting 'default'...
[01:42:24] Starting 'lint'...
[01:42:28] Finished 'lint' after 3.43 s
[01:42:28] Starting 'build'...
[01:42:28] Starting 'build-source'...
[01:42:29] Finished 'build-source' after 1.68 s
[01:42:29] Starting 'build-test'...
[01:42:31] Finished 'build-test' after 1.59 s
[01:42:31] Starting 'build-type-definitions'...
[01:42:32] Finished 'build-type-definitions' after 1.39 s
[01:42:32] Finished 'build' after 4.67 s
[01:42:32] Starting 'test'...
[01:42:32] Starting 'istanbul:hook'...
[01:42:32] Finished 'istanbul:hook' after 182 ms
[01:42:32] Starting 'mocha'...


  @Inject

    ✓ Should not generate metadata when not applied

    ✓ Should generate metadata if declared injections

    ✓ Should throw when applayed mutiple times

    ✓ Should be usable in VanillaJS applications

  Metadata

    ✓ Should set its own properties correctly

  @Named

    ✓ Should not generate metadata for unnamed parameters

    ✓ Should generate metadata for named parameters

    ✓ Should throw when applayed mutiple times

    ✓ Should throw when not applayed to a constructor

    ✓ Should be usable in VanillaJS applications

  @ParamNames

    ✓ Should not generate metadata when not applied

    ✓ Should generate metadata if declared parameter names

    ✓ Should throw when applayed mutiple times

    ✓ Should be usable in VanillaJS applications

  @Tagged

    ✓ Should not generate metadata for untagged parameters

    ✓ Should generate metadata for tagged parameters

    ✓ Should generate metadata for parameters tagged mutiple times

    ✓ Should throw when applied mutiple times

    ✓ Should throw when not applied to a constructor

    ✓ Should be usable in VanillaJS applications

  Binding

    ✓ Should set its own properties correctly

    ✓ Should be able to use implementationType as a constructor

    ✓ Should throw when attempting to use an invalid scope

  Kernel

    1) Should be able to get a service without dependencies

    2) Should be able to get a service with acomplex dependency tree

    3) Should NOT be able to get unbound dependencies

    4) Should store singleton type bindings in cache

    5) Should unbind a binding when requested

    ✓ Should unbind all bindings when requested

    6) Should throw when cannot unbind

  Lookup

    ✓ Should throw when invoking get, remove or hasKey with a null key

    ✓ Should throw when attempting to add a null key

    ✓ Should throw when attempting to add a null value

    ✓ Should be able to link multiple values to a key

    ✓ Should throws when key not found

  Context
    - Todo

  Plan
    - Todo

  Planner
    - Should generate a basic resolution plan
    - Should generate a complex resolution plan

  QueryableString

    ✓ Should be able to set its own properties

    ✓ Should be able to return its value

    ✓ Should be able to identify if it's value starts with certain text

    ✓ Should be able to identify if it's value ends with certain text

    ✓ Should be able to identify if it's value is equals to certain text

  Target

    ✓ Should be able to create instances of untagged tagets

    ✓ Should be able to create instances of named tagets

    ✓ Should be able to create instances of tagged tagets

    ✓ Should be able to identify named metadata

    ✓ Should be able to identify multi-injections

    ✓ Should be able to match named metadata

    ✓ Should be able to identify tagged metadata

    ✓ Should be able to match tagged metadata

  Resolver
    - Todo

  Utils

    ✓ Should flatten multidimensional arrays


  43 passing (42ms)
  5 pending
  6 failing

  1) Kernel Should be able to get a service without dependencies:
     TypeError: Cannot set property 'plan' of null
      at Kernel._planAndResolve (src/kernel/kernel.js:9:4561)
      at Kernel.get (src/kernel/kernel.js:9:2355)
      at Context.<anonymous> (test/kernel/kernel.test.js:12:29)

  2) Kernel Should be able to get a service with acomplex dependency tree:
     TypeError: Cannot set property 'plan' of null
      at Kernel._planAndResolve (src/kernel/kernel.js:9:4561)
      at Kernel.get (src/kernel/kernel.js:9:2355)
      at Context.<anonymous> (test/kernel/kernel.test.js:28:35)

  3) Kernel Should NOT be able to get unbound dependencies:
     TypeError: Cannot set property 'plan' of null
      at Kernel._planAndResolve (src/kernel/kernel.js:9:4561)
      at Kernel.get (src/kernel/kernel.js:9:2355)
      at Context.<anonymous> (test/kernel/kernel.test.js:41:26)

  4) Kernel Should store singleton type bindings in cache:
     TypeError: Cannot set property 'plan' of null
      at Kernel._planAndResolve (src/kernel/kernel.js:9:4561)
      at Kernel.get (src/kernel/kernel.js:9:2355)
      at Context.<anonymous> (test/kernel/kernel.test.js:51:31)

  5) Kernel Should unbind a binding when requested:
     TypeError: Cannot set property 'plan' of null
      at Kernel._planAndResolve (src/kernel/kernel.js:9:4561)
      at Kernel.get (src/kernel/kernel.js:9:2355)
      at Context.<anonymous> (test/kernel/kernel.test.js:66:26)

  6) Kernel Should throw when cannot unbind:
     AssertionError: expected [Function] to throw error including 'Could not get service FooInterface' but got 'Could not unbind service FooInterface'
      at Context.<anonymous> (test/kernel/kernel.test.js:98:35)
```

So the remaining work for me are:
- Implement the `Planner` class
- Implement the `Plan` class
- Implement the `Resolver` class
- Change `Kernel` to use `Planner` and `Resolver`

I think what I'm going to do is add some tests without 100% test coverage. Then I will merge to a branch and you guys want you can help me to achieve 100% test coverage again.

You can [browse the code as it is right now](https://github.com/remojansen/InversifyJS/tree/master/src).  Will keep you updated :rainbow:

**Comment by remojansen** [comment]
Once I'm done with my tasks. I will merge to the [2.0.0-alpha.0 branch](https://github.com/inversify/InversifyJS/tree/2.0.0-alpha.0). You can track the progress of 2.0.0-alpha.0 [here](https://github.com/inversify/InversifyJS/milestones/2.0.0-alpha.0).

**Comment by remojansen** [comment]
Hi @ktutnik welcome to the family :family: :rainbow: :fireworks: I did a hangout with the rest of the team a couple of weeks ago to plan the release of 2.0. 

At the moment the team is block by me :sob: until I merge `2.0.0-alpha.0` once I have done that I will create milestones and issues to match the roadmap and we can all work together to make it happen.

**Comment by ktutnik** [comment]
@remojansen Thanks for let me in as the team. hi all @inversify/collaborators.

No worries, i have take a look at the road map and also have check the changes you made on your fork. yes its biggie, and i think it will be awesome. Will spent time to learn the new architecture until it ready.

can you add me on hangout im? btw i living in a place @ +8:00GMT what yours?

**Comment by remojansen** [comment]
@ktutnik I'm in GTM+0 (Dublin, Ireland) I have send you an invite :)

**Comment by remojansen** [comment]
Hi @inversify/collaborators, I just want to share a quick update... I've been doing some work over the weekend and I managed to implement the `Planner`#81. 

<img width="598" alt="screen shot 2016-02-29 at 08 35 18" src="https://cloud.githubusercontent.com/assets/10656223/13389431/db42d036-debf-11e5-9eaa-b6073bd79012.png">

So I just need to complete #81 and #82 and we are good to release `2.0.0-alpha.0`.

**Comment by jamesadarich** [comment]
:+1:

**Comment by ktutnik** [comment]
great!

**Comment by remojansen** [comment]
I just merged `2.0.0-alpha.0` https://github.com/inversify/InversifyJS/pull/89 :rocket: please take a look, test it if you can. I'm going to be doing some testing and updating documentation.

**Comment by remojansen** [comment]
Hello again @inversify/collaborators I just released `2.0.0-alpha.1` :tada: it would be great if you could try it out and let me know your thoughts. Thanks!

**Comment by remojansen** [comment]
Hello @inversify/collaborators! `2.0.0-alpha.3` landed :rocket:  master just a few minutes ago :tada: I have closed the milestone and created a new milestone: [`2.0.0-beta.1`](https://github.com/inversify/InversifyJS/milestones/2.0.0-beta.1). 

There is a couple of small issue in the new milestone, the issues #107 and #105 are good candidates for PRs.

**Comment by jamesadarich** [comment]
Hey Remo,

Nice work!! Do we have a process for picking up issues? Maybe just comment on the issue to let others know you are working on it?

**Comment by remojansen** [comment]
Thanks :smile: I will add a tag "help wanted" to show show that I'm not working on something. If you want to work on it just comment to say that you want to do it and I will remove the tag and assign it to you. If I'm working on something I will assign it to me. Does that work?

**Comment by remojansen** [comment]
Hi @inversify/collaborators guys before we move from alpha to beta we really need feedback from the community. To create the final version of the APIs.

I have already started to ask online via [twitter](https://twitter.com/inversifyjs) and I will also ask for feedback at my local [type script meetup](http://www.meetup.com/Dublin-TypeScript-Meetup/events/227455644/). Do you any other ideas about how can we get some feedback about the APIs?

**Comment by jamesadarich** [comment]
Nice! If I were any good at social media I'd spread the word myself!

I'll have a think about this but maybe worth simply logging a "Suggestions" issue for people to spam their ideas?

**Comment by remojansen** [comment]
I will do that I will create a "discussion" if I feel like I want to talk about something. Please do the same if you have questions.

**Comment by remojansen** [comment]
I'm planning to finish [Enhanced fuent binding syntax](https://github.com/inversify/InversifyJS/issues/116) and do a release `2.0.0-alpha.7`. After that we can try it and if it is fine we can promote it to `2.0.0-alpha.1`. 

I have done some significant changes. 

### @injectable

I have renamed `@inject` to `@injectable`. I have done this because right now we do:

```
@inject("IKatana", "IShuriken")
```

The thing is that in the future this won't be necessary because the TypeScript compiler will be able to add:

```
["IKatana", "IShuriken"]
```

The problem is that we will no longer will need to declare the strings but we will still be required to use the decorator:

```
@inject()
```

The angular 2.0 team [is aware of this](https://angular.io/docs/ts/latest/api/core/InjectableMetadata-class.html):

![screen shot 2016-03-19 at 00 04 38 2](https://cloud.githubusercontent.com/assets/10656223/13895013/3a5d2fda-ed66-11e5-99dc-0fa8db40a9ac.png)

> Injector will throw NoAnnotationError when trying to instantiate a class that does not have @Injectable marker, as shown in the example below.

So to be prepared for the future we will start using `@injectable` instead of `@inject`.

### Kernel modules

Let's consider the following kernel modules:

```
let warriors: IKernelModule = (k: IKernel) => {
    k.bind<INinja>("INinja").to(Ninja);
};

let weapons: IKernelModule = (k: IKernel) => {
    k.bind<IKatana>("IKatana").to(Katana).inTransientScope();
    k.bind<IShuriken>("IShuriken").to(Shuriken).inSingletonScope();
};
```

Instead of:

```
let kernel = new Kernel({ modules: [ someModule ] });
```

Now we have:

```
kernel = new Kernel();
kernel.load(warriors, weapons);
```

### Middleware

Imagine that we have two middleware functions:

```
function logger(next: (context: IContext) => any) {
    return (context: IContext) => {
        let result = next(context);
        console.log("CONTEXT: ", context);
        console.log("RESULT: ", result);
        return result;
    };
};

function devTools(next: (context: IContext) => any) {
    return (context: IContext) => {
        let result = next(context);
        let _window: any = window;
        let __inversify_devtools__ = _window.__inversify_devtools__;
        if (__inversify_devtools__ !== undefined) { 
          __inversify_devtools__.log(context, result); 
        }
        return result;
    };
};
```

This wasn't fully implemented but the idea was the following.

```
let kernel = new Kernel({ middleware: [ logger, devTools ] });
```

Now we have:

```
kernel = new Kernel();
kernel.applyMiddleware(logger, devTools);
```

**Comment by remojansen** [comment]
Hi guys I've been doing some research and I have another breaking change :disappointed: #136 

You can learn get a better context about it at [The current state of dependency inversion in JavaScript](http://blog.wolksoftware.com/the-current-state-of-dependency-inversion-in-javascript).

**Comment by remojansen** [comment]
I'm closing this issue but feel free to follow updates in the gitter chat. It is likely that we will get a `2.0.0-beta.1` release during the weekend or next week :tada:
