### ISSUE TITLE
Need factory method registration

### ISSUE THREAD

**Issue by ktutnik** [inversify/InversifyJS#78]
Note: i don't see this feature yet on the master. feel free to mark as dup or delete.

Sometime Type creation require some step (via some setup builder etc). Need an easy way to register it using a factory method registration

example the object creation is like below:

```
var myTypeInstance = Builder.addProtocol("http")
   .addConverter(new MyConverter())
   .build();
```

the registration will be like below:

```
kernel.bind(new TypeBinding<MyConverter>("MyConverter", MyConverter);
kernel.bind(new FactoryMethodBinding<MyTypeInstance>("MyTypeInstance", (container) => {
   return Builder.addProtocol("http")
      .addConverter(container.resolve<MyConverter>())
      .build();
}));

```

**Comment by remojansen** [comment]
Hi @ktutnik thanks a lot for your feedback! would you like to join the team? An person with experience with IoC containers like you would be a great addition. 

p.s. Have you check our [roadmap](https://github.com/inversify/InversifyJS/wiki/Roadmap)?

**Comment by ktutnik** [comment]
@remojansen Yes would love to join. if you need to reach me `ktutnik@gmail.com`

**Comment by remojansen** [comment]
Done by https://github.com/inversify/InversifyJS/pull/97
