### ISSUE TITLE
Express controllers cant be made singleton anymore

### ISSUE THREAD

**Issue by ankitcf** [inversify/InversifyJS#781]
## Expected Behavior
In earlier versions of inversify and inversify-express-utils, we were able to add bindings for express controllers in containers and we added inSingletonScope() to each binding

e.g.  bind<interfaces.Controller>(TYPE.Controller).to(statusController).inSingletonScope().whenTargetNamed(TAGS.StatusController)

## Current Behavior
Now if add a binding for our controllers, we get a error calling out multiple @injectable and @controller bindings. If we remove the binding, we cant make our controllers singletons anymore.

## Possible Solution
Allow adding bindings of express controllers

**Comment by remojansen** [comment]
@ankitcf this was a delivered decision with the goal of supporting request scope because it was needed to support `HttpContext` and `AuthProvider`. You can make the dependencies of your controller singleton with `inSingletonScope` or `inRequestScope` (singleton per HTTP request). Why do you need a singleton at controller level? Maybe I can help you to find an alternative way.

**Comment by ankitcf** [comment]
Makes sense. Only required in some rare cases where it is needed to store
some state at server level. e.g. We have a controller which just returns a
boolean status that is used by load balancer to direct traffic. During
deployments we first make the controller return bad status so that load
balancer stops sending traffic to this instance before we stop this server
and upgrade it. We were storing this in the singleton controller itself in
a variable.

If no other solution exists, we will move this to another singleton class.

Just curious but isn't creating a new controller object for every request
costly for high throughput systems ?

**Comment by remojansen** [comment]
Yes, you are right, it is not a good idea for high throughput systems but our goal so far has been to provide developers with a nice API that they enjoy and allows them to write applications that are easier to read and maintain. Of course, we care about performance too but it is a secondary goal. Also for high throughput systems, people will probably skip express.js for something like [fastify](https://github.com/fastify/fastify) or even [skip node.js](https://raygun.com/blog/increased-throughput-net-core/) altogether. 

I will close this issue now, but please feel free to ask more questions if you wish to know more.

**Comment by rajatkb** [comment]
I want to know is there any way to have the controller be instantiated as singletons ? My server need not be the fastest, but the request scoped controller definitely is affecting the performance. So is there any way to have the controller in singleton scope manually.
