### ISSUE TITLE
Kernel modules

### ISSUE THREAD

**Issue by ktutnik** [inversify/InversifyJS#79]
Sometime there is a logic on registering Types:

```
if(config.mode == "easy"){
   kernel.bind(new TypeBinding<MyType>("MyType", EasyMyType);
   kernel.bind(new TypeBinding<MyOtherType>("MyType", EasyMyOtherType);
}
else {
   kernel.bind(new TypeBinding<MyType>("MyType", HardMyType);
   kernel.bind(new TypeBinding<MyOtherType>("MyType", HardMyOtherType);
}
```

You don't want to repeat those logic on the Unit Test and in your apps. even you need to unit test those logic.

will be better if Inversify can provide a predefined (template) registration. in Castle Windsor its called [Installer](https://github.com/castleproject/Windsor/blob/master/docs/installers.md)

**Comment by remojansen** [comment]
I need to think about this but I think this would be possible thanks to the parent Kernel feature in the roadmap: 

```
var kernel: kernel = null;
if(config.mode == "easy"){
   kernel = new Kernel(easyKernel);
}
else {
   kernel = new Kernel(hardKernel);
}
```

The Kernel chain will behave in a similar way to the JavaScript prototype chain. If a binding cannot be resolved the kernel will search in the kernel chain. This idea was inspired by [child injectors in Angular DI](http://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html#transient-dependencies-and-child-injectors).

**Comment by remojansen** [comment]
This is now done by 052dcafce8f268ed3bfce0a1ce0172f73f3ead00 

At the end I decided to leave our the parent kernel feature, we can still add it in the future but I see small real-world use cases so I decided to [leave it out until some people ask for it (A.K.A. KISS)](https://en.wikipedia.org/wiki/KISS_principle).

The way it works is the following:

```
let someModule: IKernelModule = (kernel: IKernel) => {
    kernel.bind<INinja>("INinja").to(Ninja);
    kernel.bind<IKatana>("IKatana").to(Katana);
    kernel.bind<IShuriken>("IShuriken").to(Shuriken).inSingletonScope();
};

let options: IKernelOptions = {
    modules: [
        someModule
    ]
};

let kernel = new Kernel(options);
let ninja = kernel.get<INinja>("INinja");
console.log(ninja2);
```
