### ISSUE TITLE
Typo in readme inversify-express-utils

### ISSUE THREAD

**Issue by gigi** [inversify/InversifyJS#792]
Spent some time to debug strange error while implementing Principal `Expected 0 arguments, but got 1` as shown here: https://github.com/inversify/inversify-express-utils#authprovider

Should be **constructor** instead of constr**cu**tor :)
```
public constrcutor(details: any) {
    this.details = details;
}
```

**Comment by dcavanagh** [comment]
[Pull Request](https://github.com/inversify/inversify-express-utils/pull/139)

Thanks!
