### ISSUE TITLE
Handling two authentication mechanism with express

### ISSUE THREAD

**Issue by kevynb** [inversify/InversifyJS#794]
Hello,

We have trouble upgrading from Inversify-express-utils 3.x to 5.x

We are building a webapp where we have two parts, one customer facing living on `/api` and an admin one living under `admin`. The consumer facing part and the admin part don't use the same mechanism for authentication.

Up until now we've been using two `InversifyExpressServer` sharing the same express `app` but with different containers and different middlewares to handle the auth strategies correctly.

However when migrating to express-utils 5, we find ourselves unable to separate our controllers now as they share one global "space". Because of that we seem to only be able to use one InversifyExpressServer, which is no good for our use case.

The only solution we see would be to add all of our middlewares on each of our controller, but that doesn't seem practical. 

Would you have any advice on how we could sort this out?

Thanks!

**Comment by dcavanagh** [comment]
@kevynb Could you please provide a code sample for your 3.x usage and I will take a look

**Comment by dcavanagh** [comment]
@kevynb 
Would something like this work?
```
    let server = new InversifyExpressServer(container, null, {
        rootPath: '/'
    });
    server.setConfig((app) => {
          app.use('/api', (req, res, next) => {
                console.log('api auth');
                next();
            });
            app.use('/admin', (req, res, next) => {
                console.log('admin auth');
                next();
            });
         let router = express.Router();
            app.use('/api', router);
    });
    let theApp: express.Application = server.build();
    theApp.listen(appPort);
    container.bind<express.Application>(TYPES.App).toConstantValue(theApp);
```

**Comment by dcavanagh** [comment]
I haven't heard back so I am going to close the issue. Please reopen it if you are still having trouble.

**Comment by kevynb** [comment]
Hello, Really sorry for not responding in due time.

I'm convinced this would have worked but we changed the way the apps were built and the problem disappeared. 

Thanks for your time, Inversify is a great library!
