### ISSUE TITLE
inversify-express-utils multipart upload 

### ISSUE THREAD

**Issue by mactanner** [inversify/InversifyJS#806]
I'd like to implement a file upload endpoint that can handle the content type "multipart/form-data". Unfortunately I'm struggling with the inversify-express-utils.

## Expected Behavior
I'd expect that the uploaded chunks are piped to the provided writable stream:

```
@httpPut('/')
public addMediaFile(@request() req, @response() res) {
    const mediaFileId: string = uuid();
    const busboy = new Busboy({ headers: req.headers });

    busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
        file.on('data', data => {
            console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
        });
        file.on('end', () => {
            res.json({ mediaFileId });
        });
        // getting a write stream here: either filesystem or s3 bucket
        const writeStream = this.mediaFileRepository.getWriteStreamToTempFolder(mediaFileId);
        file.pipe(writeStream);
    });
   req.pipe(busboy);
}
```

## Current Behavior
Only the first chunk is processed:
```
2018-02-28T10:49:25.41+0100 [APP/PROC/WEB/0] OUT File [file] got 1970 bytes
```

If I run the same code in a expressjs route configuration, it works as expected:

```
app.route('/rest/administration/media-files')
  .post(async (req: express.Request, res: express.Response) => {
          // same multipart code handling here 
});
```

Processing looks like this:

```
2018-02-28T10:48:15.26+0100 [APP/PROC/WEB/0] OUT File [file] got 14986 bytes
2018-02-28T10:48:15.26+0100 [APP/PROC/WEB/0] OUT File [file] got 571 bytes
2018-02-28T10:48:15.27+0100 [APP/PROC/WEB/0] OUT File [file] got 1398 bytes
2018-02-28T10:48:15.27+0100 [APP/PROC/WEB/0] OUT File [file] got 14986 bytes
2018-02-28T10:48:15.29+0100 [APP/PROC/WEB/0] OUT File [file] got 1398 bytes
2018-02-28T10:48:15.29+0100 [APP/PROC/WEB/0] OUT File [file] got 14986 bytes
2018-02-28T10:48:15.29+0100 [APP/PROC/WEB/0] OUT File [file] got 1398 bytes
2018-02-28T10:48:15.29+0100 [APP/PROC/WEB/0] OUT File [file] got 14986 bytes
...

Alle the chunks are processed. And the whole file is uploaded to the required destination (depending on the write stream).
```

## Context
I'd like to go on with the nice decorators provided by the inversify-express-utils as they work perfectly fine with our other rest endpoints. But I don't want to mix endpoint definitions because there's a problem with multipart-uploads. 

## Your Environment
I'm experiencing this behavior on my dev machine (mac osx) as well as on our cloud infrastructure (cloud foundry).

**Comment by dcavanagh** [comment]
@mactanner I was able to get it to work with a few changes.

one thing was that in the ```file.on('end', (),...``` you were putting ```res.json({ mediaFileId });```
```res.json``` actually sends the response, so if there were two files I would get a "'Can\'t set headers after they are sent.'" error because for the second file the response already left. I moved the ```res.json``` to a ````busboy.on('finish, () => {}) ``` and just logged the filename in the original.

```
@httpPut('/')
    public addMediaFile(@request() req, @response() res): void {
        const mediaFileId = 'uuid';
        const busboy = new Busboy({ headers: req.headers });
        busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
            file.on('data', data => {
                console.log('File [' + filename + '] got ' + data.length + ' bytes');
            });
            file.on('end', () => {
                console.log('File[' + filename + '] finished');
            });
            const writeStream = fs.createWriteStream(filename);
            file.pipe(writeStream);
        }).on('finish', () => {
            res.json({ mediaFileId });
        });
        req.pipe(busboy);
    }
```

**Comment by mactanner** [comment]
@AltekkeE thanks for your reply.

I did the same changes to my code. Unfortunately that doesn't work for me yet.
There's only one chunk mentioned on the console. `file.on('end', (),...` is never reached.

```
OUT File [DSC_0040.JPG] got 572 bytes
```

That's probably the reason why I didn't get the `Can't set headers after they are sent.` error...

Is that maybe a problem with my setup of the inversify express server?

```
    const server = new InversifyExpressServer(container);
    server.setConfig((application: express.Application) => {
        application.use(absoluteUrlMiddleware(container));
        application.use(cors());
        application.use(bodyParser.urlencoded({ extended: true }));
        application.use(bodyParser.json());
        application.enable('trust proxy');
    });
```

**Comment by dcavanagh** [comment]
@mactanner were you ever able to get this to work?
