### ISSUE TITLE
autoBindInjectable not working

### ISSUE THREAD

**Issue by jcreamer898** [inversify/InversifyJS#815]
`autoBindInjectable` doesn't work like I'd expect.

## Expected Behavior

I have many classes that are marked as `injectable()`, so I expected that once I created a container with `autoBindInjectable: true`, I could remove the bindings...

```typescript
@injectable()
export default class TravelAgentServer implements ITravelAgentServer {}
```

```typescript
const container = new Container({
  autoBindInjectable: true,
});
```

```typescript
container
  .bind<ITravelAgentServer>(TYPES.ITravelAgentServer)
  .to(TravelAgentServer);
```

## Current Behavior

When I run my app with, I get missing binding errors...

```typescript
  const travelAgent = container.get<ITravelAgentServer>(
    TYPES.ITravelAgentServer,
  );
```

![](https://d.pr/i/HPGG1N+)

## Possible Solution

Is it possible I'm missing something in how autoBinding works?

## Steps to Reproduce (for bugs)

Code samples above.

## Context

Trying to not have to add new bindings all the time for things I've already marked as injectable

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:
macOS, node 8.9.

# Stack trace

**Comment by paulspiteri** [comment]
I think all ```autoBindInjectable``` does is bind a type (E.g. TravelAgentServer) to itself. 
That would allow you to .get() that concrete type explicitly (not via your TYPES.ITravelAgentServer symbol)

I might be wrong though but that's my understanding.

**Comment by tonyhallett** [comment]
When there is a request, from Container 'get' method or for a to() binding constructor parameter or property, a toSelf() binding will be automatically created if there are no existing bindings for a service identifier that is a class constructor.

**Comment by notaphplover** [comment]
The current behavior is the expected one, [autoBindInjectable](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#autobindinjectable) option works a container level as docs explain, using `@injectable` is still mandatory.
