### ISSUE TITLE
Child containers don't inherit `defaultScope` setting

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [inversify/InversifyJS#825]
## Expected Behavior

If you set `defaultScope: "Singleton"` on a parent container, then create a child container with `createChild`, the child container should inherit that `defaultScope` setting, right?

## Current Behavior

Not so. The child container has the default, non-singleton `defaultScope`.

## Possible Solution

I would think it should inherit it... but if you consider that to be a breaking change, how about allowing the same constructor params object to be passed to `createChild`?

I'd be more than happy to do either in a PR once the best approach is known. 😄 

## Steps to Reproduce (for bugs)
1. Create a blank project with this code:

```typescript
class MyClass { }

const parentContainer = new Container({
    defaultScope: "Singleton",
});

parentContainer.bind(MyClass).toSelf();

const childContainer = parentContainer.createChild();

const first = childContainer.get(MyClass);
const second = childContainer.get(MyClass);

// first !== second
```

2. Cry in defeat

## Context

My app lazy-loads application bundles. Each bundle receives a child container of its parent bundle and spits out a MobX store and React view. We use child containers to avoid accidentally modifying the parent container.

For now, we'll just pass the parent container and hope nobody does bad things with it.

## Your Environment
* Version used: 4.10.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): All browsers; Node >=8 (presumably not relevant)
* Operating System and version (desktop or mobile): Windows, Mac
* Link to your project: _(internal - no can do)_

**Comment by paulspiteri** [comment]
Container.Merge has the same problem too

**Comment by JoshuaKGoldberg** [comment]
Oh hey just noticed I had fixed this and never resolved this issue. Sorry about that! 😄 

@paulspiteri FYI - recommend filing a new issue if Container.Merge is still not doing what you need?
