### ISSUE TITLE
[Inversify-express-util]Return 204 when call next(error) when I don't have any middleware that do that

### ISSUE THREAD

**Issue by hong-duc** [inversify/InversifyJS#833]
Just like the title sad, I call next(error) in catch in Promise and it return 204 status, and this made the error middleware throw error 'Can't set headers after they are sent.'

But it work normal when I call next(error) not in Promise
## Expected Behavior
call next(error) should go to the error middleware

## Current Behavior
Call to some middleware that I don't know and return 204

## Steps to Reproduce (for bugs)
1.  Create a promise
2. Make that promise reject
3. call next(error) in catch of that promise

## Context
I want to handle error in one place follow the express way

## Your Environment
* Version used: inversify ^4.11.1, inversify-express-utils ^5.2.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs 8.6.0
* Operating System and version (desktop or mobile): manjaro linux
* Link to your project:

# Stack trace

**Comment by hong-duc** [comment]
After a while I get it. So I must return promise reject and it will call the next(error) and I cannot call it by my self

**Comment by YussufElarif** [comment]
Hi @hong-duc, is it possible to share an example of how you resolved this issue, i'm having the exact same problem haha, but I'm using try and catches 😄

**Comment by YussufElarif** [comment]
Nevermind, I missed out a section from the docs. I didn't see [server.setErrorConfig()](https://github.com/inversify/inversify-express-utils#seterrorconfigerrorconfigfn)
