### ISSUE TITLE
Inversify-Express-Utils Middleware for all controllers

### ISSUE THREAD

**Issue by dcavanagh** [inversify/InversifyJS#852]
Moved from https://github.com/inversify/inversify-express-example/issues/327
---------

For example i wanna to make loggerMiddleware but connect this middleware to each controller is intolerable. Haw can i do it for all request??

**Comment by dcavanagh** [comment]
@Bon4ik inversify-express-utils is just express under the hood. If you want to register a global middle-ware you can do it in the config step
```typescript
function myMiddleWare(request: express.Request, response: express.Response, next: express.NextFunction) {
    console.log(`HTTP ${request.method} ${request.url}`);
    next();
}

let server = new InversifyExpressServer(container);

server.setConfig((app) => {
  app.use(myMiddleWare);
  app.use(bodyParser.json());
});

let serverInstance = server.build();
serverInstance.listen(3000);
```

**Comment by QuantumKing** [comment]
@dcavanagh What if I want to rebind something in a global middleware?
