### ISSUE TITLE
Auto factory

### ISSUE THREAD

**Issue by ktutnik** [inversify/InversifyJS#87]
Sometime a class need to create instance of other class on the fly instead of on creation time. So need to provide a convenient way to do that, without letting user to construct their own factory and reference container on the class.

example

``` Javascript
class Factory {
    resolve<T>(key:string){}
}

class MyClass{

}

@Inject("Factory")
class OtherClass{
    factory: Factory;
    constructor(factory: Factory){
        this.factory = factory;
    }

    myMethod(){
        var myclass = this.factory.resolve<MyClass>("MyClass");
    }
}

kernel.bind(new TypeBinding<Factory>("MyClass", MyClass));
kernel.bind(new AutoFactoryBinding<Factory>("Factory", Factory));
```

this feature require[ interception feature](https://github.com/inversify/InversifyJS/issues/86) ready

**Comment by remojansen** [comment]
:+1: We need to do some thinking about it but sound like a good idea to me.

**Comment by remojansen** [comment]
This is done by #102
