### ISSUE TITLE
code style rules

### ISSUE THREAD

**Issue by amir-arad** [inversify/InversifyJS#892]
the PR template of this project prompts contributors to check `My code follows the code style of this project`. I could not find a code style document. I suggest supplying a link to it in the CONTRIBUTING file or removing this checkbox from the PR template.

**Comment by dcavanagh** [comment]
@amir-arad were you looking at a specific repository or could you not find it in any of them?  Thanks

**Comment by notaphplover** [comment]
Closing as the contributing file is already present
