### ISSUE TITLE
ERROR in ./node_modules/inversify/lib/inversify.js

### ISSUE THREAD

**Issue by Freest10** [inversify/InversifyJS#898]
Hello, thx for your project;)
I try build example inversify project and command line show this

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/decorator_utils' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 37:24-63
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/inject' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 20:15-45
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/injectable' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 14:19-53
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/multi_inject' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 27:21-57
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/named' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 18:14-43
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/optional' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 23:17-49
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/post_construct' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 31:23-61
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/tagged' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 16:15-45
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/target_name' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 29:20-55
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './annotation/unmanaged' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 25:18-51
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './constants/literal_types' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 7:22-58
 @ ./src/inversify.config.ts
 @ ./src/index.ts

ERROR in ./node_modules/inversify/lib/inversify.js
Module not found: Error: Can't resolve './constants/metadata_keys' in 'D:\webpack4+typescript\node_modules\inversify\lib'
 @ ./node_modules/inversify/lib/inversify.js 3:11-47
 @ ./src/inversify.config.ts

If you want see test project with this errors - https://github.com/Freest10/inversify-test
It use webpack4+typescript2.9.1

**Comment by dcavanagh** [comment]
@Freest10 I got it to build by adding .js to the resolve extensions array
```javascript
const path = require('path');
const APP_DIR = path.resolve(__dirname, "./src/");

module.exports = {
    mode: 'development',
    entry: "./src/index",
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    resolve: {
        // Add `.ts` and `.tsx` as a resolvable extension.
        extensions: [".ts", ".js"],
        modules: [
            'node_modules'
        ],
    },
    module: {
        rules: [
            {
                test: /\.ts$/,
                use: 'ts-loader'
            }
        ]
    }
};
```
