### ISSUE TITLE
Create integration example (browserify)

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#9]
https://github.com/inversify/inversify-code-samples

**Comment by ulrichb** [comment]
The link above is dead. Could you post a new one with the browserify sample?

**Comment by remojansen** [comment]
Hi, we run our unit tests in browsers using karma and a bundle file which is [created using browserify](https://github.com/inversify/InversifyJS/blob/master/gulpfile.js#L134-L152) but we compile (from ts to js) in one task and then create a bundle (from js to js) in another task. A few releases ago we were compiling and bundling using one unique task:

``` js

var gulp        = require("gulp"),
    browserify  = require("browserify"),
    tsify       = require("tsify"),
    source      = require("vinyl-source-stream"),
    buffer      = require("vinyl-buffer"),
    sourcemaps  = require("gulp-sourcemaps");

gulp.task("build-bundle-test", function() {

  var mainTsFilePath = "test/inversify.test.ts";
  var outputFolder   = "temp/";
  var outputFileName = "bundle.test.js";

  var bundler = browserify({
    debug: true,
    standalone : "inversify"
  });

  // TS compiler options are read from tsconfig.json file
  return bundler.add(mainTsFilePath)
                .plugin(tsify, { typescript: require("typescript") })
                .bundle()
                .pipe(source(outputFileName))
                .pipe(buffer())
                .pipe(sourcemaps.init({ loadMaps: true }))
                .pipe(sourcemaps.write("."))
                .pipe(gulp.dest(outputFolder));
});
```

The preceding task will read the TS compiler options from the tsconfig.json file:

``` js
{
    "compilerOptions": {
        "target": "es5",
        "lib": ["es6", "dom"],
        "types": ["reflect-metadata"],
        "module": "commonjs",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```

You should be able to copy the above and change the  file paths.

If you are going to run your app in a browser, we recommend to import reflect-metadata as a global:

``` html
<script src="./node_modules/reflect-metadata/Reflect.js"></script>
```

As opposed to as part of the bundle:

``` ts
// in your main ts file
import "reflect-metadata";
```

You can learn more at:
- [Environment support and polyfills](https://github.com/inversify/InversifyJS/blob/master/wiki/environment.md)
- [Working with module bundlers](https://github.com/inversify/InversifyJS/blob/master/wiki/module_bundlers.md#browserify)
