### ISSUE TITLE
inversify-express-utils: Add json response type

### ISSUE THREAD

**Issue by zachabney** [inversify/InversifyJS#913]
To my knowledge, currently you can't change the status code when returning a json object. This will add a json helper method which will accept a status code and json content.

## Expected Behavior

Call `BaseHttpController#json(content: any, statusCode: number)` which will respond with the json content while also setting the response status code.

## Current Behavior

Currently can not change the status code when returning an object.

## Possible Solution

Create json response type and helper method where you can set the status code.

See pull request https://github.com/inversify/inversify-express-utils/pull/211

## Context

Useful when building API's that need to respond with a status code and JSON object.

**Comment by dcavanagh** [comment]
@zta192 Can you please recreate this issue in the Inversify repository. We like to track all the issues there
Thanks
