### ISSUE TITLE
Container.resolve method doesn't use options

### ISSUE THREAD

**Issue by zandroid** [inversify/InversifyJS#914]
```ts
class Test { }

@injectable()
class Test2 extends Test { }

const container = new Container({skipBaseClassChecks: true});
container.resolve(Test2);
```

## Expected Behavior
Should resolve without error.

## Current Behavior
It throws "Error: Missing required @injectable annotation in: Test" even skipBaseClassChecks is true.

**Comment by gordysc** [comment]
Just hit this today.. any plans on this being published in a release soon?
