### ISSUE TITLE
When is the new release planned?

### ISSUE THREAD

**Issue by artemdanylenko** [inversify/InversifyJS#916]
Hi, 

I contributed a change that blocks my team from returning from our fork back to this origin.
When are you planning to do next minor release?

Thanks,
Artem

**Comment by dcavanagh** [comment]
@asdanilenk Which repository did you submit a change to?

**Comment by artemdanylenko** [comment]
Hi @dcavanagh , I'm talking about this PR 
https://github.com/inversify/InversifyJS/pull/882

**Comment by gordysc** [comment]
Adding this here for visibility.  I'd like to know this as well regarding the following fix that was merged a bit ago:
https://github.com/inversify/InversifyJS/issues/914

**Comment by djflex68** [comment]
:+1:

**Comment by kalahari** [comment]
I would love to see a new release for #913 as well!

**Comment by elsasslegend** [comment]
Can you please publish a release soon ? 
We are waiting of #882 because of performance issues with Math.random.

**Comment by dcavanagh** [comment]
I am very sorry for the delay. 4.14.0 has been released
