### ISSUE TITLE
Wrong url for unit tests example

### ISSUE THREAD

**Issue by Narven** [inversify/InversifyJS#917]
In the wiki [https://github.com/Inversify/InversifyJS/blob/master/wiki/property_injection.md](https://github.com/Inversify/InversifyJS/blob/master/wiki/property_injection.md), here it says:

> Please refer to our unit tests for additional examples.

The link for the unit tests point to the same document.

## Expected Behavior
Should go to the `unit tests` examples

## Current Behavior
Points to the same page

## Possible Solution
Fix the link :) or tell me what is the proper url, and I'll PR

## Steps to Reproduce (for bugs)
Go to [https://github.com/Inversify/InversifyJS/blob/master/wiki/property_injection.md](https://github.com/Inversify/InversifyJS/blob/master/wiki/property_injection.md)

1. Click on the link in `unit tests`

What is the correct file it should be pointing to? thanks

**Comment by dcavanagh** [comment]
#929 thanks for pointing that out!
