### ISSUE TITLE
inversify-express-utils example not working

### ISSUE THREAD

**Issue by ssi-hu-istvan-banszki** [inversify/InversifyJS#932]
At inversify-express-utils GitHub page, the first example code ("Step 1: Decorate your controllers") not working. From the two HTTP Get endpoint, only the first will be mapped always during every request.
https://github.com/inversify/inversify-express-utils

Here is my code:

	@controller("/examples")
	export class ExampleController implements interfaces.Controller {

	    @httpGet("/")
	    private list(@queryParam("start") start: number, @queryParam("count") count: number): string {
	        return "list";
	    }

	    @httpGet("/")
	    private index(req: express.Request, res: express.Response, next: express.NextFunction): string {
	        return "index";
	    }
	}

It should map correctly the call for
http://localhost:3000/examples
and
http://localhost:3000/examples?start=6&count=12
but I always get back 'list' string. Otherwise, I don't get any exception or error.

**Comment by Halynsky** [comment]
It is normal behavior. In your case, you wrote the same method twice. So only one of them is registered by the server. You have two methods with the same path "/". It is similar logic to a signature of the method in some languages. You cant create two methods with the same signature (@queryParam are not a part of signature). So just make another pass for your second method.
