### ISSUE TITLE
inversify-express-utils: Type Definition Issue on decorators for Middleware

### ISSUE THREAD

**Issue by JoA-MoS** [inversify/InversifyJS#938]
I am trying to use the express-validator library (https://express-validator.github.io/docs/schema-validation.html) to perform schema validation the library provides a checkSchema function that returns a `ValidationChain[]` (according to type def `ValidationChain extends express.RequestHandler, Validator, Sanitizer`). When adding `checkSchema(mySchema)` onto the request annotation typescript complains. 

I can use @ts-ignore or expand the checkSchema response but I do not think either are the correct solution how should this be accomplished

 ```TypeScript
 // @ts-ignore
    @httpPost('/users', checkSchema(userSchema))
```
or

 ```TypeScript
    @httpPost('/users', ...checkSchema(userSchema))
```
Is this by design or a bug?

Should I be creating a custom Middleware and wrap checkSchema? if so how can I pass a parameter to my custom middleware?

## Expected Behavior
Inversify Express Utils should allow a RequestHandler[] as middleware

## Current Behavior
vscode complains stating 

```
Argument of type 'ValidationChain[]' is not assignable to parameter of type 'string | symbol | Newable<any> | Abstract<any> | RequestHandler'.
  Type 'ValidationChain[]' is not assignable to type 'RequestHandler'.
    Type 'ValidationChain[]' provides no match for the signature '(req: Request, res: Response, next: NextFunction): any'.
```

## Steps to Reproduce (for bugs)

1. npm install express-validator
2. add checkSchema function as a middleware onto decorator

## Context
I want to add a validation middleware and typescript complains

## Your Environment

* Version used: 
        "inversify": "^4.13.0",
        "inversify-express-utils": "^6.1.0",
* Environment name and version (e.g. Chrome 39, node.js 5.4):
    node v8.11.3
* Operating System and version (desktop or mobile):
    desktop

**Comment by 0xDones** [comment]
Same here.

**Comment by WandersonAlves** [comment]
#1114

**Comment by WandersonAlves** [comment]
@JoA-MoS @dpolicastro i found how to validate routes with `inversify-express-utils` + `express-validator`
