### ISSUE TITLE
[inversify-inject-decorators] lazyInject example doesn't seem to work

### ISSUE THREAD

**Issue by eduard-malakhov** [inversify/InversifyJS#939]
Hello, I am trying to reproduce the `lazyInject` example from [](https://github.com/inversify/inversify-inject-decorators) and it doesn't seem to work as expected neither in a browser (Chrome) nor in NodeJS. 

## Steps to Reproduce (for bugs)
I've published the example I've been playing with [on GitHub](https://github.com/eduard-malakhov/inversify-inject-decorators-test). I run it using `npx babel-node index.ts --extensions ".ts"` and  I reproduce the same result in Chrome.

As far as I can tell, the property is created correctly on the prototype but it has no effect on the instance object. I can suggest that this is somehow related to the fact that the instance object already has a property named "weapon" and therefore property getter on the prototype does not get invoked (as explained [here](https://hackernoon.com/understanding-javascript-prototype-and-inheritance-d55a9a23bde2) - "The prototype is a reference to another object and it is used whenever JS can’t find the property you’re looking for on the current object". However it that was true, then the entire implementation of inversify-inject-decorators wouldn't work which doesn't seem to be the case... 

Can anyone tell what I'm doing wrong?

**Comment by notaphplover** [comment]
As discussed in [a recent issue](https://github.com/inversify/InversifyJS/issues/1678#issuecomment-2539968294), the package is being archived their usage is discouraged.
