### ISSUE TITLE
No interfaces.PlanAndResolve to be found

### ISSUE THREAD

**Issue by kferrone** [inversify/InversifyJS#950]
In all of the examples about middleware in the docs, every one references an interface called `interfaces.PlanAndResolve` which I can not find anywhere. 

## Expected Behavior

Inversify has docs and examples using the latest code with no references to mystery stuff. 

## Current Behavior

There is no `PlanAndResolve`

## Possible Solution

Update the docs to use whatever is used instead. 

## Steps to Reproduce (for bugs)

1. [Try this example in your app | middleware example](https://github.com/inversify/InversifyJS/blob/master/wiki/middleware.md)
2. See in your Ide or TSC output that PlanAndResolve does not exist
3. Crawl Inversify code to see it really is not there

## Context

Can't get the middleware example to work and therefore I have no idea how to get middleware into my app. 

## Your Environment

* Version used: 4.13.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): NodeJS 10.9.0
* Operating System and version (desktop or mobile): desktop/server

# Stack trace

`Namespace 'interfaces' has no exported member 'PlanAndResolve'.`

**Comment by dcavanagh** [comment]
fixed by #978
