### ISSUE TITLE
When will pull request #777 be merged?

### ISSUE THREAD

**Issue by zveljkovic** [inversify/InversifyJS#955]
A lot of utility classes are meant to be in singleton scope i.e. DbHelper. When we want to test some parts of code we need to swap them out. If we use DI across whole project we need the singletons to work properly with snapshot() and restore() as it's useful in tests before() and after() global hooks.

## Expected Behavior
To include a pull request in reasonable amount of time

## Current Behavior
Pull request sits for 8 months. If something is missing please write so we can amend.

**Comment by dcavanagh** [comment]
@remojansen There was a conversation going on between you and @m3l7. can you please advise if this PR is ready?

**Comment by notaphplover** [comment]
Closing as #777 is merged
