### ISSUE TITLE
Is the library lightweight?

### ISSUE THREAD

**Issue by Moln** [inversify/InversifyJS#958]
In `README.md` description.  I saw InversifyJS is a lightweight (4KB) container.

Then I try only require this and build it (using webpack), but the `min.js` file size is `40+kb`.

How to use InversifyJS and build lightweight lib.

**Comment by kebie3** [comment]
InversifyJS is dependent on reflation-metadata, perhaps its size is more than 50 kb.

**Comment by remojansen** [comment]
@Moln hi sorry but as we added features the library is probably now over 4KB. I don't know what is the current size. I assume that if you enable tree-shaking in Webpack it can probably be reduced to only the bits you need.
