### ISSUE TITLE
Reorganize import/exports on the inversify-basic-example project

### ISSUE THREAD

**Issue by dlarner3194** [inversify/InversifyJS#965]
Reorganize import/exports on the inversify-basic-example project. Replace default exports.

## Expected Behavior

The change should add an index file to each folder and export the modules through that file.

## Current Behavior

In the IOC config file it is importing a lot of files which could be lessened if this was implemented. Helps with readability.

## Possible Solution

The change should add an index file to each folder and export the modules through that file.

## Context

It can help with readability and maintainability.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dcavanagh** [comment]
closed by https://github.com/inversify/inversify-basic-example/pull/56
