### ISSUE TITLE
Development flatlining?

### ISSUE THREAD

**Issue by shaunc** [inversify/InversifyJS#968]
## Expected Behavior

I expect that issues would be resolved, roadmap would be maintained, and projects would be updated in a vibrant, active project.

## Current Behavior

It seems most recent PRs (in last 6 months) are related to greenkeeper. Though this is still a quite popular project, I wonder if development has stalled for some reason? Perhaps core maintainer(s) need to pass the baton, if they are too busy?

## Context

I have a medium-sized project (25K code lines) with a custom plugin architecture, which I was considering porting to a mature dependency injection service, as I have other things to do more crucial than maintaining the plugin architecture. Is inversify still moving forward, though? Should I look for another option or wait? Overall, it looks well designed and documented and until this year also well maintained and dynamic.

**Comment by remojansen** [comment]
Hi @shaunc you are right at the moment I don't have a lot of time. @dcavanagh has been helping me but we need more contributions. We are happy to assist if someone wants to tackle an issue. Are there any particular issues that are urgent for you?

**Comment by shaunc** [comment]
@remojansen Thanks for the reply. I took the plunge and adopted anyway, and seems to be working. (I did have some issues injecting static class properties, but worked them out, and I'm not sure if doing that isn't an anti-pattern anyway.)

My concern stands though -- you've built a big and popular package. Maybe you should put a call out to collect a committee to go through outstanding issues, build/maintain a roadmap, etc. I don't think I'd be a good member both because of time pressure and because I'm just getting started using inversify. Given its popularity, however, I would bet you could gather a qualified group of stakeholders.

**Comment by remojansen** [comment]
I understand your concerns the project is not abandoned but profess will be slow. However, I can tell you that I work at a startup and we really heavily on Inversify so if there are major issues they will be resolved. The package ahs continue to grow because it might not be evolving fast but it is reliable.

**Comment by shaunc** [comment]
ok ...  keep in mind you can probably reach out for help given the popularity of the package.(And better to do it early than after people start to drift away if their issues are stagnant.)

If "inversifying" the current project works well, we have another coming up in a couple months that will require webpack deployment. I do see some open issues mentioning webpack... (And I might even be able to help -- though webpack is even more black magic to me than inversify.)

In any case -- thanks so much for inversify! I wish it continued growth.
